# Generated by Django 6.0.1 on 2026-09-22 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('employee_hierarchy', '0008_seed_default_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leave',
                'permissions': [('can_apply_leave', 'Can apply for their own leave'), ('can_apply_leave_for_others', 'Can raise a leave application for somebody else'), ('can_view_team_leave', 'Can view the leave of everyone below them'), ('can_decide_leave', 'Can approve or reject leave for their own team'), ('can_decide_any_leave', 'Can approve or reject leave for anybody'), ('can_cancel_approved_leave', 'Can cancel an already approved leave'), ('can_manage_leave_types', 'Can maintain leave types and the holiday calendar')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Short handle, e.g. 'CL'.", max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_paid', models.BooleanField(default=True, help_text='Whether a day of this counts as paid. Read by payroll, not by this module.')),
                ('allow_half_day', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False, help_text='Whether an attachment is expected, e.g. a medical certificate.')),
                ('annual_quota', models.PositiveSmallIntegerField(default=0, help_text='Days per year. 0 means the balance is not tracked for this type.')),
                ('max_consecutive_days', models.PositiveSmallIntegerField(default=0, help_text='Longest single application allowed. 0 means no limit.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_types', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave type',
                'verbose_name_plural': 'Leave types',
                'ordering': ['company_id', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('portion', models.CharField(choices=[('FULL', 'Full day'), ('FIRST_HALF', 'First half'), ('SECOND_HALF', 'Second half')], default='FULL', max_length=12)),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('reason', models.TextField(help_text='Mandatory. A leave record nobody can explain later is not a record.')),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('document', models.FileField(blank=True, help_text='Medical certificate and the like, where the type asks for one.', null=True, upload_to='leave_documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by the applicant'), ('CANCELLED', 'Cancelled after approval')], db_index=True, default='PENDING', max_length=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('applied_by', models.ForeignKey(blank=True, help_text='The login that submitted it -- the time office when raised on behalf.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_applied', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Who is going to be away. Not necessarily who filled the form in.', on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employee_hierarchy.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype')),
            ],
            options={
                'verbose_name': 'Leave request',
                'verbose_name_plural': 'Leave requests',
                'ordering': ['-applied_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('is_optional', models.BooleanField(default=False, help_text='A restricted holiday: offered, but the plant still runs.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='uniq_holiday_per_company_date')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CANCELLED', 'Cancelled'), ('PROJECTED', 'Written to the attendance sheet'), ('UNPROJECTED', 'Removed from the attendance sheet')], max_length=15)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by the applicant'), ('CANCELLED', 'Cancelled after approval')], default='', max_length=12)),
                ('to_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by the applicant'), ('CANCELLED', 'Cancelled after approval')], default='', max_length=12)),
                ('comment', models.TextField(blank=True, default='')),
                ('authority', models.CharField(blank=True, default='', max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail', to='leave.leaverequest')),
            ],
            options={
                'verbose_name': 'Leave trail entry',
                'verbose_name_plural': 'Leave trail',
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['request', '-performed_at'], name='leave_leave_request_a093ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('portion', models.CharField(choices=[('FULL', 'Full day'), ('FIRST_HALF', 'First half'), ('SECOND_HALF', 'Second half')], default='FULL', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('is_projected', models.BooleanField(db_index=True, default=False)),
                ('projected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Copied off the request so one date can be locked per person.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to='employee_hierarchy.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='leave.leaverequest')),
            ],
            options={
                'verbose_name': 'Leave day',
                'verbose_name_plural': 'Leave days',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['status', 'is_projected', 'date'], name='leave_leave_status_7b7443_idx'), models.Index(fields=['employee', 'date'], name='leave_leave_employe_b40459_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'date'), name='uniq_leave_day_per_request_date'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('employee', 'date'), name='uniq_live_leave_day_per_employee')],
            },
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_leave_type_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', '-applied_at'], name='leave_leave_status_9eddbf_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', '-from_date'], name='leave_leave_employe_644662_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['company', 'from_date', 'to_date'], name='leave_leave_company_4e1834_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__gte', models.F('from_date'))), name='leave_request_dates_in_order'),
        ),
    ]
