# Generated by Django 6.0.1 on 2026-08-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProcessingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_orders', 'Can view order processing'), ('can_sync_orders', 'Can trigger an OMS sync'), ('can_allocate_stock', 'Can allocate stock to an order'), ('can_plan_production', 'Can raise production requirements'), ('can_plan_procurement', 'Can raise procurement requirements')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OmsSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('watermark_from', models.DateTimeField(blank=True, help_text="orders.updated_at we pulled FROM — the previous run's high-water mark.", null=True)),
                ('watermark_to', models.DateTimeField(blank=True, help_text='Highest orders.updated_at seen in this run.', null=True)),
                ('orders_seen', models.PositiveIntegerField(default=0)),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_updated', models.PositiveIntegerField(default=0)),
                ('lines_written', models.PositiveIntegerField(default=0)),
                ('issues_found', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OmsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oms_order_id', models.IntegerField(db_index=True, help_text='orders.id — the dedup key.', unique=True)),
                ('order_number', models.CharField(db_index=True, help_text='ORD-YYYYMMDD-NNNN', max_length=64)),
                ('customer_code', models.CharField(db_index=True, help_text='SAP OCRD.CardCode', max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('company_code', models.CharField(blank=True, help_text="orders.company — a varchar holding '1' (Jivo Wellness) or '2' (Jivo Mart).", max_length=10)),
                ('branch_bpl_id', models.IntegerField(blank=True, help_text='orders.dispatch_from_id = SAP BPL_ID.', null=True)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('oms_status', models.CharField(db_index=True, help_text='order_statuses.code', max_length=40)),
                ('order_type', models.CharField(blank=True, help_text='PARTY or STAFF', max_length=20)),
                ('po_number', models.CharField(blank=True, max_length=80)),
                ('ship_to_address', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_foc', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Parsed from orders.delivery_date, which is TEXT in OMS, not a date.', null=True)),
                ('delivery_date_raw', models.CharField(blank=True, help_text='The unparsed text, kept so an unparseable value is visible rather than lost.', max_length=64)),
                ('sap_created', models.BooleanField(default=False)),
                ('sap_doc_number', models.CharField(blank=True, max_length=50)),
                ('quotation_cancelled', models.BooleanField(default=False)),
                ('oms_created_at', models.DateTimeField(blank=True, null=True)),
                ('oms_updated_at', models.DateTimeField(blank=True, db_index=True, help_text='The sync watermark.', null=True)),
                ('state', models.CharField(choices=[('RECEIVED', 'Received from OMS'), ('VALIDATED', 'Validated'), ('STOCK_CHECKED', 'Stock checked'), ('PARTIALLY_AVAILABLE', 'Partially available'), ('STOCK_ALLOCATED', 'Stock allocated'), ('PRODUCTION_REQUIRED', 'Production required'), ('READY_FOR_FULFILLMENT', 'Ready for fulfillment'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On hold'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=25)),
                ('first_synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order_processing.omssyncrun')),
            ],
            options={
                'ordering': ['-oms_created_at', '-oms_order_id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, help_text='Ties every event from one operation together across services.', max_length=64)),
                ('event', models.CharField(db_index=True, max_length=60)),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, help_text='OMS / SAP / SYSTEM / USER', max_length=20)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('old_state', models.CharField(blank=True, max_length=40)),
                ('new_state', models.CharField(blank=True, max_length=40)),
                ('result', models.CharField(blank=True, help_text='OK / FAILED / SKIPPED', max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='order_proce_entity__cae131_idx')],
            },
        ),
        migrations.CreateModel(
            name='OmsOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oms_line_id', models.IntegerField(db_index=True, help_text='order_items.id', unique=True)),
                ('item_code', models.CharField(db_index=True, help_text='= SAP OITM.ItemCode', max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, help_text='OIL / BEVERAGES', max_length=40)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('sub_group', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='order_items.qty — the quantity SAP is sent.', max_digits=18)),
                ('pack_size', models.DecimalField(decimal_places=4, default=0, help_text='order_items.pcs — pieces per case.', max_digits=12)),
                ('cases', models.DecimalField(decimal_places=4, default=0, help_text='order_items.boxes = round(qty/pcs, 2).', max_digits=18)),
                ('litres', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('scheme_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('warehouse_code', models.CharField(blank=True, help_text='Resolved from category. Blank for BEVERAGES — OMS sends no WarehouseCode.', max_length=40)),
                ('issues', models.JSONField(blank=True, default=list, help_text='LineIssue codes. Empty means the line is trustworthy.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order_processing.omsorder')),
            ],
            options={
                'ordering': ['order_id', 'oms_line_id'],
                'indexes': [models.Index(fields=['item_code', 'warehouse_code'], name='order_proce_item_co_845c4f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='omsorder',
            index=models.Index(fields=['state', '-oms_created_at'], name='order_proce_state_980a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='omsorder',
            index=models.Index(fields=['oms_status', 'sap_created'], name='order_proce_oms_sta_696870_idx'),
        ),
    ]
