# Generated by Django 6.0.1 on 2026-08-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0001_initial'),
        ('production_execution', '0037_rated_speed_per_bottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('warehouse_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('sap_company', models.CharField(blank=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Total shortfall across every order pointing at this requirement.', max_digits=18)),
                ('needed_by', models.DateField(blank=True, help_text='Earliest delivery date among its source orders.', null=True)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required — not yet planned'), ('PLANNED', 'Planned into production'), ('IN_PROGRESS', 'Production in progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUIRED', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_run', models.ForeignKey(blank=True, help_text='Set when accepted into production. The run is the existing model.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requirements', to='production_execution.productionrun')),
            ],
            options={
                'ordering': ['needed_by', '-quantity'],
            },
        ),
        migrations.CreateModel(
            name='RequirementSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortfall', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_sources', to='order_processing.omsorderline')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_sources', to='order_processing.omsorder')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='order_processing.productionrequirement')),
            ],
            options={
                'ordering': ['order_id', 'line_id'],
            },
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_by', models.CharField(blank=True, max_length=150)),
                ('sap_company', models.CharField(blank=True, max_length=30)),
                ('verdict', models.CharField(db_index=True, max_length=12)),
                ('total_short', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_checks', to='order_processing.omsorder')),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCheckLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('warehouse_code', models.CharField(blank=True, max_length=40)),
                ('required', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('committed_in_sap', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('local_demand', models.DecimalField(decimal_places=4, default=0, help_text='Demand from orders SAP has not been told about.', max_digits=18)),
                ('available', models.DecimalField(decimal_places=4, default=0, help_text='Free in the booking warehouse.', max_digits=18)),
                ('available_in_group', models.DecimalField(decimal_places=4, default=0, help_text='Free across the configured sourcing warehouses too.', max_digits=18)),
                ('elsewhere', models.JSONField(blank=True, default=dict, help_text='warehouse -> free quantity, for the transfer note.')),
                ('allocatable', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('short', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('verdict', models.CharField(db_index=True, max_length=12)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_lines', to='order_processing.omsorderline')),
                ('stock_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order_processing.stockcheck')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUIRED', 'PLANNED'])), fields=('item_code', 'warehouse_code'), name='uniq_open_requirement_per_item_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='requirementsource',
            constraint=models.UniqueConstraint(fields=('requirement', 'line'), name='uniq_requirement_source_line'),
        ),
    ]
