# Generated by Django 6.0.1 on 2026-08-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0002_productionrequirement_requirementsource_stockcheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('warehouse_code', models.CharField(blank=True, max_length=40)),
                ('quantity_per_unit', models.DecimalField(decimal_places=8, default=0, help_text='From the BOM at the moment of explosion — a snapshot, not a live read.', max_digits=18)),
                ('gross_required', models.DecimalField(decimal_places=4, default=0, help_text='quantity_per_unit x the production quantity.', max_digits=18)),
                ('on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('committed', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('incoming_po', models.DecimalField(decimal_places=4, default=0, help_text='Open purchase orders (POR1.OpenQty).', max_digits=18)),
                ('net_required', models.DecimalField(decimal_places=4, default=0, help_text='What is genuinely missing after stock and open POs.', max_digits=18)),
                ('stock_known', models.BooleanField(default=True, help_text='False when SAP could not be read — net figures are then unusable.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='order_processing.productionrequirement')),
            ],
            options={
                'ordering': ['-net_required', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('warehouse_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('sap_company', models.CharField(blank=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Net requirement summed across the production requirements needing it.', max_digits=18)),
                ('incoming_po', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('REQUESTED', 'Requested'), ('ORDERED', 'Ordered in SAP'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUIRED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materials', models.ManyToManyField(blank=True, help_text='Which material lines drove this, for traceability.', related_name='procurements', to='order_processing.materialrequirement')),
            ],
            options={
                'ordering': ['needed_by', '-quantity'],
            },
        ),
        migrations.AddConstraint(
            model_name='materialrequirement',
            constraint=models.UniqueConstraint(fields=('requirement', 'item_code'), name='uniq_material_per_requirement'),
        ),
        migrations.AddConstraint(
            model_name='procurementrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUIRED', 'REQUESTED'])), fields=('item_code', 'warehouse_code'), name='uniq_open_procurement_per_item_warehouse'),
        ),
    ]
