# Generated by Django 6.0.1 on 2026-09-21 12:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('log_date', models.DateField()),
                ('work_done', models.TextField(help_text='What got done today')),
                ('workers_count', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative completion. Optional, and it may not go backwards.', max_digits=5, null=True)),
                ('work_stopped', models.BooleanField(default=False)),
                ('stopped_reason', models.CharField(blank=True, choices=[('RAIN', 'Rain'), ('NO_MATERIAL', 'Material not available'), ('NO_LABOUR', 'Labour not available'), ('NO_POWER', 'No power'), ('HOLIDAY', 'Holiday'), ('APPROVAL_PENDING', 'Waiting on an approval'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'ordering': ['-log_date', '-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DailyLogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.FileField(upload_to='construction/daily-logs/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='construction_projects.dailylog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Log Photo',
                'verbose_name_plural': 'Daily Log Photos',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', help_text='Where on the campus', max_length=200)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(help_text='When this is expected to finish')),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='The budget being asked for', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('sanctioned_at', models.DateTimeField(blank=True, null=True)),
                ('sanctioned_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_projects', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_projects_decided', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_projects_managed', to=settings.AUTH_USER_MODEL)),
                ('site_incharge', models.ForeignKey(blank=True, help_text='Who fills the daily log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_projects_site', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_projects_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Project',
                'verbose_name_plural': 'Construction Projects',
                'ordering': ['-created_at'],
                'permissions': [('can_view_project', 'Can view construction projects'), ('can_view_all_projects', 'Can view every construction project'), ('can_create_project', 'Can raise a construction project'), ('can_edit_project', 'Can edit a construction project'), ('can_approve_project', 'Can approve a project or its revisions'), ('can_log_daily_work', 'Can write the daily site log'), ('can_record_expense', 'Can record construction spend'), ('can_close_project', 'Can hold, complete or cancel a project')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('spend_date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOUR', 'Labour'), ('CONTRACTOR', 'Contractor'), ('EQUIPMENT_HIRE', 'Equipment hire'), ('TRANSPORT', 'Transport'), ('PROFESSIONAL_FEES', 'Professional fees'), ('STATUTORY', 'Statutory / fees'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(help_text='e.g. "90 bags cement", "mason wages, 6 days"', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_to', models.CharField(blank=True, default='', max_length=200)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('CREDIT', 'On credit (not yet paid)')], default='CASH', max_length=10)),
                ('reference_no', models.CharField(blank=True, default='', help_text='Bill no, UTR or cheque no', max_length=60)),
                ('bill', models.FileField(blank=True, null=True, upload_to='construction/bills/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='construction_projects.project')),
            ],
            options={
                'verbose_name': 'Construction Expense',
                'verbose_name_plural': 'Construction Expenses',
                'ordering': ['-spend_date', '-id'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='construction_projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revision_no', models.PositiveIntegerField()),
                ('additional_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra budget asked for. Zero means this is a timeline-only ask.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('new_end_date', models.DateField(blank=True, help_text='The new expected ending, if it is moving', null=True)),
                ('reason', models.TextField()),
                ('budget_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('end_date_before', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_revisions_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='construction_projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_revisions_requested', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Revision',
                'verbose_name_plural': 'Project Revisions',
                'ordering': ['project_id', 'revision_no'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProjectSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_project_sequences', to='company.company')),
            ],
            options={
                'verbose_name': 'Project Number Sequence',
                'verbose_name_plural': 'Project Number Sequences',
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='constructio_company_dc810a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager'], name='constructio_manager_a02379_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['expected_end_date'], name='constructio_expecte_2197b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'spend_date'], name='constructio_project_212e61_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'category'], name='constructio_project_c696b5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['project', 'log_date'], name='constructio_project_787732_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('project', 'log_date')},
        ),
        migrations.AddIndex(
            model_name='projectrevision',
            index=models.Index(fields=['status'], name='constructio_status_0cf12b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrevision',
            unique_together={('project', 'revision_no')},
        ),
        migrations.AddConstraint(
            model_name='projectsequence',
            constraint=models.UniqueConstraint(fields=('company', 'year'), name='uniq_construction_project_sequence'),
        ),
    ]
