# Generated by Django 6.0.1 on 2026-09-22 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_projects', '0003_project_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('can_view_project', 'Can view construction projects'), ('can_view_all_projects', 'Can view every construction project'), ('can_create_project', 'Can raise a construction project'), ('can_edit_project', 'Can edit a construction project'), ('can_approve_project', 'Can approve a project or its revisions'), ('can_log_daily_work', 'Can write the daily site log'), ('can_record_expense', 'Can record construction spend'), ('can_approve_expense', "Can approve or disallow a day's spend"), ('can_close_project', 'Can hold, complete or cancel a project')], 'verbose_name': 'Construction Project', 'verbose_name_plural': 'Construction Projects'},
        ),
        migrations.AddField(
            model_name='expense',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_expenses_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='decision_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Disallowed')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'status'], name='constructio_project_ead507_idx'),
        ),
    ]
