# Generated by Django 6.0.1 on 2026-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_projects', '0007_align_batch_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebatch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Not sent yet'), ('SUBMITTED', 'Waiting for approval'), ('APPROVED', 'Approved'), ('RETURNED', 'Sent back for changes')], db_index=True, default='OPEN', max_length=10),
        ),
    ]
