# Generated by Django 6.0.1 on 2026-10-10 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('construction_projects', '0010_attachments_know_a_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_unit', models.CharField(choices=[('SQFT', 'sq ft'), ('RFT', 'running ft'), ('CUFT', 'cu ft'), ('NOS', 'nos')], default='SQFT', max_length=10)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'On hold'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('stage', models.CharField(blank=True, default='', help_text="Where it stands, in the site's words: 7th layer, WBM complete", max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('contractor', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='civil_works', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The project this work is part of; empty for a project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='construction_projects.civilwork')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Civil Work',
                'verbose_name_plural': 'Civil Works',
                'ordering': ['position', 'id'],
                'permissions': [('can_view_civil_works', 'Can view the civil works sheet'), ('can_edit_civil_works', 'Can edit the civil works sheet')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'parent', 'position'], name='constructio_company_171b2c_idx')],
            },
        ),
    ]
