# Generated by Django 6.0.1 on 2026-07-18 10:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlowingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('cavities', models.PositiveSmallIntegerField(blank=True, help_text='Number of mould cavities', null=True)),
                ('sap_warehouse_code', models.CharField(blank=True, default='', help_text='SAP production warehouse for this machine (later postings phase)', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blowing_machines', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blowing Machine',
                'verbose_name_plural': 'Blowing Machines',
                'ordering': ['company_id', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BlowingRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('operator_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('labour_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('electricity_rate_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('preform_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('scrap_rate_per_bottle', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('packing_rate_per_bottle', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blowing_rate_configs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blowing Rate Config',
                'verbose_name_plural': 'Blowing Rate Configs',
                'ordering': ['company_id', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='BlowingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('run_number', models.PositiveSmallIntegerField(help_text='Sequential per company per date')),
                ('date', models.DateField()),
                ('preform_boxes_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('machine_start_reading', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('machine_stop_reading', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('utility_units', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('total_counter_production', models.PositiveIntegerField(default=0)),
                ('rejection_pcs', models.PositiveIntegerField(default=0)),
                ('operator_count', models.PositiveIntegerField(default=0)),
                ('contract_labour_count', models.PositiveIntegerField(default=0)),
                ('own_labour_count', models.PositiveIntegerField(default=0)),
                ('scrap_carton_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Manually entered carton-scrap recovery value', max_digits=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('operator_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('labour_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('electricity_rate_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('preform_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('scrap_rate_per_bottle', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('packing_rate_per_bottle', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('machine_units', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('total_units', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('preform_used_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('rejection_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('total_manpower', models.PositiveIntegerField(default=0)),
                ('sap_preform_item_code', models.CharField(blank=True, default='', max_length=50)),
                ('sap_bottle_item_code', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blowing_runs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='blowing.blowingmachine')),
                ('rate_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='blowing.blowingrateconfig')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blowing Run',
                'verbose_name_plural': 'Blowing Runs',
                'ordering': ['-date', 'company_id', 'run_number'],
                'permissions': [('can_view_blowing_run', 'Can view blowing run'), ('can_create_blowing_run', 'Can create blowing run'), ('can_edit_blowing_run', 'Can edit blowing run'), ('can_complete_blowing_run', 'Can complete blowing run'), ('can_manage_blowing_machines', 'Can manage blowing machines'), ('can_manage_preform_specs', 'Can manage preform specs'), ('can_manage_blowing_rate_config', 'Can manage blowing rate config'), ('can_view_blowing_reports', 'Can view blowing reports')],
            },
        ),
        migrations.CreateModel(
            name='BlowingRunCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('wastage_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('scrap_bottle_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('scrap_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('blowing_cost_per_bottle', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('packing_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('per_bottle_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_summary', to='blowing.blowingrun')),
            ],
            options={
                'verbose_name': 'Blowing Run Cost',
                'verbose_name_plural': 'Blowing Run Costs',
            },
        ),
        migrations.CreateModel(
            name='PreformSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('make', models.CharField(help_text='e.g. Frystal', max_length=100)),
                ('gram', models.DecimalField(decimal_places=2, help_text='Preform weight in grams', max_digits=6)),
                ('preforms_per_box', models.PositiveIntegerField(help_text='Preform pieces in one box (for box -> grams conversion)')),
                ('sap_item_code', models.CharField(blank=True, default='', max_length=50)),
                ('sap_item_name', models.CharField(blank=True, default='', max_length=200)),
                ('bottle_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bottles_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preform_specs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preform Spec',
                'verbose_name_plural': 'Preform Specs',
                'ordering': ['company_id', 'make', 'gram'],
                'unique_together': {('company', 'make', 'gram')},
            },
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='preform_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='blowing.preformspec'),
        ),
        migrations.AddIndex(
            model_name='blowingrun',
            index=models.Index(fields=['company', 'date'], name='blowing_blo_company_22738c_idx'),
        ),
        migrations.AddIndex(
            model_name='blowingrun',
            index=models.Index(fields=['status'], name='blowing_blo_status_810a90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blowingrun',
            unique_together={('company', 'date', 'run_number')},
        ),
    ]
