# Generated by Django 6.0.1 on 2026-07-20 04:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0002_create_blowing_group'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blowingmachine',
            name='depreciation_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Straight-line machine depreciation per operating day (fixed cost)', max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrateconfig',
            name='factory_overhead_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrateconfig',
            name='maintenance_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrateconfig',
            name='qa_cost_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='factory_overhead_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='machine_depreciation_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='maintenance_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='mould_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='mould_life_bottles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='qa_cost_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='fixed_cost_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='fully_loaded_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='good_bottles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='machine_depreciation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='make_cost_per_bottle',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='mould_amortization',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='preform_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='qa_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='variable_cost_per_bottle',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='blowingruncost',
            name='variable_cost_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='preformspec',
            name='mould_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mould/tooling capital cost for this size', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='preformspec',
            name='mould_life_bottles',
            field=models.PositiveIntegerField(blank=True, help_text='Expected mould life in bottles (shots)', null=True),
        ),
        migrations.CreateModel(
            name='BottleBuyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('effective_from', models.DateField()),
                ('buy_price', models.DecimalField(decimal_places=4, help_text='Supplier unit price per bottle', max_digits=12)),
                ('freight_per_bottle', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('duties_per_bottle', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('carrying_pct_annual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Inventory carrying cost %/yr (typ. 18-25)', max_digits=6)),
                ('inventory_days', models.PositiveIntegerField(default=30, help_text='Avg days of bottle inventory held (for carrying cost)')),
                ('qa_allowance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Incoming reject / QA allowance %', max_digits=6)),
                ('risk_premium_per_bottle', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottle_buy_prices', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('preform_spec', models.ForeignKey(help_text='The bottle size this quote is for', on_delete=django.db.models.deletion.PROTECT, related_name='buy_prices', to='blowing.preformspec')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bottle Buy Price',
                'verbose_name_plural': 'Bottle Buy Prices',
                'ordering': ['company_id', 'preform_spec_id', '-effective_from'],
            },
        ),
    ]
