# Generated by Django 6.0.1 on 2026-07-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0003_blowingmachine_depreciation_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preformspec',
            name='std_make_cost_per_bottle',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Target fully-loaded make cost per bottle', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='preformspec',
            name='std_reject_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Target rejection %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='preformspec',
            name='std_units_per_bottle',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Target electricity units per bottle', max_digits=10, null=True),
        ),
    ]
