# Generated by Django 6.0.1 on 2026-07-20 05:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0004_preformspec_std_make_cost_per_bottle_and_more'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blowingrun',
            options={'ordering': ['-date', 'company_id', 'run_number'], 'permissions': [('can_view_blowing_run', 'Can view blowing run'), ('can_create_blowing_run', 'Can create blowing run'), ('can_edit_blowing_run', 'Can edit blowing run'), ('can_complete_blowing_run', 'Can complete blowing run'), ('can_manage_blowing_machines', 'Can manage blowing machines'), ('can_manage_preform_specs', 'Can manage preform specs'), ('can_manage_blowing_rate_config', 'Can manage blowing rate config'), ('can_view_blowing_reports', 'Can view blowing reports'), ('can_create_blowing_breakdown', 'Can create blowing breakdown'), ('can_manage_blowing_breakdown_categories', 'Can manage blowing breakdown categories'), ('can_request_preform', 'Can request preform from warehouse'), ('can_approve_preform_request', 'Can approve preform request')], 'verbose_name': 'Blowing Run', 'verbose_name_plural': 'Blowing Runs'},
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='total_breakdown_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='total_running_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='warehouse_approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', max_length=25),
        ),
        migrations.CreateModel(
            name='BlowingBreakdownCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blowing_breakdown_categories', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blowing Breakdown Category',
                'verbose_name_plural': 'Blowing Breakdown Categories',
                'ordering': ['company_id', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BlowingBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('breakdown_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_unrecovered', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blowing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='blowing.blowingrun')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdowns', to='blowing.blowingmachine')),
                ('breakdown_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='breakdowns', to='blowing.blowingbreakdowncategory')),
            ],
            options={
                'verbose_name': 'Blowing Breakdown',
                'verbose_name_plural': 'Blowing Breakdowns',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlowingPreformRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_item_code', models.CharField(blank=True, default='', max_length=50)),
                ('sap_item_name', models.CharField(blank=True, default='', max_length=200)),
                ('warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('uom', models.CharField(blank=True, default='PCS', max_length=20)),
                ('required_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('available_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('approved_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('blowing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preform_requests', to='blowing.blowingrun')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blowing_preform_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blowing_preform_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blowing_preform_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blowing Preform Request',
                'verbose_name_plural': 'Blowing Preform Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlowingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('produced_pcs', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blowing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='blowing.blowingrun')),
            ],
            options={
                'verbose_name': 'Blowing Segment',
                'verbose_name_plural': 'Blowing Segments',
                'ordering': ['start_time'],
            },
        ),
    ]
