# Generated by Django 6.0.1 on 2026-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0007_rename_cavities_to_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blowingmachine',
            name='heads',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of blowing heads (bottles per cycle)', null=True),
        ),
    ]
