# Generated by Django 6.0.1 on 2026-07-20 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0008_alter_blowingmachine_heads'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlowingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blowing_audit_logs', to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blowing_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blowing Audit Log',
                'verbose_name_plural': 'Blowing Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'entity_type', 'entity_id'], name='blowing_blo_company_93d25a_idx')],
            },
        ),
    ]
