# Generated by Django 6.0.1 on 2026-07-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0009_blowingauditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlowingPreformRequest',
        ),
    ]
