# Generated by Django 6.0.1 on 2026-07-28 11:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0011_reset_orphaned_preform_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blowingrateconfig',
            name='preform_rate_per_kg',
        ),
        migrations.RemoveField(
            model_name='blowingrun',
            name='preform_rate_per_kg',
        ),
        migrations.AddField(
            model_name='blowingrun',
            name='preform_rate_per_bottle',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='preformspec',
            name='preform_rate_per_bottle',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Preform cost per bottle (per piece) — each preform variant has its own rate', max_digits=10),
        ),
    ]
