# Generated by Django 6.0.1 on 2026-07-30 06:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0014_seed_blowing_cost_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='blowingrun',
            name='utility_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed utility electricity charge for the day (₹), entered per run.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='blowingcostrate',
            name='category',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('LABOUR', 'Labour (contract + own)'), ('ELECTRICITY_MACHINE', 'Electricity — Machine (metered)'), ('ELECTRICITY_UTILITY', 'Electricity — Utility (fixed/day)'), ('PACKING', 'Packing'), ('SCRAP_RECOVERY', 'Scrap Recovery'), ('WASTAGE', 'Wastage (rejected preforms)'), ('BENCHMARK_BLOWING_PER_BOTTLE', 'Industry Blowing Cost / Bottle (benchmark)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='blowingrun',
            name='utility_units',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Deprecated — superseded by utility_cost (fixed ₹/day).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='blowingruncostline',
            name='category',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('LABOUR', 'Labour (contract + own)'), ('ELECTRICITY_MACHINE', 'Electricity — Machine (metered)'), ('ELECTRICITY_UTILITY', 'Electricity — Utility (fixed/day)'), ('PACKING', 'Packing'), ('SCRAP_RECOVERY', 'Scrap Recovery'), ('WASTAGE', 'Wastage (rejected preforms)'), ('BENCHMARK_BLOWING_PER_BOTTLE', 'Industry Blowing Cost / Bottle (benchmark)')], max_length=40),
        ),
    ]
