# Generated by Django 6.0.1 on 2026-07-30 15:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0015_blowingrun_utility_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blowingrun',
            name='utility_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deprecated — utility electricity is now metered from utility_units × ₹/unit.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='blowingrun',
            name='utility_units',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Utility electricity units the operator reads per run (metered × ₹/unit).', max_digits=12),
        ),
    ]
