# Generated by Django 6.0.1 on 2026-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0016_alter_blowingrun_utility_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blowingcostrate',
            name='category',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('LABOUR', 'Labour (contract + own)'), ('ELECTRICITY_MACHINE', 'Electricity — Machine (metered)'), ('ELECTRICITY_UTILITY', 'Electricity — Utility (metered)'), ('PACKING', 'Packing'), ('SCRAP_RECOVERY', 'Scrap Recovery'), ('WASTAGE', 'Wastage (rejected preforms)'), ('BENCHMARK_BLOWING_PER_BOTTLE', 'Industry Blowing Cost / Bottle (benchmark)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='blowingruncostline',
            name='category',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('LABOUR', 'Labour (contract + own)'), ('ELECTRICITY_MACHINE', 'Electricity — Machine (metered)'), ('ELECTRICITY_UTILITY', 'Electricity — Utility (metered)'), ('PACKING', 'Packing'), ('SCRAP_RECOVERY', 'Scrap Recovery'), ('WASTAGE', 'Wastage (rejected preforms)'), ('BENCHMARK_BLOWING_PER_BOTTLE', 'Industry Blowing Cost / Bottle (benchmark)')], max_length=40),
        ),
    ]
