# Generated by Django 6.0.1 on 2026-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0017_alter_blowingcostrate_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preformspec',
            name='std_make_cost_per_bottle',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Target blowing (conversion) cost per bottle — excludes the preform', max_digits=12, null=True),
        ),
    ]
