# Generated by Django 6.0.1 on 2026-08-10 06:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_supply_chain', 'Can view the supply chain dashboard'), ('can_manage_supply_chain_reference', 'Can upload/edit supply chain reference data')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReferenceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('lead_times_loaded', models.PositiveIntegerField(default=0)),
                ('machines_loaded', models.PositiveIntegerField(default=0)),
                ('mappings_loaded', models.PositiveIntegerField(default=0)),
                ('examples_skipped', models.PositiveIntegerField(default=0, help_text='Grey italic template example rows, which must never load as data.')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('imported_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyChainPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('floor_percent', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Safety-stock floor as a percentage of the sales trend. The brief says 35%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('floor_basis', models.CharField(choices=[('MONTHLY_AVERAGE', '35% of the monthly average'), ('THREE_MONTH_TOTAL', '35% of the three-month total')], default='MONTHLY_AVERAGE', help_text='What the percentage applies to. The brief does not say; the two differ by 3x.', max_length=20)),
                ('urgency_window_days', models.PositiveIntegerField(default=7, help_text='Order-by dates inside this many days read as ORDER_NOW rather than SCHEDULED.')),
                ('use_net_of_open_po', models.BooleanField(default=True, help_text='Drive alarms from net_shortage_qty (requirement less open purchase orders) rather than the gross requirement. Off means already-ordered material is ordered again every cycle.')),
                ('apply_moq_rounding', models.BooleanField(default=True, help_text="Round each order quantity up to the supplier's MOQ. The template collects MOQ.")),
                ('include_changeover_in_capacity', models.BooleanField(default=True, help_text="Deduct changeover time from a machine's available hours. The template collects changeover minutes; ignoring them passes plans the floor cannot run.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Supply chain policies',
            },
        ),
        migrations.CreateModel(
            name='MachineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('machine_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('pack_type', models.CharField(blank=True, max_length=80)),
                ('pack_size_range', models.CharField(blank=True, max_length=80)),
                ('output_per_hour', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('shift_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shifts_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('working_days_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('changeover_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Machine capacities',
                'ordering': ['machine_id'],
                'constraints': [models.UniqueConstraint(fields=('company_code', 'machine_id'), name='uniq_sc_machine')],
            },
        ),
        migrations.CreateModel(
            name='MaterialLeadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('material_type', models.CharField(choices=[('PACKAGING', 'Packaging'), ('RAW', 'Oil / Raw Material')], default='PACKAGING', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Category / spec, e.g. Cap', max_length=120)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Order placed -> material usable in production.')),
                ('moq', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_code'],
                'constraints': [models.UniqueConstraint(fields=('company_code', 'material_code'), name='uniq_sc_lead_time_material')],
            },
        ),
        migrations.CreateModel(
            name='MaterialMachineMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('sku_code', models.CharField(db_index=True, max_length=100)),
                ('sku_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('pack_type', models.CharField(blank=True, max_length=80)),
                ('pack_size', models.CharField(blank=True, max_length=80)),
                ('primary_machine_id', models.CharField(db_index=True, max_length=50)),
                ('alternate_machine_ids', models.CharField(blank=True, help_text='Comma-separated, as in the template.', max_length=200)),
                ('output_on_primary', models.DecimalField(decimal_places=4, default=0, help_text="Units/hour for THIS SKU. Falls back to the machine's own rate when 0.", max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sku_code'],
                'constraints': [models.UniqueConstraint(fields=('company_code', 'sku_code'), name='uniq_sc_sku_machine')],
            },
        ),
    ]
