# Generated by Django 6.0.1 on 2026-08-10 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(blank=True, help_text='e.g. Packaging Procurement', max_length=120)),
                ('permission_codename', models.CharField(help_text='Everyone holding this permission is notified, directly or via a group.', max_length=100)),
                ('include_overdue', models.BooleanField(default=True)),
                ('include_order_now', models.BooleanField(default=True)),
                ('include_missing_lead_time', models.BooleanField(default=False, help_text='Materials with no lead time on file — chase the reference data.')),
                ('include_capacity', models.BooleanField(default=False, help_text='Also alarm when a line is over capacity.')),
                ('material_type', models.CharField(blank=True, choices=[('PACKAGING', 'Packaging'), ('RAW', 'Oil / Raw Material')], help_text='Limit to packaging or raw material. Blank = everything.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_code', 'label'],
            },
        ),
        migrations.AddField(
            model_name='supplychainpolicy',
            name='floor_source',
            field=models.CharField(choices=[('PROCEDURE', 'min_stock as returned by the HANA procedure'), ('POLICY', 'Recomputed here from the 3-month sales trend')], default='POLICY', help_text="POLICY enforces the brief's own floor rule, but only for items with a SalesTrend on file — everything else keeps the procedure's min_stock, so switching this changes nothing until trend data is loaded.", max_length=20),
        ),
        migrations.CreateModel(
            name='SalesTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('three_month_qty', models.DecimalField(decimal_places=6, default=0, help_text='Total units sold over the trailing three months.', max_digits=24)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Where the figure came from, e.g. ERP or CSV.', max_length=40)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_code'],
                'constraints': [models.UniqueConstraint(fields=('company_code', 'item_code'), name='uniq_sc_sales_trend_item')],
            },
        ),
        migrations.CreateModel(
            name='AlarmDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('digest', models.CharField(db_index=True, help_text='Fingerprint of the alarm content, so an unchanged digest is not re-sent.', max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('overdue_count', models.PositiveIntegerField(default=0)),
                ('order_now_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='supply_chain.alarmsubscription')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['company_code', '-sent_at'], name='supply_chai_company_0e13b8_idx')],
            },
        ),
    ]
