# Generated by Django 6.0.1 on 2026-08-10 09:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_alarmsubscription_supplychainpolicy_floor_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lead_time_percentile', models.PositiveIntegerField(default=80, help_text='Which percentile of past deliveries to trust. 80 = right 8 times out of 10.')),
                ('min_delivery_samples', models.PositiveIntegerField(default=3, help_text='Below this many samples, a measured lead time is not trusted.')),
                ('amber_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Cover below lead time x this, but above lead time, reads AMBER.', max_digits=5)),
                ('working_days_per_month', models.DecimalField(decimal_places=2, default=Decimal('26'), help_text='Used to convert days of cover (production days) into calendar days.', max_digits=5)),
                ('calendar_days_per_month', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5)),
                ('max_red_before_block', models.PositiveIntegerField(default=25, help_text="More red rows than this blocks the run from being published: the playbook's rule that a flood of alarms means bad inputs, not a crisis.")),
                ('last_changed_reason', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Operating parameters',
            },
        ),
        migrations.CreateModel(
            name='DailyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('run_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated — not yet reviewed'), ('REVIEWED', 'Reviewed by the analyst'), ('PUBLISHED', 'Published to the buyer and HODs'), ('BLOCKED', 'Blocked — too many alarms to be credible')], default='GENERATED', max_length=20)),
                ('red_count', models.PositiveIntegerField(default=0)),
                ('amber_count', models.PositiveIntegerField(default=0)),
                ('green_count', models.PositiveIntegerField(default=0)),
                ('unknown_count', models.PositiveIntegerField(default=0)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, help_text='The one line the analyst writes: what changed since yesterday.')),
                ('parameters_snapshot', models.JSONField(blank=True, default=dict, help_text='The parameters in force when this run was built, so an old run still explains itself.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.CharField(blank=True, max_length=150)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-run_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company_code', 'run_date'), name='uniq_sc_daily_run_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyRunRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(db_index=True, max_length=100)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('material_type', models.CharField(blank=True, max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('units_per_day', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('quantity_per_unit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('consumption_per_day', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('on_hand', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('committed', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('free_stock', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('days_of_cover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cover_calendar_days', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time_source', models.CharField(blank=True, help_text='MEASURED, TEMPLATE, or blank when unknown.', max_length=30)),
                ('lead_time_samples', models.PositiveIntegerField(default=0)),
                ('stockout_date', models.DateField(blank=True, null=True)),
                ('order_by_date', models.DateField(blank=True, null=True)),
                ('days_late', models.IntegerField(default=0)),
                ('verdict', models.CharField(choices=[('RED', 'Order today'), ('AMBER', 'Getting close'), ('GREEN', 'Fine'), ('UNKNOWN', 'Could not be judged')], default='UNKNOWN', max_length=10)),
                ('owner', models.CharField(blank=True, help_text='Named person. A red row nobody owns will not get done.', max_length=150)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='supply_chain.dailyrun')),
            ],
            options={
                'ordering': ['-days_late', 'days_of_cover', 'material_code'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('sku_code', models.CharField(blank=True, max_length=100)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('blocking', models.BooleanField(default=False, help_text='True when it stopped a material being judged at all.')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='supply_chain.dailyrun')),
            ],
            options={
                'ordering': ['-blocking', 'code', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('on_hand', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('committed', models.DecimalField(decimal_places=6, default=0, help_text='Already promised to other production orders.', max_digits=24)),
                ('warehouses', models.CharField(blank=True, help_text='Which godowns this figure covers.', max_length=255)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_code'],
                'constraints': [models.UniqueConstraint(fields=('company_code', 'material_code'), name='uniq_sc_material_stock')],
            },
        ),
        migrations.CreateModel(
            name='MonitoredSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('sku_code', models.CharField(db_index=True, max_length=100)),
                ('sku_name', models.CharField(blank=True, max_length=255)),
                ('plan_quantity', models.DecimalField(decimal_places=6, default=0, help_text='Units still to make this period. From the plan, less what is already made.', max_digits=24)),
                ('working_days_left', models.PositiveIntegerField(default=0, help_text='Production days remaining in the period.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sku_code'],
                'constraints': [models.UniqueConstraint(fields=('company_code', 'sku_code'), name='uniq_sc_monitored_sku')],
            },
        ),
        migrations.CreateModel(
            name='RowVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('REAL', 'Real — we were genuinely short'), ('WRONG_DATA', 'Wrong data — stock or PO in SAP was not correct'), ('ALREADY_HANDLED', 'Already handled — material was coming')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('supplier_promised_date', models.DateField(blank=True, help_text='The date the supplier actually committed to on the call.', null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='row_verdict', to='supply_chain.dailyrunrow')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SkuComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('material_type', models.CharField(choices=[('PACKAGING', 'Packaging'), ('RAW', 'Oil / Raw Material')], default='PACKAGING', max_length=20)),
                ('quantity_per_unit', models.DecimalField(decimal_places=8, default=1, help_text='e.g. 1 cap per bottle; 0.05 carton per bottle (20 to a carton).', max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='supply_chain.monitoredsku')),
            ],
            options={
                'ordering': ['material_code'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('ordered_on', models.DateField()),
                ('received_on', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('reference', models.CharField(blank=True, help_text='PO number.', max_length=80)),
            ],
            options={
                'ordering': ['material_code', '-received_on'],
                'indexes': [models.Index(fields=['company_code', 'material_code'], name='supply_chai_company_6a7fb1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dailyrunrow',
            index=models.Index(fields=['run', 'verdict'], name='supply_chai_run_id_51d511_idx'),
        ),
        migrations.AddConstraint(
            model_name='skucomponent',
            constraint=models.UniqueConstraint(fields=('sku', 'material_code'), name='uniq_sc_sku_component'),
        ),
    ]
