# Generated by Django 6.0.1 on 2026-08-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_operatingparameters_dailyrun_dailyrunrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmsubscription',
            name='live_trail_department',
            field=models.CharField(blank=True, db_index=True, help_text='Bind this subscription to one Live Trail department: PRODUCTION, PACKAGING_PROCUREMENT, RAW_PROCUREMENT, INFRASTRUCTURE or FINANCE. Leave blank and the autopilot falls back to the supply-chain view permission, so a department nobody has bound still gets told.', max_length=40),
        ),
    ]
