# Generated by Django 6.0.1 on 2026-09-16 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_user_employee_code'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_date', models.DateField(help_text='The day the labour is needed')),
                ('shift', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], default='DAY', max_length=5)),
                ('requested_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', help_text='What the labour is for', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approved_count', models.PositiveIntegerField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_requests_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_requests', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Request',
                'verbose_name_plural': 'Labour Requests',
                'ordering': ['-work_date', 'shift', 'department_id'],
                'permissions': [('can_view_labour_request', 'Can view labour requests'), ('can_raise_labour_request', 'Can raise a labour request for a department'), ('can_decide_labour_request', 'Can approve or reject a labour request')],
            },
        ),
        migrations.CreateModel(
            name='LabourRequestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Raised request'), ('UPDATE', 'Updated request'), ('APPROVE', 'Approved request'), ('REJECT', 'Rejected request'), ('REOPEN', 'Reopened request'), ('DELETE', 'Deleted request'), ('RESTORE', 'Restored request')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('old_value', models.IntegerField(blank=True, null=True)),
                ('new_value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_request_audits', to='company.company')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_request_audits', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='labour_request.labourrequest')),
            ],
            options={
                'verbose_name': 'Labour Request Audit',
                'verbose_name_plural': 'Labour Request Audit',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='labourrequest',
            index=models.Index(fields=['work_date', 'shift'], name='labour_requ_work_da_877fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='labourrequest',
            index=models.Index(fields=['status'], name='labour_requ_status_d6d713_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labourrequest',
            unique_together={('company', 'department', 'work_date', 'shift')},
        ),
        migrations.AddIndex(
            model_name='labourrequestaudit',
            index=models.Index(fields=['request', 'created_at'], name='labour_requ_request_ae727a_idx'),
        ),
    ]
