# Generated by Django 6.0.3 on 2026-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_stock_dashboard', 'Can view Stock Dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StockAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=50)),
                ('warehouse', models.CharField(max_length=20)),
                ('stock_status', models.CharField(choices=[('low', 'Low'), ('critical', 'Critical')], max_length=10)),
                ('on_hand', models.FloatField()),
                ('min_stock', models.FloatField()),
                ('notified_at', models.DateTimeField(auto_now=True)),
                ('cooldown_until', models.DateTimeField(help_text='Do not re-send this alert until after this timestamp')),
            ],
            options={
                'indexes': [models.Index(fields=['cooldown_until'], name='stock_dashb_cooldow_dd9b05_idx')],
                'unique_together': {('company_code', 'item_code', 'warehouse')},
            },
        ),
    ]
