# Generated by Django 6.0.1 on 2026-09-11 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50)),
                ('warehouse', models.CharField(max_length=20)),
                ('capacity_tonnes', models.DecimalField(blank=True, decimal_places=2, help_text='Rated capacity in tonnes. Leave empty where the warehouse has no rated figure.', max_digits=12, null=True)),
                ('last_audit_date', models.DateField(blank=True, help_text='When stock in this warehouse was last physically verified.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_board_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse board settings',
                'verbose_name_plural': 'Warehouse board settings',
                'unique_together': {('company_code', 'warehouse')},
            },
        ),
    ]
