# Generated by Django 6.0.1 on 2026-09-11 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0002_warehouseboardsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsBoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, unique=True)),
                ('owned_vehicles', models.PositiveIntegerField(blank=True, help_text='Trucks the company owns. Leave empty if not tracked.', null=True)),
                ('warehouse_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('warehouse_salary_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dispatch_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('dispatch_salary_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transport_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('transport_salary_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_board_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistics board settings',
                'verbose_name_plural': 'Logistics board settings',
            },
        ),
    ]
