# Generated by Django 6.0.1 on 2026-09-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0003_logisticsboardsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsboardsettings',
            name='labour_rate_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What one labourer costs for a day. Priced against the gate's own head count. Leave empty to fall back to the Cost Master rate.", max_digits=10, null=True),
        ),
    ]
