# Generated by Django 6.0.1 on 2026-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0004_logisticsboardsettings_labour_rate_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsboardsettings',
            name='owned_vehicle_numbers',
            field=models.TextField(blank=True, default='', help_text="Registrations of the trucks the company owns, one per line. The board looks each one up in today's gate arrivals to say whether it is working or free."),
        ),
    ]
