# Generated by Django 6.0.1 on 2026-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0005_logisticsboardsettings_owned_vehicle_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsboardsettings',
            name='vehicles_out_of_service',
            field=models.TextField(blank=True, default='', help_text='Registrations that are off the road -- damaged, in the workshop, sold. One per line. Nothing in any feed records this.'),
        ),
    ]
