# Generated by Django 6.0.1 on 2026-09-11 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0006_logisticsboardsettings_vehicles_out_of_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBoardWorkforce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=64)),
                ('employees', models.PositiveIntegerField(blank=True, help_text='People in this department. Leave empty if nobody has counted.', null=True)),
                ('salary_monthly', models.DecimalField(blank=True, decimal_places=2, help_text="The department's wage bill for a MONTH. The board divides it by the days in the month to show a daily run rate.", max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_board_workforce_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant board workforce',
                'verbose_name_plural': 'Plant board workforce',
                'unique_together': {('company_code', 'department')},
            },
        ),
    ]
