# Generated by Django 6.0.1 on 2026-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0007_plantboardworkforce'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantboardworkforce',
            name='band',
            field=models.CharField(blank=True, default='', help_text="Which band's workforce strip this department reports under: purchase, store, production or shifting. Blank on a built-in.", max_length=20),
        ),
        migrations.AddField(
            model_name='plantboardworkforce',
            name='kind',
            field=models.CharField(blank=True, default='', help_text="'employee' for people on the payroll, 'labour' for hired in. Blank on a built-in.", max_length=20),
        ),
        migrations.AddField(
            model_name='plantboardworkforce',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Display name. Blank on a built-in department, which takes its name from the code catalogue.', max_length=120),
        ),
    ]
