# Generated by Django 6.0.1 on 2026-09-12 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0008_plantboardworkforce_band_plantboardworkforce_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, unique=True)),
                ('sqft_per_pallet', models.DecimalField(blank=True, decimal_places=2, default=15, help_text='Floor a single pallet stands on. The factory measured 15 sq ft. Leave empty and the board reports the floor and the stock separately rather than guessing how full the stores are.', max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_board_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant board settings',
                'verbose_name_plural': 'Plant board settings',
            },
        ),
    ]
