# Generated by Django 6.0.1 on 2026-10-10 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_dashboard', '0010_warehouseboardsettings_on_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBoardPlanStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, unique=True)),
                ('warehouses', models.JSONField(blank=True, help_text='Warehouse codes counted as stock. Empty means every warehouse.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_board_plan_stock_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant board plan stock warehouses',
                'verbose_name_plural': 'Plant board plan stock warehouses',
            },
        ),
    ]
