# Generated by Django 6.0.1 on 2026-09-07 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Issue Tracker',
                'verbose_name_plural': 'Issue Tracker',
                'permissions': [('can_view_issues', 'Can view the issue tracker'), ('can_create_issues', 'Can report a new issue'), ('can_triage_issues', 'Can triage any issue (label, assign, close, reopen, edit)'), ('can_manage_issue_settings', 'Can manage issue labels and areas')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IssueNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Issue Number Sequence',
                'verbose_name_plural': 'Issue Number Sequence',
            },
        ),
        migrations.CreateModel(
            name='IssueArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short slug used in the search box, e.g. 'dispatch'.", max_length=40, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, help_text='Suggested assignees for a new issue in this area.', related_name='owned_issue_areas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Area',
                'verbose_name_plural': 'Issue Areas',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveIntegerField(editable=False, help_text="The issue's human handle, e.g. 41 for '#41'. Allocated on create.", unique=True)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True, default='', help_text='Markdown. Rendered read-only by the client.')),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('state_reason', models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('NOT_PLANNED', 'Not planned'), ('DUPLICATE', 'Duplicate')], default='', max_length=15)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('page_url', models.CharField(blank=True, default='', help_text="Where in the app it happened, e.g. '/dispatch/bills-linking'. Captured from the reporter's browser so a bug report says where to look.", max_length=500)),
                ('locked', models.BooleanField(default=False, help_text='Locked conversations take no new comments.')),
                ('pinned', models.BooleanField(default=False, help_text='Pinned issues sort to the top of the open list.')),
                ('comment_count', models.PositiveIntegerField(default=0, editable=False)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='issues_assigned', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_reported', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='The company unit the reporter was working in, when it matters.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issues.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issues.issuearea')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('body', models.TextField(help_text='Markdown.')),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_comments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Comment',
                'verbose_name_plural': 'Issue Comments',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='issue_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_attachments', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issuecomment')),
            ],
            options={
                'verbose_name': 'Issue Attachment',
                'verbose_name_plural': 'Issue Attachments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6b7280', help_text="Chip colour as a hex string, e.g. '#d73a4a'.", max_length=7)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='Order in the label picker.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Label',
                'verbose_name_plural': 'Issue Labels',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issues.issuelabel'),
        ),
        migrations.CreateModel(
            name='IssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('OPENED', 'Opened'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('LABELED', 'Labeled'), ('UNLABELED', 'Unlabeled'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('RENAMED', 'Renamed'), ('EDITED', 'Description edited'), ('PRIORITY_CHANGED', 'Priority changed'), ('AREA_CHANGED', 'Area changed'), ('MARKED_DUPLICATE', 'Marked as duplicate'), ('PINNED', 'Pinned'), ('UNPINNED', 'Unpinned'), ('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked')], max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_events', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='issues.issue')),
            ],
            options={
                'verbose_name': 'Issue Event',
                'verbose_name_plural': 'Issue Events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['issue', 'created_at'], name='issues_issu_issue_i_5b5865_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['state', '-last_activity_at'], name='issues_issu_state_cf629d_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['-number'], name='issues_issu_number_89cf03_idx'),
        ),
    ]
