# Generated by Django 6.0.1 on 2026-03-25 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_management', '0007_alter_vehicleentry_entry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Outbound Purpose',
                'verbose_name_plural': 'Outbound Purposes',
                'ordering': ['name'],
                'permissions': [('can_manage_outbound_purpose', 'Can manage outbound purposes')],
            },
        ),
        migrations.CreateModel(
            name='OutboundGateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_ref', models.CharField(blank=True, help_text='SAP Sales Order number the vehicle is coming to fulfil', max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_code', models.CharField(blank=True, max_length=50)),
                ('transporter_name', models.CharField(blank=True, max_length=200)),
                ('transporter_contact', models.CharField(blank=True, max_length=15)),
                ('lr_number', models.CharField(blank=True, help_text='Lorry Receipt / Transport document number', max_length=100)),
                ('vehicle_empty_confirmed', models.BooleanField(default=False, help_text='Security confirmed the vehicle is empty on arrival')),
                ('trailer_type', models.CharField(blank=True, max_length=50)),
                ('trailer_length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assigned_zone', models.CharField(choices=[('ZONE_C', 'Zone C (Outbound Bays 19-30)'), ('YARD', 'Yard / Holding Area')], default='YARD', max_length=20)),
                ('assigned_bay', models.CharField(blank=True, max_length=10)),
                ('expected_loading_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('released_for_loading_at', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_gate_entries_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_entry', to='driver_management.vehicleentry')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outbound_gatein.outboundpurpose')),
            ],
            options={
                'verbose_name': 'Outbound Gate Entry',
                'verbose_name_plural': 'Outbound Gate Entries',
                'ordering': ['-arrival_time'],
                'permissions': [('can_complete_outbound_entry', 'Can complete outbound gate entry'), ('can_release_for_loading', 'Can release vehicle for loading')],
            },
        ),
    ]
