# Generated by Django 6.0.1 on 2026-09-09 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapApproverIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_user_code', models.CharField(max_length=50)),
                ('sap_user_name', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_approver_identities', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sap_approver_identity',
                'ordering': ['company__code', 'sap_user_code'],
                'permissions': [('can_manage_sap_identities', 'Can map app users to SAP user accounts')],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_sap_identity_per_user_company'), models.UniqueConstraint(fields=('company', 'sap_user_code'), name='unique_sap_identity_per_company_code')],
            },
        ),
    ]
