# Generated by Django 6.0.1 on 2026-09-28 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('exim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ADVANCE', 'Advance Authorisation'), ('DFIA', 'DFIA')], max_length=10)),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('issue_date', models.DateField()),
                ('import_validity', models.DateField()),
                ('export_validity', models.DateField()),
                ('cif_value_inr', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cif_exchange_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cif_value_usd', models.DecimalField(decimal_places=3, max_digits=18)),
                ('fob_value_inr', models.DecimalField(decimal_places=3, max_digits=18)),
                ('fob_exchange_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fob_value_usd', models.DecimalField(decimal_places=3, max_digits=18)),
                ('authorised_qty_mts', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_import_mts', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_export_mts', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('obligation_mts', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('balance_mts', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exim_ref', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('copied_from_exim_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exim_licences', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', 'number'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LicenceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=10)),
                ('document_no', models.CharField(max_length=50)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('value_usd', models.DecimalField(decimal_places=3, max_digits=18)),
                ('quantity_mts', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exim_ref', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='exim.licence')),
                ('linked_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='exim.licenceline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_date', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.UniqueConstraint(fields=('company', 'kind', 'number'), name='exim_licence_unique_number'),
        ),
    ]
