# Generated by Django 6.0.1 on 2026-09-30 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('exim', '0003_tank_farm_and_lots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=30)),
                ('delivery_terms', models.CharField(blank=True, choices=[('FOR', 'FOR (delivered)'), ('EXW', 'EXW (we collect)')], max_length=3)),
                ('freight_per_mt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('brokerage_per_mt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copied_from_exim_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exim_contract_terms', to='company.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-po_number'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('company', 'po_number'), name='exim_contractterms_unique_po')],
            },
        ),
    ]
