# Generated by Django 6.0.1 on 2026-09-30 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('exim', '0004_contract_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commodity', models.CharField(max_length=125)),
                ('factory_price_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packed_price_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('with_gst_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('with_gst_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('SHEET', 'The price sheet'), ('EXIM', 'EXIM')], default='SHEET', max_length=5)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exim_commodity_prices', to='company.company')),
            ],
            options={
                'ordering': ['-date', 'commodity'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('company', 'date', 'commodity'), name='exim_commodityprice_unique_day')],
            },
        ),
        migrations.CreateModel(
            name='PackRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pack_type', models.CharField(max_length=125)),
                ('commodity', models.CharField(max_length=125)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=12)),
                ('source', models.CharField(choices=[('SHEET', 'The price sheet'), ('EXIM', 'EXIM')], default='SHEET', max_length=5)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exim_pack_rates', to='company.company')),
            ],
            options={
                'ordering': ['-date', 'pack_type', 'commodity'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('company', 'date', 'pack_type', 'commodity'), name='exim_packrate_unique_day')],
            },
        ),
    ]
