# Generated by Django 6.0.1 on 2026-09-26 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapBudgetChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10)),
                ('doc_entry', models.PositiveIntegerField(blank=True, help_text="The BUDGET document's DocEntry in SAP.", null=True)),
                ('budget_code', models.CharField(blank=True, default='', max_length=50)),
                ('sub_budget_code', models.CharField(blank=True, default='', max_length=50)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_budget_changes', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_sap_ledgers', 'Can view SAP journal entries, general ledger and chart of accounts'), ('can_view_sap_budgets', 'Can view SAP budgets'), ('can_manage_sap_budgets', 'Can create, edit and delete SAP budgets')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'doc_entry'], name='sap_finance_company_9bd996_idx')],
            },
        ),
    ]
