# Generated by Django 6.0.1 on 2026-10-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapbudgetchange',
            options={'default_permissions': (), 'ordering': ['-created_at', '-id'], 'permissions': [('can_view_sap_ledgers', 'Can view SAP journal entries, general ledger and chart of accounts'), ('can_view_sap_budgets', 'Can view SAP budgets'), ('can_manage_sap_budgets', 'Can create, edit and delete SAP budgets'), ('can_view_sap_outstanding', 'Can view SAP outstanding: party balances, open A/P and A/R, open GRPOs, customer aging')]},
        ),
    ]
