# Generated by Django 6.0.1 on 2026-07-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whs_code', models.CharField(help_text='SAP OWHS.WhsCode', max_length=20)),
                ('warehouse_name', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(choices=[('RM_STORE', 'RM Store'), ('PM_STORE', 'PM Store'), ('PRODUCTION_CONSUMPTION', 'Production Consumption (BOM issue point)'), ('FG_RECEIPT', 'FG Receipt (from production)'), ('GR_STAGING', 'GR Staging'), ('WASTAGE', 'Wastage'), ('VIRTUAL', 'Virtual / Consolidation'), ('INACTIVE', 'Inactive (cleanup)'), ('OTHER', 'Other')], max_length=30)),
                ('family', models.CharField(choices=[('RM', 'Raw Material'), ('PM', 'Packaging Material'), ('FG', 'Finished Goods'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='PM', max_length=10)),
                ('is_grpo_target', models.BooleanField(default=False, help_text='Packaging GRPO for this company is received into this warehouse.')),
                ('is_bom_issue_point', models.BooleanField(default=False, help_text='Production BOM is issued ONLY from this warehouse (one per company/family).')),
                ('feeds_whs_code', models.CharField(blank=True, default='', help_text='If a store, the issue-point warehouse it replenishes.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_review', models.BooleanField(default=False, help_text='Provisional mapping pending user confirmation (e.g. Beverages).')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_roles', to='company.company')),
            ],
            options={
                'ordering': ['company__code', 'whs_code'],
                'permissions': [('can_view_warehouse_roles', 'Can view warehouse role config'), ('can_manage_warehouse_roles', 'Can manage warehouse role config'), ('can_view_production_stock', 'Can view production warehouse stock')],
                'unique_together': {('company', 'whs_code')},
            },
        ),
    ]
