# Generated by Django 6.0.1 on 2026-07-28 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_movements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserole',
            name='transfer_needs_request',
            field=models.BooleanField(default=False, help_text='Moving FROM this store to the issue point requires a SAP Inventory Transfer Request first (SP rule 67081). E.g. Oil BH-PM->BH-PC = True, BH-BS->BH-PC = False.'),
        ),
        migrations.CreateModel(
            name='WarehouseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('GRPO_RECEIPT', 'GRPO Receipt'), ('TRANSFER_REQUEST', 'Inventory Transfer Request'), ('TRANSFER', 'Stock Transfer'), ('BOM_ISSUE', 'BOM Issue'), ('FG_RECEIPT', 'FG Receipt')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DRY_RUN', 'Dry Run (not posted)'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('from_whs_code', models.CharField(blank=True, default='', max_length=20)),
                ('to_whs_code', models.CharField(blank=True, default='', max_length=20)),
                ('sap_object_type', models.CharField(blank=True, default='', help_text='SAP object type: 67 transfer, 20 GRPO, 60 issue, etc.', max_length=20)),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('itr_doc_entry', models.IntegerField(blank=True, help_text='DocEntry of the Inventory Transfer Request this transfer is based on.', null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('payload_preview', models.JSONField(blank=True, help_text='The Service-Layer payload built for this movement (dry-run visibility).', null=True)),
                ('reference', models.CharField(blank=True, default='', help_text='Optional caller reference (e.g. BOM request id, run id).', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_movements', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('from_whs_code', models.CharField(blank=True, default='', max_length=20)),
                ('to_whs_code', models.CharField(blank=True, default='', max_length=20)),
                ('base_line', models.IntegerField(blank=True, null=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production_movements.warehousemovement')),
            ],
        ),
        migrations.AddIndex(
            model_name='warehousemovement',
            index=models.Index(fields=['company', 'movement_type', 'status'], name='production__company_cc8f73_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousemovement',
            index=models.Index(fields=['sap_object_type', 'sap_doc_entry'], name='production__sap_obj_abe036_idx'),
        ),
    ]
