# Generated by Django 6.0.1 on 2026-07-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_movements', '0002_warehouserole_transfer_needs_request_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousemovement',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_movement', 'Can create warehouse movements (transfers)'), ('can_view_movements', 'Can view the warehouse movement ledger')]},
        ),
    ]
