# Generated by Django 6.0.1 on 2026-07-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnable_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnablepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_returnable_module', 'Can view returnable items module'), ('can_view_returnable_gatepass', 'Can view returnable gate passes'), ('can_manage_returnable_gatepass', 'Can create and edit returnable gate passes'), ('can_submit_returnable_gatepass', 'Can submit a returnable gate pass for approval'), ('can_approve_returnable_gatepass', 'Can approve or reject a returnable gate pass'), ('can_gate_out_returnable', 'Can gate out a returnable gate pass'), ('can_gate_in_returnable', 'Can record a returnable gate pass return at the gate'), ('can_reject_returnable_at_gate', 'Can reject a returnable gate pass at the gate'), ('can_acknowledge_returnable', 'Can acknowledge receipt of returned items'), ('can_close_returnable', 'Can close a returnable gate pass'), ('can_short_close_returnable', 'Can short close a returnable gate pass'), ('can_cancel_returnable', 'Can cancel a returnable gate pass'), ('can_view_returnable_reports', 'Can view returnable item reports')], 'verbose_name': 'Returnable Permission'},
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='approval_rejected_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returnable_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING_GATE_OUT', 'Pending Gate Out'), ('OUT', 'Out'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnablegatepasslog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('APPROVAL_REJECTED', 'Rejected by Approver'), ('GATE_OUT', 'Gate Out'), ('REJECTED_AT_GATE', 'Rejected at Gate'), ('RETURN_RECORDED', 'Return Recorded'), ('ACKNOWLEDGED', 'Receipt Acknowledged'), ('CLOSED', 'Closed'), ('SHORT_CLOSED', 'Short Closed'), ('CANCELLED', 'Cancelled'), ('DUE_TODAY', 'Return Due Today'), ('OVERDUE_FLAGGED', 'Flagged Overdue')], max_length=25),
        ),
    ]
