# Generated by Django 6.0.1 on 2026-07-10 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('returnable_items', '0002_alter_returnablepermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='returnablegatepasssequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returnable_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='recipient_contact',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='recipient_department',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='returnablegatepasssequence',
            name='prefix',
            field=models.CharField(default='RGP', max_length=8),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='party_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='returnablegatepasssequence',
            unique_together={('company', 'financial_year', 'prefix')},
        ),
    ]
