# Generated by Django 6.0.1 on 2026-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnable_items', '0003_alter_returnablegatepasssequence_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnablegatepass',
            name='carried_by_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='returnablegatepass',
            name='is_hand_carried',
            field=models.BooleanField(default=False),
        ),
    ]
