# Generated by Django 6.0.1 on 2026-07-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnable_items', '0004_returnablegatepass_carried_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnablegatepass',
            name='issued_by_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
