# Generated by Django 6.0.1 on 2026-07-28 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0013_alter_vehicleentry_entry_type'),
        ('maintenance', '0020_alter_maintenancepermission_options_and_more'),
        ('returnable_items', '0005_returnablegatepass_issued_by_name'),
        ('vehicle_management', '0007_transporter_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnablegatepass',
            name='pass_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='returnablegatepass',
            constraint=models.UniqueConstraint(fields=('company', 'pass_no'), name='uniq_returnable_pass_no_per_company'),
        ),
    ]
