# Generated by Django 6.0.1 on 2026-07-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material_gatein', '0014_poreplacementlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGItemReceipt',
            fields=[
            ],
            options={
                'verbose_name': 'Finished Goods Receipt Item',
                'verbose_name_plural': 'Finished Goods Receipt Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('raw_material_gatein.poitemreceipt',),
        ),
        migrations.CreateModel(
            name='FGReceipt',
            fields=[
            ],
            options={
                'verbose_name': 'Finished Goods Receipt',
                'verbose_name_plural': 'Finished Goods Receipts',
                'permissions': [('can_receive_fg_po', 'Can receive finished goods PO'), ('can_complete_fg_entry', 'Can complete finished goods gate entry')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('raw_material_gatein.poreceipt',),
        ),
    ]
