# Generated by Django 6.0.3 on 2026-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_warehouse_dashboard', 'Can view warehouse dashboard'), ('can_view_inventory', 'Can view inventory'), ('can_view_inward', 'Can view inward receipts'), ('can_execute_inward', 'Can execute inward putaway'), ('can_view_transfers', 'Can view stock transfers'), ('can_request_transfer', 'Can request stock transfer'), ('can_approve_transfer', 'Can approve stock transfer'), ('can_pick_transfer', 'Can pick stock transfer'), ('can_receive_transfer', 'Can receive stock transfer'), ('can_post_transfer_to_sap', 'Can post stock transfer to SAP'), ('can_view_goods_issue', 'Can view goods issues'), ('can_request_goods_issue', 'Can request goods issue'), ('can_approve_goods_issue', 'Can approve goods issue'), ('can_execute_goods_issue', 'Can execute goods issue'), ('can_post_goods_issue_to_sap', 'Can post goods issue to SAP'), ('can_view_stock_count', 'Can view stock counts'), ('can_plan_stock_count', 'Can plan stock count'), ('can_execute_stock_count', 'Can execute stock count'), ('can_review_stock_count', 'Can review stock count'), ('can_post_stock_count_to_sap', 'Can post stock count to SAP'), ('can_view_picking', 'Can view pick lists'), ('can_execute_picking', 'Can execute picking'), ('can_manage_picking', 'Can manage pick lists'), ('can_view_dispatch_tracking', 'Can view dispatch tracking'), ('can_manage_dispatch_tracking', 'Can manage dispatch tracking'), ('can_view_returns', 'Can view returns'), ('can_create_return', 'Can create return'), ('can_inspect_return', 'Can inspect return'), ('can_complete_return', 'Can complete return'), ('can_view_non_moving', 'Can view non-moving report'), ('can_manage_non_moving_config', 'Can manage expiry threshold config'), ('can_view_capacity_limits', 'Can view capacity limits'), ('can_manage_capacity_limits', 'Can manage capacity limits'), ('can_view_audit', 'Can view daily audits'), ('can_execute_audit', 'Can execute daily audit')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
