# Generated by Django 6.0.1 on 2026-04-06 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0014_productionrun_required_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_doc_entry', models.IntegerField(blank=True, help_text='SAP Production Order DocEntry', null=True)),
                ('required_qty', models.DecimalField(decimal_places=2, help_text='Required production quantity (units to produce)', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=25)),
                ('remarks', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason for rejection (filled by warehouse)')),
                ('material_issue_status', models.CharField(choices=[('NOT_ISSUED', 'Not Issued'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('FULLY_ISSUED', 'Fully Issued')], default='NOT_ISSUED', max_length=25)),
                ('sap_issue_doc_entries', models.JSONField(blank=True, default=list, help_text='List of SAP Goods Issue DocEntries')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_requests', to='company.company')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_requests', to='production_execution.productionrun')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOM Request',
                'verbose_name_plural': 'BOM Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('per_unit_qty', models.DecimalField(decimal_places=4, default=0, help_text='BOM quantity per single unit of finished good', max_digits=12)),
                ('required_qty', models.DecimalField(decimal_places=3, help_text='Scaled quantity = per_unit_qty * production required_qty', max_digits=12)),
                ('available_stock', models.DecimalField(decimal_places=3, default=0, help_text='Warehouse stock at the time of review', max_digits=12)),
                ('approved_qty', models.DecimalField(decimal_places=3, default=0, help_text='Quantity approved by warehouse', max_digits=12)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=0, help_text='Quantity actually issued to production', max_digits=12)),
                ('warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('base_line', models.IntegerField(default=0, help_text='WOR1 LineNum (0-based) for SAP issue linking')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.bomrequest')),
            ],
            options={
                'verbose_name': 'BOM Request Line',
                'verbose_name_plural': 'BOM Request Lines',
                'ordering': ['base_line'],
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_doc_entry', models.IntegerField(blank=True, help_text='SAP Production Order DocEntry', null=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('produced_qty', models.DecimalField(decimal_places=2, help_text='Total quantity produced', max_digits=12)),
                ('good_qty', models.DecimalField(decimal_places=2, help_text='Good quantity (produced - rejected)', max_digits=12)),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('posting_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('SAP_POSTED', 'SAP Posted'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sap_receipt_doc_entry', models.IntegerField(blank=True, help_text='SAP Goods Receipt DocEntry after posting', null=True)),
                ('sap_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_receipts', to='company.company')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_receipts', to='production_execution.productionrun')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_receipts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finished Goods Receipt',
                'verbose_name_plural': 'Finished Goods Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
