# Generated by Django 6.0.1 on 2026-06-30 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0012_intercompanytransfer_entity_type'),
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0013_alter_vehicleentry_entry_type'),
        ('vehicle_management', '0007_transporter_gstin'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSTTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.CharField(blank=True, default='', max_length=50)),
                ('sap_doc_date', models.DateField(blank=True, null=True)),
                ('sap_from_warehouse', models.CharField(blank=True, default='', max_length=50)),
                ('sap_to_warehouse', models.CharField(blank=True, default='', max_length=50)),
                ('sap_reference', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_no', models.CharField(blank=True, default='', help_text='Invoice / document number the warehouse user typed to look up the BST.', max_length=100)),
                ('requires_gate', models.BooleanField(default=False, help_text='True when source/destination is outside the factory and the Gate must mark the vehicle out/in.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCANNING', 'Scanning'), ('DISPATCHED', 'Dispatched'), ('AWAITING_GATE_OUT', 'Awaiting Gate Out'), ('GATED_OUT', 'Gated Out'), ('IN_TRANSIT', 'In Transit'), ('AWAITING_GATE_IN', 'Awaiting Gate In'), ('GATED_IN', 'Gated In'), ('ARRIVED', 'Arrived'), ('RECEIVING', 'Receiving'), ('RECEIVED', 'Received'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('gated_out_at', models.DateTimeField(blank=True, null=True)),
                ('gated_in_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Source company (sender / dispatching branch).', on_delete=django.db.models.deletion.PROTECT, related_name='bst_transfers_sent', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_dispatched', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_transfers', to='driver_management.driver')),
                ('gated_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_gated_in', to=settings.AUTH_USER_MODEL)),
                ('gated_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_gated_out', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_received_by', to=settings.AUTH_USER_MODEL)),
                ('to_company', models.ForeignKey(help_text='Destination company (receiving branch).', on_delete=django.db.models.deletion.PROTECT, related_name='bst_transfers_received', to='company.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_transfers', to='vehicle_management.vehicle')),
            ],
            options={
                'verbose_name': 'BST Transfer',
                'verbose_name_plural': 'BST Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BSTBoxScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_barcode', models.CharField(max_length=50)),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=50)),
                ('warehouse_code', models.CharField(blank=True, default='', max_length=50)),
                ('pallet_code', models.CharField(blank=True, default='', max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('receive_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('is_unexpected', models.BooleanField(default=False, help_text='Receiver scanned this box but the sender never dispatched it.')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_box_scans', to='barcode.box')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_box_scans', to='barcode.pallet')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_box_scans_received', to=settings.AUTH_USER_MODEL)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_box_scans', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scans', to='warehouse.bsttransfer')),
            ],
            options={
                'verbose_name': 'BST Box Scan',
                'verbose_name_plural': 'BST Box Scans',
                'ordering': ['scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='BSTTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField()),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=50)),
                ('from_warehouse', models.CharField(blank=True, default='', max_length=50)),
                ('to_warehouse', models.CharField(blank=True, default='', max_length=50)),
                ('expected_boxes', models.PositiveIntegerField(default=0)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.bsttransfer')),
            ],
            options={
                'ordering': ['line_num'],
            },
        ),
        migrations.AddIndex(
            model_name='bsttransfer',
            index=models.Index(fields=['company', 'status'], name='warehouse_b_company_546f33_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttransfer',
            index=models.Index(fields=['to_company', 'status'], name='warehouse_b_to_comp_00c2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttransfer',
            index=models.Index(fields=['company', 'created_at'], name='warehouse_b_company_c94327_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttransfer',
            index=models.Index(fields=['sap_doc_num'], name='warehouse_b_sap_doc_a4bb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='bstboxscan',
            index=models.Index(fields=['transfer'], name='warehouse_b_transfe_d96554_idx'),
        ),
        migrations.AddIndex(
            model_name='bstboxscan',
            index=models.Index(fields=['transfer', 'receive_status'], name='warehouse_b_transfe_5b2394_idx'),
        ),
        migrations.AddIndex(
            model_name='bstboxscan',
            index=models.Index(fields=['box_barcode'], name='warehouse_b_box_bar_efc57b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bstboxscan',
            constraint=models.UniqueConstraint(fields=('transfer', 'box_barcode'), name='unique_bst_transfer_box'),
        ),
        migrations.AddConstraint(
            model_name='bsttransferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'line_num'), name='unique_bst_transfer_line'),
        ),
    ]
