# Generated by Django 6.0.1 on 2026-06-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0013_alter_vehicleentry_entry_type'),
        ('vehicle_management', '0007_transporter_gstin'),
        ('warehouse', '0002_bsttransfer_bstboxscan_bsttransferitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsttransfer',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bst_transfers', to='driver_management.driver'),
        ),
        migrations.AlterField(
            model_name='bsttransfer',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bst_transfers', to='vehicle_management.vehicle'),
        ),
    ]
