# Generated by Django 6.0.1 on 2026-06-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0003_alter_bsttransfer_driver_alter_bsttransfer_vehicle'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bsttransfer',
            name='warehouse_b_to_comp_00c2f9_idx',
        ),
        migrations.AlterField(
            model_name='bsttransfer',
            name='company',
            field=models.ForeignKey(help_text='The company the transfer belongs to (BST is intra-company).', on_delete=django.db.models.deletion.PROTECT, related_name='bst_transfers', to='company.company'),
        ),
        migrations.RemoveField(
            model_name='bsttransfer',
            name='to_company',
        ),
    ]
