# Generated by Django 6.0.1 on 2026-06-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_bsttransfer_warehouse_b_to_comp_00c2f9_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bsttransfer',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_bst', 'Can create a branch stock transfer'), ('can_scan_bst', 'Can scan boxes onto a branch stock transfer'), ('can_dispatch_bst', 'Can dispatch a branch stock transfer'), ('can_receive_bst', 'Can receive a branch stock transfer'), ('can_gate_bst', 'Can mark a branch stock transfer out/in at the gate')], 'verbose_name': 'BST Transfer', 'verbose_name_plural': 'BST Transfers'},
        ),
    ]
