# Generated by Django 6.0.1 on 2026-07-04 11:43

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0024_lineclearance_lineclr_co_date_idx_and_more'),
        ('warehouse', '0006_bsttransfer_scan_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='bomrequest',
            index=models.Index(fields=['company', 'status'], name='bomreq_co_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='bomrequest',
            index=models.Index(fields=['company', '-created_at'], name='bomreq_co_created_idx'),
        ),
        AddIndexConcurrently(
            model_name='finishedgoodsreceipt',
            index=models.Index(fields=['company', 'status'], name='fgr_co_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='finishedgoodsreceipt',
            index=models.Index(fields=['company', '-created_at'], name='fgr_co_created_idx'),
        ),
    ]
