# Generated by Django 6.0.1 on 2026-07-03 08:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_transfer_docs(apps, schema_editor):
    """Give every existing BST entry a single document mirroring its head SAP
    fields, and link its lines to that document."""
    BSTTransfer = apps.get_model('warehouse', 'BSTTransfer')
    BSTTransferDoc = apps.get_model('warehouse', 'BSTTransferDoc')
    for transfer in BSTTransfer.objects.all():
        doc = BSTTransferDoc.objects.create(
            transfer=transfer,
            sap_doc_entry=transfer.sap_doc_entry or 0,
            sap_doc_num=transfer.sap_doc_num or '',
            sap_doc_date=transfer.sap_doc_date,
            sap_reference=transfer.sap_reference or '',
            invoice_no=transfer.invoice_no or '',
        )
        transfer.items.update(doc=doc)


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_bsttransfer_scan_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSTTransferDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.CharField(blank=True, default='', max_length=50)),
                ('sap_doc_date', models.DateField(blank=True, null=True)),
                ('sap_reference', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_no', models.CharField(blank=True, default='', help_text='Invoice / document number the warehouse user typed to look up this document.', max_length=100)),
            ],
            options={
                'verbose_name': 'BST Transfer Document',
                'verbose_name_plural': 'BST Transfer Documents',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bsttransferitem',
            name='unique_bst_transfer_line',
        ),
        migrations.AddField(
            model_name='bsttransferdoc',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='warehouse.bsttransfer'),
        ),
        migrations.AddField(
            model_name='bsttransferitem',
            name='doc',
            field=models.ForeignKey(blank=True, help_text='The SAP document this line came from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.bsttransferdoc'),
        ),
        migrations.AddConstraint(
            model_name='bsttransferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'doc', 'line_num'), name='unique_bst_transfer_line'),
        ),
        migrations.AddConstraint(
            model_name='bsttransferdoc',
            constraint=models.UniqueConstraint(fields=('transfer', 'sap_doc_entry'), name='unique_bst_transfer_doc'),
        ),
        migrations.RunPython(backfill_transfer_docs, migrations.RunPython.noop),
    ]
