# Generated by Django 6.0.1 on 2026-07-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_bsttransfer_source_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomrequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_bom_request', 'Can view BOM requests'), ('can_create_bom_request', 'Can create/submit BOM requests'), ('can_approve_bom_request', 'Can approve or reject BOM requests'), ('can_issue_materials', 'Can issue BOM materials to SAP')], 'verbose_name': 'BOM Request', 'verbose_name_plural': 'BOM Requests'},
        ),
        migrations.AlterModelOptions(
            name='finishedgoodsreceipt',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_fg_receipt', 'Can view finished goods receipts'), ('can_create_fg_receipt', 'Can create finished goods receipts'), ('can_receive_fg', 'Can receive finished goods'), ('can_post_fg_to_sap', 'Can post finished goods receipt to SAP')], 'verbose_name': 'Finished Goods Receipt', 'verbose_name_plural': 'Finished Goods Receipts'},
        ),
    ]
