# Generated by Django 6.0.1 on 2026-07-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0009_blowingauditlog'),
        ('production_execution', '0027_grant_line_clearance_manager_to_tajinderjit'),
        ('warehouse', '0011_run_viewers_fg_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomrequest',
            name='blowing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_requests', to='blowing.blowingrun'),
        ),
        migrations.AlterField(
            model_name='bomrequest',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_requests', to='production_execution.productionrun'),
        ),
    ]
