# Generated by Django 6.0.1 on 2026-07-25 12:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0013_bomrequest_parent_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSTPartialTransferApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_qty', models.DecimalField(decimal_places=3, default=0, help_text='Total scanned quantity when the request was raised.', max_digits=18)),
                ('expected_qty', models.DecimalField(decimal_places=3, default=0, help_text='Expected (bill) quantity when the request was raised.', max_digits=18)),
                ('reason', models.TextField(help_text='Why the transfer is sealed with a partial scan.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bst_partial_transfer_requests', to='company.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_partial_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_partial_transfer_reviews', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_transfer_requests', to='warehouse.bsttransfer')),
            ],
            options={
                'verbose_name': 'BST Partial Transfer Approval',
                'verbose_name_plural': 'BST Partial Transfer Approvals',
                'ordering': ['-requested_at', '-id'],
                'permissions': [('can_request_bst_partial_transfer', 'Can request to seal a BST with a partial scan'), ('can_view_bst_partial_transfer', 'Can view BST partial transfer requests'), ('can_approve_bst_partial_transfer', 'Can approve or reject BST partial transfer requests')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('transfer',), name='unique_pending_bst_partial_transfer')],
            },
        ),
    ]
