# Generated by Django 6.0.1 on 2026-08-13 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_bstpartialtransferapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSTManualItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_manual_entries', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='warehouse.bsttransfer')),
            ],
            options={
                'verbose_name': 'BST Manual Item Entry',
                'verbose_name_plural': 'BST Manual Item Entries',
                'ordering': ['item_code'],
                'indexes': [models.Index(fields=['transfer'], name='warehouse_b_transfe_70fbd8_idx')],
                'constraints': [models.UniqueConstraint(fields=('transfer', 'item_code'), name='unique_bst_manual_item_entry')],
            },
        ),
    ]
