# Generated by Django 6.0.1 on 2026-08-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0015_bstmanualitementry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('from_warehouse', models.CharField(max_length=20)),
                ('to_warehouse', models.CharField(max_length=20)),
                ('route_type', models.CharField(choices=[('INTRA_BRANCH', 'Within one branch'), ('CROSS_BRANCH', 'Between branches (via in-transit)')], default='INTRA_BRANCH', max_length=15)),
                ('from_branch_id', models.IntegerField(blank=True, help_text='OWHS.BPLid of the source warehouse', null=True)),
                ('to_branch_id', models.IntegerField(blank=True, help_text='OWHS.BPLid of the destination warehouse', null=True)),
                ('intransit_warehouse', models.CharField(blank=True, default='', help_text='Cross-branch only: the *-INT warehouse leg 1 ships into.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25)),
                ('remarks', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('sap_request_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_request_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('sap_request_closed_at', models.DateTimeField(blank=True, help_text='When the ITR was closed in SAP, releasing its reservation.', null=True)),
                ('posting_status', models.CharField(choices=[('NOT_POSTED', 'Not Posted'), ('IN_TRANSIT', 'Leg 1 posted — in transit'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], default='NOT_POSTED', max_length=15)),
                ('sap_transfer_doc_entry', models.IntegerField(blank=True, help_text='Intra-branch: the whole move. Cross-branch: leg 1.', null=True)),
                ('sap_transfer_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('sap_leg2_doc_entry', models.IntegerField(blank=True, help_text='Cross-branch only: in-transit to destination, posted at receipt.', null=True)),
                ('sap_leg2_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('posting_error', models.TextField(blank=True, default='', help_text='Last SAP rejection, kept so the operator can see why.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bst_transfer', models.ForeignKey(blank=True, help_text='The BST seeded from the posted transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='warehouse.bsttransfer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='company.company')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_posted', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_raised', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Transfer Request',
                'ordering': ['-created_at'],
                'permissions': [('can_view_transfer_request', 'Can view warehouse transfer requests'), ('can_create_transfer_request', 'Can raise a warehouse transfer request'), ('can_approve_transfer_request', 'Can approve or reject a transfer request'), ('can_post_transfer_to_sap', 'Can post an approved transfer to SAP')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField(help_text='Zero-based, mirroring the SAP document line number.')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('from_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('to_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('approved_qty', models.DecimalField(decimal_places=3, default=0, help_text='Set by the receiving warehouse; may be less than requested.', max_digits=15)),
                ('transferred_qty', models.DecimalField(decimal_places=3, default=0, help_text='Actually moved by a posted transfer.', max_digits=15)),
                ('is_batch_managed', models.BooleanField(default=False, help_text='From OITM.ManBtchNum — batch-managed lines must carry a split.')),
                ('batch_allocation', models.JSONField(blank=True, default=list, help_text='The BatchNumbers split sent to SAP, kept for reconciliation against IBT1 (a Service Layer GET returns an empty list).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.warehousetransferrequest')),
            ],
            options={
                'verbose_name': 'Warehouse Transfer Request Line',
                'ordering': ['line_num'],
            },
        ),
        migrations.AddIndex(
            model_name='warehousetransferrequest',
            index=models.Index(fields=['company', 'status'], name='warehouse_w_company_e30129_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransferrequest',
            index=models.Index(fields=['company', 'posting_status'], name='warehouse_w_company_40d5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransferrequest',
            index=models.Index(fields=['sap_request_doc_entry'], name='warehouse_w_sap_req_569409_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransferrequest',
            index=models.Index(fields=['sap_transfer_doc_entry'], name='warehouse_w_sap_tra_69d579_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousetransferrequestline',
            unique_together={('request', 'line_num')},
        ),
    ]
