# Generated by Django 6.0.1 on 2026-08-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0016_transfer_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_managers', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'warehouse manager',
                'verbose_name_plural': 'warehouse managers',
                'db_table': 'warehouse_user_warehouse',
                'ordering': ['company__code', 'warehouse_code', 'user__full_name'],
                'permissions': [('can_manage_user_warehouses', 'Can assign users as warehouse managers')],
                'indexes': [models.Index(fields=['company', 'warehouse_code'], name='warehouse_u_company_ca47f5_idx'), models.Index(fields=['user', 'company'], name='warehouse_u_user_id_17d80a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'company', 'warehouse_code'), name='uniq_user_company_warehouse')],
            },
        ),
    ]
