# Generated by Django 6.0.1 on 2026-09-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_userwarehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwarehouse',
            options={'ordering': ['company__code', 'warehouse_code', 'user__full_name'], 'permissions': [('can_manage_user_warehouses', 'Can assign users as warehouse managers'), ('can_receive_barcodes', 'Can receive and activate printed barcodes at a warehouse')], 'verbose_name': 'warehouse manager', 'verbose_name_plural': 'warehouse managers'},
        ),
    ]
