# Generated by Django 6.0.1 on 2026-09-08 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0018_receive_barcodes_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapApprovalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_code', models.IntegerField(db_index=True)),
                ('draft_entry', models.IntegerField(blank=True, null=True)),
                ('obj_type', models.CharField(blank=True, default='', max_length=20)),
                ('doc_num', models.BigIntegerField(blank=True, null=True)),
                ('from_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('to_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('sap_approver', models.CharField(blank=True, default='', max_length=50)),
                ('stage_code', models.IntegerField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('sap_message', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_approval_audits', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse_sap_approval_audit',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='sapapprovalaudit',
            index=models.Index(fields=['company', 'approval_code'], name='warehouse_s_company_3d82a7_idx'),
        ),
    ]
