# Generated by Django 6.0.1 on 2026-09-08 12:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0019_sapapprovalaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(db_index=True, max_length=50)),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('uom', models.CharField(blank=True, default='', help_text='Inventory UoM as SAP holds it (OITM.InvntryUom).', max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Quantity the warehouse states it is holding.', max_digits=18)),
                ('as_of_date', models.DateField(help_text='The date this quantity is true as of.')),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rm_stock_rows', to='company.company')),
                ('set_by', models.ForeignKey(blank=True, help_text='Who last set the quantity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_stock_rows_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'raw material stock',
                'verbose_name_plural': 'raw material stock',
                'db_table': 'warehouse_rm_stock',
                'ordering': ['warehouse_code', 'item_code'],
                'permissions': [('can_view_rm_stock', 'Can view raw material stock quantities'), ('can_set_rm_stock', 'Can set raw material stock quantities')],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(db_index=True, max_length=50)),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('REMOVED', 'Removed'), ('RESTORED', 'Restored')], max_length=10)),
                ('previous_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_stock_changes', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rm_stock_entries', to='company.company')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='warehouse.rawmaterialstock')),
            ],
            options={
                'verbose_name': 'raw material stock change',
                'verbose_name_plural': 'raw material stock changes',
                'db_table': 'warehouse_rm_stock_entry',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='rawmaterialstock',
            index=models.Index(fields=['company', 'warehouse_code'], name='warehouse_r_company_72cdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialstock',
            index=models.Index(fields=['company', 'item_code'], name='warehouse_r_company_4336c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterialstock',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse_code', 'item_code'), name='uniq_rm_stock_company_whs_item'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialstockentry',
            index=models.Index(fields=['company', 'warehouse_code', 'item_code'], name='warehouse_r_company_71732b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialstockentry',
            index=models.Index(fields=['-changed_at'], name='warehouse_r_changed_629b7a_idx'),
        ),
    ]
