# Generated by Django 6.0.1 on 2026-09-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_rawmaterialstock_rawmaterialstockentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomrequest',
            name='material_kind',
            field=models.CharField(choices=[('RM', 'Raw material'), ('PM', 'Packing material'), ('MIXED', 'Mixed (pre-split)')], default='MIXED', help_text='Whether this request covers raw material or packing material. A run raises one of each, settled against different evidence. MIXED is only for requests raised before the two were split apart.', max_length=10),
        ),
    ]
