# Generated by Django 6.0.1 on 2026-09-10 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0021_bom_request_material_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('movement_date', models.DateField(db_index=True, help_text='The day this stock is to move.')),
                ('from_warehouse', models.CharField(db_index=True, max_length=50)),
                ('to_warehouse', models.CharField(db_index=True, max_length=50)),
                ('from_warehouse_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_warehouse_name', models.CharField(blank=True, default='', max_length=200)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_movements_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pf_movements', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_movements_created', to=settings.AUTH_USER_MODEL)),
                ('to_company', models.ForeignKey(help_text="The company the destination warehouse belongs to. Often the same as `company`, but the Gupta finished godown the PF floor ships into is Mart's while the floor is Oil's.", on_delete=django.db.models.deletion.PROTECT, related_name='pf_movements_inbound', to='company.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_movements_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'godown stock movement',
                'verbose_name_plural': 'godown stock movements',
                'db_table': 'warehouse_pf_movement',
                'ordering': ['-movement_date', '-id'],
                'permissions': [('can_view_pf_movement', 'Can view godown stock movements'), ('can_record_pf_movement', 'Can record godown stock movements')],
            },
        ),
        migrations.CreateModel(
            name='PFStockMovementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('CANCELLED', 'Cancelled'), ('RESTORED', 'Restored')], max_length=10)),
                ('movement_date', models.DateField(blank=True, null=True)),
                ('to_warehouse', models.CharField(blank=True, default='', max_length=50)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('total_boxes', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_movement_changes', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warehouse.pfstockmovement')),
            ],
            options={
                'verbose_name': 'godown stock movement change',
                'verbose_name_plural': 'godown stock movement changes',
                'db_table': 'warehouse_pf_movement_event',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PFStockMovementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('uom', models.CharField(blank=True, default='', help_text='Inventory UoM as SAP holds it (OITM.InvntryUom).', max_length=20)),
                ('boxes', models.PositiveIntegerField(help_text='Boxes the keeper is sending. A whole count — the floor does not move part boxes between godowns.')),
                ('pieces_per_box', models.PositiveIntegerField(blank=True, help_text='OITM.SalFactor2 as it stood when this line was typed.', null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.pfstockmovement')),
            ],
            options={
                'verbose_name': 'godown stock movement line',
                'verbose_name_plural': 'godown stock movement lines',
                'db_table': 'warehouse_pf_movement_line',
                'ordering': ['item_code'],
            },
        ),
        migrations.AddIndex(
            model_name='pfstockmovement',
            index=models.Index(fields=['company', '-movement_date'], name='warehouse_p_company_10ed43_idx'),
        ),
        migrations.AddIndex(
            model_name='pfstockmovement',
            index=models.Index(fields=['company', 'from_warehouse', '-movement_date'], name='warehouse_p_company_de40e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pfstockmovement',
            index=models.Index(fields=['to_company', 'to_warehouse', '-movement_date'], name='warehouse_p_to_comp_86e937_idx'),
        ),
        migrations.AddIndex(
            model_name='pfstockmovementevent',
            index=models.Index(fields=['-changed_at'], name='warehouse_p_changed_4a3e39_idx'),
        ),
        migrations.AddConstraint(
            model_name='pfstockmovementline',
            constraint=models.UniqueConstraint(fields=('movement', 'item_code'), name='uniq_pf_movement_line_item'),
        ),
    ]
