# Generated by Django 6.0.1 on 2026-09-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0022_pf_stock_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pfstockmovement',
            name='destination_kind',
            field=models.CharField(choices=[('GODOWN', 'To another godown'), ('DISPATCH', 'Dispatched directly')], db_index=True, default='GODOWN', help_text='Whether this load is going to another godown or straight out on a dispatch.', max_length=10),
        ),
        migrations.AddField(
            model_name='pfstockmovement',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Invoice or bilty number, if the paperwork exists yet.', max_length=50),
        ),
        migrations.AddField(
            model_name='pfstockmovementevent',
            name='destination_kind',
            field=models.CharField(blank=True, choices=[('GODOWN', 'To another godown'), ('DISPATCH', 'Dispatched directly')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pfstockmovement',
            name='to_company',
            field=models.ForeignKey(blank=True, help_text="The company the destination warehouse belongs to. Often the same as `company`, but the Gupta finished godown the PF floor ships into is Mart's while the floor is Oil's. Null on a dispatch, which has no destination godown.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pf_movements_inbound', to='company.company'),
        ),
        migrations.AlterField(
            model_name='pfstockmovement',
            name='to_warehouse',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='pfstockmovement',
            index=models.Index(fields=['company', 'destination_kind', '-movement_date'], name='warehouse_p_company_2edee3_idx'),
        ),
        migrations.AddConstraint(
            model_name='pfstockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_kind', 'GODOWN'), ('to_company__isnull', False), models.Q(('to_warehouse', ''), _negated=True)), models.Q(('destination_kind', 'DISPATCH'), ('to_company__isnull', True), ('to_warehouse', '')), _connector='OR'), name='pf_movement_destination_matches_kind'),
        ),
    ]
