# Generated by Django 6.0.1 on 2026-09-12 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_pf_movement_pieces_and_litres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bsttransfer',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_bst', 'Can create a branch stock transfer'), ('can_scan_bst', 'Can scan boxes onto a branch stock transfer'), ('can_dispatch_bst', 'Can dispatch a branch stock transfer'), ('can_receive_bst', 'Can receive a branch stock transfer'), ('can_gate_bst', 'Can mark a branch stock transfer out/in at the gate'), ('can_edit_bst_loaded_at', 'Can correct the loaded-at time on a branch stock transfer')], 'verbose_name': 'BST Transfer', 'verbose_name_plural': 'BST Transfers'},
        ),
        migrations.AddField(
            model_name='bsttransfer',
            name='loaded_at',
            field=models.DateTimeField(blank=True, help_text='When loading finished and the transfer was handed to the gate.', null=True),
        ),
        migrations.AddField(
            model_name='bsttransfer',
            name='loaded_at_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bsttransfer',
            name='loaded_at_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_loaded_at_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bsttransfer',
            name='loaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_transfers_loaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
