# Generated by Django 6.0.1 on 2026-09-12 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0026_backfill_bst_loaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapTransferDraftPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('draft_entry', models.IntegerField(db_index=True)),
                ('draft_doc_num', models.BigIntegerField(blank=True, null=True)),
                ('from_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('to_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('line_count', models.IntegerField(default=0)),
                ('doc_entry', models.IntegerField(blank=True, null=True)),
                ('doc_num', models.BigIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('POSTED', 'Posted'), ('FAILED', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_transfer_draft_posts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse_sap_transfer_draft_post',
                'ordering': ['-created_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'draft_entry'], name='warehouse_s_company_0360e8_idx')],
            },
        ),
    ]
