# Generated by Django 6.0.1 on 2026-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_sap_transfer_draft_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsttransfer',
            name='loaded_at',
            field=models.DateTimeField(blank=True, help_text='When loading finished and the vehicle was handed to the gate.', null=True),
        ),
    ]
