# Generated by Django 6.0.1 on 2026-09-16 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('warehouse', '0028_alter_bsttransfer_loaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteApprovalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_code', models.IntegerField(db_index=True)),
                ('draft_entry', models.IntegerField(blank=True, null=True)),
                ('obj_type', models.CharField(blank=True, default='', max_length=20)),
                ('doc_num', models.BigIntegerField(blank=True, null=True)),
                ('card_code', models.CharField(blank=True, default='', max_length=50)),
                ('party_name', models.CharField(blank=True, default='', max_length=200)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sap_approver', models.CharField(blank=True, default='', max_length=50)),
                ('stage_code', models.IntegerField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('sap_message', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_approval_audits', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse_credit_note_approval_audit',
                'ordering': ['-created_at'],
                'permissions': [('can_view_credit_note_approval', 'Can view the SAP credit-note approval queue'), ('can_approve_credit_note', 'Can approve or reject a SAP credit note')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'approval_code'], name='warehouse_c_company_3ba8d1_idx')],
            },
        ),
    ]
