# Generated by Django 6.0.1 on 2026-09-19 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_alter_creditnoteapprovalaudit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMRequestLineSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(help_text="Godown the quantity is drawn from — never the line's own consumption warehouse, whose stock is already at the line.", max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='warehouse.bomrequestline')),
            ],
            options={
                'verbose_name': 'BOM Request Line Source',
                'verbose_name_plural': 'BOM Request Line Sources',
                'ordering': ['-qty', 'warehouse_code'],
                'constraints': [models.UniqueConstraint(fields=('line', 'warehouse_code'), name='uniq_bom_line_source_warehouse')],
            },
        ),
    ]
