# Generated by Django 6.0.1 on 2026-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_bomrequestlinesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransferrequest',
            name='raised_by_side',
            field=models.CharField(choices=[('SENDER', 'Sending warehouse (offered)'), ('RECEIVER', 'Receiving warehouse (asked for)')], default='SENDER', help_text='Which warehouse raised it. The other one approves or rejects.', max_length=10),
        ),
    ]
