# Generated by Django 6.0.1 on 2026-10-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_transfer_request_raised_by_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsttransfer',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='bsttransferdoc',
            name='invoice_no',
        ),
    ]
