# Generated by Django 6.0.1 on 2026-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0033_drop_bst_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransferrequestline',
            name='chosen_batches',
            field=models.JSONField(blank=True, default=list, help_text="Batches the requester picked when raising it, as [{batch_number, quantity}] adding up to requested_qty. Empty means oldest first. Never sent to SAP's request; posting starts from it."),
        ),
        # Django's default lives in Python only, so code that predates this
        # column — the old gunicorn mid-deploy, or another checkout sharing the
        # dev database — would insert NULL and fail. The database default lets
        # it keep raising requests.
        migrations.RunSQL(
            "ALTER TABLE warehouse_warehousetransferrequestline "
            "ALTER COLUMN chosen_batches SET DEFAULT '[]'::jsonb",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
