# Generated by Django 6.0.1 on 2026-10-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_planning_requirement', '0002_use_weekly_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplanningrequirementrow',
            name='received_qty',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Quantity received on posted GRPOs within the forecast's dates. Null on rows loaded before it was read.", max_digits=24, null=True),
        ),
    ]
