# Generated by Django 6.0.1 on 2026-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0007_transporter_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
