# Generated by Django 6.0.1 on 2026-10-08 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('vehicle_management', '0008_vehicle_height_m_vehicle_length_m_vehicle_width_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterSAPLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card_code', models.CharField(max_length=50)),
                ('card_name', models.CharField(blank=True, default='', max_length=150)),
                ('gstin', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_sap_links', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_links', to='vehicle_management.transporter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'card_code'], name='vehicle_man_company_545c63_idx')],
                'constraints': [models.UniqueConstraint(fields=('transporter', 'company', 'card_code'), name='uniq_transporter_sap_link')],
            },
        ),
    ]
