# Generated by Django 6.0.1 on 2026-06-22 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('docking_admin', '0002_create_docking_admin_groups'),
        ('gate_core', '0044_arrivalgatepasssequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockingPartialScanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scanned_boxes', models.PositiveIntegerField(default=0, help_text='Boxes scanned when the request was raised.')),
                ('expected_boxes', models.PositiveIntegerField(default=0, help_text='Expected box count for the docking when the request was raised.')),
                ('reason', models.TextField(help_text='Why the load is dispatched with a partial box scan.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docking_partial_scan_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docking_partial_scan_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docking_partial_scan_reviews', to=settings.AUTH_USER_MODEL)),
                ('sales_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_scan_requests', to='gate_core.salesdispatchgateout')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docking Partial Scan Request',
                'verbose_name_plural': 'Docking Partial Scan Requests',
                'ordering': ['-requested_at', '-id'],
                'permissions': [('can_request_docking_partial_scan', 'Can request to dispatch a docking with a partial box scan'), ('can_view_docking_partial_scan', 'Can view docking partial scan requests'), ('can_approve_docking_partial_scan', 'Can approve or reject docking partial scan requests')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('sales_dispatch',), name='unique_pending_partial_scan_per_dispatch')],
            },
        ),
    ]
