# Generated by Django 6.0.1 on 2026-09-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('docking_admin', '0004_partial_scan_group_permissions'),
        ('gate_core', '0058_dispatch_box_loose_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dockingpartialscanrequest',
            name='unique_pending_partial_scan_per_dispatch',
        ),
        migrations.AddField(
            model_name='dockingpartialscanrequest',
            name='document',
            field=models.ForeignKey(blank=True, help_text='The bill this partial-dispatch approval covers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partial_scan_requests', to='gate_core.salesdispatchgateoutdocument'),
        ),
        migrations.AddField(
            model_name='dockingpartialscanrequest',
            name='expected_pieces',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity the bill invoices, excluding scan-exempt lines.', max_digits=14),
        ),
        migrations.AddField(
            model_name='dockingpartialscanrequest',
            name='scanned_pieces',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity scanned against this bill when the request was raised.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='dockingpartialscanrequest',
            name='expected_boxes',
            field=models.PositiveIntegerField(default=0, help_text='Boxes the bill expects, as the scan page counts them.'),
        ),
        migrations.AlterField(
            model_name='dockingpartialscanrequest',
            name='scanned_boxes',
            field=models.PositiveIntegerField(default=0, help_text='Boxes scanned against this bill when the request was raised.'),
        ),
        migrations.AddConstraint(
            model_name='dockingpartialscanrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('sales_dispatch', 'document'), name='unique_pending_partial_scan_per_bill'),
        ),
        migrations.AddConstraint(
            model_name='dockingpartialscanrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', True), ('status', 'PENDING')), fields=('sales_dispatch',), name='unique_pending_partial_scan_per_dispatch'),
        ),
    ]
