# Generated by Django 6.0.1 on 2026-07-04 11:43

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('docking_admin', '0004_partial_scan_group_permissions'),
        ('gate_core', '0046_alter_emptyvehiclegatein_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='dockingpartialscanrequest',
            index=models.Index(fields=['company', 'status'], name='dockpart_co_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='dockingpartialscanrequest',
            index=models.Index(fields=['company', '-requested_at'], name='dockpart_co_reqat_idx'),
        ),
        AddIndexConcurrently(
            model_name='dockingscanskiprequest',
            index=models.Index(fields=['company', 'status'], name='dockskip_co_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='dockingscanskiprequest',
            index=models.Index(fields=['company', '-requested_at'], name='dockskip_co_reqat_idx'),
        ),
    ]
