# Generated by Django 6.0.1 on 2026-09-16 10:05

import django.db.models.deletion
import docking_admin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docking_admin', '0005_partial_scan_request_per_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockingApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=docking_admin.models.approval_attachment_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partial_scan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='docking_admin.dockingpartialscanrequest')),
                ('scan_skip_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='docking_admin.dockingscanskiprequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docking_approval_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docking Approval Attachment',
                'verbose_name_plural': 'Docking Approval Attachments',
                'ordering': ['uploaded_at', 'id'],
                'indexes': [models.Index(fields=['scan_skip_request'], name='docking_adm_scan_sk_51f5a1_idx'), models.Index(fields=['partial_scan_request'], name='docking_adm_partial_c05fc2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('partial_scan_request__isnull', True), ('scan_skip_request__isnull', False)), models.Q(('partial_scan_request__isnull', False), ('scan_skip_request__isnull', True)), _connector='OR'), name='approval_attachment_belongs_to_one_request')],
            },
        ),
    ]
