# Generated by Django 6.0.1 on 2026-07-09 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_combos', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('FG', 'Finished Good'), ('PM', 'Packing Material')], max_length=2)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity per 1 combo unit.', max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='marketplace.combodefinition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('order_id', models.CharField(max_length=120)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('sap_warehouse_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISPATCHED', 'Dispatched'), ('RETURNED', 'Returned'), ('PARTIAL', 'Partial')], default='OPEN', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_orders', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('order_id', models.CharField(max_length=120)),
                ('invoice_number', models.CharField(max_length=60, unique=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('sap_delivery_note_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_delivery_note_num', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SUBMITTED', 'Submitted')], default='CONFIRMED', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_billings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('sap_warehouse_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCANNING', 'Scanning'), ('READY', 'Ready to confirm'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('sap_delivery_note_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_delivery_note_num', models.CharField(blank=True, max_length=50)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_dispatches', to='company.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_dispatches_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='marketplace.marketplaceorder')),
                ('internal_billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch', to='marketplace.marketplaceorderbilling')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_dispatch', 'Can view marketplace dispatch'), ('add_dispatch', 'Can create marketplace dispatch'), ('scan_dispatch', 'Can scan marketplace dispatch'), ('confirm_dispatch', 'Can confirm marketplace dispatch'), ('cancel_dispatch', 'Can cancel marketplace dispatch'), ('view_reconciliation', 'Can view marketplace reconciliation')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_sku', models.CharField(max_length=120)),
                ('sku_name', models.CharField(blank=True, max_length=200)),
                ('ordered_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='marketplace.marketplaceorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCANNING', 'Scanning'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('internal_credit_doc_num', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_returns', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='marketplace.marketplaceorder')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_returns_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_return', 'Can view marketplace return'), ('add_return', 'Can create marketplace return'), ('submit_return', 'Can submit marketplace return')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReturnScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('barcode_raw', models.CharField(max_length=500)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('component_type', models.CharField(blank=True, choices=[('FG', 'Finished Good'), ('PM', 'Packing Material')], max_length=2)),
                ('source_sku', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_return_scans', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('mp_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='marketplace.marketplacereturn')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_return_scans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('barcode_raw', models.CharField(max_length=500)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('component_type', models.CharField(blank=True, choices=[('FG', 'Finished Good'), ('PM', 'Packing Material')], max_length=2)),
                ('source_sku', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('warehouse_code', models.CharField(blank=True, max_length=50)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_scans', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='marketplace.marketplacedispatch')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_scans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('sap_warehouse_code', models.CharField(max_length=50)),
                ('sap_customer_card_code', models.CharField(blank=True, help_text='SAP business partner used as CardCode on the delivery note.', max_length=50)),
                ('facility_code', models.CharField(blank=True, help_text='e.g. MAYAPURI', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_warehouses', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkuMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('marketplace_sku', models.CharField(max_length=120)),
                ('sku_name', models.CharField(blank=True, max_length=200)),
                ('sku_type', models.CharField(choices=[('RAW', 'Raw (direct FG)'), ('COMBO', 'Combo / Kit')], default='RAW', max_length=10)),
                ('fg_item_code', models.CharField(blank=True, max_length=100)),
                ('fg_item_name', models.CharField(blank=True, max_length=200)),
                ('default_uom', models.CharField(blank=True, max_length=20)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sku_mappings', to='marketplace.combodefinition')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_sku_mappings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'marketplace_sku'],
                'permissions': [('view_master', 'Can view marketplace master data'), ('change_master', 'Can change marketplace master data')],
            },
        ),
        migrations.AddConstraint(
            model_name='combodefinition',
            constraint=models.UniqueConstraint(fields=('company', 'channel', 'code'), name='uniq_mp_combo_code'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_cb75e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorder',
            constraint=models.UniqueConstraint(fields=('company', 'channel', 'order_id'), name='uniq_mp_order'),
        ),
        migrations.AddIndex(
            model_name='marketplacedispatch',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_21f284_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplacereturnscan',
            constraint=models.UniqueConstraint(fields=('mp_return', 'barcode_raw'), name='uniq_mp_return_scan'),
        ),
        migrations.AddConstraint(
            model_name='marketplacescan',
            constraint=models.UniqueConstraint(fields=('dispatch', 'barcode_raw'), name='uniq_mp_dispatch_scan'),
        ),
        migrations.AddConstraint(
            model_name='marketplacewarehouse',
            constraint=models.UniqueConstraint(fields=('company', 'channel', 'sap_warehouse_code'), name='uniq_mp_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='skumapping',
            constraint=models.UniqueConstraint(fields=('company', 'channel', 'marketplace_sku'), name='uniq_mp_sku_mapping'),
        ),
    ]
