# Generated by Django 6.0.1 on 2026-07-11 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0002_marketplace_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combodefinition',
            name='image',
            field=models.ImageField(blank=True, help_text='Combo/pack reference photo (pick-and-pack aid).', null=True, upload_to='marketplace/combos/'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='dispatch_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='flipkart_shipment_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='order_type',
            field=models.CharField(blank=True, help_text='e.g. NON_FBF', max_length=40),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='ship_to_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='fsn',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='order_item_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='order_state',
            field=models.CharField(blank=True, help_text="Flipkart 'Order State'", max_length=40),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='raw_row',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='skumapping',
            name='image',
            field=models.ImageField(blank=True, help_text='SKU reference photo (pick-and-pack aid).', null=True, upload_to='marketplace/skus/'),
        ),
        migrations.CreateModel(
            name='MarketplaceIssueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('sap_warehouse_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to warehouse'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued'), ('RECEIVED', 'Received')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('sap_issue_doc_entries', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_issue_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_issue_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('send_issue_request', 'Can send marketplace issue request to warehouse'), ('review_issue_request', 'Can approve/reject marketplace issue request'), ('issue_materials', 'Can issue materials for a marketplace request'), ('receive_issue', 'Can receive issued marketplace materials')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('component_type', models.CharField(choices=[('FG', 'Finished Good'), ('PM', 'Packing Material')], max_length=2)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('required_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('available_stock', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('approved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('source_skus', models.JSONField(blank=True, default=list)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='marketplace.marketplaceissuerequest')),
            ],
            options={
                'ordering': ['component_type', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/returns/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.marketplacereturnscan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], default='FLIPKART', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='marketplace/imports/')),
                ('status', models.CharField(choices=[('PARSED', 'Parsed'), ('RESOLVED', 'Resolved'), ('REQUESTED', 'Sent to warehouse'), ('ISSUED', 'Issued'), ('DISPATCHING', 'Dispatching'), ('CLOSED', 'Closed')], default='PARSED', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('line_count', models.IntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_import_batches', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('import_orders', 'Can import marketplace order sheets'), ('view_batch', 'Can view marketplace import batches')],
            },
        ),
        migrations.AddField(
            model_name='marketplaceissuerequest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_requests', to='marketplace.orderimportbatch'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.orderimportbatch'),
        ),
    ]
