# Generated by Django 6.0.1 on 2026-07-13 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0004_sheet_flow_group_perms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PACKING', 'In progress'), ('PACKED', 'Packed')], default='PENDING', max_length=20)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_packings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing', to='marketplace.marketplaceorder')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_packings_packed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_packing', 'Can view marketplace packing'), ('pack_order', 'Can pack marketplace orders')],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePackBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('source_sku', models.CharField(blank=True, max_length=120)),
                ('printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_pack_barcodes', to='company.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_barcodes', to='marketplace.marketplaceorder')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='marketplace.marketplacepacking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
