# Generated by Django 6.0.1 on 2026-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_packing_group_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_post_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
