# Generated by Django 6.0.1 on 2026-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_marketplacedispatch_sap_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_goods_issue_doc_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_goods_issue_num',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
