# Generated by Django 6.0.1 on 2026-07-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_marketplacedispatch_sap_goods_issue_doc_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacewarehouse',
            name='post_goods_issue',
            field=models.BooleanField(default=True, help_text='Post the packing-material Goods Issue when dispatching. Off = Delivery Note only.'),
        ),
        migrations.AddField(
            model_name='marketplacewarehouse',
            name='sap_series',
            field=models.CharField(blank=True, help_text='SAP document numbering Series for the Delivery Note / Goods Issue. Blank = SAP default.', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacewarehouse',
            name='sap_tax_code',
            field=models.CharField(blank=True, help_text='Default tax code (VatGroup) applied to each Delivery Note line. Blank = none.', max_length=20),
        ),
    ]
