# Generated by Django 6.0.1 on 2026-07-14 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0009_marketplacewarehouse_post_goods_issue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skumapping',
            name='fsn',
            field=models.CharField(blank=True, db_index=True, help_text='Flipkart FSN — primary key mapped to the SAP item code.', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='skumapping',
            constraint=models.UniqueConstraint(condition=models.Q(('fsn__gt', '')), fields=('company', 'channel', 'fsn'), name='uniq_mp_sku_fsn'),
        ),
    ]
