# Generated by Django 6.0.1 on 2026-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_skumapping_fsn_skumapping_uniq_mp_sku_fsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepacking',
            name='pack_barcode',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketplacereturnscan',
            name='condition',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('WRONG_ITEM', 'Wrong Item Received'), ('PARTIAL', 'Partial Receiving'), ('MISSING', 'Missing Item'), ('EXCESS', 'Excess Quantity'), ('PACKAGING_DAMAGED', 'Packaging Damaged'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacereturnscan',
            name='condition_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
