# Generated by Django 6.0.1 on 2026-07-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_marketplacepacking_pack_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacepackbarcode',
            name='barcode',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
