# Generated by Django 6.0.1 on 2026-07-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0012_alter_marketplacepackbarcode_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('skip_packing', models.BooleanField(default=False, help_text='Skip the Packing step: issued orders go straight to Outward.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_settings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace settings',
                'verbose_name_plural': 'Marketplace settings',
                'ordering': ['channel'],
                'constraints': [models.UniqueConstraint(fields=('company', 'channel'), name='uniq_mp_settings')],
            },
        ),
    ]
