# Generated by Django 6.0.1 on 2026-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_marketplacesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='defer_delivery_note',
            field=models.BooleanField(default=False, help_text="Don't post the SAP Delivery Note when a dispatch is confirmed. Instead cut one bulk Delivery Note for all confirmed dispatches from the SAP Delivery Notes page."),
        ),
    ]
