# Generated by Django 6.0.1 on 2026-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_marketplacesettings_defer_delivery_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacewarehouse',
            name='sap_branch_id',
            field=models.IntegerField(blank=True, help_text="SAP Business Place / Branch (BPLId) the delivery note is booked under. Required by SAP's GST localization.", null=True),
        ),
    ]
