# Generated by Django 6.0.1 on 2026-07-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_marketplacewarehouse_sap_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_delivery_note_draft_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_dn_ref',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='marketplacedispatch',
            name='sap_post_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('FAILED', 'Failed'), ('AWAITING_APPROVAL', 'Awaiting SAP approval')], default='PENDING', max_length=20),
        ),
    ]
