# Generated by Django 6.0.1 on 2026-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_marketplacedispatch_sap_delivery_note_draft_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacewarehouse',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected warehouse when cutting a delivery note for this channel. The operator can still choose a different one at cut time.'),
        ),
    ]
