# Generated by Django 6.0.1 on 2026-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_marketplacewarehouse_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorderline',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
