# Generated by Django 6.0.1 on 2026-07-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_backfill_line_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuMappingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Operator-facing name, e.g. 'SANO Sunflower'.", max_length=200)),
                ('sku_type', models.CharField(choices=[('RAW', 'Raw (direct FG)'), ('COMBO', 'Combo / Kit')], default='RAW', max_length=10)),
                ('fg_item_code', models.CharField(blank=True, max_length=100)),
                ('fg_item_name', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapping_options', to='marketplace.combodefinition')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='marketplace.skumapping')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.AddField(
            model_name='marketplaceorderline',
            name='chosen_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_lines', to='marketplace.skumappingoption'),
        ),
    ]
