# Generated by Django 6.0.1 on 2026-07-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_skumappingoption_marketplaceorderline_chosen_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorderline',
            name='component_choices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ComboComponentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='marketplace.combocomponent')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
    ]
