# Generated by Django 6.0.1 on 2026-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_marketplaceorderline_component_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacewarehouse',
            name='shipto_by_state',
            field=models.JSONField(blank=True, default=dict, help_text='Optional ship-to STATE → SAP ship-to/bill-to address code, splitting the delivery note by GST place of supply (the branch stays sap_branch_id). e.g. {"Delhi": "FLIPKART B2C DELHI", "*": "FLIPKART B2C HARYANA"} sets Delhi ship-to orders to the Delhi address and every other state to the Haryana address. "*" = default for unlisted states. Empty = no ShipToCode set (SAP uses the customer\'s default address, one delivery note).'),
        ),
    ]
