# Generated by Django 6.0.1 on 2026-07-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_marketplacewarehouse_shipto_by_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='combocomponentoption',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Combo units of THIS item when it is the one picked. Blank = same quantity as the component.', max_digits=18, null=True),
        ),
    ]
