# Generated by Django 6.0.1 on 2026-07-27 09:03
# Uses AddIndexConcurrently (atomic=False) so creating these indexes on the live
# Postgres tables does NOT take a write lock. Runs outside a transaction.
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('marketplace', '0023_combocomponentoption_quantity'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='marketplaceissuerequest',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_ec2aef_idx'),
        ),
        AddIndexConcurrently(
            model_name='marketplacereturn',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_9d49da_idx'),
        ),
        AddIndexConcurrently(
            model_name='orderimportbatch',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_64a241_idx'),
        ),
    ]
