# Generated by Django 6.0.1 on 2026-07-27 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0023_combocomponentoption_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketplaceissuerequest',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_ec2aef_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacereturn',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_9d49da_idx'),
        ),
        migrations.AddIndex(
            model_name='orderimportbatch',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_64a241_idx'),
        ),
    ]
