# Generated by Django 6.0.1 on 2026-07-27 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0024_marketplaceissuerequest_marketplace_company_ec2aef_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marketplacereturn',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_credit_doc_num', ''), _negated=True), fields=('company', 'internal_credit_doc_num'), name='uq_mp_return_note_per_company'),
        ),
    ]
