# Generated by Django 6.0.1 on 2026-07-28 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0025_marketplacereturn_uq_mp_return_note_per_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceImportSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_id', models.CharField(max_length=120)),
                ('reason', models.CharField(choices=[('DISPATCHED', 'Already dispatched on an earlier sheet'), ('DUPLICATE', 'Not re-imported (duplicate)')], max_length=12)),
                ('row_count', models.PositiveSmallIntegerField(default=0)),
                ('tracking_ids', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_import_skips', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='marketplace.orderimportbatch')),
                ('kept_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.marketplaceorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_id'],
                'indexes': [models.Index(fields=['company', 'import_batch'], name='marketplace_company_5a017d_idx')],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'order_id'), name='uq_mp_import_skip')],
            },
        ),
    ]
