# Generated by Django 6.0.1 on 2026-07-31 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_marketplaceimportskip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='gate_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='gate_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_dispatches_gate_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='gate_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='gate_status',
            field=models.CharField(choices=[('PENDING', 'Pending gate check'), ('APPROVED', 'Approved (OK from gate)'), ('HOLD', 'Held at gate')], default='PENDING', max_length=12),
        ),
    ]
