# Generated by Django 6.0.1 on 2026-07-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_marketplacedispatch_gate_checked_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacedispatch',
            options={'ordering': ['-created_at'], 'permissions': [('view_dispatch', 'Can view marketplace dispatch'), ('add_dispatch', 'Can create marketplace dispatch'), ('scan_dispatch', 'Can scan marketplace dispatch'), ('confirm_dispatch', 'Can confirm marketplace dispatch'), ('cancel_dispatch', 'Can cancel marketplace dispatch'), ('view_reconciliation', 'Can view marketplace reconciliation'), ('gate_check', 'Can perform the marketplace out-gate check')]},
        ),
    ]
