# Generated by Django 6.0.1 on 2026-08-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_gate_check_group_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='marketplace.orderimportbatch'),
        ),
    ]
