# Generated by Django 6.0.1 on 2026-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_backfill_dispatch_import_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacedispatch',
            options={'ordering': ['-created_at'], 'permissions': [('view_dispatch', 'Can view marketplace dispatch'), ('add_dispatch', 'Can create marketplace dispatch'), ('scan_dispatch', 'Can scan marketplace dispatch'), ('confirm_dispatch', 'Can confirm marketplace dispatch'), ('backdate_delivery_note', 'Can cut a marketplace delivery note into a previous month'), ('cancel_dispatch', 'Can cancel marketplace dispatch'), ('view_reconciliation', 'Can view marketplace reconciliation'), ('gate_check', 'Can perform the marketplace out-gate check')]},
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_delivery_note_doc_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
