# Generated by Django 6.0.1 on 2026-08-12 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0015_alter_vehicleentry_entry_type'),
        ('marketplace', '0033_backdate_delivery_note_perm'),
        ('vehicle_management', '0008_vehicle_height_m_vehicle_length_m_vehicle_width_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WEIGHED', 'Weighed'), ('GATEPASS_PRINTED', 'Gatepass printed'), ('DISPATCHED', 'Dispatched out'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('transporter_name', models.CharField(blank=True, max_length=150)),
                ('transporter_gstin', models.CharField(blank=True, max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_mobile_no', models.CharField(blank=True, max_length=15)),
                ('driver_license_no', models.CharField(blank=True, max_length=50)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=12, null=True)),
                ('weighbridge_slip_no', models.CharField(blank=True, max_length=50)),
                ('first_weighment_at', models.DateTimeField(blank=True, null=True)),
                ('second_weighment_at', models.DateTimeField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('parcel_count', models.PositiveIntegerField(default=0)),
                ('gatepass_no', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('random_code', models.CharField(blank=True, max_length=50)),
                ('qr_payload', models.TextField(blank=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('gate_out_date', models.DateField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('security_name', models.CharField(blank=True, max_length=100)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_passes_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_gate_passes', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_passes_dispatched', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_passes', to='driver_management.driver')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='marketplace.orderimportbatch')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_passes_printed', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_passes', to='vehicle_management.transporter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_passes', to='vehicle_management.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view_mp_gate_pass', 'Can view marketplace gate passes'), ('can_manage_mp_gate_pass', 'Can create and edit marketplace gate passes'), ('can_weigh_mp_gate_pass', 'Can record marketplace gate pass weighment'), ('can_print_mp_gate_pass', 'Can print a marketplace gatepass'), ('can_dispatch_mp_gate_pass', 'Can mark a marketplace gate pass out')],
            },
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='gate_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='marketplace.marketplacegatepass'),
        ),
        migrations.CreateModel(
            name='MarketplaceGatepassSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_gatepass_sequences', to='company.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='marketplacegatepass',
            index=models.Index(fields=['company', 'channel', 'status'], name='marketplace_company_d5e2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacegatepass',
            index=models.Index(fields=['company', 'import_batch'], name='marketplace_company_fd5611_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacegatepass',
            index=models.Index(fields=['company', 'gate_out_date'], name='marketplace_company_6a1673_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplacegatepasssequence',
            constraint=models.UniqueConstraint(fields=('company', 'financial_year'), name='unique_marketplace_gatepass_sequence'),
        ),
    ]
