# Generated by Django 6.0.1 on 2026-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0034_marketplacegatepass_marketplacedispatch_gate_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_posted_lines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
