# Generated by Django 6.0.1 on 2026-08-17 11:54

from django.db import migrations, models


def demote_extra_defaults(apps, schema_editor):
    """Leave exactly one default per parent before the constraint is applied.

    Nothing in the database stopped a second default being written, so live data
    may carry several. Resolution already behaves as if only the first exists
    (options are ordered default-first, then by id), so keeping the lowest-id
    default and demoting the rest changes what ships for nobody — it just makes
    the stored data say what the code was already doing.
    """
    for model_name, parent in (
        ("SkuMappingOption", "mapping_id"),
        ("ComboComponentOption", "component_id"),
    ):
        model = apps.get_model("marketplace", model_name)
        keep = set()
        demote = []
        for pk, parent_id in (
            model.objects.filter(is_default=True)
            .order_by(parent, "id")
            .values_list("id", parent)
        ):
            if parent_id in keep:
                demote.append(pk)
            else:
                keep.add(parent_id)
        if demote:
            model.objects.filter(id__in=demote).update(is_default=False)


def noop(apps, schema_editor):
    """Nothing to undo: the demoted rows were never reachable as defaults."""


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_gate_pass_group_perms'),
    ]

    operations = [
        migrations.RunPython(demote_extra_defaults, noop),
        migrations.AddConstraint(
            model_name='combocomponentoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('component',), name='uniq_mp_component_option_default'),
        ),
        migrations.AddConstraint(
            model_name='skumappingoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('mapping',), name='uniq_mp_mapping_option_default'),
        ),
    ]
