# Generated by Django 6.0.1 on 2026-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_combocomponentoption_uniq_mp_component_option_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='shipped_trackings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
