# Generated by Django 6.0.1 on 2026-08-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_marketplacedispatch_shipped_trackings'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedispatch',
            name='sap_ship_to_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
