# Generated by Django 6.0.1 on 2026-08-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_dispatch_sap_ship_to_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceGatePassAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DELIVERY_NOTE', 'Delivery Note'), ('GATEPASS', 'Gatepass'), ('BILTY', 'Bilty'), ('EWAY_BILL', 'E-Way Bill'), ('TRUCK_PHOTO', 'Truck Photo'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='marketplace/gate_passes/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('document_no', models.CharField(blank=True, max_length=100)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('remove_reason', models.TextField(blank=True)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketplace.marketplacegatepass')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_pass_attachments_removed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_gate_pass_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['gate_pass', 'document_type'], name='marketplace_gate_pa_ba2449_idx')],
            },
        ),
    ]
