# Generated by Django 6.0.1 on 2026-08-27 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_marketplacegatepassattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacegatepass',
            name='box_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplacegatepass',
            name='delivery_note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacegatepass',
            name='delivery_note_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketplacegatepass',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='marketplace.orderimportbatch'),
        ),
    ]
