# Generated by Django 6.0.1 on 2026-08-31 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('marketplace', '0041_marketplacegatepass_box_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketplaceorder',
            name='uniq_mp_order',
        ),
        migrations.AddField(
            model_name='marketplacedispatch',
            name='dn_covered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_dispatches', to='marketplace.marketplacedispatch'),
        ),
        migrations.AlterField(
            model_name='marketplacedispatch',
            name='sap_post_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('FAILED', 'Failed'), ('AWAITING_APPROVAL', 'Awaiting SAP approval'), ('NOT_REQUIRED', 'Not required (already shipped on an earlier sheet)')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['company', 'channel', 'order_id'], name='marketplace_company_cfd507_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorder',
            constraint=models.UniqueConstraint(condition=models.Q(('import_batch__isnull', False)), fields=('company', 'channel', 'order_id', 'import_batch'), name='uniq_mp_order_per_sheet'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorder',
            constraint=models.UniqueConstraint(condition=models.Q(('import_batch__isnull', True)), fields=('company', 'channel', 'order_id'), name='uniq_mp_order_no_sheet'),
        ),
    ]
