# Generated by Django 6.0.1 on 2026-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_remove_marketplaceorder_uniq_mp_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorderline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
