# Generated by Django 6.0.1 on 2026-03-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0004_remove_production_planning_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinebreakdown',
            name='type',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='external_breakdown_time',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='line_breakdown_time',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='total_minutes_me',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='total_minutes_pe',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='unrecorded_time',
        ),
        migrations.AddField(
            model_name='machinebreakdown',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True if breakdown is ongoing'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='total_running_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total running minutes from segments'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='total_production',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total cases produced (entered at completion)', max_digits=12),
        ),
        migrations.CreateModel(
            name='BreakdownCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_categories', to='company.company')),
            ],
            options={
                'verbose_name': 'Breakdown Category',
                'verbose_name_plural': 'Breakdown Categories',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='machinebreakdown',
            name='breakdown_category',
            field=models.ForeignKey(blank=True, help_text='Configurable breakdown type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='breakdowns', to='production_execution.breakdowncategory'),
        ),
        migrations.CreateModel(
            name='ProductionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('produced_cases', models.DecimalField(decimal_places=1, default=0, help_text='Cases produced during this running period', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='True if this segment is currently running')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='production_execution.productionrun')),
            ],
            options={
                'verbose_name': 'Production Segment',
                'verbose_name_plural': 'Production Segments',
                'ordering': ['start_time'],
            },
        ),
        migrations.DeleteModel(
            name='ProductionLog',
        ),
    ]
