# Generated by Django 6.0.1 on 2026-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0005_remove_machinebreakdown_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsegment',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
