# Generated by Django 6.0.1 on 2026-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0006_productionsegment_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrun',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='sap_order_no',
        ),
        migrations.AddField(
            model_name='productionrun',
            name='labour_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of labourers'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='machines',
            field=models.ManyToManyField(blank=True, help_text='Machines used in this run', related_name='production_runs', to='production_execution.machine'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='operators',
            field=models.CharField(blank=True, default='', help_text='Engineer/operator names', max_length=500),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='other_manpower_count',
            field=models.PositiveIntegerField(default=0, help_text='Other manpower count'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='product',
            field=models.CharField(blank=True, default='', help_text='Product name (auto-filled from SAP ItemName)', max_length=200),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='rated_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rated speed (cases/hr)', max_digits=10, null=True),
        ),
    ]
