# Generated by Django 6.0.1 on 2026-03-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0007_remove_productionrun_brand_remove_productionrun_pack_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionmaterialusage',
            options={'ordering': ['material_name'], 'verbose_name': 'Production Material Usage', 'verbose_name_plural': 'Production Material Usages'},
        ),
        migrations.RemoveField(
            model_name='productionmaterialusage',
            name='batch_number',
        ),
    ]
