# Generated by Django 6.0.1 on 2026-03-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0008_alter_productionmaterialusage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcelabour',
            name='worker_name',
        ),
        migrations.AddField(
            model_name='resourcelabour',
            name='description',
            field=models.CharField(blank=True, default='', help_text='e.g., Skilled labourers, Helpers', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcelabour',
            name='worker_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
