# Generated by Django 6.0.1 on 2026-03-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0009_remove_resourcelabour_worker_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productionrun',
            unique_together={('company', 'date', 'run_number')},
        ),
    ]
