# Generated by Django 6.0.1 on 2026-03-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0010_alter_productionrun_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineclearance',
            name='sap_doc_entry',
        ),
        migrations.AddField(
            model_name='lineclearance',
            name='production_run',
            field=models.ForeignKey(blank=True, help_text='Links clearance to a specific production run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_clearances', to='production_execution.productionrun'),
        ),
    ]
