# Generated by Django 6.0.1 on 2026-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0011_remove_lineclearance_sap_doc_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='rejected_qty',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Rejected quantity from QC failures', max_digits=12),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='reworked_qty',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Reworked quantity from QC failures', max_digits=12),
        ),
    ]
