# Generated by Django 6.0.3 on 2026-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0012_productionrun_rejected_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='sap_receipt_doc_entry',
            field=models.IntegerField(blank=True, help_text='SAP receipt DocEntry after production is synced', null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='sap_sync_error',
            field=models.TextField(blank=True, default='', help_text='Error message from last SAP sync attempt'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='sap_sync_status',
            field=models.CharField(blank=True, default='', help_text='SAP sync status (e.g. PENDING, SUCCESS, FAILED)', max_length=20),
        ),
    ]
