# Generated by Django 6.0.1 on 2026-03-31 07:12
# Fixed: now depends on 0013_add_sap_sync_fields which adds the same fields.
# The AlterField ops update the field definitions to the final version.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0013_add_sap_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrun',
            name='sap_receipt_doc_entry',
            field=models.IntegerField(blank=True, help_text='SAP Goods Receipt DocEntry after successful post', null=True),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='sap_sync_error',
            field=models.TextField(blank=True, default='', help_text='Error message if SAP goods receipt post fails'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='sap_sync_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NOT_APPLICABLE', help_text='SAP goods receipt sync status', max_length=20),
        ),
    ]
