# Generated by Django 6.0.1 on 2026-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0013_sap_goods_receipt_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='required_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required production quantity — BOM scales to this', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='warehouse_approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', help_text='Warehouse BOM approval status', max_length=25),
        ),
    ]
