# Generated by Django 6.0.1 on 2026-04-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0014_productionrun_required_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSkuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, default='', help_text='SAP Item Code (SKU). Leave blank for line-level defaults.', max_length=100)),
                ('sku_name', models.CharField(blank=True, default='', help_text='Product / SKU name for display', max_length=300)),
                ('rated_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Rated speed in cases/hr for this line+SKU', max_digits=10, null=True)),
                ('labour_count', models.PositiveIntegerField(default=0, help_text='Standard labour count for this line+SKU')),
                ('other_manpower_count', models.PositiveIntegerField(default=0, help_text='Standard other manpower count')),
                ('supervisor', models.CharField(blank=True, default='', help_text='Default supervisor name', max_length=200)),
                ('operators', models.CharField(blank=True, default='', help_text='Default engineer/operator names', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_sku_configs', to='company.company')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sku_configs', to='production_execution.productionline')),
            ],
            options={
                'verbose_name': 'Line SKU Config',
                'verbose_name_plural': 'Line SKU Configs',
                'ordering': ['line', 'sku_name'],
                'unique_together': {('company', 'line', 'sku_code')},
            },
        ),
    ]
