# Generated by Django 6.0.1 on 2026-04-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0015_add_line_sku_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineskuconfig',
            options={'ordering': ['line', 'config_name'], 'verbose_name': 'Line Config', 'verbose_name_plural': 'Line Configs'},
        ),
        migrations.AlterUniqueTogether(
            name='lineskuconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lineskuconfig',
            name='config_name',
            field=models.CharField(default='Default', help_text="Display name for this preset (e.g., 'Olive Oil 1L - Day Shift')", max_length=300),
        ),
        migrations.AlterField(
            model_name='lineskuconfig',
            name='labour_count',
            field=models.PositiveIntegerField(default=0, help_text='Standard labour count'),
        ),
        migrations.AlterField(
            model_name='lineskuconfig',
            name='rated_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rated speed in cases/hr', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lineskuconfig',
            name='sku_code',
            field=models.CharField(blank=True, default='', help_text='SAP Item Code (SKU). Optional.', max_length=100),
        ),
        migrations.AlterField(
            model_name='lineskuconfig',
            name='sku_name',
            field=models.CharField(blank=True, default='', help_text='Product / SKU name', max_length=300),
        ),
    ]
