# Generated by Django 6.0.3 on 2026-04-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0016_update_line_config_add_name_remove_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineclearance',
            name='production_incharge_sign',
        ),
        migrations.AddField(
            model_name='lineclearance',
            name='all_checks_passed',
            field=models.BooleanField(default=False),
        ),
    ]
