# Generated by Django 6.0.1 on 2026-07-04 11:43

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0023_alter_machinebreakdown_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='lineclearance',
            index=models.Index(fields=['company', '-date'], name='lineclr_co_date_idx'),
        ),
        AddIndexConcurrently(
            model_name='productionrun',
            index=models.Index(fields=['company', 'status', '-date'], name='prodrun_co_status_date_idx'),
        ),
        AddIndexConcurrently(
            model_name='productionrun',
            index=models.Index(fields=['sap_doc_entry'], name='prodrun_sap_doc_idx'),
        ),
    ]
