# Generated by Django 6.0.1 on 2026-07-16 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0023_alter_machinebreakdown_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineclearance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ON_HOLD', 'On Hold'), ('CLEARED', 'Cleared'), ('NOT_CLEARED', 'Not Cleared')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='LineClearanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='line_clearance_attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='production_execution.lineclearance')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_clearance_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Line Clearance Attachment',
                'verbose_name_plural': 'Line Clearance Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
