# Generated by Django 6.0.1 on 2026-07-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0024_alter_lineclearance_status_lineclearanceattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineclearance',
            name='qa_remarks',
            field=models.TextField(blank=True, default='', help_text='QC remarks captured on hold/reject (and optionally on approve)'),
        ),
    ]
