# Generated by Django 6.0.1 on 2026-07-16 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0025_lineclearance_qa_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionrun',
            options={'ordering': ['-date', 'line', 'run_number'], 'permissions': [('can_manage_production_lines', 'Can manage production lines'), ('can_manage_machines', 'Can manage machines'), ('can_manage_checklist_templates', 'Can manage checklist templates'), ('can_view_production_run', 'Can view production runs'), ('can_create_production_run', 'Can create production runs'), ('can_edit_production_run', 'Can edit production runs'), ('can_complete_production_run', 'Can complete production runs'), ('can_view_production_log', 'Can view production logs'), ('can_edit_production_log', 'Can create/edit production logs'), ('can_view_breakdown', 'Can view breakdowns'), ('can_create_breakdown', 'Can create breakdowns'), ('can_edit_breakdown', 'Can edit breakdowns'), ('can_view_material_usage', 'Can view material usage'), ('can_create_material_usage', 'Can create material usage'), ('can_edit_material_usage', 'Can edit material usage'), ('can_view_machine_runtime', 'Can view machine runtime'), ('can_create_machine_runtime', 'Can create machine runtime'), ('can_view_manpower', 'Can view manpower'), ('can_create_manpower', 'Can create manpower'), ('can_view_line_clearance', 'Can view line clearance'), ('can_create_line_clearance', 'Can create line clearance'), ('can_approve_line_clearance_qa', 'Can QA-approve line clearance'), ('can_manage_line_clearance', 'Can manage/override line clearance decisions'), ('can_view_machine_checklist', 'Can view machine checklists'), ('can_create_machine_checklist', 'Can create machine checklist entries'), ('can_view_waste_log', 'Can view waste logs'), ('can_create_waste_log', 'Can create waste logs'), ('can_approve_waste_engineer', 'Can engineer-approve waste'), ('can_approve_waste_am', 'Can AM-approve waste'), ('can_approve_waste_store', 'Can store-approve waste'), ('can_approve_waste_hod', 'Can HOD-approve waste'), ('can_view_reports', 'Can view production reports')], 'verbose_name': 'Production Run', 'verbose_name_plural': 'Production Runs'},
        ),
        migrations.CreateModel(
            name='LineClearanceDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ON_HOLD', 'On Hold'), ('CLEARED', 'Cleared'), ('NOT_CLEARED', 'Not Cleared')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='production_execution.lineclearance')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_clearance_decision_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Line Clearance Decision Log',
                'verbose_name_plural': 'Line Clearance Decision Logs',
                'ordering': ['-decided_at', '-id'],
                'indexes': [models.Index(fields=['clearance', '-decided_at'], name='production__clearan_8faddd_idx')],
            },
        ),
    ]
