# Generated by Django 6.0.1 on 2026-07-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0027_grant_line_clearance_manager_to_tajinderjit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='item_code',
            field=models.CharField(blank=True, default='', help_text='SAP item code (OITM ItemCode) — BOM lookup key for OITT/ITT1', max_length=100),
        ),
    ]
