# Generated by Django 6.0.1 on 2026-07-25 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0028_productionrun_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='electricity_units_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Standard electricity units (kWh) drawn per running hour. Variable electricity cost = this x running_hours x rate/unit.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionline',
            name='standard_hours_per_month',
            field=models.DecimalField(decimal_places=2, default=572, help_text='Standard operating hours per month for this line (e.g. 26 days x 22 hr = 572). Denominator for apportioning PER_MONTH fixed costs onto a run: (rate/month / std_hours) x run_running_hours.', max_digits=8),
        ),
        migrations.CreateModel(
            name='CostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELECTRICITY_VARIABLE', 'Electricity — Variable'), ('ELECTRICITY_FIXED', 'Electricity — Fixed (Demand Charge)'), ('LABOUR', 'Labour'), ('MANPOWER_SALARIED', 'Supervisor / Salaried Manpower'), ('LUBRICATION', 'Lubrication'), ('LAB_CHEMICALS', 'Lab Chemicals'), ('BATCH_CODING', 'Batch Coding (Ink)'), ('MAINTENANCE', 'Maintenance / Spares'), ('WATER', 'Water'), ('OVERHEAD', 'Overhead (Rent / Admin / ETP)'), ('WASTE_RECOVERY', 'Waste Sale Recovery'), ('OTHER', 'Other')], max_length=30)),
                ('basis', models.CharField(choices=[('PER_UNIT', 'Per Unit (per case produced)'), ('PER_HOUR', 'Per Hour (per running hour)'), ('PER_MONTH', 'Per Month (fixed — apportioned)')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='Rate value, interpreted per the basis.', max_digits=15)),
                ('is_credit', models.BooleanField(default=False, help_text='True if this reduces net cost (e.g. waste sale recovery).')),
                ('label', models.CharField(blank=True, default='', help_text="Optional custom label (e.g. 'Diesel for DG set').", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_rates', to='company.company')),
                ('line', models.ForeignKey(blank=True, help_text='NULL = company-wide default; set = per-line override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_rates', to='production_execution.productionline')),
            ],
            options={
                'verbose_name': 'Cost Rate',
                'verbose_name_plural': 'Cost Rates',
                'ordering': ['line', 'category'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('line__isnull', True)), fields=('company', 'category'), name='uniq_active_global_cost_rate_per_category'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('line__isnull', False)), fields=('company', 'line', 'category'), name='uniq_active_line_cost_rate_per_category')],
            },
        ),
    ]
