# Generated by Django 6.0.1 on 2026-07-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0029_productionline_electricity_units_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmaterialusage',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='SAP unit price (LastPurPrc) snapshotted at run start. Drives material cost.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='productionruncost',
            name='net_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total_cost minus credits (e.g. waste recovery).', max_digits=15),
        ),
        migrations.AddField(
            model_name='productionruncost',
            name='waste_recovery_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value recovered by selling waste/scrap (a credit).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='costrate',
            name='category',
            field=models.CharField(choices=[('MATERIAL', 'BOM Material'), ('ELECTRICITY_VARIABLE', 'Electricity — Variable'), ('ELECTRICITY_FIXED', 'Electricity — Fixed (Demand Charge)'), ('LABOUR', 'Labour'), ('MANPOWER_SALARIED', 'Supervisor / Salaried Manpower'), ('LUBRICATION', 'Lubrication'), ('LAB_CHEMICALS', 'Lab Chemicals'), ('BATCH_CODING', 'Batch Coding (Ink)'), ('MAINTENANCE', 'Maintenance / Spares'), ('WATER', 'Water'), ('OVERHEAD', 'Overhead (Rent / Admin / ETP)'), ('WASTE_RECOVERY', 'Waste Sale Recovery'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productionruncost',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all cost components (before credits).', max_digits=15),
        ),
        migrations.CreateModel(
            name='ProductionRunCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIAL', 'BOM Material'), ('ELECTRICITY_VARIABLE', 'Electricity — Variable'), ('ELECTRICITY_FIXED', 'Electricity — Fixed (Demand Charge)'), ('LABOUR', 'Labour'), ('MANPOWER_SALARIED', 'Supervisor / Salaried Manpower'), ('LUBRICATION', 'Lubrication'), ('LAB_CHEMICALS', 'Lab Chemicals'), ('BATCH_CODING', 'Batch Coding (Ink)'), ('MAINTENANCE', 'Maintenance / Spares'), ('WATER', 'Water'), ('OVERHEAD', 'Overhead (Rent / Admin / ETP)'), ('WASTE_RECOVERY', 'Waste Sale Recovery'), ('OTHER', 'Other')], max_length=30)),
                ('basis', models.CharField(blank=True, choices=[('PER_UNIT', 'Per Unit (per case produced)'), ('PER_HOUR', 'Per Hour (per running hour)'), ('PER_MONTH', 'Per Month (fixed — apportioned)')], default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_credit', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', help_text="Human-readable calc note, e.g. '120 kWh × ₹7.00'.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='production_execution.productionrun')),
            ],
            options={
                'verbose_name': 'Production Run Cost Line',
                'verbose_name_plural': 'Production Run Cost Lines',
                'ordering': ['production_run', 'category'],
                'unique_together': {('production_run', 'category')},
            },
        ),
    ]
