# Generated by Django 6.0.1 on 2026-07-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0030_productionmaterialusage_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='standard_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=22, help_text='Standard operating hours per day for this line. Denominator for apportioning PER_DAY fixed costs: (rate/day / std_hours_per_day) x run_running_hours.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='costrate',
            name='basis',
            field=models.CharField(choices=[('PER_UNIT', 'Per Unit (per case produced)'), ('PER_HOUR', 'Per Hour (per running hour)'), ('PER_DAY', 'Per Day (fixed — apportioned)'), ('PER_MONTH', 'Per Month (fixed — apportioned)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionruncostline',
            name='basis',
            field=models.CharField(blank=True, choices=[('PER_UNIT', 'Per Unit (per case produced)'), ('PER_HOUR', 'Per Hour (per running hour)'), ('PER_DAY', 'Per Day (fixed — apportioned)'), ('PER_MONTH', 'Per Month (fixed — apportioned)')], default='', max_length=20),
        ),
    ]
