# Generated by Django 6.0.1 on 2026-07-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0031_productionline_standard_hours_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineskuconfig',
            name='electricity_cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='lineskuconfig',
            name='labour_cost_per_hour',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='electricity_cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='productionrun',
            name='labour_cost_per_hour',
        ),
    ]
