# Generated by Django 6.0.1 on 2026-07-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0032_remove_lineskuconfig_electricity_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrate',
            name='basis',
            field=models.CharField(choices=[('PER_UNIT', 'Per Case'), ('PER_PERSON_DAY', 'Per Person per Day'), ('PER_DAY', 'Per Day (fixed)'), ('PER_HOUR', 'Per Hour'), ('PER_MONTH', 'Per Month')], max_length=20),
        ),
        migrations.AlterField(
            model_name='costrate',
            name='category',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('ELECTRICITY_VARIABLE', 'Electricity — Usage'), ('ELECTRICITY_FIXED', 'Electricity — Fixed (per day)'), ('LABOUR', 'Labour'), ('MANPOWER_SALARIED', 'Salary'), ('LUBRICATION', 'Lubrication'), ('LAB_CHEMICALS', 'Lab Chemicals'), ('BATCH_CODING', 'Batch Coding'), ('MAINTENANCE', 'Maintenance'), ('WATER', 'Water'), ('OVERHEAD', 'Overhead'), ('WASTE_RECOVERY', 'Waste Recovery'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productionruncostline',
            name='basis',
            field=models.CharField(blank=True, choices=[('PER_UNIT', 'Per Case'), ('PER_PERSON_DAY', 'Per Person per Day'), ('PER_DAY', 'Per Day (fixed)'), ('PER_HOUR', 'Per Hour'), ('PER_MONTH', 'Per Month')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionruncostline',
            name='category',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('ELECTRICITY_VARIABLE', 'Electricity — Usage'), ('ELECTRICITY_FIXED', 'Electricity — Fixed (per day)'), ('LABOUR', 'Labour'), ('MANPOWER_SALARIED', 'Salary'), ('LUBRICATION', 'Lubrication'), ('LAB_CHEMICALS', 'Lab Chemicals'), ('BATCH_CODING', 'Batch Coding'), ('MAINTENANCE', 'Maintenance'), ('WATER', 'Water'), ('OVERHEAD', 'Overhead'), ('WASTE_RECOVERY', 'Waste Recovery'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
