# Generated by Django 6.0.1 on 2026-07-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0033_alter_costrate_basis_alter_costrate_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionrun',
            options={'ordering': ['-date', 'line', 'run_number'], 'permissions': [('can_manage_production_lines', 'Can manage production lines'), ('can_manage_machines', 'Can manage machines'), ('can_manage_checklist_templates', 'Can manage checklist templates'), ('can_view_production_run', 'Can view production runs'), ('can_create_production_run', 'Can create production runs'), ('can_edit_production_run', 'Can edit production runs'), ('can_complete_production_run', 'Can complete production runs'), ('can_view_production_log', 'Can view production logs'), ('can_edit_production_log', 'Can create/edit production logs'), ('can_view_breakdown', 'Can view breakdowns'), ('can_create_breakdown', 'Can create breakdowns'), ('can_edit_breakdown', 'Can edit breakdowns'), ('can_view_material_usage', 'Can view material usage'), ('can_create_material_usage', 'Can create material usage'), ('can_edit_material_usage', 'Can edit material usage'), ('can_view_machine_runtime', 'Can view machine runtime'), ('can_create_machine_runtime', 'Can create machine runtime'), ('can_view_manpower', 'Can view manpower'), ('can_create_manpower', 'Can create manpower'), ('can_view_line_clearance', 'Can view line clearance'), ('can_create_line_clearance', 'Can create line clearance'), ('can_approve_line_clearance_qa', 'Can QA-approve line clearance'), ('can_manage_line_clearance', 'Can manage/override line clearance decisions'), ('can_view_machine_checklist', 'Can view machine checklists'), ('can_create_machine_checklist', 'Can create machine checklist entries'), ('can_view_waste_log', 'Can view waste logs'), ('can_create_waste_log', 'Can create waste logs'), ('can_approve_waste_engineer', 'Can engineer-approve waste'), ('can_approve_waste_am', 'Can AM-approve waste'), ('can_approve_waste_store', 'Can store-approve waste'), ('can_approve_waste_hod', 'Can HOD-approve waste'), ('can_view_reports', 'Can view production reports'), ('can_view_run_cost', 'Can view run cost / costing')], 'verbose_name': 'Production Run', 'verbose_name_plural': 'Production Runs'},
        ),
    ]
