# Generated by Django 6.0.1 on 2026-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0034_alter_productionrun_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinebreakdown',
            name='is_manual',
            field=models.BooleanField(default=False, help_text="True if backfilled via 'Add Past Breakdown' (manual entry), not from a live breakdown."),
        ),
        migrations.AddField(
            model_name='productionsegment',
            name='is_manual',
            field=models.BooleanField(default=False, help_text="True if backfilled via 'Add Running' (manual entry), not from live Start/Stop."),
        ),
    ]
