# Generated by Django 6.0.1 on 2026-08-04 07:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_company_from_run(apps, schema_editor):
    WasteLog = apps.get_model('production_execution', 'WasteLog')
    ProductionRun = apps.get_model('production_execution', 'ProductionRun')
    for run_id, company_id in ProductionRun.objects.filter(
        waste_logs__isnull=False
    ).values_list('id', 'company_id').distinct():
        WasteLog.objects.filter(production_run_id=run_id).update(company_id=company_id)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0035_machinebreakdown_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_logs', to='company.company'),
        ),
        migrations.AlterField(
            model_name='wastelog',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='production_execution.productionrun'),
        ),
        migrations.RunPython(backfill_company_from_run, migrations.RunPython.noop),
    ]
