# Generated by Django 6.0.1 on 2026-08-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0036_wastelog_company_alter_wastelog_production_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineskuconfig',
            name='pieces_per_case',
            field=models.PositiveIntegerField(blank=True, help_text='Bottles per case for this SKU (SAP OITM.SalFactor2). Null means not yet resolved — the per-bottle backfill uses this as its already-converted marker.', null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='pieces_per_case',
            field=models.PositiveIntegerField(blank=True, help_text="Bottles per case for the run's SKU (SAP OITM.SalFactor2), snapshot at creation. Converts case counts (production is entered in cases) to bottles for speed/OEE math.", null=True),
        ),
        migrations.AlterField(
            model_name='lineskuconfig',
            name='rated_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rated speed in bottles/hr', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='rated_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rated speed (bottles/hr)', max_digits=10, null=True),
        ),
    ]
