# Generated by Django 6.0.1 on 2026-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0037_rated_speed_per_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='litres_per_piece',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Litres in one bottle/piece of the run's SKU (SAP OITM.SalPackUn), snapshot at creation. Litres produced = cases x pieces_per_case x this. Null means the SKU holds no liquid (or was never resolved), so its litres read as '—' rather than zero.", max_digits=12, null=True),
        ),
    ]
