# Generated by Django 6.0.1 on 2026-09-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0039_production_run_planning_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrun',
            name='warehouse_approval_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUESTED', help_text='Warehouse BOM approval status. NOT_REQUIRED means the run was submitted and nothing needed approving — raw material comes from the Raw Material register and any packing material was already staged at BH-PC. It starts like an approved run; NOT_REQUESTED, which blocks, means nobody has submitted anything yet.', max_length=25),
        ),
    ]
