# Generated by Django 6.0.1 on 2026-09-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0041_production_run_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='line_config',
            field=models.ForeignKey(blank=True, help_text='The line configuration this run was planned from. The speed, manpower and names on the run are a snapshot taken from it, so they stay as planned if the preset is later edited — this only records which one was chosen, so reopening the plan shows the same answer. Null on runs planned without a preset, and on runs planned before this was recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='production_execution.lineskuconfig'),
        ),
    ]
