# Generated by Django 6.0.1 on 2026-09-23 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0043_line_config_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelog',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_waste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='rejected_sign',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wastelog',
            name='wastage_approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('FULLY_APPROVED', 'Fully Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
