# Generated by Django 6.0.1 on 2026-09-23 10:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0044_waste_log_rejection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionrun',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-date', 'line', 'run_number'], 'permissions': [('can_manage_production_lines', 'Can manage production lines'), ('can_manage_machines', 'Can manage machines'), ('can_manage_checklist_templates', 'Can manage checklist templates'), ('can_view_production_run', 'Can view production runs'), ('can_create_production_run', 'Can create production runs'), ('can_edit_production_run', 'Can edit production runs'), ('can_complete_production_run', 'Can complete production runs'), ('can_view_production_log', 'Can view production logs'), ('can_edit_production_log', 'Can create/edit production logs'), ('can_view_breakdown', 'Can view breakdowns'), ('can_create_breakdown', 'Can create breakdowns'), ('can_edit_breakdown', 'Can edit breakdowns'), ('can_view_material_usage', 'Can view material usage'), ('can_create_material_usage', 'Can create material usage'), ('can_edit_material_usage', 'Can edit material usage'), ('can_view_machine_runtime', 'Can view machine runtime'), ('can_create_machine_runtime', 'Can create machine runtime'), ('can_view_manpower', 'Can view manpower'), ('can_create_manpower', 'Can create manpower'), ('can_view_line_clearance', 'Can view line clearance'), ('can_create_line_clearance', 'Can create line clearance'), ('can_approve_line_clearance_qa', 'Can QA-approve line clearance'), ('can_manage_line_clearance', 'Can manage/override line clearance decisions'), ('can_view_machine_checklist', 'Can view machine checklists'), ('can_create_machine_checklist', 'Can create machine checklist entries'), ('can_view_waste_log', 'Can view waste logs'), ('can_create_waste_log', 'Can create waste logs'), ('can_approve_waste_engineer', 'Can engineer-approve waste'), ('can_approve_waste_am', 'Can AM-approve waste'), ('can_approve_waste_store', 'Can store-approve waste'), ('can_approve_waste_hod', 'Can HOD-approve waste'), ('can_view_reports', 'Can view production reports'), ('can_view_run_cost', 'Can view run cost / costing'), ('can_view_filling_cost', 'Can view the filling cost sheet'), ('can_manage_filling_cost', 'Can enter/edit the filling cost sheet'), ('can_view_line_config', 'Can view line configuration (read-only)'), ('can_manage_line_config', 'Can edit line configuration')], 'verbose_name': 'Production Run', 'verbose_name_plural': 'Production Runs'},
        ),
        migrations.CreateModel(
            name='FillingCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month the sheet covers.')),
                ('cases', models.DecimalField(decimal_places=2, default=Decimal('160000'), help_text="Cases the month's cost is spread over — the sheet's 'Per N Cases' heading, and the divisor behind every per-case figure on it.", max_digits=15)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filling_cost_sheets', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filling_cost_sheets_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, help_text='Blank = the filling floor as a whole; set = that line only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filling_cost_sheets', to='production_execution.productionline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filling_cost_sheets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filling Cost Sheet',
                'verbose_name_plural': 'Filling Cost Sheets',
                'ordering': ['-period', 'line'],
            },
        ),
        migrations.CreateModel(
            name='FillingCostSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(help_text="The head as the sheet names it, e.g. 'Ground Water Extraction Bill'. Free text: the heads are the factory's, not a fixed list, and nothing resolves against them.", max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="The month's amount for this head.", max_digits=15)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Row order on the sheet.')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production_execution.fillingcostsheet')),
            ],
            options={
                'verbose_name': 'Filling Cost Entry',
                'verbose_name_plural': 'Filling Cost Entries',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fillingcostsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('line__isnull', True)), fields=('company', 'period'), name='uniq_filling_cost_sheet_per_month'),
        ),
        migrations.AddConstraint(
            model_name='fillingcostsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('line__isnull', False)), fields=('company', 'line', 'period'), name='uniq_filling_cost_sheet_per_line_month'),
        ),
        migrations.AlterUniqueTogether(
            name='fillingcostsheetentry',
            unique_together={('sheet', 'head')},
        ),
    ]
