# Generated by Django 6.0.1 on 2026-09-26 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0045_filling_cost_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_warehouse', models.CharField(help_text='SAP warehouse raw material is drawn from for production.', max_length=20)),
                ('pm_warehouse', models.CharField(help_text='SAP warehouse packing material is drawn from for production.', max_length=20)),
                ('fg_warehouse', models.CharField(help_text='SAP warehouse finished goods are received into.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_settings', to='company.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Settings',
                'verbose_name_plural': 'Production Settings',
                'permissions': [('can_manage_production_settings', 'Can change production settings')],
                'default_permissions': (),
            },
        ),
    ]
