# Generated by Django 6.0.1 on 2026-09-26 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0046_production_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapProductionOrderAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('RELEASE', 'Released'), ('CLOSE', 'Closed'), ('ISSUE', 'Issued for production'), ('RECEIPT', 'Received from production')], max_length=10)),
                ('order_doc_entry', models.PositiveIntegerField(blank=True, help_text='OWOR.DocEntry of the production order.', null=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('sap_doc_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('sap_doc_num', models.PositiveIntegerField(blank=True, null=True)),
                ('pending_approval_draft', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_production_order_actions', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_sap_production_orders', 'Can view SAP production orders'), ('can_create_sap_production_orders', 'Can create SAP production orders'), ('can_release_close_sap_production_orders', 'Can release and close SAP production orders'), ('can_issue_for_sap_production_orders', 'Can issue materials to SAP production orders'), ('can_receive_from_sap_production_orders', 'Can receive finished goods from SAP production orders')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'order_doc_entry'], name='production__company_418c7b_idx')],
            },
        ),
    ]
