# Generated by Django 6.0.1 on 2026-09-29 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0048_sapproductionorderaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillingcostsheet',
            options={'ordering': ['-date', 'line', 'shift'], 'verbose_name': 'Filling Cost Sheet', 'verbose_name_plural': 'Filling Cost Sheets'},
        ),
        migrations.RemoveConstraint(
            model_name='fillingcostsheet',
            name='uniq_filling_cost_sheet_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='fillingcostsheet',
            name='uniq_filling_cost_sheet_per_line_day',
        ),
        migrations.AddField(
            model_name='fillingcostsheet',
            name='shift',
            field=models.CharField(blank=True, choices=[('DAY', 'Day (07:00-19:00)'), ('NIGHT', 'Night (19:00-07:00)')], default='', help_text='Blank = the whole day; set = that shift only.', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='fillingcostsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('line__isnull', True)), fields=('company', 'date', 'shift'), name='uniq_filling_cost_sheet_per_shift'),
        ),
        migrations.AddConstraint(
            model_name='fillingcostsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('line__isnull', False)), fields=('company', 'line', 'date', 'shift'), name='uniq_filling_cost_sheet_per_line_shift'),
        ),
    ]
