# Generated by Django 6.0.1 on 2026-10-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0049_filling_cost_sheet_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinebreakdown',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='BreakdownSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='production_execution.breakdowncategory')),
            ],
            options={
                'verbose_name': 'Breakdown Sub-category',
                'verbose_name_plural': 'Breakdown Sub-categories',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='machinebreakdown',
            name='breakdown_subcategory',
            field=models.ForeignKey(blank=True, help_text='The specific fault under breakdown_category, where it has any', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='breakdowns', to='production_execution.breakdownsubcategory'),
        ),
    ]
