# Generated by Django 6.0.1 on 2026-03-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0009_update_grpo_group_attachments'),
        ('raw_material_gatein', '0010_add_po_detail_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grpoposting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grpoposting',
            name='po_receipts',
            field=models.ManyToManyField(blank=True, help_text='All PO receipts included in this GRPO (same supplier).', related_name='merged_grpo_postings', to='raw_material_gatein.poreceipt'),
        ),
        migrations.AlterField(
            model_name='grpoposting',
            name='po_receipt',
            field=models.ForeignKey(blank=True, help_text='Legacy single PO link. Use po_receipts M2M for merged GRPOs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grpo_postings', to='raw_material_gatein.poreceipt'),
        ),
    ]
