# Generated by Django 6.0.1 on 2026-03-27 09:02

from django.db import migrations


def populate_m2m(apps, schema_editor):
    """Copy existing po_receipt FK into po_receipts M2M for all GRPOPosting records."""
    GRPOPosting = apps.get_model('grpo', 'GRPOPosting')
    for posting in GRPOPosting.objects.filter(po_receipt__isnull=False):
        posting.po_receipts.add(posting.po_receipt)


def reverse_m2m(apps, schema_editor):
    """No-op reverse — M2M data can be safely dropped."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0010_alter_grpoposting_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_m2m, reverse_m2m),
    ]
