# Generated by Django 6.0.1 on 2026-07-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0001_initial'),
        ('grpo', '0015_service_grpo_line_dispatch_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpoattachment',
            name='document_code',
            field=models.OneToOneField(blank=True, help_text='Controlled-document code assigned to this file.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='document_control.documentcode'),
        ),
        migrations.AddField(
            model_name='servicegrpoattachment',
            name='document_code',
            field=models.OneToOneField(blank=True, help_text='Controlled-document code assigned to this file.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='document_control.documentcode'),
        ),
    ]
