# Generated by Django 6.0.1 on 2026-07-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0016_grpoattachment_document_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpoposting',
            name='request_payload',
            field=models.JSONField(blank=True, help_text='Saved GRPO posting request (for draft save / retry).', null=True),
        ),
        migrations.AlterField(
            model_name='grpoposting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed'), ('PARTIALLY_POSTED', 'Partially Posted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicegrpoposting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed'), ('PARTIALLY_POSTED', 'Partially Posted')], default='PENDING', max_length=20),
        ),
    ]
