# Generated by Django 6.0.1 on 2026-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0017_grpo_draft_save_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpolineposting',
            name='batches',
            field=models.JSONField(blank=True, default=list, help_text='Batch allocations posted on this line (SAP BatchNumbers)'),
        ),
    ]
