# Generated by Django 6.0.1 on 2026-09-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0018_grpolineposting_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grpoposting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed'), ('PARTIALLY_POSTED', 'Partially Posted'), ('QUEUED', 'Waiting for SAP')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicegrpoposting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed'), ('PARTIALLY_POSTED', 'Partially Posted'), ('QUEUED', 'Waiting for SAP')], default='PENDING', max_length=20),
        ),
    ]
