# Generated by Django 6.0.1 on 2026-10-03 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('grpo', '0019_status_queued'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POPrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_source', models.CharField(choices=[('SAP', 'From SAP'), ('MANUAL', 'Entered here')], default='SAP', max_length=10)),
                ('approver_name', models.CharField(blank=True, default='', help_text="Printed as the approver when the source is 'Entered here'.", max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='po_print_settings', to='company.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_print_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO Print Settings',
                'verbose_name_plural': 'PO Print Settings',
                'permissions': [('can_manage_po_print_settings', 'Can change the PO print settings')],
                'default_permissions': (),
            },
        ),
    ]
