# Generated by Django 6.0.1 on 2026-07-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Activity Center',
                'verbose_name_plural': 'Activity Center',
                'permissions': [('can_view_my_activities', 'Can view own pending and completed activities'), ('can_view_all_activities', "Can view every user's activities (supervisor)"), ('can_view_activity_reports', 'Can view activity completion reports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
