# Generated by Django 6.0.1 on 2026-10-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('company_code', models.CharField(blank=True, max_length=32)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_string', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, max_length=300)),
                ('view', models.CharField(blank=True, max_length=255)),
                ('app_label', models.CharField(blank=True, max_length=60)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('response_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True)),
                ('response_body', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='api_call_time_idx'), models.Index(fields=['user', '-started_at'], name='api_call_user_idx'), models.Index(fields=['app_label', '-started_at'], name='api_call_app_idx')],
            },
        ),
    ]
