# Generated by Django 6.0.1 on 2026-03-06 09:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_planning', '0003_redesign_production_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductionentry',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planmaterialrequirement',
            name='required_qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='due_date',
            field=models.DateField(help_text='Required completion date'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='planned_qty',
            field=models.DecimalField(decimal_places=3, help_text='Total planned production quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='sap_doc_entry',
            field=models.IntegerField(blank=True, help_text='SAP OWOR DocEntry', null=True),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='sap_doc_num',
            field=models.IntegerField(blank=True, help_text='SAP OWOR DocNum', null=True),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='sap_status',
            field=models.CharField(blank=True, help_text='SAP order status after posting: P=Planned, R=Released', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='target_start_date',
            field=models.DateField(help_text='Planned production start date'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='uom',
            field=models.CharField(blank=True, default='', help_text='Unit of measure', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', help_text='Production warehouse code', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='produced_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='week_number',
            field=models.PositiveSmallIntegerField(help_text='Week number: 1, 2, 3, 4 ...'),
        ),
    ]
