# Generated by Django 6.0.1 on 2026-09-28 10:56

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('source_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('params', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('SENDING', 'Sending to SAP'), ('QUEUED', 'Waiting for SAP'), ('POSTED', 'Posted to SAP'), ('REJECTED', 'Refused by SAP'), ('CANCELLED', 'Cancelled')], db_index=True, default='SENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_postings_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_postings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_postings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SapPostingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('by_worker', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('POSTED', 'Posted'), ('WAITING', 'SAP not answering'), ('REJECTED', 'Refused')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_log', to='sap_postings.sapposting')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddIndex(
            model_name='sapposting',
            index=models.Index(fields=['status', 'next_attempt_at'], name='sap_posting_status_4d7900_idx'),
        ),
        migrations.AddIndex(
            model_name='sapposting',
            index=models.Index(fields=['kind', 'source_id'], name='sap_posting_kind_26bc97_idx'),
        ),
        migrations.AddConstraint(
            model_name='sapposting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SENDING', 'QUEUED'])), fields=('kind', 'source_id'), name='one_live_sap_posting_per_record'),
        ),
        migrations.AddConstraint(
            model_name='sappostingattempt',
            constraint=models.UniqueConstraint(fields=('posting', 'number'), name='one_attempt_number_per_posting'),
        ),
    ]
