# Generated by Django 6.0.1 on 2026-09-28 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('sap_postings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sapposting',
            index=models.Index(fields=['company', 'status', '-created_at'], name='sap_posting_tab_idx'),
        ),
        migrations.AddIndex(
            model_name='sapposting',
            index=models.Index(fields=['company', '-created_at'], name='sap_posting_all_idx'),
        ),
    ]
