from django.urls import path

from .views import (
    AlarmPreviewAPI,
    DailyRunDetailAPI,
    DailyRunGenerateAPI,
    DailyRunListAPI,
    DailyRunPublishAPI,
    DailyRunReviewAPI,
    DailyRunRowOwnerAPI,
    DailyRunVerdictAPI,
    MonitoredSkuListAPI,
    OperatingParametersAPI,
    WeeklyReviewAPI,
    AlarmSendAPI,
    CapacityCheckAPI,
    FloorAuditAPI,
    FloorConventionAPI,
    LeadTimeListAPI,
    LiveTrailAPI,
    MachineCapacityListAPI,
    MaterialMachineMapListAPI,
    ProcurementAlarmsAPI,
    ReferenceImportHistoryAPI,
    ReferenceTemplateUploadAPI,
    SupplyChainDashboardAPI,
    SupplyChainPolicyAPI,
)

app_name = "supply_chain"

urlpatterns = [
    path("dashboard/", SupplyChainDashboardAPI.as_view(), name="sc-dashboard"),
    path("live-trail/", LiveTrailAPI.as_view(), name="sc-live-trail"),
    path("procurement/", ProcurementAlarmsAPI.as_view(), name="sc-procurement"),
    path("capacity/", CapacityCheckAPI.as_view(), name="sc-capacity"),
    path("policy/", SupplyChainPolicyAPI.as_view(), name="sc-policy"),
    path("floors/", FloorAuditAPI.as_view(), name="sc-floors"),
    path("floor-convention/", FloorConventionAPI.as_view(), name="sc-floor-convention"),
    path("alarms/preview/", AlarmPreviewAPI.as_view(), name="sc-alarm-preview"),
    path("alarms/send/", AlarmSendAPI.as_view(), name="sc-alarm-send"),
    # ── The daily operating loop ──
    path("runs/", DailyRunListAPI.as_view(), name="sc-runs"),
    path("runs/generate/", DailyRunGenerateAPI.as_view(), name="sc-run-generate"),
    path("runs/latest/", DailyRunDetailAPI.as_view(), name="sc-run-latest"),
    path("runs/<int:run_id>/", DailyRunDetailAPI.as_view(), name="sc-run-detail"),
    path("runs/<int:run_id>/review/", DailyRunReviewAPI.as_view(), name="sc-run-review"),
    path("runs/<int:run_id>/publish/", DailyRunPublishAPI.as_view(), name="sc-run-publish"),
    path("rows/<int:row_id>/owner/", DailyRunRowOwnerAPI.as_view(), name="sc-row-owner"),
    path("rows/<int:row_id>/verdict/", DailyRunVerdictAPI.as_view(), name="sc-row-verdict"),
    path("weekly/", WeeklyReviewAPI.as_view(), name="sc-weekly"),
    path("monitored-skus/", MonitoredSkuListAPI.as_view(), name="sc-monitored-skus"),
    path("parameters/", OperatingParametersAPI.as_view(), name="sc-parameters"),
    path("reference/lead-times/", LeadTimeListAPI.as_view(), name="sc-lead-times"),
    path("reference/machines/", MachineCapacityListAPI.as_view(), name="sc-machines"),
    path("reference/sku-machines/", MaterialMachineMapListAPI.as_view(), name="sc-sku-machines"),
    path("reference/upload/", ReferenceTemplateUploadAPI.as_view(), name="sc-reference-upload"),
    path("reference/imports/", ReferenceImportHistoryAPI.as_view(), name="sc-reference-imports"),
]
