# Generated by Django 6.0.1 on 2026-09-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalSearchPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_use_universal_search', 'Can use universal search')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
