# Generated by Django 6.0.1 on 2026-06-29 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Settings',
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, help_text="Client-generated record id (UUID, or 'wms-settings').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text='The full camelCase record document as authored by the frontend.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('company', 'record_id')},
            },
        ),
    ]
