# Generated by Django 6.0.1 on 2026-06-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'ⓘ Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wms.movement',),
        ),
    ]
