# Generated by Django 6.0.1 on 2026-07-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_fold_zones_into_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellpurpose',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='cellpurpose',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='movement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='template',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted (null while live).', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. A deleted record is excluded from every read (list + detail) but the row is retained so it can be recovered.'),
        ),
    ]
