# Generated by Django 6.0.1 on 2026-07-04 11:43

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('person_gatein', '0007_entrylog_actual_entry_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='entrylog',
            index=models.Index(fields=['status', 'entry_time'], name='entrylog_status_time_idx'),
        ),
        AddIndexConcurrently(
            model_name='entrylog',
            index=models.Index(fields=['labour', 'status'], name='entrylog_labour_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='entrylog',
            index=models.Index(fields=['visitor', 'status'], name='entrylog_visitor_status_idx'),
        ),
    ]
