# Generated by Django 6.0.1 on 2026-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0018_add_send_back_perm_to_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinspection',
            name='internal_lot_no',
            field=models.CharField(max_length=50),
        ),
    ]
