# Generated by Django 6.0.1 on 2026-03-19 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0012_productionrun_rejected_qty_and_more'),
        ('quality_control', '0019_alter_rawmaterialinspection_internal_lot_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionQCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_number', models.PositiveSmallIntegerField(help_text='Auto-incremented round number per run (Round 1, 2, 3...)')),
                ('session_type', models.CharField(choices=[('IN_PROCESS', 'In-Process'), ('FINAL', 'Final')], default='IN_PROCESS', max_length=15)),
                ('checked_at', models.DateTimeField(help_text='When this QC round was performed')),
                ('overall_result', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='', help_text='Auto-calculated from individual parameter results', max_length=10)),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_sessions_approved', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_sessions_checked', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(help_text='Product/material type defining which QC parameters to check', on_delete=django.db.models.deletion.PROTECT, related_name='production_qc_sessions', to='quality_control.materialtype')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_sessions', to='production_execution.productionrun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_number'],
                'permissions': [('can_view_production_qc', 'Can view production QC'), ('can_create_production_qc', 'Can create production QC session'), ('can_submit_production_qc', 'Can submit production QC for approval'), ('can_approve_production_qc', 'Can approve production QC session'), ('can_reject_production_qc', 'Can reject production QC session')],
                'unique_together': {('production_run', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductionQCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter_name', models.CharField(max_length=200)),
                ('standard_value', models.CharField(max_length=200)),
                ('result_value', models.CharField(blank=True, max_length=200)),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_within_spec', models.BooleanField(null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parameter_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_results', to='quality_control.qcparametermaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality_control.productionqcsession')),
            ],
            options={
                'ordering': ['parameter_master__sequence'],
                'unique_together': {('session', 'parameter_master')},
            },
        ),
    ]
