# Generated by Django 6.0.1 on 2026-03-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0020_productionqcsession_productionqcresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionqcsession',
            options={'ordering': ['session_number'], 'permissions': [('can_view_production_qc', 'Can view production QC'), ('can_create_production_qc', 'Can create production QC session'), ('can_submit_production_qc', 'Can submit production QC session')]},
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='approval_remarks',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_sessions_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionqcsession',
            name='overall_result',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='', help_text='Set by QC person on submission', max_length=10),
        ),
        migrations.AlterField(
            model_name='productionqcsession',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=15),
        ),
    ]
