# Generated by Django 6.0.1 on 2026-06-11 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0025_add_line_clearance_qc_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTypeSAPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_material_type_sap_items', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_items', to='quality_control.materialtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_code'],
                'indexes': [models.Index(fields=['company', 'item_code'], name='quality_con_company_8956cb_idx'), models.Index(fields=['material_type', 'is_active'], name='quality_con_materia_da95dd_idx')],
                'unique_together': {('company', 'item_code')},
            },
        ),
    ]
