# Generated by Django 6.0.1 on 2026-07-04 11:43

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('production_execution', '0024_lineclearance_lineclr_co_date_idx_and_more'),
        ('quality_control', '0029_raw_material_inspection_decisions'),
        ('raw_material_gatein', '0014_poreplacementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='materialarrivalslip',
            index=models.Index(fields=['status', 'submitted_at'], name='matslip_status_subat_idx'),
        ),
        AddIndexConcurrently(
            model_name='productionqcsession',
            index=models.Index(fields=['workflow_status', 'session_type'], name='prodqc_wfstatus_type_idx'),
        ),
    ]
