# Generated by Django 6.0.1 on 2026-07-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0030_inspectionmanagerdecisionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterialinspection',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_inspection', 'Can submit inspection for approval'), ('can_approve_as_chemist', 'Can approve inspection as QA Chemist'), ('can_approve_as_qam', 'Can approve inspection as QA Manager'), ('can_reject_inspection', 'Can reject inspection')]},
        ),
        migrations.RemoveIndex(
            model_name='rawmaterialinspection',
            name='quality_con_factory_bdd01f_idx',
        ),
        migrations.RemoveField(
            model_name='rawmaterialinspection',
            name='factory_head',
        ),
        migrations.RemoveField(
            model_name='rawmaterialinspection',
            name='factory_head_decided_at',
        ),
        migrations.RemoveField(
            model_name='rawmaterialinspection',
            name='factory_head_decision',
        ),
        migrations.RemoveField(
            model_name='rawmaterialinspection',
            name='factory_head_remarks',
        ),
    ]
