# Generated by Django 6.0.1 on 2026-07-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0031_alter_rawmaterialinspection_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialtypesapitem',
            unique_together={('company', 'item_code', 'material_type')},
        ),
    ]
