# Generated by Django 6.0.1 on 2026-07-24 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0028_productionrun_item_code'),
        ('quality_control', '0033_arrivalslipattachment_document_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('sku', models.CharField(blank=True, default='', help_text='SAP item code / SKU', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('flavour', models.CharField(blank=True, default='', max_length=120)),
                ('shift', models.CharField(blank=True, choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], default='', max_length=2)),
                ('batch_no', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, default='')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_quality_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_quality_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_quality_records', to='production_execution.productionline')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_quality_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_quality_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'permissions': [('can_view_online_monitoring', 'Can view online quality monitoring'), ('can_create_online_monitoring', 'Can create/edit draft online monitoring'), ('can_submit_online_monitoring', 'Can submit online monitoring'), ('can_approve_online_monitoring', 'Can approve/reject online monitoring')],
            },
        ),
        migrations.CreateModel(
            name='OnlineQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reading_time', models.TimeField()),
                ('filler_speed', models.DecimalField(blank=True, decimal_places=2, help_text='BPH', max_digits=10, null=True)),
                ('taste', models.CharField(blank=True, choices=[('ACCEPTABLE', 'Acceptable'), ('NOT_ACCEPTABLE', 'Not Acceptable')], default='', max_length=15)),
                ('aroma', models.CharField(blank=True, choices=[('ACCEPTABLE', 'Acceptable'), ('NOT_ACCEPTABLE', 'Not Acceptable')], default='', max_length=15)),
                ('appearance', models.CharField(blank=True, choices=[('ACCEPTABLE', 'Acceptable'), ('NOT_ACCEPTABLE', 'Not Acceptable')], default='', max_length=15)),
                ('ph', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('turbidity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('alkalinity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_hardness', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('magnesium', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('chloride', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('package_attribute', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='', max_length=8)),
                ('date_code', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='', max_length=8)),
                ('rub_test', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='', max_length=6)),
                ('closure_jump_test', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='', max_length=6)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='quality_control.onlinequalityrecord')),
            ],
            options={
                'ordering': ['reading_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineQualitySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter_key', models.CharField(help_text="Stable key matching a reading field, e.g. 'ph', 'tds', 'torque'.", max_length=40)),
                ('parameter_name', models.CharField(max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('specification_text', models.CharField(blank=True, default='', help_text="Human spec as printed, e.g. '6.5-8.5' or '10 ± 2'.", max_length=60)),
                ('validation_type', models.CharField(choices=[('RANGE', 'Range (min–max)'), ('MIN', 'Minimum only'), ('MAX', 'Maximum only'), ('NONE', 'No numeric check')], default='RANGE', max_length=10)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, help_text='Null = applies to all companies (global default).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_quality_specs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'parameter_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'parameter_key'), name='uq_online_spec_company_key')],
            },
        ),
        migrations.CreateModel(
            name='OnlineQualityTorque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head_no', models.PositiveSmallIntegerField()),
                ('torque_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torque_heads', to='quality_control.onlinequalityreading')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['head_no'],
                'constraints': [models.UniqueConstraint(fields=('reading', 'head_no'), name='uq_online_torque_reading_head')],
            },
        ),
    ]
