# Generated by Django 6.0.1 on 2026-08-12 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0036_onlinequalityreadingattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionparameterresult',
            options={'ordering': ['sequence', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productionqcresult',
            options={'ordering': ['sequence', 'id']},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialinspection',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_inspection', 'Can submit inspection for approval'), ('can_approve_as_chemist', 'Can approve inspection as QA Chemist'), ('can_approve_as_qam', 'Can approve inspection as QA Manager'), ('can_reject_inspection', 'Can reject inspection'), ('can_override_qc_vendor', "Can inspect against a vendor other than the PO's")]},
        ),
        migrations.AddField(
            model_name='inspectionparameterresult',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspectionparameterresult',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inspectionparameterresult',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inspectionparameterresult',
            name='parameter_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectionparameterresult',
            name='parameter_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text/Descriptive'), ('BOOLEAN', 'Pass/Fail'), ('RANGE', 'Numeric Range')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionparameterresult',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionparameterresult',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productionqcresult',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productionqcresult',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionqcresult',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionqcresult',
            name='parameter_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productionqcresult',
            name='parameter_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text/Descriptive'), ('BOOLEAN', 'Pass/Fail'), ('RANGE', 'Numeric Range')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='productionqcresult',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionqcresult',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rawmaterialinspection',
            name='vendor_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rawmaterialinspection',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='rawmaterialinspection',
            name='vendor_override_reason',
            field=models.TextField(blank=True, default='', help_text='Why the QC vendor differs from the one on the PO'),
        ),
        migrations.AlterField(
            model_name='qcparametermaster',
            name='material_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_parameters', to='quality_control.materialtype'),
        ),
        migrations.CreateModel(
            name='QCParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=30)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to='quality_control.materialtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendor_code', 'vendor_name'],
            },
        ),
        migrations.AddField(
            model_name='qcparametermaster',
            name='parameter_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality_control.qcparameterset'),
        ),
        migrations.AddField(
            model_name='rawmaterialinspection',
            name='parameter_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='quality_control.qcparameterset'),
        ),
        migrations.AddIndex(
            model_name='qcparameterset',
            index=models.Index(fields=['material_type', 'vendor_code', 'is_active'], name='quality_con_materia_9804cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qcparameterset',
            unique_together={('material_type', 'vendor_code')},
        ),
    ]
