# Generated by Django 6.0.1 on 2026-08-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0038_backfill_default_parameter_sets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qcparametermaster',
            unique_together={('parameter_set', 'parameter_code')},
        ),
        migrations.AlterField(
            model_name='qcparametermaster',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality_control.qcparameterset'),
        ),
        migrations.RemoveField(
            model_name='qcparametermaster',
            name='material_type',
        ),
    ]
