# Generated by Django 6.0.1 on 2026-08-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0039_qc_parameters_by_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcprintdocument',
            name='document_key',
            field=models.CharField(choices=[('RAW_MATERIAL_INSPECTION', 'Raw Material Inspection Print'), ('QC_PARAMETERS', 'QC Parameters Print')], max_length=60),
        ),
    ]
