# Generated by Django 6.0.1 on 2026-08-31 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0040_alter_qcprintdocument_document_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_code', models.CharField(help_text="Controlled document code as printed, e.g. 'QA-TST-INH-14-02-10'.", max_length=64)),
                ('title', models.CharField(help_text="Procedure title, e.g. 'ARGEMONE OIL ADULTERATION TESTING'.", max_length=255)),
                ('procedure_type', models.CharField(choices=[('INHOUSE', 'In-house Testing Procedure'), ('STANDARD', 'Standard Testing Procedure')], default='INHOUSE', max_length=12)),
                ('heading', models.CharField(blank=True, default='', help_text="Banner line above the title, e.g. 'INHOUSE TESTING PROCEDURE'.", max_length=255)),
                ('organisation', models.CharField(blank=True, default='', help_text="Issuing entity as printed, e.g. 'JIVO WELLNESS PVT.LTD.'.", max_length=255)),
                ('revision_number', models.CharField(blank=True, default='', help_text="Revision as printed, e.g. '00'.", max_length=8)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('total_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, default='', help_text="e.g. 'Business Confidential'.", max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('source_text', models.TextField(blank=True, default='', help_text='The raw pasted text this record was parsed from. Kept so a mis-parse can be re-analysed without re-typing the document.')),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_procedures', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_code', 'title'],
                'permissions': [('can_view_testing_procedures', 'Can view testing procedures'), ('can_manage_testing_procedures', 'Can create/edit testing procedures')],
            },
        ),
        migrations.CreateModel(
            name='TestingProcedureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='Display order within the procedure.')),
                ('section_number', models.CharField(blank=True, default='', help_text="Number as printed, e.g. '7'.", max_length=8)),
                ('section_key', models.CharField(choices=[('SCOPE', 'Scope'), ('PRINCIPLE', 'Principle'), ('RESPONSIBILITY', 'Responsibility'), ('APPARATUS', 'Apparatus / Glassware'), ('REAGENT', 'Reagent'), ('SAMPLE_REQUIREMENT', 'Sample Requirement'), ('PROCEDURE', 'Procedure'), ('OBSERVATION', 'Observation and Interpretation'), ('ACCEPTANCE_CRITERIA', 'Acceptance Criteria'), ('PRECAUTIONS', 'Precautions'), ('SAFETY', 'Safety'), ('CALCULATION', 'Calculation'), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('title', models.CharField(help_text="Heading as printed, e.g. 'Apparatus / Glassware'.", max_length=255)),
                ('body', models.TextField(blank=True, default='', help_text='Prose belonging to the section itself (around its lines).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quality_control.testingprocedure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestingProcedureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('BULLET', 'Bullet'), ('STEP', 'Numbered step'), ('TABLE_ROW', 'Table row'), ('PARAGRAPH', 'Paragraph')], default='BULLET', max_length=12)),
                ('marker', models.CharField(blank=True, default='', help_text="Step number or bullet as printed, e.g. '3'.", max_length=8)),
                ('text', models.TextField(help_text='The line, or the first column of a table row.')),
                ('interpretation', models.TextField(blank=True, default='', help_text='Second column of a table row, e.g. the interpretation of an observation. Blank for bullets and steps.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quality_control.testingproceduresection')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='testingprocedure',
            index=models.Index(fields=['company', 'procedure_type'], name='quality_con_company_30964b_idx'),
        ),
        migrations.AddIndex(
            model_name='testingprocedure',
            index=models.Index(fields=['company', 'status'], name='quality_con_company_7f4b94_idx'),
        ),
        migrations.AddConstraint(
            model_name='testingprocedure',
            constraint=models.UniqueConstraint(fields=('company', 'document_code'), name='uq_testing_procedure_company_code'),
        ),
        migrations.AddIndex(
            model_name='testingproceduresection',
            index=models.Index(fields=['procedure', 'sequence'], name='quality_con_procedu_aaf358_idx'),
        ),
        migrations.AddIndex(
            model_name='testingprocedureline',
            index=models.Index(fields=['section', 'sequence'], name='quality_con_section_a107cc_idx'),
        ),
    ]
