# Generated by Django 6.0.1 on 2026-09-01 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0042_grant_testing_procedure_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_code', models.CharField(help_text="Controlled document code as printed, e.g. 'QA-FRM-14-00-05-05'.", max_length=64)),
                ('title', models.CharField(help_text="e.g. 'NMW DAILY WATER MONITORING RECORD'.", max_length=255)),
                ('organisation', models.CharField(blank=True, default='', max_length=255)),
                ('revision_number', models.CharField(blank=True, default='', max_length=8)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_templates', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_date', models.DateField()),
                ('shift', models.CharField(blank=True, default='', max_length=8)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_records_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_records_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='quality_control.recordtemplate')),
            ],
            options={
                'ordering': ['-record_date', '-id'],
                'permissions': [('can_view_qc_records', 'Can view QC record forms and filled records'), ('can_fill_qc_records', 'Can open and fill QC records'), ('can_approve_qc_records', 'Can approve QC records and maintain record forms')],
            },
        ),
        migrations.CreateModel(
            name='RecordTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quality_control.recordtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecordTemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('sr_no', models.CharField(blank=True, default='', help_text='Sr.No as printed.', max_length=8)),
                ('name', models.CharField(help_text="e.g. 'pH', 'Turbidity'.", max_length=120)),
                ('frequency', models.CharField(blank=True, default='', help_text="As printed, e.g. 'Every Startup / Every 2 Hours'.", max_length=160)),
                ('specification', models.CharField(blank=True, default='', help_text="As printed, e.g. '6.5 - 8.5', 'Max 2.0 NTU', 'No off Odour'.", max_length=160)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('value_type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Free text'), ('CHOICE', 'One of a fixed list')], default='NUMBER', max_length=8)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('allowed_values', models.JSONField(blank=True, default=list, help_text="For CHOICE parameters, e.g. ['Acceptable', 'Not Acceptable'].")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality_control.recordtemplatesection')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecordTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('slot_time', models.TimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='quality_control.qcrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'slot_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecordValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='quality_control.recordtemplateparameter')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='quality_control.qcrecord')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='quality_control.recordtimeslot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_slot__sequence', 'parameter__sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recordtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'document_code'), name='uq_record_template_company_code'),
        ),
        migrations.AddIndex(
            model_name='qcrecord',
            index=models.Index(fields=['company', 'record_date'], name='quality_con_company_b4b392_idx'),
        ),
        migrations.AddIndex(
            model_name='qcrecord',
            index=models.Index(fields=['company', 'status'], name='quality_con_company_eb00c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='qcrecord',
            constraint=models.UniqueConstraint(fields=('company', 'template', 'record_date', 'shift'), name='uq_qc_record_day'),
        ),
        migrations.AddIndex(
            model_name='recordtemplatesection',
            index=models.Index(fields=['template', 'sequence'], name='quality_con_templat_e596e6_idx'),
        ),
        migrations.AddIndex(
            model_name='recordtemplateparameter',
            index=models.Index(fields=['section', 'sequence'], name='quality_con_section_92089c_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordtimeslot',
            constraint=models.UniqueConstraint(fields=('record', 'slot_time'), name='uq_record_time_slot'),
        ),
        migrations.AddIndex(
            model_name='recordvalue',
            index=models.Index(fields=['record'], name='quality_con_record__c5a84b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordvalue',
            constraint=models.UniqueConstraint(fields=('time_slot', 'parameter'), name='uq_record_value_cell'),
        ),
    ]
