# Generated by Django 6.0.1 on 2026-09-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0044_seed_qc_record_form_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtemplateparameter',
            name='conforming_values',
            field=models.JSONField(blank=True, default=list, help_text="The subset of observations that MEET the specification, e.g. ['No off Odour']. Kept separate from allowed_values because that list offers both the passing and the failing option. Leave empty to record the observation without judging it."),
        ),
        migrations.AlterField(
            model_name='recordtemplateparameter',
            name='allowed_values',
            field=models.JSONField(blank=True, default=list, help_text="Suggestions offered for a CHOICE parameter, e.g. ['No off Odour', 'Off Odour']. These are only suggestions -- the operator may still type any other observation."),
        ),
    ]
