# Generated by Django 6.0.1 on 2026-09-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0046_backfill_conforming_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_code', models.CharField(help_text="Controlled document code as printed, e.g. 'QA-TST-INH-14-02-10'.", max_length=64)),
                ('title', models.CharField(help_text='Document title as printed on the sheet.', max_length=255)),
                ('revision', models.CharField(blank=True, default='', help_text="Revision as printed, free text, e.g. '00/15-10-2023' or '01'.", max_length=64)),
                ('file', models.FileField(upload_to='qc_document_files/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes, as uploaded.', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_document_files', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_code', 'title'],
                'permissions': [('can_view_document_files', 'Can view the QC PDF document library'), ('can_manage_document_files', 'Can upload and remove QC PDF documents')],
                'indexes': [models.Index(fields=['company', 'title'], name='quality_con_company_d82568_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_code'), name='uq_qc_document_file_company_code')],
            },
        ),
    ]
