# Generated by Django 6.0.1 on 2026-09-02 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0049_qc_document_page_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qcdocumentfile',
            name='procedure_type',
            field=models.CharField(choices=[('INHOUSE', 'In-house Testing Procedure'), ('STANDARD', 'Standard Testing Procedure')], default='INHOUSE', help_text='In-house or standard, matching the INH / STD segment of the document code.', max_length=12),
        ),
        migrations.AddIndex(
            model_name='qcdocumentfile',
            index=models.Index(fields=['company', 'procedure_type'], name='quality_con_company_1459a7_idx'),
        ),
    ]
