# Generated by Django 6.0.1 on 2026-09-03 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0050_qcdocumentfile_procedure_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qcdocumentfile',
            name='uq_qc_document_file_company_code',
        ),
        migrations.AlterField(
            model_name='qcdocumentfile',
            name='document_code',
            field=models.CharField(blank=True, default='', help_text="Controlled document code as printed, e.g. 'QA-TST-INH-14-02-10'. Optional -- not every sheet carries one.", max_length=64),
        ),
        migrations.AddConstraint(
            model_name='qcdocumentfile',
            constraint=models.UniqueConstraint(condition=models.Q(('document_code', ''), _negated=True), fields=('company', 'document_code'), name='uq_qc_document_file_company_code'),
        ),
    ]
