# Generated by Django 6.0.1 on 2026-09-04 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0051_remove_qcdocumentfile_uq_qc_document_file_company_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qcdocumentfile',
            name='uq_qc_document_file_company_code',
        ),
        migrations.RemoveConstraint(
            model_name='qcrecord',
            name='uq_qc_record_day',
        ),
        migrations.RemoveConstraint(
            model_name='recordtemplate',
            name='uq_record_template_company_code',
        ),
        migrations.RemoveConstraint(
            model_name='testingprocedure',
            name='uq_testing_procedure_company_code',
        ),
        migrations.AddConstraint(
            model_name='qcdocumentfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('document_code', ''), _negated=True)), fields=('company', 'document_code'), name='uq_qc_document_file_company_code'),
        ),
        migrations.AddConstraint(
            model_name='qcrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'template', 'record_date', 'shift'), name='uq_qc_record_day'),
        ),
        migrations.AddConstraint(
            model_name='recordtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'document_code'), name='uq_record_template_company_code'),
        ),
        migrations.AddConstraint(
            model_name='testingprocedure',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'document_code'), name='uq_testing_procedure_company_code'),
        ),
    ]
