# Generated by Django 6.0.1 on 2026-09-04 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0052_remove_qcdocumentfile_uq_qc_document_file_company_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qcdocumentfile',
            name='uq_qc_document_file_company_code',
        ),
        migrations.AlterField(
            model_name='qcdocumentfile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null = a shared QA document, visible from every company. New uploads are shared; a value here keeps the document private to one company (older rows were filed that way).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_document_files', to='company.company'),
        ),
        migrations.AddConstraint(
            model_name='qcdocumentfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('company__isnull', False), models.Q(('document_code', ''), _negated=True)), fields=('company', 'document_code'), name='uq_qc_document_file_company_code'),
        ),
        migrations.AddConstraint(
            model_name='qcdocumentfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('company__isnull', True), models.Q(('document_code', ''), _negated=True)), fields=('document_code',), name='uq_qc_document_file_shared_code'),
        ),
    ]
