# Generated by Django 6.0.1 on 2026-09-04 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0053_remove_qcdocumentfile_uq_qc_document_file_company_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recordtemplate',
            name='uq_record_template_company_code',
        ),
        migrations.AlterField(
            model_name='recordtemplate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null = a shared form, usable from every company. Set a company only to keep a form private to that one plant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_templates', to='company.company'),
        ),
        migrations.AddConstraint(
            model_name='recordtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('company__isnull', False)), fields=('company', 'document_code'), name='uq_record_template_company_code'),
        ),
        migrations.AddConstraint(
            model_name='recordtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('company__isnull', True)), fields=('document_code',), name='uq_record_template_shared_code'),
        ),
    ]
