# Generated by Django 6.0.1 on 2026-09-04 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0055_consolidate_shared_record_forms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCDocumentFileAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(blank=True, default='', help_text="Document code at the moment of the event, not today's.", max_length=64)),
                ('title', models.CharField(blank=True, default='', help_text="Title at the moment of the event, not today's.", max_length=255)),
                ('action', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EDITED', 'Edited'), ('RETIRED', 'Retired')], max_length=12)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="{field: {'old': ..., 'new': ...}} for an edit; the filed values for an upload; empty for a retire.")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text="Company the user was working in. The documents themselves are shared, so this is the acting context, not the document's owner.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_document_file_audit_logs', to='company.company')),
                ('document', models.ForeignKey(blank=True, help_text='The document this happened to. Null once a row is hard-deleted from the database; the snapshot below still identifies it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='quality_control.qcdocumentfile')),
                ('user', models.ForeignKey(blank=True, help_text='Who did it. Null only if the account was later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_document_file_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QA Procedure Audit Log',
                'verbose_name_plural': 'QA Procedure Audit Log',
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_document_file_audit', 'Can view the QA Procedures audit log')],
                'indexes': [models.Index(fields=['-created_at', '-id'], name='quality_con_created_4d0ab0_idx'), models.Index(fields=['document', '-created_at'], name='quality_con_documen_8af19c_idx'), models.Index(fields=['user', '-created_at'], name='quality_con_user_id_428b54_idx'), models.Index(fields=['action', '-created_at'], name='quality_con_action_8e3e47_idx')],
            },
        ),
    ]
