# Generated by Django 6.0.1 on 2026-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0059_share_existing_qa_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='cell_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recordtemplate',
            name='cell_fields',
            field=models.JSONField(blank=True, default=dict, help_text="Which cells of the layout are filled in, keyed by cell (e.g. 'D10'): {type, label, min, max, options, ok, spec}."),
        ),
        migrations.AddField(
            model_name='recordtemplate',
            name='layout',
            field=models.JSONField(blank=True, help_text='The uploaded sheet as drawn: column widths, row heights, cells with their text and style, merges and pictures. Produced only by the Excel import, never typed.', null=True),
        ),
        migrations.AddField(
            model_name='recordtemplate',
            name='source_file_name',
            field=models.CharField(blank=True, default='', help_text='Name of the Excel file the layout was read from.', max_length=255),
        ),
    ]
