# Generated by Django 6.0.1 on 2026-09-29 05:33
"""Remove the QC flows nobody used: Production QC, Online Quality Monitoring,
the fillable record sheets (Documents) and the typed-up Testing Procedures.

Their tables are dropped. Before that, the permissions are sorted out:

* The two line-clearance QC permissions were declared on ProductionQCSession
  although they gate Line Clearance QA, which stays. Their rows are moved onto
  RawMaterialInspection, so every group that holds them keeps them (on live:
  "Production QC" and "qc_manager").
* The removed models' own permissions are deleted, which also takes them off
  every group that held them.
* "QC Procedures" and "QC Documents" held nothing else; each is deleted if
  nobody is in it and it is left with no permissions.
"""

from django.conf import settings
from django.db import migrations

APP = "quality_control"

LINE_CLEARANCE_QC_CODENAMES = [
    "can_view_line_clearance_qc",
    "can_approve_line_clearance_qc",
]
OLD_HOST = "productionqcsession"
NEW_HOST = "rawmaterialinspection"

REMOVED_MODELS = [
    "productionqcsession",
    "productionqcresult",
    "onlinequalityrecord",
    "onlinequalityreading",
    "onlinequalityreadingattachment",
    "onlinequalitytorque",
    "onlinequalityspec",
    "recordtemplate",
    "recordtemplatesection",
    "recordtemplateparameter",
    "qcrecord",
    "recordtimeslot",
    "recordvalue",
    "testingprocedure",
    "testingproceduresection",
    "testingprocedureline",
]

EMPTIED_GROUPS = ["QC Procedures", "QC Documents"]


def _move_permissions(apps, schema_editor, from_model, to_model):
    db = schema_editor.connection.alias
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    source = ContentType.objects.using(db).filter(app_label=APP, model=from_model).first()
    if source is None:
        return
    target, _ = ContentType.objects.using(db).get_or_create(app_label=APP, model=to_model)

    for codename in LINE_CLEARANCE_QC_CODENAMES:
        old = Permission.objects.using(db).filter(content_type=source, codename=codename).first()
        if old is None:
            continue
        new = Permission.objects.using(db).filter(content_type=target, codename=codename).first()
        if new is None:
            # Re-pointing the row keeps its id, so every grant follows it.
            old.content_type = target
            old.save(update_fields=["content_type"])
            continue
        # Both rows exist (post_migrate already made the new one): hand the
        # old row's grants to the new one before dropping it.
        for group in Group.objects.using(db).filter(permissions=old):
            group.permissions.add(new)
        for user in User.objects.using(db).filter(user_permissions=old):
            user.user_permissions.add(new)
        old.delete()


def move_line_clearance_permissions(apps, schema_editor):
    _move_permissions(apps, schema_editor, OLD_HOST, NEW_HOST)


def move_line_clearance_permissions_back(apps, schema_editor):
    _move_permissions(apps, schema_editor, NEW_HOST, OLD_HOST)


def drop_removed_permissions(apps, schema_editor):
    db = schema_editor.connection.alias
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    Permission.objects.using(db).filter(
        content_type__app_label=APP, content_type__model__in=REMOVED_MODELS
    ).exclude(codename__in=LINE_CLEARANCE_QC_CODENAMES).delete()

    for group in Group.objects.using(db).filter(name__in=EMPTIED_GROUPS):
        if not group.user_set.exists() and not group.permissions.exists():
            group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0060_record_sheet_layout'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            move_line_clearance_permissions, move_line_clearance_permissions_back
        ),
        # Not reversible: the grants are gone with the permissions.
        migrations.RunPython(drop_removed_permissions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='onlinequalityreading',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityreading',
            name='record',
        ),
        migrations.RemoveField(
            model_name='onlinequalityreading',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityreadingattachment',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='onlinequalityreadingattachment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityreadingattachment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityrecord',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityrecord',
            name='company',
        ),
        migrations.RemoveField(
            model_name='onlinequalityrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityrecord',
            name='production_line',
        ),
        migrations.RemoveField(
            model_name='onlinequalityrecord',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityrecord',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityrecord',
            name='updated_by',
        ),
        migrations.RemoveConstraint(
            model_name='onlinequalityspec',
            name='uq_online_spec_company_key',
        ),
        migrations.RemoveConstraint(
            model_name='onlinequalitytorque',
            name='uq_online_torque_reading_head',
        ),
        migrations.AlterUniqueTogether(
            name='productionqcresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productionqcresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionqcresult',
            name='parameter_master',
        ),
        migrations.RemoveField(
            model_name='productionqcresult',
            name='session',
        ),
        migrations.RemoveField(
            model_name='productionqcresult',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='productionqcsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='production_run',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='productionqcsession',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='qcrecord',
            name='quality_con_company_b4b392_idx',
        ),
        migrations.RemoveIndex(
            model_name='qcrecord',
            name='quality_con_company_eb00c3_idx',
        ),
        migrations.RemoveConstraint(
            model_name='qcrecord',
            name='uq_qc_record_day',
        ),
        migrations.RemoveConstraint(
            model_name='recordtemplate',
            name='uq_record_template_company_code',
        ),
        migrations.RemoveConstraint(
            model_name='recordtemplate',
            name='uq_record_template_shared_code',
        ),
        migrations.RemoveIndex(
            model_name='recordtemplateparameter',
            name='quality_con_section_92089c_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordtemplatesection',
            name='quality_con_templat_e596e6_idx',
        ),
        migrations.RemoveConstraint(
            model_name='recordtimeslot',
            name='uq_record_time_slot',
        ),
        migrations.RemoveIndex(
            model_name='recordvalue',
            name='quality_con_record__c5a84b_idx',
        ),
        migrations.RemoveConstraint(
            model_name='recordvalue',
            name='uq_record_value_cell',
        ),
        migrations.RemoveIndex(
            model_name='testingprocedure',
            name='quality_con_company_30964b_idx',
        ),
        migrations.RemoveIndex(
            model_name='testingprocedure',
            name='quality_con_company_7f4b94_idx',
        ),
        migrations.RemoveConstraint(
            model_name='testingprocedure',
            name='uq_testing_procedure_company_code',
        ),
        migrations.RemoveIndex(
            model_name='testingprocedureline',
            name='quality_con_section_a107cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='testingproceduresection',
            name='quality_con_procedu_aaf358_idx',
        ),
        migrations.AlterModelOptions(
            name='rawmaterialinspection',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_inspection', 'Can submit inspection for approval'), ('can_approve_as_chemist', 'Can approve inspection as QA Chemist'), ('can_approve_as_qam', 'Can approve inspection as QA Manager'), ('can_reject_inspection', 'Can reject inspection'), ('can_override_qc_vendor', "Can inspect against a vendor other than the PO's"), ('can_view_line_clearance_qc', 'Can view line clearance QC'), ('can_approve_line_clearance_qc', 'Can approve line clearance QC')]},
        ),
        migrations.DeleteModel(
            name='OnlineQualityReadingAttachment',
        ),
        migrations.DeleteModel(
            name='OnlineQualityRecord',
        ),
        migrations.RemoveField(
            model_name='onlinequalityspec',
            name='company',
        ),
        migrations.RemoveField(
            model_name='onlinequalityspec',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalityspec',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalitytorque',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlinequalitytorque',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='onlinequalitytorque',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ProductionQCResult',
        ),
        migrations.DeleteModel(
            name='ProductionQCSession',
        ),
        migrations.RemoveField(
            model_name='qcrecord',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='qcrecord',
            name='company',
        ),
        migrations.RemoveField(
            model_name='qcrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qcrecord',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='qcrecord',
            name='template',
        ),
        migrations.RemoveField(
            model_name='qcrecord',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='recordtemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recordtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordtemplate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='recordtemplateparameter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordtemplateparameter',
            name='section',
        ),
        migrations.RemoveField(
            model_name='recordtemplateparameter',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='recordtemplatesection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordtemplatesection',
            name='template',
        ),
        migrations.RemoveField(
            model_name='recordtemplatesection',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='recordtimeslot',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordtimeslot',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordtimeslot',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='recordvalue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordvalue',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='recordvalue',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordvalue',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='recordvalue',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='testingprocedure',
            name='company',
        ),
        migrations.RemoveField(
            model_name='testingprocedure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testingprocedure',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='testingprocedureline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testingprocedureline',
            name='section',
        ),
        migrations.RemoveField(
            model_name='testingprocedureline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='testingproceduresection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testingproceduresection',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='testingproceduresection',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='OnlineQualitySpec',
        ),
        migrations.DeleteModel(
            name='OnlineQualityReading',
        ),
        migrations.DeleteModel(
            name='OnlineQualityTorque',
        ),
        migrations.DeleteModel(
            name='RecordTemplate',
        ),
        migrations.DeleteModel(
            name='RecordTemplateSection',
        ),
        migrations.DeleteModel(
            name='RecordTemplateParameter',
        ),
        migrations.DeleteModel(
            name='QCRecord',
        ),
        migrations.DeleteModel(
            name='RecordTimeSlot',
        ),
        migrations.DeleteModel(
            name='RecordValue',
        ),
        migrations.DeleteModel(
            name='TestingProcedureLine',
        ),
        migrations.DeleteModel(
            name='TestingProcedure',
        ),
        migrations.DeleteModel(
            name='TestingProcedureSection',
        ),
    ]
