# Generated by Django 6.0.1 on 2026-09-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0061_remove_unused_qc_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcprintdocument',
            name='document_key',
            field=models.CharField(choices=[('RAW_MATERIAL_INSPECTION', 'Arrival Slip Inspection Print'), ('QC_PARAMETERS', 'Arrival Slip QC Parameters Print')], max_length=60),
        ),
    ]
