# Generated by Django 6.0.1 on 2026-09-29 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0048_sapproductionorderaction'),
        ('quality_control', '0062_relabel_print_documents_for_arrival_slips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_parameter_types', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter_name', models.CharField(max_length=200)),
                ('parameter_code', models.CharField(max_length=50)),
                ('standard_value', models.CharField(help_text="e.g. '910±5', 'NLT 20', 'Proper', 'Free from leak'", max_length=200)),
                ('value_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text/Descriptive'), ('BOOLEAN', 'Pass/Fail'), ('RANGE', 'Numeric Range')], default='TEXT', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality_control.productionparametertype')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'unique_together': {('parameter_type', 'parameter_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductionQCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('checked_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('SENT_BACK', 'Sent Back'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True)),
                ('sent_back_at', models.DateTimeField(blank=True, null=True)),
                ('send_back_remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_entries_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_qc_entries', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_entries', to='production_execution.productionline')),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='quality_control.productionparametertype')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_entries', to='production_execution.productionrun')),
                ('sent_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_entries_sent_back', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_entries_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
                'permissions': [('can_view_production_qc_entries', 'Can view production QC entries'), ('can_fill_production_qc_entries', 'Can make and correct production QC entries'), ('can_approve_production_qc_entries', 'Can approve production QC entries'), ('can_manage_production_qc_parameters', 'Can manage production QC parameter types')],
            },
        ),
        migrations.CreateModel(
            name='ProductionQCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter_name', models.CharField(max_length=200)),
                ('parameter_code', models.CharField(blank=True, default='', max_length=50)),
                ('standard_value', models.CharField(max_length=200)),
                ('parameter_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text/Descriptive'), ('BOOLEAN', 'Pass/Fail'), ('RANGE', 'Numeric Range')], default='TEXT', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, default='', max_length=50)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('result_value', models.CharField(blank=True, max_length=200)),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_within_spec', models.BooleanField(null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality_control.productionqcentry')),
                ('parameter_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='quality_control.productionparameter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionParameterTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_parameter_type_items', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality_control.productionparametertype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_code'],
                'indexes': [models.Index(fields=['company', 'item_code'], name='quality_con_company_f7c15d_idx')],
                'unique_together': {('company', 'item_code', 'parameter_type')},
            },
        ),
        migrations.AddIndex(
            model_name='productionqcentry',
            index=models.Index(fields=['company', 'status'], name='quality_con_company_d30713_idx'),
        ),
        migrations.AddIndex(
            model_name='productionqcentry',
            index=models.Index(fields=['company', 'checked_at'], name='quality_con_company_286a54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionqcresult',
            unique_together={('entry', 'parameter_master')},
        ),
    ]
