# Generated by Django 6.0.1 on 2026-09-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0064_production_qc_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionparametertype',
            name='document_code',
            field=models.CharField(blank=True, default='', help_text="e.g. 'QA-FRM-14-01-05-02'", max_length=64),
        ),
        migrations.AddField(
            model_name='productionparametertype',
            name='revision',
            field=models.CharField(blank=True, default='', help_text="e.g. '02'", max_length=20),
        ),
        migrations.AddField(
            model_name='productionparametertype',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
