# Generated by Django 6.0.1 on 2026-09-30 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('quality_control', '0065_production_parameter_type_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qcprintdocument',
            options={'ordering': ['document_key', 'production_parameter_type__name']},
        ),
        migrations.AlterUniqueTogether(
            name='qcprintdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qcprintdocument',
            name='production_parameter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_documents', to='quality_control.productionparametertype'),
        ),
        migrations.AlterField(
            model_name='qcprintdocument',
            name='document_key',
            field=models.CharField(choices=[('RAW_MATERIAL_INSPECTION', 'Arrival Slip Inspection Print'), ('QC_PARAMETERS', 'Arrival Slip QC Parameters Print'), ('PRODUCTION_QC_SHEET', 'Production QC Sheet')], max_length=60),
        ),
        migrations.AddConstraint(
            model_name='qcprintdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('production_parameter_type__isnull', True)), fields=('company', 'document_key'), name='uq_qc_print_document_company_key'),
        ),
        migrations.AddConstraint(
            model_name='qcprintdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('production_parameter_type__isnull', False)), fields=('company', 'production_parameter_type'), name='uq_qc_print_document_company_type'),
        ),
        migrations.AddConstraint(
            model_name='qcprintdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_key', 'PRODUCTION_QC_SHEET'), ('production_parameter_type__isnull', False)), models.Q(models.Q(('document_key', 'PRODUCTION_QC_SHEET'), _negated=True), ('production_parameter_type__isnull', True)), _connector='OR'), name='ck_qc_print_document_sheet_has_type'),
        ),
    ]
