# Generated by Django 6.0.1 on 2026-09-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0068_remove_productionparametertype_document_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productionparametertypeitem',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='productionparametertypeitem',
            name='quality_con_company_f7c15d_idx',
        ),
        migrations.DeleteModel(
            name='ProductionParameterTypeItem',
        ),
    ]
