# Generated by Django 6.0.1 on 2026-10-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0069_drop_production_type_product_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionqcentry',
            options={'ordering': ['-checked_at', '-id'], 'permissions': [('can_view_production_qc_entries', 'Can view QC document entries'), ('can_fill_production_qc_entries', 'Can fill and correct QC document entries'), ('can_approve_production_qc_entries', 'Can approve QC document entries'), ('can_manage_production_qc_parameters', 'Can manage QC document types')]},
        ),
        migrations.RemoveField(
            model_name='productionqcentry',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='productionqcentry',
            name='line',
        ),
        migrations.RemoveField(
            model_name='productionqcentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productionqcentry',
            name='production_run',
        ),
        migrations.AlterField(
            model_name='qcprintdocument',
            name='document_key',
            field=models.CharField(choices=[('RAW_MATERIAL_INSPECTION', 'Arrival Slip Inspection Print'), ('QC_PARAMETERS', 'Arrival Slip QC Parameters Print'), ('PRODUCTION_QC_SHEET', 'QC Document Sheet')], max_length=60),
        ),
    ]
