# Generated by Django 6.0.1 on 2026-10-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0072_rename_documents_to_qa_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionqcentry',
            name='default_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ProductionParameterTypeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='quality_control.productionparametertype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionParameterDefaultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_value', models.CharField(blank=True, max_length=200)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_values', to='quality_control.productionparameter')),
                ('default', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='quality_control.productionparametertypedefault')),
            ],
        ),
        migrations.AddField(
            model_name='productionqcentry',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='quality_control.productionparametertypedefault'),
        ),
        migrations.AddConstraint(
            model_name='productionparametertypedefault',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parameter_type', 'name'), name='uq_production_type_default_name'),
        ),
        migrations.AlterUniqueTogether(
            name='productionparameterdefaultvalue',
            unique_together={('default', 'parameter')},
        ),
    ]
