# Generated by Django 6.0.1 on 2026-07-23 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('section', models.CharField(max_length=8)),
                ('doctype', models.CharField(max_length=8)),
                ('cc', models.CharField(max_length=2)),
                ('ss', models.CharField(max_length=2)),
                ('gg', models.CharField(max_length=2)),
                ('nn', models.PositiveSmallIntegerField(help_text='Sequential serial within the SECTION+DOCTYPE+clause group.')),
                ('revision_number', models.PositiveSmallIntegerField(default=0, help_text='Revision number, starts at 00. A revision bumps this; the code itself never changes.')),
                ('issue_date', models.DateField(help_text='Revision / issue date.')),
                ('total_pages', models.PositiveIntegerField(default=1, help_text='Number of pages in the controlled document.')),
                ('module', models.CharField(blank=True, max_length=16)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_document_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'doctype', 'cc', 'ss', 'gg', 'nn'],
                'indexes': [models.Index(fields=['section', 'doctype', 'cc', 'ss', 'gg'], name='document_co_section_c125b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'doctype', 'cc', 'ss', 'gg', 'nn'), name='uq_documentcode_group_serial')],
            },
        ),
    ]
