# Generated by Django 6.0.1 on 2026-08-24 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPurchasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_production_plan', 'Can view production plans and requirement'), ('can_create_purchase_order', 'Can create purchase orders from a plan'), ('can_approve_purchase_order', 'Can approve purchase orders'), ('can_post_purchase_order_to_sap', 'Can post purchase orders to SAP')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('plan_abs_id', models.IntegerField(blank=True, help_text='SAP OFCT AbsID of the plan this was raised from', null=True)),
                ('plan_code', models.CharField(blank=True, default='', max_length=100)),
                ('plan_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_code', models.CharField(db_index=True, max_length=50)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=200)),
                ('doc_date', models.DateField(help_text='Posting date sent to SAP')),
                ('doc_due_date', models.DateField(help_text='Delivery date required')),
                ('warehouse_code', models.CharField(blank=True, default='', help_text='Receiving warehouse for every line unless a line overrides it', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted to SAP'), ('FAILED', 'SAP post failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.BigIntegerField(blank=True, null=True)),
                ('sap_error_message', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('simulated', models.BooleanField(default=False, help_text='True when the post ran under PLANNING_PURCHASE_SIMULATE_SAP and no SAP document was actually created')),
                ('idempotency_key', models.CharField(db_index=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_planning_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planning_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_planning_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order (from plan)',
                'verbose_name_plural': 'Purchase Orders (from plan)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('material_type', models.CharField(choices=[('PACKAGING', 'Packaging Material'), ('RAW', 'Raw Material'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uom', models.CharField(blank=True, default='', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('warehouse_code', models.CharField(blank=True, default='', max_length=20)),
                ('required_date', models.DateField(blank=True, help_text='Date production needs it (SAP ShipDate)', null=True)),
                ('required_qty', models.DecimalField(decimal_places=6, default=0, help_text='BOM requirement for the plan at the time the order was raised', max_digits=20)),
                ('available_qty', models.DecimalField(decimal_places=6, default=0, help_text='Net available stock (on hand - committed) at that time', max_digits=20)),
                ('on_order_qty', models.DecimalField(decimal_places=6, default=0, help_text='Already on open purchase orders at that time', max_digits=20)),
                ('shortage_qty', models.DecimalField(decimal_places=6, default=0, help_text='required - available - on_order, floored at zero', max_digits=20)),
                ('moq_applied', models.DecimalField(blank=True, decimal_places=6, help_text='Set when the quantity was rounded up to a minimum order quantity', max_digits=20, null=True)),
                ('sap_line_num', models.IntegerField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning_purchase.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Line',
                'verbose_name_plural': 'Purchase Order Lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company_code', 'status'], name='planning_pu_company_c3dd05_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company_code', 'plan_abs_id'], name='planning_pu_company_9a3281_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company_code', 'idempotency_key'), name='uniq_planning_po_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'item_code'), name='uniq_planning_po_line_item'),
        ),
    ]
