# Generated by Django 6.0.1 on 2026-10-05 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('planning_purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningpurchasepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_production_plan', 'Can view production plans and requirement'), ('can_create_purchase_order', 'Can create purchase orders from a plan'), ('can_approve_purchase_order', 'Can approve purchase orders'), ('can_post_purchase_order_to_sap', 'Can post purchase orders to SAP'), ('can_view_open_pos', "Can view SAP's open purchase orders"), ('can_upload_monthly_plan', 'Can upload and remove the monthly plan workbook')]},
        ),
        migrations.CreateModel(
            name='MonthlyPlanUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the planned month.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, help_text="The sheet's own banner.", max_length=255)),
                ('source_file', models.CharField(max_length=255)),
                ('uploaded_by_label', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('row_count', models.IntegerField(default=0)),
                ('commodity_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('premium_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ecom_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exim_id', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_plan_uploads', to='company.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-version'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('head', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('per_ltrs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ltrs_per_box', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('case_pack', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('commodity_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commodity_w1', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commodity_w2', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commodity_w3', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commodity_w4', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('premium_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('premium_w1', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('premium_w2', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('premium_w3', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('premium_w4', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ecom_planning', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_planning', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='planning_purchase.monthlyplanupload')),
            ],
            options={
                'ordering': ['-total_planning', 'code'],
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyplanupload',
            constraint=models.UniqueConstraint(fields=('company', 'month', 'version'), name='pp_monthlyplan_unique_version'),
        ),
    ]
