# Generated by Django 6.0.1 on 2026-09-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARInvoicePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_code', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=100)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('doc_due_date', models.DateField(blank=True, null=True)),
                ('tax_date', models.DateField(blank=True, null=True)),
                ('selected_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('branch_id', models.IntegerField()),
                ('comments', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_APPROVAL', 'Awaiting SAP approval'), ('APPROVED', 'Approved — not yet posted'), ('POSTED', 'Posted to SAP'), ('REJECTED', 'Rejected in approval'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sap_draft_entry', models.IntegerField(blank=True, null=True)),
                ('sap_approval_code', models.IntegerField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, default='')),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('sap_doc_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoice_postings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoice_postings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ar_invoice_posting',
                'ordering': ['-created_at'],
                'permissions': [('view_ar_invoice_posting', 'Can view A/R invoice postings'), ('create_ar_invoice_posting', 'Can create and post A/R invoices')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ARInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_entry', models.IntegerField()),
                ('base_line', models.IntegerField()),
                ('base_doc_num', models.IntegerField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_code', models.CharField(blank=True, default='', max_length=50)),
                ('warehouse_code', models.CharField(blank=True, default='', max_length=20)),
                ('ar_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ar_invoice.arinvoiceposting')),
            ],
            options={
                'db_table': 'ar_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='ARInvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ar_invoice_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('sap_attachment_status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded to SAP'), ('LINKED', 'Linked to SAP Document'), ('FAILED', 'Upload Failed')], default='PENDING', max_length=20)),
                ('sap_absolute_entry', models.IntegerField(blank=True, null=True)),
                ('sap_error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoice_attachments', to=settings.AUTH_USER_MODEL)),
                ('ar_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ar_invoice.arinvoiceposting')),
            ],
            options={
                'db_table': 'ar_invoice_attachment',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='arinvoiceposting',
            index=models.Index(fields=['company', 'customer_code'], name='ar_invoice__company_16e2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='arinvoiceposting',
            index=models.Index(fields=['company', 'status'], name='ar_invoice__company_522b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='arinvoiceposting',
            index=models.Index(fields=['sap_draft_entry'], name='ar_invoice__sap_dra_21dc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='arinvoiceposting',
            index=models.Index(fields=['sap_doc_entry'], name='ar_invoice__sap_doc_ef6d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='arinvoiceline',
            index=models.Index(fields=['base_entry', 'base_line'], name='ar_invoice__base_en_9c09eb_idx'),
        ),
    ]
