# Generated by Django 6.0.1 on 2026-09-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_invoice', '0002_ar_invoice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoiceposting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_APPROVAL', 'Awaiting SAP approval'), ('APPROVED', 'Approved — not yet posted'), ('POSTED', 'Posted to SAP'), ('REJECTED', 'Rejected in approval'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
