# Generated by Django 6.0.1 on 2026-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_invoice', '0003_alter_arinvoiceposting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoiceline',
            name='cost_center',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='arinvoiceline',
            name='base_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arinvoiceline',
            name='base_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
