# Generated by Django 6.0.1 on 2026-09-12 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_invoice', '0004_arinvoiceline_cost_center_and_more'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Payment pending'), ('PARTIAL', 'Partly received'), ('RECEIVED', 'Payment received')], default='PENDING', max_length=20)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], default='', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('ar_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ar_invoice.arinvoiceposting')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoice_payments', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ar_invoice_payment',
                'ordering': ['-updated_at'],
                'permissions': [('mark_ar_invoice_payment', 'Can record whether an A/R invoice has been paid')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'status'], name='ar_invoice__company_22f18d_idx'), models.Index(fields=['company', 'sap_doc_entry'], name='ar_invoice__company_5a2cc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'sap_doc_entry'), name='uniq_ar_payment_per_invoice')],
            },
        ),
    ]
