# Generated by Django 6.0.1 on 2026-09-29 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_invoice', '0007_ar_invoice_dispatch_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoiceposting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_MANAGER', 'Awaiting warehouse manager'), ('PENDING_APPROVAL', 'Awaiting SAP approval'), ('APPROVED', 'Approved — not yet posted'), ('POSTED', 'Posted to SAP'), ('REJECTED', 'Rejected in approval'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ARInvoiceWarehouseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('ar_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_approvals', to='ar_invoice.arinvoiceposting')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoice_warehouse_decisions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ar_invoice_warehouse_approval',
                'ordering': ['id'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['warehouse_code', 'status'], name='ar_invoice__warehou_70c28a_idx')],
                'constraints': [models.UniqueConstraint(fields=('ar_invoice', 'warehouse_code'), name='uniq_ar_invoice_warehouse_approval')],
            },
        ),
    ]
