# Generated by Django 6.0.1 on 2026-03-24 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0006_alter_vehicleentry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_doc_entry', models.IntegerField(help_text='SAP Sales Order DocEntry')),
                ('sap_doc_num', models.IntegerField(help_text='SAP Sales Order DocNum')),
                ('customer_code', models.CharField(help_text='SAP Business Partner code', max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('ship_to_address', models.TextField(blank=True, default='')),
                ('carrier_code', models.CharField(blank=True, default='', max_length=50)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_date', models.DateField(help_text='Planned dispatch date')),
                ('dock_bay', models.CharField(blank=True, default='', help_text='Assigned bay (Zone C: 19-30)', max_length=10)),
                ('dock_slot_start', models.DateTimeField(blank=True, null=True)),
                ('dock_slot_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RELEASED', 'Released'), ('PICKING', 'Picking'), ('PACKED', 'Packed'), ('STAGED', 'Staged'), ('LOADING', 'Loading'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], default='RELEASED', max_length=20)),
                ('bill_of_lading_no', models.CharField(blank=True, default='', max_length=50)),
                ('seal_number', models.CharField(blank=True, default='', max_length=50)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Total load weight in kg', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_orders', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_shipments', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_sync_shipments', 'Can sync shipment orders from SAP'), ('can_assign_dock_bay', 'Can assign dock bay to shipments'), ('can_dispatch_shipment', 'Can dispatch shipments'), ('can_view_outbound_dashboard', 'Can view outbound dashboard')],
                'unique_together': {('company', 'sap_doc_entry')},
            },
        ),
        migrations.CreateModel(
            name='OutboundLoadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trailer_condition', models.CharField(choices=[('CLEAN', 'Clean'), ('DAMAGED', 'Damaged'), ('REJECTED', 'Rejected')], default='CLEAN', max_length=20)),
                ('trailer_temp_ok', models.BooleanField(blank=True, help_text='Temperature check passed', null=True)),
                ('trailer_temp_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature reading in Celsius', max_digits=6, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('loading_started_at', models.DateTimeField(blank=True, null=True)),
                ('loading_completed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_inspections', to=settings.AUTH_USER_MODEL)),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_loads', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_loads', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('shipment_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load_record', to='outbound_dispatch.shipmentorder')),
            ],
            options={
                'permissions': [('can_inspect_trailer', 'Can inspect trailers'), ('can_load_truck', 'Can load trucks'), ('can_confirm_load', 'Can confirm load as supervisor')],
            },
        ),
        migrations.CreateModel(
            name='GoodsIssuePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_doc_entry', models.IntegerField(blank=True, help_text='SAP Goods Issue DocEntry', null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, help_text='SAP Goods Issue DocNum', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_issue_postings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('shipment_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue', to='outbound_dispatch.shipmentorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_post_goods_issue', 'Can post goods issue to SAP'), ('can_retry_goods_issue', 'Can retry failed goods issue')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_line_num', models.IntegerField(help_text='SAP Sales Order line number')),
                ('item_code', models.CharField(help_text='SAP Item code', max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('ordered_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('picked_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('packed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('loaded_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('uom', models.CharField(help_text='Unit of measure', max_length=20)),
                ('warehouse_code', models.CharField(help_text='Source warehouse in SAP', max_length=20)),
                ('batch_number', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Item weight in kg', max_digits=12, null=True)),
                ('pick_status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKED', 'Picked'), ('SHORT', 'Short Pick')], default='PENDING', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shipment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outbound_dispatch.shipmentorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sap_line_num'],
                'unique_together': {('shipment_order', 'sap_line_num')},
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pick_location', models.CharField(help_text='Warehouse bin/slot location', max_length=50)),
                ('pick_qty', models.DecimalField(decimal_places=3, help_text='Quantity to pick', max_digits=12)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SHORT', 'Short Pick')], default='PENDING', max_length=20)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_barcode', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pick_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('shipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='outbound_dispatch.shipmentorderitem')),
            ],
            options={
                'ordering': ['pick_location'],
                'permissions': [('can_execute_pick_task', 'Can execute pick tasks')],
            },
        ),
    ]
