"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
from corsheaders.defaults import default_headers


def cast_debug(value):
    normalized = str(value).strip().lower()
    if normalized in {'1', 'true', 'yes', 'on', 'debug'}:
        return True
    if normalized in {'0', 'false', 'no', 'off', 'release', 'prod', 'production'}:
        return False
    raise ValueError(f"Invalid DEBUG value: {value}")


def cast_optional_int(value):
    if value is None:
        return None
    normalized = str(value).strip()
    if not normalized:
        return None
    return int(normalized)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Core Settings
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=cast_debug)
DISPATCH_USE_LOCAL_GRPO_LINES_FOR_TESTING = config(
    'DISPATCH_USE_LOCAL_GRPO_LINES_FOR_TESTING',
    default=DEBUG,
    cast=cast_debug,
)
DISPATCH_LOCAL_GRPO_TEST_BRANCH_ID = config(
    'DISPATCH_LOCAL_GRPO_TEST_BRANCH_ID',
    default=2,
    cast=int,
)
DISPATCH_SIMULATE_AP_INVOICE_POSTING = config(
    'DISPATCH_SIMULATE_AP_INVOICE_POSTING',
    default=False,
    cast=cast_debug,
)
# Marketplace: when true, the confirm-dispatch flow does NOT call SAP. It skips
# stock checks and returns synthetic delivery-note / goods-issue numbers, so the
# scan→confirm flow can be demoed/tested without a live SAP connection. Defaults
# to DEBUG so production posts for real.
MARKETPLACE_SIMULATE_SAP = config(
    'MARKETPLACE_SIMULATE_SAP',
    default=DEBUG,
    cast=cast_debug,
)
# Planning & Purchase: when true, posting a purchase order marks it posted
# WITHOUT creating anything in SAP. A purchase order is a commitment to a
# supplier, so this defaults to DEBUG — development and demos stay harmless and
# only a deployed production box posts for real. The flag is also recorded on
# every order (`PurchaseOrder.simulated`), so an order raised in simulate mode
# still reads as simulated after the setting changes.
PLANNING_PURCHASE_SIMULATE_SAP = config(
    'PLANNING_PURCHASE_SIMULATE_SAP',
    default=DEBUG,
    cast=cast_debug,
)
# The factory calendar behind day/week bucketing. Python weekday numbers,
# Monday 0 ... Sunday 6. This factory runs Monday-Saturday, so Sunday is the
# only non-working day; a change of shift pattern is a config change, not code.
PLANNING_NON_WORKING_WEEKDAYS = config(
    'PLANNING_NON_WORKING_WEEKDAYS',
    default='6',
    cast=Csv(int),
)
PLANNING_WEEK_START_DAY = config('PLANNING_WEEK_START_DAY', default=0, cast=int)
# Which warehouses count as available stock, per kind of material.
#
# Packaging and oil are not kept in the same places, so scoping them together
# lets a packaging item pick up stock from a tank farm and an oil pick up stock
# from a carton store.
#
#   PACKAGING  BH-PS  Bhakharpur Preshit             holds neither today
#              BH-PC  Production Consumption         2.87 M packaging
#              BH-PM  Packaging Materials 1st Floor  6.00 M packaging
#   RAW        BH-LO  Loose Oil                      753 K raw (62% of all RM)
#              BH-OT  Param                          321 K raw (26% of all RM)
#
# Scoping at all matters more than which list wins: summing the whole estate
# counts finished-goods godowns, non-moving stores, job-work locations and
# wastage as material production could draw on, which understates every shortage
# and under-buys.
#
# BH-PC is deliberately NOT in the RAW list even though it holds 93 K litres --
# for several oils more than BH-LO does. It is a production-consumption staging
# area for material already pulled towards a run, so it is not free for a new
# plan to spend. BH-PP (4.98 M packaging, flagged inactive in SAP) and BH-WST
# (wastage) are out of both lists. All of it is config rather than code.
PLANNING_PURCHASE_PM_WAREHOUSES = config(
    'PLANNING_PURCHASE_PM_WAREHOUSES',
    default='BH-PS,BH-PC,BH-PM',
    cast=Csv(),
)
PLANNING_PURCHASE_RM_WAREHOUSES = config(
    'PLANNING_PURCHASE_RM_WAREHOUSES',
    default='BH-LO,BH-OT',
    cast=Csv(),
)
# The marketplace module is enabled for exactly one company unit. Requests made
# under any other company are rejected (403) and the UI hides the module. Blank
# disables the restriction (all companies).
MARKETPLACE_COMPANY_CODE = config('MARKETPLACE_COMPANY_CODE', default='JIVO_MART')
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    # local apps
    'accounts',
    'company',
    'gate_core',
    'vehicle_management',
    'driver_management',
    'security_checks',
    'sap_client',
    'raw_material_gatein',
    'finished_goods_gatein',
    'weighment',
    'quality_control',
    'daily_needs_gatein',
    'maintenance_gatein',
    'maintenance.apps.MaintenanceConfig',
    'returnable_items.apps.ReturnableItemsConfig',
    'construction_gatein',
    'fixed_asset_gatein',
    'labour_count',
    'labour_gate',
    'person_gatein',
    'grpo',
    'notifications',
    'docking_admin',
    'production_execution',
    'planning_purchase',
    'stock_dashboard',
    'dispatch_plans',
    'django_apscheduler',
    'non_moving_rm',
    'sales_planning_requirement',
    'warehouse',
    'barcode',
    'ai_assistant',
    'wms',
    'marketplace',
    'blowing',
    'attendance',
    'goods_return',
    'invoice_approval',
    'document_control',
    'activity_center.apps.ActivityCenterConfig',
    'etp.apps.EtpConfig',
    'sap_reports',
    'factory_expense',
    'cost_master',
    'org_chart.apps.OrgChartConfig',
    'budget_approvals',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serve static files (incl. the Django admin CSS/JS) directly from the app,
    # so the admin is styled even when DEBUG=False or behind gunicorn. Must sit
    # right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
    }
}
AI_DB_NAME = config('AI_DB_NAME', default='')
if AI_DB_NAME:
    DATABASES['ai_readonly'] = {
        'ENGINE': config('AI_DB_ENGINE', default=config('DB_ENGINE', default='django.db.backends.postgresql')),
        'NAME': AI_DB_NAME,
        'USER': config('AI_DB_USER'),
        'PASSWORD': config('AI_DB_PASSWORD'),
        'HOST': config('AI_DB_HOST', default=config('DB_HOST')),
        'PORT': config('AI_DB_PORT', default=config('DB_PORT', default='5432')),
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Admin Panel Customization
ADMIN_SITE_HEADER = 'JI Admin'
ADMIN_SITE_TITLE = "JI"
ADMIN_INDEX_TITLE = "JI Factory Jivo Wellness Admin"

# Static files (served by WhiteNoise — see MIDDLEWARE above)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Let WhiteNoise serve files straight from the staticfiles finders, so the admin
# is styled in development without first running `collectstatic`. For production
# run `python manage.py collectstatic`; WhiteNoise then serves from STATIC_ROOT.
WHITENOISE_USE_FINDERS = True

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Media files
MEDIA_URL = '/media/'
# Env-configurable so uploads can live in a PERSISTENT directory that survives the
# release-based deploy (each release is a fresh dir, so the default BASE_DIR/media is
# wiped on every deploy). Point MEDIA_ROOT at a shared path (e.g. outside releases/)
# to keep proof-of-delivery photos, bilty scans, etc. across deploys.
MEDIA_ROOT = config('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

# File upload limits (15 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/day',
    #     'user': '1000/day',
    # }
}

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# Simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1500),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS settings
LOCAL_DEV_CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'http://localhost:5175',
    'http://127.0.0.1:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5176',
]
CORS_ALLOWED_ORIGINS = list(dict.fromkeys([
    *config('CORS_ALLOWED_ORIGINS', default='', cast=Csv()),
    *LOCAL_DEV_CORS_ALLOWED_ORIGINS,
]))
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ['Company-Code']

# SAP HANA and Service Layer settings
HANA_HOST = config('HANA_HOST')
HANA_PORT = config('HANA_PORT', cast=int)
HANA_USER = config('HANA_USER')
HANA_PASSWORD = config('HANA_PASSWORD')

SL_URL = config('SL_URL')
SL_USER = config('SL_USER')
SL_PASSWORD = config('SL_PASSWORD')

# Invoice-approval decisions are recorded in SAP's approval workflow, which
# authenticates the deciding user — the Service Layer integration account (SL_USER)
# is usually NOT a registered approver, so decisions must be signed by a SAP user
# who is (a superuser can decide any request). Set these to that account; when
# blank the writer falls back to SL_USER (which only works if it is an approver).
SAP_APPROVAL_USER = config('SAP_APPROVAL_USER', default='')
SAP_APPROVAL_PASSWORD = config('SAP_APPROVAL_PASSWORD', default='')

# When SAP's Service Layer cannot reach its Attachments Folder (error -5002/-43),
# write the attachment header/line straight into HANA (OATC/ATC1) instead of
# failing the whole posting. Only safe when the file is already in SAP's
# attachments folder (i.e. the SAP file-uploader path). Off by default.
SAP_ATTACHMENT_HANA_FALLBACK = config(
    'SAP_ATTACHMENT_HANA_FALLBACK', default=False, cast=cast_debug
)

SAP_GATEPASS_CRYSTAL_REPORT_PATH = config(
    "SAP_GATEPASS_CRYSTAL_REPORT_PATH",
    default="",
)
SAP_GATEPASS_CRYSTAL_RENDERER_COMMAND = config(
    "SAP_GATEPASS_CRYSTAL_RENDERER_COMMAND",
    default="",
)
SAP_GATEPASS_CRYSTAL_RENDER_TIMEOUT_SECONDS = config(
    "SAP_GATEPASS_CRYSTAL_RENDER_TIMEOUT_SECONDS",
    default=120,
    cast=int,
)
SAP_GATEPASS_CRYSTAL_ENABLE_FALLBACK_PDF = config(
    "SAP_GATEPASS_CRYSTAL_ENABLE_FALLBACK_PDF",
    default=True,
    cast=cast_debug,
)
SAP_GATEPASS_CRYSTAL_OBJECT_IDS = {
    "INVOICE": config("SAP_GATEPASS_CRYSTAL_OBJECT_ID_INVOICE", default="13"),
    "STOCK_TRANSFER": config("SAP_GATEPASS_CRYSTAL_OBJECT_ID_STOCK_TRANSFER", default="67"),
}

COMPANY_DB = {
    "JIVO_OIL": config('COMPANY_DB_JIVO_OIL'),
    "JIVO_MART": config('COMPANY_DB_JIVO_MART'),
    "JIVO_BEVERAGES": config('COMPANY_DB_JIVO_BEVERAGES'),
}

# Docking: company codes for which finished-goods box scanning is OPTIONAL.
# These companies don't scan boxes at the factory, so operators can continue past the
# Docking scan step and print the gatepass without scanning any box and without an
# admin scan-skip approval. Other companies keep the scan + approval requirement.
DOCKING_BOX_SCAN_OPTIONAL_COMPANY_CODES = config(
    "DOCKING_BOX_SCAN_OPTIONAL_COMPANY_CODES",
    default="JIVO_BEVERAGES",
    cast=Csv(),
)

SAP_ATTACHMENT_DIRECT_COPY_PATHS = {
    "JIVO_OIL": config("SAP_ATTACHMENT_DIRECT_COPY_PATH_JIVO_OIL", default=""),
    "JIVO_MART": config("SAP_ATTACHMENT_DIRECT_COPY_PATH_JIVO_MART", default=""),
    "JIVO_BEVERAGES": config(
        "SAP_ATTACHMENT_DIRECT_COPY_PATH_JIVO_BEVERAGES",
        default="",
    ),
}
SAP_ATTACHMENT_DIRECT_COPY_USERNAME = config(
    "SAP_ATTACHMENT_DIRECT_COPY_USERNAME",
    default="",
)
SAP_ATTACHMENT_DIRECT_COPY_PASSWORD = config(
    "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD",
    default="",
)
SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL = config(
    "SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL",
    default=SAP_ATTACHMENT_DIRECT_COPY_USERNAME,
)
SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL = config(
    "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL",
    default=SAP_ATTACHMENT_DIRECT_COPY_PASSWORD,
)
SAP_ATTACHMENT_DIRECT_COPY_CREDENTIALS = {
    "JIVO_OIL": {
        "username": SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL,
        "password": SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL,
    },
    "JIVO_MART": {
        "username": config(
            "SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_MART",
            default=SAP_ATTACHMENT_DIRECT_COPY_USERNAME,
        ),
        "password": config(
            "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_MART",
            default=SAP_ATTACHMENT_DIRECT_COPY_PASSWORD,
        ),
    },
    "JIVO_BEVERAGES": {
        "username": config(
            "SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_BEVERAGES",
            default=SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL,
        ),
        "password": config(
            "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_BEVERAGES",
            default=SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL,
        ),
    },
}

SAP_FILE_UPLOADER_ENABLED = config(
    "SAP_FILE_UPLOADER_ENABLED",
    default=False,
    cast=cast_debug,
)
SAP_FILE_UPLOADER_BASE_URL = config(
    "SAP_FILE_UPLOADER_BASE_URL",
    default="",
)
SAP_FILE_UPLOADER_API_KEY = config(
    "SAP_FILE_UPLOADER_API_KEY",
    default="",
)
# Per-attempt timeout, not the whole operation: the uploader writes into a
# Windows share that stalls intermittently, so a failed attempt is retried
# rather than surfaced, and SAP_FILE_UPLOADER_TOTAL_BUDGET_SECONDS caps the
# lot. Keep the budget clear of nginx's proxy_read_timeout (120s) - the SAP
# Service Layer calls after the upload share the same browser request.
SAP_FILE_UPLOADER_TIMEOUT_SECONDS = config(
    "SAP_FILE_UPLOADER_TIMEOUT_SECONDS",
    default=30,
    cast=int,
)
SAP_FILE_UPLOADER_MAX_ATTEMPTS = config(
    "SAP_FILE_UPLOADER_MAX_ATTEMPTS",
    default=3,
    cast=int,
)
SAP_FILE_UPLOADER_RETRY_BACKOFF_SECONDS = config(
    "SAP_FILE_UPLOADER_RETRY_BACKOFF_SECONDS",
    default=3,
    cast=int,
)
SAP_FILE_UPLOADER_TOTAL_BUDGET_SECONDS = config(
    "SAP_FILE_UPLOADER_TOTAL_BUDGET_SECONDS",
    default=65,
    cast=int,
)
SAP_FILE_UPLOADER_FOLDER_IDS = {
    "JIVO_OIL": config(
        "SAP_FILE_UPLOADER_FOLDER_ID_JIVO_OIL",
        default="",
        cast=cast_optional_int,
    ),
    "JIVO_MART": config(
        "SAP_FILE_UPLOADER_FOLDER_ID_JIVO_MART",
        default="",
        cast=cast_optional_int,
    ),
    "JIVO_BEVERAGES": config(
        "SAP_FILE_UPLOADER_FOLDER_ID_JIVO_BEVERAGES",
        default="",
        cast=cast_optional_int,
    ),
}
SAP_FILE_UPLOADER_SOURCE_PATHS = {
    "JIVO_OIL": config("SAP_FILE_UPLOADER_SOURCE_PATH_JIVO_OIL", default=""),
    "JIVO_MART": config("SAP_FILE_UPLOADER_SOURCE_PATH_JIVO_MART", default=""),
    "JIVO_BEVERAGES": config(
        "SAP_FILE_UPLOADER_SOURCE_PATH_JIVO_BEVERAGES",
        default="",
    ),
}

# OMS invoice-approval proxy — the external OMS app (repos harshit-jivo/OMS-*)
# is where head-office billing raises AR invoices; the factory approver page
# (frontend under Warehouse) shows OMS entries by default, with the direct SAP
# approval drafts behind a toggle. We proxy so the browser uses our JWT +
# Company-Code auth and our own invoice_approval.* permissions. OMS_SIMULATE
# serves fixtures (no network) — mirrors MARKETPLACE_SIMULATE_SAP.
#
# The prod server cannot reach OMS's public IP/oms.jivo.in (no NAT hairpin) —
# server-to-server must use the internal LAN address: 20.20.45.75:8001 (OMS
# prod) / :8081 (OMS test). Leaving OMS_BASE_URL empty fails loudly with a
# config error rather than silently dialling an unreachable host.
#
# Auth (confirmed against OMS `test`): the invoice read endpoints have NO
# permission class, so GET all/ + history/ are open. BUT update-status
# (approve/reject) does InvocieHistory.objects.create(created_by=request.user),
# so a token-less PATCH hits AnonymousUser and 500s. => to enable approve/
# reject, set OMS_AUTH_ENABLED=True and OMS_USERNAME/OMS_PASSWORD to a real OMS
# service account (the approver identity OMS records). Reads work without it.
OMS_ENABLED = config("OMS_ENABLED", default=False, cast=cast_debug)
OMS_SIMULATE = config("OMS_SIMULATE", default=DEBUG, cast=cast_debug)
OMS_AUTH_ENABLED = config("OMS_AUTH_ENABLED", default=False, cast=cast_debug)
OMS_BASE_URL = config("OMS_BASE_URL", default="")
OMS_USERNAME = config("OMS_USERNAME", default="")
OMS_PASSWORD = config("OMS_PASSWORD", default="")
OMS_TIMEOUT_SECONDS = config("OMS_TIMEOUT_SECONDS", default=30, cast=int)
# Access token lives ~1 day on OMS; cache a bit under that. On the default
# per-process LocMemCache this is per-worker (fine at this scale); configure
# CACHES with the already-installed django-redis to share one token across workers.
OMS_TOKEN_TTL_SECONDS = config("OMS_TOKEN_TTL_SECONDS", default=82800, cast=int)

SALES_PLANNING_REQUIREMENT_REFRESH_DAY = config(
    "SALES_PLANNING_REQUIREMENT_REFRESH_DAY",
    default=1,
    cast=int,
)
SALES_PLANNING_REQUIREMENT_REFRESH_HOUR = config(
    "SALES_PLANNING_REQUIREMENT_REFRESH_HOUR",
    default=2,
    cast=int,
)
SALES_PLANNING_REQUIREMENT_REFRESH_MINUTE = config(
    "SALES_PLANNING_REQUIREMENT_REFRESH_MINUTE",
    default=30,
    cast=int,
)
SALES_PLANNING_REQUIREMENT_RUN_TIMEOUT_HOURS = config(
    "SALES_PLANNING_REQUIREMENT_RUN_TIMEOUT_HOURS",
    default=4,
    cast=int,
)

# Firebase Cloud Messaging
FCM_CREDENTIALS_PATH = config('FCM_CREDENTIALS_PATH', default='firebase-service-account.json')

# Stock Alert Scheduler
STOCK_ALERT_INTERVAL_MINUTES = config('STOCK_ALERT_INTERVAL_MINUTES', default=10, cast=int)
STOCK_ALERT_COOLDOWN_MINUTES = config('STOCK_ALERT_COOLDOWN_MINUTES', default=60, cast=int)

# APScheduler
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # seconds

# AI assistant
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-2.5-flash-lite')
GEMINI_FALLBACK_MODELS = config(
    'GEMINI_FALLBACK_MODELS',
    default='gemini-flash-lite-latest,gemini-2.0-flash-lite',
    cast=Csv(),
)
AI_ASSISTANT_TIMEOUT_SECONDS = config('AI_ASSISTANT_TIMEOUT_SECONDS', default=45, cast=int)
AI_ASSISTANT_MAX_CONTEXT_ROWS = config('AI_ASSISTANT_MAX_CONTEXT_ROWS', default=5, cast=int)
AI_ASSISTANT_SQL_DATABASE_ALIAS = config(
    'AI_ASSISTANT_SQL_DATABASE_ALIAS',
    default='ai_readonly' if AI_DB_NAME else 'default',
)
