"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
from corsheaders.defaults import default_headers


def cast_debug(value):
    normalized = str(value).strip().lower()
    if normalized in {'1', 'true', 'yes', 'on', 'debug'}:
        return True
    if normalized in {'0', 'false', 'no', 'off', 'release', 'prod', 'production'}:
        return False
    raise ValueError(f"Invalid DEBUG value: {value}")


def cast_optional_int(value):
    if value is None:
        return None
    normalized = str(value).strip()
    if not normalized:
        return None
    return int(normalized)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Core Settings
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=cast_debug)
DISPATCH_USE_LOCAL_GRPO_LINES_FOR_TESTING = config(
    'DISPATCH_USE_LOCAL_GRPO_LINES_FOR_TESTING',
    default=DEBUG,
    cast=cast_debug,
)
DISPATCH_LOCAL_GRPO_TEST_BRANCH_ID = config(
    'DISPATCH_LOCAL_GRPO_TEST_BRANCH_ID',
    default=2,
    cast=int,
)
DISPATCH_SIMULATE_AP_INVOICE_POSTING = config(
    'DISPATCH_SIMULATE_AP_INVOICE_POSTING',
    default=False,
    cast=cast_debug,
)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    # local apps
    'accounts',
    'company',
    'gate_core',
    'vehicle_management',
    'driver_management',
    'security_checks',
    'sap_client',
    'raw_material_gatein',
    'weighment',
    'quality_control',
    'daily_needs_gatein',
    'maintenance_gatein',
    'maintenance.apps.MaintenanceConfig',
    'construction_gatein',
    'person_gatein',
    'grpo',
    'notifications',
    'production_execution',
    'sap_plan_dashboard',
    'stock_dashboard',
    'inventory_age',
    'dispatch_plans',
    'django_apscheduler',
    'non_moving_rm',
    'sales_planning_requirement',
    'warehouse',
    'barcode',
    'ai_assistant',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
    }
}
AI_DB_NAME = config('AI_DB_NAME', default='')
if AI_DB_NAME:
    DATABASES['ai_readonly'] = {
        'ENGINE': config('AI_DB_ENGINE', default=config('DB_ENGINE', default='django.db.backends.postgresql')),
        'NAME': AI_DB_NAME,
        'USER': config('AI_DB_USER'),
        'PASSWORD': config('AI_DB_PASSWORD'),
        'HOST': config('AI_DB_HOST', default=config('DB_HOST')),
        'PORT': config('AI_DB_PORT', default=config('DB_PORT', default='5432')),
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Admin Panel Customization
ADMIN_SITE_HEADER = 'JI Admin'
ADMIN_SITE_TITLE = "JI"
ADMIN_INDEX_TITLE = "JI Factory Jivo Wellness Admin"

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload limits (15 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/day',
    #     'user': '1000/day',
    # }
}

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# Simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1500),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS settings
LOCAL_DEV_CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'http://localhost:5175',
    'http://127.0.0.1:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5176',
]
CORS_ALLOWED_ORIGINS = list(dict.fromkeys([
    *config('CORS_ALLOWED_ORIGINS', default='', cast=Csv()),
    *LOCAL_DEV_CORS_ALLOWED_ORIGINS,
]))
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ['Company-Code']

# SAP HANA and Service Layer settings
HANA_HOST = config('HANA_HOST')
HANA_PORT = config('HANA_PORT', cast=int)
HANA_USER = config('HANA_USER')
HANA_PASSWORD = config('HANA_PASSWORD')

SL_URL = config('SL_URL')
SL_USER = config('SL_USER')
SL_PASSWORD = config('SL_PASSWORD')

SAP_GATEPASS_CRYSTAL_REPORT_PATH = config(
    "SAP_GATEPASS_CRYSTAL_REPORT_PATH",
    default="",
)
SAP_GATEPASS_CRYSTAL_RENDERER_COMMAND = config(
    "SAP_GATEPASS_CRYSTAL_RENDERER_COMMAND",
    default="",
)
SAP_GATEPASS_CRYSTAL_RENDER_TIMEOUT_SECONDS = config(
    "SAP_GATEPASS_CRYSTAL_RENDER_TIMEOUT_SECONDS",
    default=120,
    cast=int,
)
SAP_GATEPASS_CRYSTAL_ENABLE_FALLBACK_PDF = config(
    "SAP_GATEPASS_CRYSTAL_ENABLE_FALLBACK_PDF",
    default=True,
    cast=cast_debug,
)
SAP_GATEPASS_CRYSTAL_OBJECT_IDS = {
    "INVOICE": config("SAP_GATEPASS_CRYSTAL_OBJECT_ID_INVOICE", default="13"),
    "STOCK_TRANSFER": config("SAP_GATEPASS_CRYSTAL_OBJECT_ID_STOCK_TRANSFER", default="67"),
}

COMPANY_DB = {
    "JIVO_OIL": config('COMPANY_DB_JIVO_OIL'),
    "JIVO_MART": config('COMPANY_DB_JIVO_MART'),
    "JIVO_BEVERAGES": config('COMPANY_DB_JIVO_BEVERAGES'),
}

SAP_ATTACHMENT_DIRECT_COPY_PATHS = {
    "JIVO_OIL": config("SAP_ATTACHMENT_DIRECT_COPY_PATH_JIVO_OIL", default=""),
    "JIVO_MART": config("SAP_ATTACHMENT_DIRECT_COPY_PATH_JIVO_MART", default=""),
    "JIVO_BEVERAGES": config(
        "SAP_ATTACHMENT_DIRECT_COPY_PATH_JIVO_BEVERAGES",
        default="",
    ),
}
SAP_ATTACHMENT_DIRECT_COPY_USERNAME = config(
    "SAP_ATTACHMENT_DIRECT_COPY_USERNAME",
    default="",
)
SAP_ATTACHMENT_DIRECT_COPY_PASSWORD = config(
    "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD",
    default="",
)
SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL = config(
    "SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL",
    default=SAP_ATTACHMENT_DIRECT_COPY_USERNAME,
)
SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL = config(
    "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL",
    default=SAP_ATTACHMENT_DIRECT_COPY_PASSWORD,
)
SAP_ATTACHMENT_DIRECT_COPY_CREDENTIALS = {
    "JIVO_OIL": {
        "username": SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL,
        "password": SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL,
    },
    "JIVO_MART": {
        "username": config(
            "SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_MART",
            default=SAP_ATTACHMENT_DIRECT_COPY_USERNAME,
        ),
        "password": config(
            "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_MART",
            default=SAP_ATTACHMENT_DIRECT_COPY_PASSWORD,
        ),
    },
    "JIVO_BEVERAGES": {
        "username": config(
            "SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_BEVERAGES",
            default=SAP_ATTACHMENT_DIRECT_COPY_USERNAME_JIVO_OIL,
        ),
        "password": config(
            "SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_BEVERAGES",
            default=SAP_ATTACHMENT_DIRECT_COPY_PASSWORD_JIVO_OIL,
        ),
    },
}

SAP_FILE_UPLOADER_ENABLED = config(
    "SAP_FILE_UPLOADER_ENABLED",
    default=False,
    cast=cast_debug,
)
SAP_FILE_UPLOADER_BASE_URL = config(
    "SAP_FILE_UPLOADER_BASE_URL",
    default="",
)
SAP_FILE_UPLOADER_API_KEY = config(
    "SAP_FILE_UPLOADER_API_KEY",
    default="",
)
SAP_FILE_UPLOADER_TIMEOUT_SECONDS = config(
    "SAP_FILE_UPLOADER_TIMEOUT_SECONDS",
    default=120,
    cast=int,
)
SAP_FILE_UPLOADER_FOLDER_IDS = {
    "JIVO_OIL": config(
        "SAP_FILE_UPLOADER_FOLDER_ID_JIVO_OIL",
        default="",
        cast=cast_optional_int,
    ),
    "JIVO_MART": config(
        "SAP_FILE_UPLOADER_FOLDER_ID_JIVO_MART",
        default="",
        cast=cast_optional_int,
    ),
    "JIVO_BEVERAGES": config(
        "SAP_FILE_UPLOADER_FOLDER_ID_JIVO_BEVERAGES",
        default="",
        cast=cast_optional_int,
    ),
}
SAP_FILE_UPLOADER_SOURCE_PATHS = {
    "JIVO_OIL": config("SAP_FILE_UPLOADER_SOURCE_PATH_JIVO_OIL", default=""),
    "JIVO_MART": config("SAP_FILE_UPLOADER_SOURCE_PATH_JIVO_MART", default=""),
    "JIVO_BEVERAGES": config(
        "SAP_FILE_UPLOADER_SOURCE_PATH_JIVO_BEVERAGES",
        default="",
    ),
}

SALES_PLANNING_REQUIREMENT_REFRESH_DAY = config(
    "SALES_PLANNING_REQUIREMENT_REFRESH_DAY",
    default=1,
    cast=int,
)
SALES_PLANNING_REQUIREMENT_REFRESH_HOUR = config(
    "SALES_PLANNING_REQUIREMENT_REFRESH_HOUR",
    default=2,
    cast=int,
)
SALES_PLANNING_REQUIREMENT_REFRESH_MINUTE = config(
    "SALES_PLANNING_REQUIREMENT_REFRESH_MINUTE",
    default=30,
    cast=int,
)
SALES_PLANNING_REQUIREMENT_RUN_TIMEOUT_HOURS = config(
    "SALES_PLANNING_REQUIREMENT_RUN_TIMEOUT_HOURS",
    default=4,
    cast=int,
)

# Firebase Cloud Messaging
FCM_CREDENTIALS_PATH = config('FCM_CREDENTIALS_PATH', default='firebase-service-account.json')

# Stock Alert Scheduler
STOCK_ALERT_INTERVAL_MINUTES = config('STOCK_ALERT_INTERVAL_MINUTES', default=10, cast=int)
STOCK_ALERT_COOLDOWN_MINUTES = config('STOCK_ALERT_COOLDOWN_MINUTES', default=60, cast=int)

# APScheduler
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # seconds

# AI assistant
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-2.5-flash-lite')
GEMINI_FALLBACK_MODELS = config(
    'GEMINI_FALLBACK_MODELS',
    default='gemini-flash-lite-latest,gemini-2.0-flash-lite',
    cast=Csv(),
)
AI_ASSISTANT_TIMEOUT_SECONDS = config('AI_ASSISTANT_TIMEOUT_SECONDS', default=45, cast=int)
AI_ASSISTANT_MAX_CONTEXT_ROWS = config('AI_ASSISTANT_MAX_CONTEXT_ROWS', default=5, cast=int)
AI_ASSISTANT_SQL_DATABASE_ALIAS = config(
    'AI_ASSISTANT_SQL_DATABASE_ALIAS',
    default='ai_readonly' if AI_DB_NAME else 'default',
)
