# Generated by Django 6.0.1 on 2026-09-01 06:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryExpensePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_factory_expense', 'Can view the Factory Expense board'), ('can_configure_factory_expense', 'Can configure the Factory Expense board')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactoryExpenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_labour', models.BooleanField(default=True)),
                ('show_salary', models.BooleanField(default=True)),
                ('show_electricity', models.BooleanField(default=True)),
                ('show_maintenance', models.BooleanField(default=True)),
                ('maintenance_include_spares', models.BooleanField(default=True, help_text='Count spares issued or consumed on work orders, at their unit cost.')),
                ('maintenance_include_indents', models.BooleanField(default=True, help_text='Count material indents once a company has been selected or the goods have moved.')),
                ('electricity_only_company_meters', models.BooleanField(default=True, help_text='Count only meters tagged with this company. Turn off to show every meter on the campus, including untagged ones.')),
                ('refresh_seconds', models.PositiveIntegerField(default=60, help_text='How often the board re-reads itself. Minimum 15 seconds.', validators=[django.core.validators.MinValueValidator(15)])),
                ('rotate_seconds', models.PositiveIntegerField(default=12, help_text='How long each panel of a rotating list holds before it scrolls.', validators=[django.core.validators.MinValueValidator(4)])),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_expense_settings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factory Expense Settings',
                'verbose_name_plural': 'Factory Expense Settings',
            },
        ),
        migrations.CreateModel(
            name='DepartmentSalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.DateField(help_text='Any date in the month; stored as the 1st.')),
                ('employee_count', models.PositiveIntegerField(default=0, help_text='Optional. Drives the cost-per-employee figure; 0 hides it.')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Total salary cost for this department for the whole month.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_department_salaries', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_department_salaries', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Salary',
                'verbose_name_plural': 'Department Salaries',
                'ordering': ['-month', 'department__name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'department', 'month'), name='uniq_department_salary_per_month')],
            },
        ),
        migrations.CreateModel(
            name='LabourRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shift', models.CharField(choices=[('ANY', 'Any shift'), ('DAY', 'Day'), ('NIGHT', 'Night')], default='ANY', help_text='ANY is the fallback; a DAY or NIGHT row overrides it for that shift.', max_length=6)),
                ('rate_per_person_per_day', models.DecimalField(decimal_places=2, help_text='What one labourer costs for one full shift.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_from', models.DateField(help_text='First work date this rate applies to. Earlier dates keep the older rate.')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_labour_rates', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Leave empty for the company-wide default rate.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factory_labour_rates', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Rate',
                'verbose_name_plural': 'Labour Rates',
                'ordering': ['company_id', '-effective_from', 'department_id', 'shift'],
                'constraints': [models.UniqueConstraint(fields=('company', 'department', 'shift', 'effective_from'), name='uniq_labour_rate_per_scope_date')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bucket', models.CharField(choices=[('LABOUR', 'Labour'), ('SALARY', 'Salary'), ('ELECTRICITY', 'Electricity'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('month', models.DateField(help_text='Any date in the month; stored as the 1st.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_expense_budgets', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Budget',
                'verbose_name_plural': 'Monthly Budgets',
                'ordering': ['-month', 'bucket'],
                'constraints': [models.UniqueConstraint(fields=('company', 'bucket', 'month'), name='uniq_expense_budget_per_bucket_month')],
            },
        ),
    ]
