# Generated by Django 6.0.1 on 2026-09-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_expense', '0003_carry_legacy_rates_into_cost_master'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentsalaryconfig',
            name='uniq_department_salary_per_month',
        ),
        migrations.RemoveConstraint(
            model_name='labourrateconfig',
            name='uniq_labour_rate_per_scope_date',
        ),
        migrations.RemoveField(
            model_name='labourrateconfig',
            name='company',
        ),
        migrations.RemoveField(
            model_name='labourrateconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labourrateconfig',
            name='department',
        ),
        migrations.RemoveField(
            model_name='labourrateconfig',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='DepartmentSalaryConfig',
        ),
        migrations.DeleteModel(
            name='LabourRateConfig',
        ),
    ]
