# Generated by Django 6.0.1 on 2026-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_expense', '0004_drop_legacy_rate_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryexpensesettings',
            name='labour_cost_type_code',
            field=models.SlugField(default='factory-labour', help_text='Cost Master type the labour tile prices head count with.', max_length=60),
        ),
        migrations.AddField(
            model_name='factoryexpensesettings',
            name='salary_cost_type_code',
            field=models.SlugField(default='factory-salary', help_text='Cost Master type the salary tile reads its monthly figures from.', max_length=60),
        ),
    ]
