# Generated by Django 6.0.1 on 2026-06-29 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('person_gatein', '0007_entrylog_actual_entry_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourGateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_date', models.DateField()),
                ('count_in', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_gate_entries', to='company.company')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_gate_entries', to='person_gatein.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Gate Entry',
                'verbose_name_plural': 'Labour Gate Entries',
                'ordering': ['-work_date', 'contractor_id'],
                'permissions': [('can_record_labour_in', 'Can record labour in'), ('can_record_labour_out', 'Can record labour out')],
            },
        ),
        migrations.CreateModel(
            name='LabourGateOutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_batches', to='labour_gate.labourgateentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Out Batch',
                'verbose_name_plural': 'Labour Out Batches',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='labourgateentry',
            index=models.Index(fields=['work_date'], name='labour_gate_work_da_9262a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labourgateentry',
            unique_together={('company', 'contractor', 'work_date')},
        ),
    ]
