# Generated by Django 6.0.1 on 2026-06-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        ('labour_gate', '0001_initial'),
        ('person_gatein', '0007_entrylog_actual_entry_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourgateentry',
            options={'ordering': ['-work_date', 'department_id', 'contractor_id'], 'permissions': [('can_record_labour_in', 'Can record labour in'), ('can_record_labour_out', 'Can record labour out')], 'verbose_name': 'Labour Gate Entry', 'verbose_name_plural': 'Labour Gate Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='labourgateentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='labourgateentry',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labour_gate_entries', to='accounts.department'),
        ),
        migrations.AlterUniqueTogether(
            name='labourgateentry',
            unique_together={('company', 'department', 'contractor', 'work_date')},
        ),
    ]
