# Generated by Django 6.0.1 on 2026-07-02 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('labour_gate', '0003_labourgateentry_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourGateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_IN', 'Recorded labour in'), ('UPDATE_IN', 'Updated labour-in count'), ('MARK_OUT', 'Marked labour out'), ('UNDO_OUT', 'Undid labour-out batch'), ('DELETE', 'Deleted entry'), ('RESTORE', 'Restored entry')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('old_value', models.IntegerField(blank=True, null=True)),
                ('new_value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_gate_audits', to='company.company')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='labour_gate.labourgateentry')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_gate_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Gate Audit',
                'verbose_name_plural': 'Labour Gate Audit',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entry', 'created_at'], name='labour_gate_entry_i_64bcd2_idx')],
            },
        ),
    ]
