# Generated by Django 6.0.1 on 2026-07-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour_gate', '0005_create_labour_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourgateentry',
            options={'ordering': ['-work_date', 'department_id', 'contractor_id'], 'permissions': [('can_record_labour_in', 'Can record labour in'), ('can_record_labour_out', 'Can record labour out'), ('can_allocate_labour_department', 'Can allocate labour to department')], 'verbose_name': 'Labour Gate Entry', 'verbose_name_plural': 'Labour Gate Entries'},
        ),
    ]
