# Generated by Django 6.0.1 on 2026-07-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        ('labour_gate', '0007_hod_allocate_permission'),
        ('person_gatein', '0007_entrylog_actual_entry_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourgateentry',
            options={'ordering': ['-work_date', 'shift', 'department_id', 'contractor_id'], 'permissions': [('can_record_labour_in', 'Can record labour in'), ('can_record_labour_out', 'Can record labour out'), ('can_allocate_labour_department', 'Can allocate labour to department')], 'verbose_name': 'Labour Gate Entry', 'verbose_name_plural': 'Labour Gate Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='labourgateentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='labourgateentry',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], default='DAY', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='labourgateentry',
            unique_together={('company', 'department', 'contractor', 'work_date', 'shift')},
        ),
    ]
