# Generated by Django 6.0.1 on 2026-09-26 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapAttachmentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('abs_entry', models.PositiveIntegerField(help_text="ATC1.AbsEntry — the document's AttachmentEntry.")),
                ('line', models.IntegerField(help_text='ATC1.Line — which file of that entry.')),
                ('file_name', models.CharField(blank=True, default='', max_length=300)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_attachment_downloads', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_sap_documents', 'Can browse SAP documents and their attachment lists'), ('can_download_sap_attachments', 'Can download SAP document attachments')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'abs_entry'], name='sap_documen_company_29d213_idx')],
            },
        ),
    ]
