# Generated by Django 6.0.1 on 2026-09-21 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True, help_text='What this board is for. Shown in the list and under the heading.')),
                ('mode', models.CharField(choices=[('WALL', 'Wall screen'), ('PAGE', 'In-app page')], default='WALL', max_length=10)),
                ('columns', models.PositiveSmallIntegerField(default=4)),
                ('rows', models.PositiveSmallIntegerField(default=3)),
                ('surface', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Dark or light. A property of the room the screen is in.', max_length=10)),
                ('density', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('roomy', 'Roomy')], default='normal', max_length=10)),
                ('accent', models.CharField(choices=[('warehouse', 'Warehouse'), ('dispatch', 'Dispatch'), ('transport', 'Transport'), ('purchase', 'Purchase'), ('store', 'Store'), ('production', 'Production'), ('shifting', 'Shifting')], default='warehouse', help_text='The hue a newly dropped card takes unless it is given its own.', max_length=20)),
                ('show_heading', models.BooleanField(default=True, help_text="Print the board's name across the top. Off for a wall that is only ever seen by people who know what they are looking at.")),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private to its author'), ('PUBLISHED', 'Published')], default='PRIVATE', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('in_carousel', models.BooleanField(default=False)),
                ('audience', models.ManyToManyField(blank=True, help_text="Groups this board is published to. Empty means the whole company -- still subject to each card's own feed right.", related_name='custom_boards', to='auth.group')),
                ('company', models.ForeignKey(help_text='The company whose figures this board reads.', on_delete=django.db.models.deletion.PROTECT, related_name='custom_boards', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_boards', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_boards_published', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.CharField(max_length=80)),
                ('column', models.PositiveSmallIntegerField()),
                ('row', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, help_text="Replaces the catalogue's name for this card on this board. For a board whose reader calls the same figure something else.", max_length=80)),
                ('accent', models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('dispatch', 'Dispatch'), ('transport', 'Transport'), ('purchase', 'Purchase'), ('store', 'Store'), ('production', 'Production'), ('shifting', 'Shifting')], help_text="Overrides the board's default hue for this card alone.", max_length=20)),
                ('options', models.JSONField(blank=True, default=dict, help_text="This card's own settings -- the window in days, which warehouse, and so on. Validated against the card's declared options.")),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='board_builder.customboard')),
            ],
            options={
                'ordering': ['row', 'column'],
            },
        ),
        migrations.AddIndex(
            model_name='customboard',
            index=models.Index(fields=['company', 'visibility'], name='board_build_company_20c1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='customboard',
            index=models.Index(fields=['owner'], name='board_build_owner_i_9fb632_idx'),
        ),
        migrations.AddConstraint(
            model_name='customboard',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='board_builder_unique_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='boardplacement',
            constraint=models.UniqueConstraint(fields=('board', 'row', 'column'), name='board_builder_one_card_per_cell'),
        ),
    ]
