from django.urls import path

from .views_bill_summary import (
    BillSummaryCancelAPI,
    BillSummaryDetailAPI,
    BillSummaryListCreateAPI,
    BillSummaryPickAPI,
    BillSummaryLookupAPI,
    BillSummaryStampAPI,
)

from .views import (
    DispatchBiltyGRPOOptionsAPI,
    DispatchBiltyGRPOPostingDetailAPI,
    DispatchBiltyGRPOPostingHistoryAPI,
    DispatchBiltyGRPOSummaryAPI,
    DispatchBiltyGRPOPreviewAPI,
    DispatchBiltyServiceGRPOPostAPI,
    DispatchPendingBiltyGRPOListAPI,
    OpenBiltyListAPI,
    TransporterAPInvoiceDetailAPI,
    TransporterAPInvoiceHistoryAPI,
    TransporterAPInvoicePostAPI,
    TransporterAPInvoicePreviewAPI,
    TransporterAPInvoiceSubmitAPI,
)

urlpatterns = [
    path("open-bilties/", OpenBiltyListAPI.as_view(), name="dispatch-open-bilties"),
    path(
        "bilty-grpo/pending/",
        DispatchPendingBiltyGRPOListAPI.as_view(),
        name="dispatch-bilty-grpo-pending",
    ),
    path(
        "bilty-grpo/options/",
        DispatchBiltyGRPOOptionsAPI.as_view(),
        name="dispatch-bilty-grpo-options",
    ),
    path(
        "bilty-grpo/preview/<int:dispatch_plan_id>/",
        DispatchBiltyGRPOPreviewAPI.as_view(),
        name="dispatch-bilty-grpo-preview",
    ),
    path(
        "bilty-grpo/post/",
        DispatchBiltyServiceGRPOPostAPI.as_view(),
        name="dispatch-bilty-grpo-post",
    ),
    path(
        "bilty-grpo/summary/",
        DispatchBiltyGRPOSummaryAPI.as_view(),
        name="dispatch-bilty-grpo-summary",
    ),
    path(
        "bilty-grpo/history/",
        DispatchBiltyGRPOPostingHistoryAPI.as_view(),
        name="dispatch-bilty-grpo-history",
    ),
    path(
        "bilty-grpo/<int:posting_id>/",
        DispatchBiltyGRPOPostingDetailAPI.as_view(),
        name="dispatch-bilty-grpo-detail",
    ),
    path(
        "transporter-invoices/preview/",
        TransporterAPInvoicePreviewAPI.as_view(),
        name="dispatch-transporter-invoice-preview",
    ),
    path(
        "transporter-invoices/submit/",
        TransporterAPInvoiceSubmitAPI.as_view(),
        name="dispatch-transporter-invoice-submit",
    ),
    path(
        "transporter-invoices/post-ap-invoice/",
        TransporterAPInvoicePostAPI.as_view(),
        name="dispatch-transporter-invoice-post",
    ),
    path(
        "transporter-invoices/<int:posting_id>/post-ap-invoice/",
        TransporterAPInvoicePostAPI.as_view(),
        name="dispatch-transporter-invoice-post-submitted",
    ),
    path(
        "transporter-invoices/history/",
        TransporterAPInvoiceHistoryAPI.as_view(),
        name="dispatch-transporter-invoice-history",
    ),
    path(
        "transporter-invoices/<int:posting_id>/",
        TransporterAPInvoiceDetailAPI.as_view(),
        name="dispatch-transporter-invoice-detail",
    ),

    # ------------------------------------------------------------------
    # Bill summary — the picking sheet the floor works from.
    # ------------------------------------------------------------------
    path(
        "bill-summaries/lookup/",
        BillSummaryLookupAPI.as_view(),
        name="bill-summary-lookup",
    ),
    path(
        "bill-summaries/",
        BillSummaryListCreateAPI.as_view(),
        name="bill-summary-list-create",
    ),
    path(
        "bill-summaries/<int:pk>/",
        BillSummaryDetailAPI.as_view(),
        name="bill-summary-detail",
    ),
    path(
        "bill-summaries/<int:pk>/pick/",
        BillSummaryPickAPI.as_view(),
        name="bill-summary-pick",
    ),
    path(
        "bill-summaries/<int:pk>/stamp-sap/",
        BillSummaryStampAPI.as_view(),
        name="bill-summary-stamp-sap",
    ),
    path(
        "bill-summaries/<int:pk>/cancel/",
        BillSummaryCancelAPI.as_view(),
        name="bill-summary-cancel",
    ),
]
