# Generated by Django 6.0.1 on 2026-10-06 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RM', 'Raw Material'), ('PM', 'Packing Material'), ('FG', 'Finished Goods')], max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_owners', to='company.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stock_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amounts_board_stock_owner',
                'permissions': [('can_view_amounts_board', 'Can view the Amounts board'), ('can_manage_stock_owners', 'Can set the RM / PM / FG owners on the Amounts board')],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('company', 'category'), name='amounts_board_one_owner_per_category')],
            },
        ),
    ]
