# Generated by Django 6.0.1 on 2026-09-01 08:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.SlugField(help_text='Stable identifier consumers resolve rates by, e.g. "labour-contract". Never reused for a different cost.', max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('default_basis', models.CharField(choices=[('PER_DAY', 'Per Day (fixed)'), ('PER_PERSON_DAY', 'Per Person per Day'), ('PER_HOUR', 'Per Hour'), ('PER_MONTH', 'Per Month'), ('PER_UNIT', 'Per Electricity Unit'), ('PER_CASE', 'Per Case'), ('PER_BOTTLE', 'Per Bottle'), ('PER_KG', 'Per Kg'), ('PER_LITRE', 'Per Litre'), ('FLAT', 'Flat Amount')], default='PER_DAY', help_text='Pre-selected basis when a rate is entered for this type.', max_length=20)),
                ('is_credit', models.BooleanField(default=False, help_text='True if this reduces cost (e.g. scrap recovery).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Type',
                'verbose_name_plural': 'Cost Types',
                'ordering': ['name'],
                'permissions': [('can_view_cost_master', 'Can view cost master'), ('can_manage_cost_master', 'Can manage cost master')],
            },
        ),
        migrations.CreateModel(
            name='CostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('FACTORY', 'Factory-wide'), ('COMPANY', 'Company-wide'), ('DEPARTMENT', 'Department-wide'), ('VALUE', 'Specific value')], max_length=15)),
                ('value_key', models.CharField(blank=True, default='', help_text='Identifier the rate is particular to, e.g. "machine:BM-01".', max_length=200)),
                ('basis', models.CharField(choices=[('PER_DAY', 'Per Day (fixed)'), ('PER_PERSON_DAY', 'Per Person per Day'), ('PER_HOUR', 'Per Hour'), ('PER_MONTH', 'Per Month'), ('PER_UNIT', 'Per Electricity Unit'), ('PER_CASE', 'Per Case'), ('PER_BOTTLE', 'Per Bottle'), ('PER_KG', 'Per Kg'), ('PER_LITRE', 'Per Litre'), ('FLAT', 'Flat Amount')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('effective_from', models.DateField(help_text='Applies on or after this date. To change a rate, add a row with a later date rather than editing this one.')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_master_rates', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_master_rates', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='cost_master.costtype')),
            ],
            options={
                'verbose_name': 'Cost Rate',
                'verbose_name_plural': 'Cost Rates',
                'ordering': ['cost_type_id', 'scope', '-effective_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope', 'FACTORY')), fields=('cost_type', 'effective_from'), name='uniq_active_factory_cost_rate_per_date'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope', 'COMPANY')), fields=('cost_type', 'company', 'effective_from'), name='uniq_active_company_cost_rate_per_date'), models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('is_active', True), ('scope', 'DEPARTMENT')), fields=('cost_type', 'department', 'effective_from'), name='uniq_active_department_cost_rate_per_date'), models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('is_active', True), ('scope', 'DEPARTMENT')), fields=('cost_type', 'company', 'department', 'effective_from'), name='uniq_active_company_department_cost_rate_per_date'), models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('is_active', True), ('scope', 'VALUE')), fields=('cost_type', 'value_key', 'effective_from'), name='uniq_active_value_cost_rate_per_date'), models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('is_active', True), ('scope', 'VALUE')), fields=('cost_type', 'company', 'value_key', 'effective_from'), name='uniq_active_company_value_cost_rate_per_date')],
            },
        ),
    ]
