# Generated by Django 6.0.1 on 2026-09-02 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        ('cost_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='costrate',
            index=models.Index(fields=['cost_type', 'company', 'effective_from'], name='idx_cost_rate_resolve'),
        ),
        migrations.AddIndex(
            model_name='costrate',
            index=models.Index(fields=['value_key'], name='idx_cost_rate_value_key'),
        ),
    ]
