# Generated by Django 6.0.1 on 2026-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDispatchPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_production_dispatch', 'Can view the Production & Dispatch (pallet) report')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
