# Generated by Django 6.0.1 on 2026-06-04 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0005_alter_sparemovement_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('work_type', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('BREAKDOWN', 'Breakdown'), ('GENERAL', 'General Maintenance'), ('PREVENTIVE', 'Preventive Maintenance'), ('INSPECTION', 'Inspection'), ('CALIBRATION', 'Calibration'), ('AMC_VENDOR', 'AMC / Vendor Visit'), ('PROJECT', 'Project / Improvement')], default='PREVENTIVE', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('next_due_date', models.DateField()),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('advance_days', models.PositiveSmallIntegerField(default=0)),
                ('auto_create_work_order', models.BooleanField(default=True)),
                ('checklist_required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_plans', to='maintenance.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_pm_plans_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_pm_plans', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preventive Maintenance Plan',
                'verbose_name_plural': 'Preventive Maintenance Plans',
                'ordering': ['next_due_date', 'plan_code'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenanceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_executions', to='maintenance.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_pm_executions', to='company.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_pm_executions_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_execution', to='maintenance.maintenanceworkorder')),
                ('pm_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='maintenance.preventivemaintenanceplan')),
            ],
            options={
                'verbose_name': 'Preventive Maintenance Execution',
                'verbose_name_plural': 'Preventive Maintenance Executions',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task', models.CharField(max_length=250)),
                ('input_type', models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('PASS_FAIL', 'Pass / Fail'), ('NUMBER', 'Number'), ('TEXT', 'Text')], default='CHECKBOX', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('expected_text', models.CharField(blank=True, default='', max_length=200)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('uom', models.CharField(blank=True, default='', max_length=30)),
                ('safety_critical', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_checklist_template_items', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('pm_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='maintenance.preventivemaintenanceplan')),
            ],
            options={
                'verbose_name': 'Maintenance Checklist Template Item',
                'verbose_name_plural': 'Maintenance Checklist Template Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task_snapshot', models.CharField(max_length=250)),
                ('input_type', models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('PASS_FAIL', 'Pass / Fail'), ('NUMBER', 'Number'), ('TEXT', 'Text')], max_length=20)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_ok', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_checklist_results', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='maintenance.maintenancechecklisttemplateitem')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='maintenance.preventivemaintenanceexecution')),
            ],
            options={
                'verbose_name': 'Maintenance Checklist Result',
                'verbose_name_plural': 'Maintenance Checklist Results',
                'ordering': ['template_item__sort_order', 'id'],
                'unique_together': {('execution', 'template_item')},
            },
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['company', 'next_due_date'], name='maintenance_company_78cfaf_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['asset', 'frequency'], name='maintenance_asset_i_f9d2bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preventivemaintenanceplan',
            unique_together={('company', 'plan_code')},
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceexecution',
            index=models.Index(fields=['company', 'status', 'due_date'], name='maintenance_company_507bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceexecution',
            index=models.Index(fields=['asset', 'due_date'], name='maintenance_asset_i_d6b68b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preventivemaintenanceexecution',
            unique_together={('company', 'pm_plan', 'due_date')},
        ),
        migrations.AddIndex(
            model_name='maintenancechecklisttemplateitem',
            index=models.Index(fields=['company', 'pm_plan', 'sort_order'], name='maintenance_company_de91c3_idx'),
        ),
    ]
