# Generated by Django 6.0.1 on 2026-06-30 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_preventive_maintenance_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.asset'),
        ),
    ]
