# Generated by Django 6.0.1 on 2026-07-01 09:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0007_alter_maintenanceworkorder_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_fire', 'Can view Maintenance fire store'), ('can_manage_fire', 'Can manage Maintenance fire store'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports')]},
        ),
        migrations.CreateModel(
            name='FireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Fire Category',
                'verbose_name_plural': 'Maintenance Fire Categories',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=100)),
                ('sap_item_code', models.CharField(blank=True, default='', max_length=100)),
                ('uom', models.CharField(default='NOS', max_length=30)),
                ('is_critical', models.BooleanField(default=False)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('storage_location', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fire_items', to='maintenance.firecategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fire_items', to='company.company')),
                ('compatible_assets', models.ManyToManyField(blank=True, related_name='compatible_fire_items', to='maintenance.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Fire Item',
                'verbose_name_plural': 'Maintenance Fire Items',
                'ordering': ['part_number', 'name'],
                'unique_together': {('company', 'part_number')},
            },
        ),
        migrations.CreateModel(
            name='FireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('ISSUED', 'Issued'), ('PARTIALLY_CONSUMED', 'Partially Consumed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('issued_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('consumed_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('returned_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('store_remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fire_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_fire_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fire_requests', to='maintenance.maintenanceworkorder')),
                ('fire_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='maintenance.maintenancefire')),
            ],
            options={
                'verbose_name': 'Maintenance Fire Request',
                'verbose_name_plural': 'Maintenance Fire Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FireMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt from Gate'), ('ISSUE', 'Issue to Work Order'), ('CONSUME', 'Consume on Work Order'), ('RETURN', 'Return Unused Spare'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fire_movements', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_fire_movements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fire_movements', to='maintenance.maintenanceworkorder')),
                ('fire_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='maintenance.firerequest')),
                ('fire_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='maintenance.maintenancefire')),
            ],
            options={
                'verbose_name': 'Maintenance Fire Movement',
                'verbose_name_plural': 'Maintenance Fire Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
