# Generated by Django 6.0.1 on 2026-07-01 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0008_alter_maintenancepermission_options_firecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_fire', 'Can view Maintenance fire store'), ('can_manage_fire', 'Can manage Maintenance fire store'), ('can_view_fire_report', 'Can view Fire shift reports'), ('can_manage_fire_report', 'Can manage Fire shift reports'), ('can_review_fire_report', 'Can review Fire shift reports'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports')]},
        ),
        migrations.CreateModel(
            name='FireShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], default='DAY', max_length=10)),
                ('area', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='SUBMITTED', max_length=20)),
                ('summary_remarks', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fire_reports', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_fire_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_fire_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fire Shift Report',
                'verbose_name_plural': 'Fire Shift Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FireShiftReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('PUMP', 'Pump'), ('HYDRANT', 'Hydrant'), ('EXTINGUISHER', 'Extinguisher'), ('SPRINKLER', 'Sprinkler'), ('ALARM_PANEL', 'Alarm / Panel'), ('HOSE', 'Hose / Reel'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not Okay'), ('NEEDS_ATTENTION', 'Needs Attention')], default='OK', max_length=20)),
                ('reading', models.CharField(blank=True, default='', max_length=120)),
                ('remarks', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_report_items', to='maintenance.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fire_report_items', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.fireshiftreport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fire Shift Report Item',
                'verbose_name_plural': 'Fire Shift Report Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FireShiftReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.FileField(upload_to='maintenance/fire-reports/photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('taken_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.fireshiftreportitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fire Shift Report Photo',
                'verbose_name_plural': 'Fire Shift Report Photos',
                'ordering': ['-taken_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fireshiftreport',
            index=models.Index(fields=['company', 'report_date', 'shift'], name='maintenance_company_1930e3_idx'),
        ),
        migrations.AddIndex(
            model_name='fireshiftreport',
            index=models.Index(fields=['company', 'status'], name='maintenance_company_c31534_idx'),
        ),
    ]
