# Generated by Django 6.0.1 on 2026-07-01 12:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0010_fireshiftreportattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_fire', 'Can view Maintenance fire store'), ('can_manage_fire', 'Can manage Maintenance fire store'), ('can_view_fire_report', 'Can view Fire shift reports'), ('can_manage_fire_report', 'Can manage Fire shift reports'), ('can_review_fire_report', 'Can review Fire shift reports'), ('can_view_fire_issue', 'Can view Fire equipment issue register'), ('can_manage_fire_issue', 'Can manage Fire equipment issue register'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports')]},
        ),
        migrations.CreateModel(
            name='FireEquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_to_name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('contact', models.CharField(blank=True, default='', max_length=50)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('RETURNED', 'Returned')], default='ISSUED', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fire_issues', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_fire_issues', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fire Equipment Issue',
                'verbose_name_plural': 'Fire Equipment Issues',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FireEquipmentIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_name', models.CharField(max_length=200)),
                ('quantity_issued', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('quantity_returned', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('return_condition', models.CharField(choices=[('OK', 'OK'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='OK', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fire_issue_items', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fire_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_lines', to='maintenance.maintenancefire')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.fireequipmentissue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fire Equipment Issue Item',
                'verbose_name_plural': 'Fire Equipment Issue Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='fireequipmentissue',
            index=models.Index(fields=['company', 'status'], name='maintenance_company_6fec49_idx'),
        ),
        migrations.AddIndex(
            model_name='fireequipmentissue',
            index=models.Index(fields=['company', 'issued_at'], name='maintenance_company_282cf2_idx'),
        ),
    ]
