# Generated by Django 6.0.1 on 2026-07-04 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0012_asset_workorder_department_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_fire', 'Can view Maintenance fire store'), ('can_manage_fire', 'Can manage Maintenance fire store'), ('can_view_fire_report', 'Can view Fire shift reports'), ('can_manage_fire_report', 'Can manage Fire shift reports'), ('can_review_fire_report', 'Can review Fire shift reports'), ('can_view_fire_issue', 'Can view Fire equipment issue register'), ('can_manage_fire_issue', 'Can manage Fire equipment issue register'), ('can_view_work_permit', 'Can view Work permits'), ('can_manage_work_permit', 'Can manage Work permits'), ('can_issue_work_permit', 'Can issue Work permits'), ('can_approve_work_permit', 'Can approve Work permits'), ('can_accept_work_permit', 'Can accept Work permits'), ('can_close_work_permit', 'Can close Work permits'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports')]},
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_no', models.CharField(blank=True, default='', max_length=40)),
                ('permit_types', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('APPROVED', 'Approved'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('valid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('issuing_dept', models.CharField(blank=True, default='', max_length=150)),
                ('issuer_name', models.CharField(blank=True, default='', max_length=200)),
                ('issuer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('issued_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('issued_to_phone', models.CharField(blank=True, default='', max_length=50)),
                ('cross_ref', models.CharField(blank=True, default='', max_length=150)),
                ('job_location', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('hazards_identified', models.JSONField(blank=True, default=list)),
                ('control_measures', models.TextField(blank=True, default='')),
                ('electrical_isolation_required', models.BooleanField(default=False)),
                ('electrical_isolation_detail', models.CharField(blank=True, default='', max_length=300)),
                ('service_isolation_required', models.BooleanField(default=False)),
                ('service_isolation_detail', models.CharField(blank=True, default='', max_length=300)),
                ('process_isolation_required', models.BooleanField(default=False)),
                ('process_isolation_detail', models.CharField(blank=True, default='', max_length=300)),
                ('ppe', models.JSONField(blank=True, default=list)),
                ('precautions', models.JSONField(blank=True, default=list)),
                ('modification_authorization_required', models.BooleanField(default=False)),
                ('fire_watcher_name', models.CharField(blank=True, default='', max_length=200)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('contractor_company', models.CharField(blank=True, default='', max_length=200)),
                ('service_energization', models.BooleanField(default=False)),
                ('process_energization', models.BooleanField(default=False)),
                ('electrical_energization', models.BooleanField(default=False)),
                ('completion_type', models.CharField(blank=True, choices=[('ABANDONED', 'Abandoned'), ('VERIFIED', 'Verified Closure')], default='', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_time', models.DateTimeField(blank=True, null=True)),
                ('handover_by', models.CharField(blank=True, default='', max_length=200)),
                ('handover_to', models.CharField(blank=True, default='', max_length=200)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_permits_accepted', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_permits', to='company.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_permits_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Permit',
                'verbose_name_plural': 'Work Permits',
                'ordering': ['-valid_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPermitApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('ISSUER', 'Issuer'), ('AREA_INCHARGE', 'Area Incharge'), ('SAFETY_COORDINATOR', 'Safety Co-ordinator'), ('FACTORY_MANAGER', 'Factory / Plant Manager')], max_length=30)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_permit_approvals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='maintenance.workpermit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Permit Approval',
                'verbose_name_plural': 'Work Permit Approvals',
                'ordering': ['approved_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkPermitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='maintenance/work-permits/attachments/')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.workpermit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Permit Attachment',
                'verbose_name_plural': 'Work Permit Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPermitWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=150)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='maintenance.workpermit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Permit Worker',
                'verbose_name_plural': 'Work Permit Workers',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='workpermit',
            index=models.Index(fields=['company', 'status'], name='maintenance_company_612e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='workpermit',
            index=models.Index(fields=['company', 'valid_date'], name='maintenance_company_582d34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workpermitapproval',
            unique_together={('permit', 'role')},
        ),
    ]
