# Generated by Django 6.0.1 on 2026-07-07 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_alter_maintenancepermission_options_workpermit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_permits_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='maintenance.workpermit'),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_permits_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_permits_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='workpermitapproval',
            name='role',
            field=models.CharField(choices=[('FIRE_DEPARTMENT_HEAD', 'Fire Department Head'), ('ISSUER', 'Issuer'), ('AREA_INCHARGE', 'Area Incharge'), ('SAFETY_COORDINATOR', 'Safety Co-ordinator'), ('FACTORY_MANAGER', 'Factory / Plant Manager')], max_length=30),
        ),
    ]
