# Generated by Django 6.0.1 on 2026-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_maintenancepermission_options_safetyfine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
