# Generated by Django 6.0.1 on 2026-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_alter_maintenancepermission_options_materialindent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialindentitem',
            name='expected_date',
        ),
        migrations.AddField(
            model_name='materialindentitem',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
    ]
