# Generated by Django 6.0.1 on 2026-07-16 10:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_remove_materialindentitem_expected_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_fire', 'Can view Maintenance fire store'), ('can_manage_fire', 'Can manage Maintenance fire store'), ('can_view_fire_report', 'Can view Fire shift reports'), ('can_manage_fire_report', 'Can manage Fire shift reports'), ('can_review_fire_report', 'Can review Fire shift reports'), ('can_view_fire_issue', 'Can view Fire equipment issue register'), ('can_manage_fire_issue', 'Can manage Fire equipment issue register'), ('can_view_safety_fine', 'Can view Safety fines'), ('can_manage_safety_fine', 'Can manage Safety fines'), ('can_view_material_indent', 'Can view Material indents'), ('can_manage_material_indent', 'Can raise Material indents'), ('can_review_material_indent', 'Can review/issue Material indents (store)'), ('can_approve_material_indent', 'Can approve Material indent purchases'), ('can_purchase_material_indent', 'Can purchase Material indents'), ('can_view_work_permit', 'Can view Work permits'), ('can_manage_work_permit', 'Can manage Work permits'), ('can_issue_work_permit', 'Can issue Work permits'), ('can_approve_work_permit', 'Can approve Work permits'), ('can_accept_work_permit', 'Can accept Work permits'), ('can_close_work_permit', 'Can close Work permits'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports')]},
        ),
        migrations.AddField(
            model_name='materialindent',
            name='purchase_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_material_indents_purchased', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_material_indents_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='store_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialindentitem',
            name='issued_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='materialindent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Store'), ('ISSUED', 'Issued from Store'), ('PENDING_APPROVAL', 'Pending Purchase Approval'), ('APPROVED', 'Approved for Purchase'), ('PURCHASED', 'Purchased'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
