# Generated by Django 6.0.1 on 2026-08-01 06:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_alter_maintenancepermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialindent',
            name='quotation_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='quotation_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='quotation_selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_material_indents_quotation_selected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='quotations_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialindent',
            name='quotations_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_material_indents_quoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialindent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Store'), ('ISSUED', 'Issued from Store'), ('PENDING_APPROVAL', 'Pending Purchase Approval'), ('APPROVED', 'Approved for Purchase'), ('PENDING_QUOTATION_SELECTION', 'Pending Company Selection'), ('QUOTATION_SELECTED', 'Company Selected'), ('PURCHASED', 'Purchased'), ('GATE_IN', 'Arrived at Gate'), ('RECEIVED', 'Received into Store'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='materialindentattachment',
            name='doc_type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('BILL', 'Bill'), ('QUOTATION', 'Quotation'), ('OTHER', 'Other')], default='INVOICE', max_length=20),
        ),
        migrations.CreateModel(
            name='MaterialIndentQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact_no', models.CharField(blank=True, default='', max_length=50)),
                ('gstin', models.CharField(blank=True, default='', max_length=20)),
                ('quotation_no', models.CharField(blank=True, default='', max_length=60)),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=200)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='maintenance.materialindent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Indent Quotation',
                'verbose_name_plural': 'Material Indent Quotations',
                'ordering': ['company_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='materialindent',
            name='selected_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_indents', to='maintenance.materialindentquotation'),
        ),
        migrations.AddField(
            model_name='materialindentattachment',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.materialindentquotation'),
        ),
        migrations.CreateModel(
            name='MaterialIndentQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='maintenance.materialindentitem')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='maintenance.materialindentquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Indent Quotation Line',
                'verbose_name_plural': 'Material Indent Quotation Lines',
                'ordering': ['item__line_num', 'id'],
                'constraints': [models.UniqueConstraint(fields=('quotation', 'item'), name='uniq_quotation_line_per_item')],
            },
        ),
    ]
