# Generated by Django 6.0.1 on 2026-08-03 06:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_alter_maintenancepermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_fire', 'Can view Maintenance fire store'), ('can_manage_fire', 'Can manage Maintenance fire store'), ('can_view_fire_report', 'Can view Fire shift reports'), ('can_manage_fire_report', 'Can manage Fire shift reports'), ('can_review_fire_report', 'Can review Fire shift reports'), ('can_view_fire_issue', 'Can view Fire equipment issue register'), ('can_manage_fire_issue', 'Can manage Fire equipment issue register'), ('can_view_safety_fine', 'Can view Safety fines'), ('can_manage_safety_fine', 'Can manage Safety fines'), ('can_view_material_indent', 'Can view Material indents'), ('can_manage_material_indent', 'Can raise Material indents'), ('can_review_material_indent', 'Can review/issue Material indents (store)'), ('can_approve_material_indent', 'Can approve Material indent purchases'), ('can_purchase_material_indent', 'Can purchase Material indents'), ('can_gatein_material_indent', 'Can gate-in purchased Material indents'), ('can_receive_material_indent', 'Can receive Material indents into store stock'), ('can_view_work_permit', 'Can view Work permits'), ('can_manage_work_permit', 'Can manage Work permits'), ('can_issue_work_permit', 'Can issue Work permits'), ('can_approve_work_permit', 'Can approve Work permits'), ('can_accept_work_permit', 'Can accept Work permits'), ('can_close_work_permit', 'Can close Work permits'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports'), ('can_view_daily_electricity', 'Can view Daily electricity register'), ('can_manage_daily_electricity', 'Can manage Daily electricity register'), ('can_view_daily_wastage', 'Can view Daily wastage register'), ('can_manage_daily_wastage', 'Can manage Daily wastage register')]},
        ),
        migrations.CreateModel(
            name='DailyWastageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('material_name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='maintenance/daily-wastage/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Wastage Log',
                'verbose_name_plural': 'Daily Wastage Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('meter_number', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Default rate per unit used to cost new readings', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electricity Meter',
                'verbose_name_plural': 'Electricity Meters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('opening_reading', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_reading', models.DecimalField(decimal_places=2, max_digits=14)),
                ('units_consumed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_readings', to='maintenance.electricitymeter')),
            ],
            options={
                'verbose_name': 'Daily Electricity Reading',
                'verbose_name_plural': 'Daily Electricity Readings',
                'ordering': ['-date', 'meter__name'],
                'constraints': [models.UniqueConstraint(fields=('meter', 'date'), name='uniq_meter_reading_per_day')],
            },
        ),
    ]
