# Generated by Django 6.0.1 on 2026-08-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_alter_maintenancepermission_options_dailywastagelog_and_more'),
        ('maintenance', '0021_materialindent_quotation_remarks_and_more'),
    ]

    operations = [
    ]
