# Generated by Django 6.0.1 on 2026-08-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0023_alter_maintenancepermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitymeter',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this meter serves. Pick more than one for a meter shared between companies; leave empty if it is not attributed to any.', related_name='electricity_meters', to='company.company'),
        ),
    ]
