# Generated by Django 6.0.1 on 2026-08-24 09:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_electricitymeter_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyelectricityreading',
            name='multiplying_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='multiplying_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text="Grid multiplying factor (MF). The meter dial under-reads, so the day's dial difference is multiplied by this to get the billed units. 1 means the dial is read as-is.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
