# Generated by Django 6.0.1 on 2026-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_dailyelectricityreading_multiplying_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='asset_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
