# Generated by Django 6.0.1 on 2026-08-26 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_maintenanceworkorder_asset_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='assigned_to_text',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='rework_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_SPARE', 'Waiting Spare'), ('WAITING_VENDOR', 'Waiting Vendor'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('STATUS', 'Status Changed'), ('COMPLETED', 'Completed'), ('SENT_BACK', 'Sent Back'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_SPARE', 'Waiting Spare'), ('WAITING_VENDOR', 'Waiting Vendor'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Work Order Log',
                'verbose_name_plural': 'Maintenance Work Order Logs',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
