# Generated by Django 6.0.1 on 2026-09-02 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0027_maintenanceworkorder_assigned_to_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='maintenance/work-orders/attachments/')),
                ('doc_type', models.CharField(choices=[('COMPLAINT', 'Complaint / Fault Note'), ('QUOTATION', 'Quotation'), ('SERVICE_REPORT', 'Service Report'), ('INVOICE', 'Invoice / Bill'), ('DRAWING', 'Drawing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Work Order Attachment',
                'verbose_name_plural': 'Maintenance Work Order Attachments',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['work_order'], name='maintenance_work_or_136c2d_idx')],
            },
        ),
    ]
