# Generated by Django 6.0.1 on 2026-09-21 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0031_electricitymeter_supply_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='maintenance.electricitymeter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_electricity_meters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'electricity meter manager',
                'verbose_name_plural': 'electricity meter managers',
                'db_table': 'maintenance_user_electricity_meter',
                'ordering': ['meter__name', 'user__full_name'],
                'permissions': [('can_manage_user_electricity_meters', 'Can assign users as electricity meter managers')],
                'indexes': [models.Index(fields=['meter', 'is_active'], name='maintenance_meter_i_1284b4_idx'), models.Index(fields=['user', 'is_active'], name='maintenance_user_id_1fa9fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'meter'), name='uniq_user_electricity_meter')],
            },
        ),
    ]
