# Generated by Django 6.0.1 on 2026-09-22 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SIDLE = {"code": "SIDLE", "name": "Sidle"}


def add_sidle(apps, schema_editor):
    """The one non-company consumer the register needs on day one.

    Seeded here rather than left to somebody's admin session: the picker is
    shipping with Sidle in it, and a code the UI offers but the database does
    not hold is a save that fails for no reason the operator can see.
    """
    Consumer = apps.get_model("maintenance", "ElectricityConsumer")
    Consumer.objects.get_or_create(code=SIDLE["code"], defaults={"name": SIDLE["name"]})


def drop_sidle(apps, schema_editor):
    Consumer = apps.get_model("maintenance", "ElectricityConsumer")
    Consumer.objects.filter(code=SIDLE["code"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0032_userelectricitymeter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyelectricityreading',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text="Companies this day's units are attributed to. Filled from the meter when the reading is added; leave empty on an old reading to fall back to the meter.", related_name='daily_electricity_readings', to='company.company'),
        ),
        migrations.AddField(
            model_name='dailyelectricityreading',
            name='reading_time',
            field=models.TimeField(blank=True, help_text='Clock time the meter was read. Defaults to now when a reading is added; blank on readings entered before this was recorded.', null=True),
        ),
        migrations.CreateModel(
            name='ElectricityConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electricity Consumer (non-company)',
                'verbose_name_plural': 'Electricity Consumers (non-company)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dailyelectricityreading',
            name='consumers',
            field=models.ManyToManyField(blank=True, help_text="Non-company consumers (Sidle) this day's units are attributed to.", related_name='daily_electricity_readings', to='maintenance.electricityconsumer'),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='consumers',
            field=models.ManyToManyField(blank=True, help_text='Non-company consumers this meter also feeds (Sidle). Chosen alongside the companies above — a meter shared with one carries both.', related_name='electricity_meters', to='maintenance.electricityconsumer'),
        ),
        migrations.RunPython(add_sidle, drop_sidle),
    ]
