# Generated by Django 6.0.1 on 2026-09-24 10:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowing', '0019_blowingcostrate_effective_from'),
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0033_electricity_reading_attribution_and_time'),
        ('production_execution', '0045_filling_cost_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_fire', 'Can view Maintenance fire store'), ('can_manage_fire', 'Can manage Maintenance fire store'), ('can_view_fire_report', 'Can view Fire shift reports'), ('can_manage_fire_report', 'Can manage Fire shift reports'), ('can_review_fire_report', 'Can review Fire shift reports'), ('can_view_fire_issue', 'Can view Fire equipment issue register'), ('can_manage_fire_issue', 'Can manage Fire equipment issue register'), ('can_view_safety_fine', 'Can view Safety fines'), ('can_manage_safety_fine', 'Can manage Safety fines'), ('can_view_material_indent', 'Can view Material indents'), ('can_manage_material_indent', 'Can raise Material indents'), ('can_draft_material_indent', 'Can create Material indent drafts (cannot send for approval)'), ('can_submit_material_indent', 'Can send Material indents for approval'), ('can_review_material_indent', 'Can review/issue Material indents (store)'), ('can_approve_material_indent', 'Can approve Material indent purchases'), ('can_purchase_material_indent', 'Can purchase Material indents'), ('can_gatein_material_indent', 'Can gate-in purchased Material indents'), ('can_receive_material_indent', 'Can receive Material indents into store stock'), ('can_view_work_permit', 'Can view Work permits'), ('can_manage_work_permit', 'Can manage Work permits'), ('can_issue_work_permit', 'Can issue Work permits'), ('can_approve_work_permit', 'Can approve Work permits'), ('can_accept_work_permit', 'Can accept Work permits'), ('can_close_work_permit', 'Can close Work permits'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports'), ('can_view_daily_electricity', 'Can view Daily electricity register'), ('can_manage_daily_electricity', 'Can manage Daily electricity register'), ('can_view_electricity_meter', 'Can view Electricity meter master'), ('can_manage_electricity_meter', 'Can manage Electricity meter master'), ('can_add_daily_electricity', 'Can record Daily electricity readings'), ('can_edit_daily_electricity', 'Can correct Daily electricity readings'), ('can_delete_daily_electricity', 'Can delete Daily electricity readings'), ('can_manage_electricity_allocation', 'Can set who pays for each electricity meter'), ('can_view_daily_wastage', 'Can view Daily wastage register'), ('can_manage_daily_wastage', 'Can manage Daily wastage register')]},
        ),
        migrations.AddField(
            model_name='dailyelectricityreading',
            name='meter_reset',
            field=models.BooleanField(default=False, help_text='The meter was replaced or its dial reset, so this opening does not follow on from the previous closing.'),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='register_of',
            field=models.ForeignKey(blank=True, help_text='Daily Electricity++: set when this is a second register of another meter — KVAH on the KWH meter. The meter tree shows it beside that meter and never counts it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='maintenance.electricitymeter'),
        ),
        migrations.CreateModel(
            name='ElectricityMeterSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('in_service', models.BooleanField(default=True, help_text='Off from this date: the meter is out of the tree (removed or disconnected).')),
                ('basis', models.CharField(choices=[('UNASSIGNED', 'Not decided yet'), ('FIXED', 'Fixed shares'), ('RUN_HOURS', 'By production run hours'), ('METER_RATIO', 'In proportion to other meters')], default='UNASSIGNED', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Why this version exists — what changed on the floor, or what was corrected.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='maintenance.electricitymeter')),
                ('parent', models.ForeignKey(blank=True, help_text='The meter this one is a sub-meter of. Empty for a main meter.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_setups', to='maintenance.electricitymeter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electricity Meter Setup',
                'verbose_name_plural': 'Electricity Meter Setups',
                'ordering': ['meter__name', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityMeterDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('blowing_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blowing.blowingmachine')),
                ('company', models.ForeignKey(blank=True, help_text='Who a followed meter stands for. Lines and machines carry their own company.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.company')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driven_setups', to='maintenance.electricitymeter')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production_execution.productionline')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='maintenance.electricitymetersetup')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityMeterShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.company')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maintenance.electricityconsumer')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='maintenance.electricitymetersetup')),
            ],
            options={
                'ordering': ['-percent', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='electricitymetersetup',
            constraint=models.UniqueConstraint(fields=('meter', 'effective_from'), name='uniq_electricity_meter_setup_per_day'),
        ),
        migrations.AddConstraint(
            model_name='electricitymeterdriver',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('blowing_machine__isnull', True), ('meter__isnull', True), ('production_line__isnull', False)), models.Q(('blowing_machine__isnull', False), ('meter__isnull', True), ('production_line__isnull', True)), models.Q(('blowing_machine__isnull', True), ('company__isnull', False), ('meter__isnull', False), ('production_line__isnull', True)), _connector='OR'), name='electricity_driver_names_one_source'),
        ),
        migrations.AddConstraint(
            model_name='electricitymetershare',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', False), ('consumer__isnull', True)), models.Q(('company__isnull', True), ('consumer__isnull', False)), _connector='OR'), name='electricity_share_names_one_party'),
        ),
        migrations.AddConstraint(
            model_name='electricitymetershare',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('setup', 'company'), name='uniq_electricity_share_company'),
        ),
        migrations.AddConstraint(
            model_name='electricitymetershare',
            constraint=models.UniqueConstraint(condition=models.Q(('consumer__isnull', False)), fields=('setup', 'consumer'), name='uniq_electricity_share_consumer'),
        ),
    ]
