# Generated by Django 6.0.1 on 2026-09-29 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0034_electricity_meter_tree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyelectricityreading',
            options={'ordering': ['-date', '-shift', 'meter__name'], 'verbose_name': 'Daily Electricity Reading', 'verbose_name_plural': 'Daily Electricity Readings'},
        ),
        migrations.RemoveConstraint(
            model_name='dailyelectricityreading',
            name='uniq_meter_reading_per_day',
        ),
        migrations.AddField(
            model_name='dailyelectricityreading',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], default='DAY', help_text="The day or night round. The night opens on the day's closing.", max_length=5),
        ),
        migrations.AddConstraint(
            model_name='dailyelectricityreading',
            constraint=models.UniqueConstraint(fields=('meter', 'date', 'shift'), name='uniq_meter_reading_per_shift'),
        ),
    ]
