# Generated by Django 6.0.1 on 2026-09-09 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Employee Hierarchy & Salary',
                'verbose_name_plural': 'Employee Hierarchy & Salary',
                'permissions': [('can_view_employees', 'Can view employees and the org chart'), ('can_manage_employees', 'Can add and edit employees, and move them in the tree'), ('can_manage_org_structure', 'Can maintain departments and designations'), ('can_view_workforce_reports', 'Can view headcount and org reports'), ('can_view_employee_audit', 'Can view the employee audit trail'), ('can_view_own_salary', 'Can view their own salary'), ('can_view_subordinate_salary', 'Can view the salary of anyone below them'), ('can_view_department_salary', 'Can view salaries within their department'), ('can_view_all_salaries', "Can view every employee's salary"), ('can_view_salary_history', 'Can view past salary records, not just the current one'), ('can_create_salary', 'Can create a salary record'), ('can_update_salary', 'Can draft a salary revision'), ('can_approve_salary_revision', 'Can approve a salary revision')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Short handle used in search and filters, e.g. 'ENG'.", max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Position among its siblings on the department tree.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_departments', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The department this one sits inside. Blank for a top-level department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='employee_hierarchy.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Short handle, e.g. 'SR_DEV'.", max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.PositiveSmallIntegerField(default=5, help_text='Organisational level: 1 is the top of the ladder (CEO), higher is lower down.')),
                ('is_managerial', models.BooleanField(default=False, help_text="Whether this rung is expected to manage people. Seeds the employee's manager flag.")),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_designations', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(help_text="The code people quote, e.g. 'EMP001'.", max_length=40)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('full_name', models.CharField(blank=True, help_text='Rebuilt from first / last on save. Do not set it directly.', max_length=201)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Profile photo. The org chart falls back to initials without one.', null=True, upload_to='employees/photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('exit_date', models.DateField(blank=True, help_text='Last working day. Set when the status becomes an exit; drives turnover reporting.', null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('job_title', models.CharField(blank=True, default='', help_text='What the business card says. The designation is the grade; this is the job.', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('hierarchy_level', models.PositiveSmallIntegerField(default=1, help_text='Reporting hops from the top, 1 for a top-level employee. Derived.')),
                ('hierarchy_path', models.CharField(blank=True, db_index=True, help_text="Materialised path of ids ending in their own, e.g. '/1/4/9/'. Derived.", max_length=512)),
                ('is_manager', models.BooleanField(default=False, help_text='Whether this person is expected to manage people.')),
                ('current_salary_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Cache of the active salary record's total. Never the source of truth.", max_digits=14, null=True)),
                ('current_salary_currency', models.CharField(blank=True, default='INR', max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee_hierarchy.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee_hierarchy.designation')),
                ('reporting_manager', models.ForeignKey(blank=True, help_text='The one manager. Blank for a top-level employee such as the CEO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='employee_hierarchy.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='The app login this employee is. Required for them to see their own salary.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['hierarchy_level', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Who runs the department. Blank until somebody is named.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_departments', to='employee_hierarchy.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee details updated'), ('MANAGER_CHANGED', 'Reporting manager changed'), ('MANAGER_REMOVED', 'Reporting manager removed'), ('SUBTREE_MOVED', 'Team moved under a new manager'), ('DEPARTMENT_CHANGED', 'Department changed'), ('DESIGNATION_CHANGED', 'Designation changed'), ('PROMOTED', 'Promoted'), ('STATUS_CHANGED', 'Employment status changed'), ('SALARY_CREATED', 'Salary record created'), ('SALARY_APPROVED', 'Salary revision approved'), ('SALARY_REJECTED', 'Salary revision rejected'), ('SALARY_VIEWED', 'Salary information viewed')], db_index=True, max_length=30)),
                ('field', models.CharField(blank=True, default='', help_text="Which attribute moved, e.g. 'reporting_manager'.", max_length=60)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='employee_hierarchy.employee')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee audit entry',
                'verbose_name_plural': 'Employee audit trail',
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('JOINED', 'Joined'), ('MANAGER_CHANGED', 'Reporting manager changed'), ('MANAGER_REMOVED', 'Reporting manager removed'), ('DEPARTMENT_CHANGED', 'Moved department'), ('DESIGNATION_CHANGED', 'Designation changed'), ('PROMOTED', 'Promoted'), ('LEVEL_CHANGED', 'Hierarchy level changed'), ('LOCATION_CHANGED', 'Location changed'), ('SALARY_REVISED', 'Salary revised'), ('STATUS_CHANGED', 'Employment status changed'), ('TEAM_MOVED', 'Team moved with them'), ('EXITED', 'Left the company')], db_index=True, max_length=30)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, help_text='The day it took effect, which may differ from when it was recorded.')),
                ('from_value', models.CharField(blank=True, default='', max_length=255)),
                ('to_value', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='employee_hierarchy.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee history entry',
                'verbose_name_plural': 'Employee history',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_compensation', models.DecimalField(decimal_places=2, default=0, help_text='basic + allowances + bonuses − deductions. Recomputed on save.', max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField(help_text='The day this salary starts being the one paid.')),
                ('revision_date', models.DateField(default=django.utils.timezone.localdate, help_text='The day the decision was taken, which is often months earlier.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('SCHEDULED', 'Approved – starts later'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salaries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employee_hierarchy.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary record',
                'verbose_name_plural': 'Salary records',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total compensation before. Blank for a joining salary.', max_digits=14, null=True)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_date', models.DateField()),
                ('revision_date', models.DateField(default=django.utils.timezone.localdate)),
                ('revision_type', models.CharField(choices=[('ANNUAL_INCREMENT', 'Annual Increment'), ('PROMOTION', 'Promotion'), ('PERFORMANCE', 'Performance Revision'), ('ROLE_CHANGE', 'Role Change'), ('DEPARTMENT_TRANSFER', 'Department Transfer'), ('MARKET_ADJUSTMENT', 'Market Adjustment'), ('BONUS', 'Bonus'), ('INITIAL', 'Joining Salary'), ('OTHER', 'Other')], default='ANNUAL_INCREMENT', max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='employee_hierarchy.employee')),
                ('salary_record', models.OneToOneField(help_text='The record this revision put in place.', on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='employee_hierarchy.employeesalary')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary revision',
                'verbose_name_plural': 'Salary revisions',
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['company', 'level'], name='employee_hi_company_1dbd4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_designation_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_designation_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'employment_status'], name='employee_hi_company_0f9068_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'department'], name='employee_hi_company_084313_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'designation'], name='employee_hi_company_9e52fc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'reporting_manager'], name='employee_hi_company_9a1ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'hierarchy_level'], name='employee_hi_company_f5c77d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'joining_date'], name='employee_hi_company_a2f84e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'current_salary_amount'], name='employee_hi_company_6e2cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='employee_hi_full_na_908fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employee_hi_employe_ac8223_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_code'), name='uniq_employee_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('company', 'email'), name='uniq_employee_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('reporting_manager', models.F('id')), _negated=True), name='employee_not_own_manager'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('hierarchy_level__gte', 1)), name='employee_level_at_least_one'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'status'], name='employee_hi_company_1f3327_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_hr_department_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_hr_department_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='employeeauditlog',
            index=models.Index(fields=['employee', '-performed_at'], name='employee_hi_employe_519549_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeauditlog',
            index=models.Index(fields=['action', '-performed_at'], name='employee_hi_action_981a17_idx'),
        ),
        migrations.AddIndex(
            model_name='employeehistory',
            index=models.Index(fields=['employee', 'occurred_on'], name='employee_hi_employe_ac50f4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['employee', 'status'], name='employee_hi_employe_8938bc_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['status', 'effective_from'], name='employee_hi_status_ba1d36_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeesalary',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='uniq_salary_per_effective_date'),
        ),
        migrations.AddIndex(
            model_name='salaryrevision',
            index=models.Index(fields=['employee', 'effective_date'], name='employee_hi_employe_9c623c_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrevision',
            index=models.Index(fields=['revision_type'], name='employee_hi_revisio_1a8398_idx'),
        ),
    ]
