# Generated by Django 6.0.1 on 2026-09-14 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('employee_hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentLabourStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headcount', models.PositiveIntegerField(default=0, help_text='Permanent labourers on the rolls, e.g. 85.')),
                ('note', models.CharField(blank=True, default='', help_text='Why it is what it is — a sanction order, a revision date.', max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_labour_strength', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permanent labour strength',
                'verbose_name_plural': 'Permanent labour strength',
                'permissions': [('can_record_labour_presence', 'Can record how many permanent labourers were present')],
            },
        ),
        migrations.CreateModel(
            name='PermanentLabourPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(help_text='The day worked. For NIGHT, the date the shift started.')),
                ('shift', models.CharField(choices=[('DAY', 'Day (07:00-19:00)'), ('NIGHT', 'Night (19:00-07:00)')], max_length=10)),
                ('present_count', models.PositiveIntegerField(help_text='How many permanent labourers were on site for this shift.')),
                ('strength', models.PositiveIntegerField(help_text="What the strength master said when this was recorded. A snapshot, so history is never restated at today's number.")),
                ('remark', models.CharField(blank=True, default='', help_text='Anything that explains the figure — a holiday, a strike.', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_labour_presence', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permanent labour presence',
                'verbose_name_plural': 'Permanent labour presence',
                'ordering': ['-work_date', 'shift'],
                'indexes': [models.Index(fields=['company', '-work_date'], name='employee_hi_company_68ecfe_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'work_date', 'shift'), name='uniq_permanent_presence_per_shift')],
            },
        ),
    ]
