# Generated by Django 6.0.1 on 2026-09-14 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('employee_hierarchy', '0002_permanent_labour_presence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentLabourAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('STRENGTH', 'Strength on the rolls'), ('PRESENCE', 'Shift presence')], db_index=True, max_length=10)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, default='', max_length=10)),
                ('previous_count', models.PositiveIntegerField(blank=True, help_text='What it was. Null on the first write.', null=True)),
                ('new_count', models.PositiveIntegerField(help_text='What it became.')),
                ('previous_remark', models.CharField(blank=True, default='', max_length=255)),
                ('new_remark', models.CharField(blank=True, default='', max_length=255)),
                ('strength', models.PositiveIntegerField(blank=True, help_text='For a presence write, the strength it was measured against.', null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_labour_audit', to='company.company')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_labour_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('presence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='employee_hierarchy.permanentlabourpresence')),
            ],
            options={
                'verbose_name': 'Permanent labour audit entry',
                'verbose_name_plural': 'Permanent labour audit trail',
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['company', 'subject', '-performed_at'], name='employee_hi_company_4f92e3_idx'), models.Index(fields=['presence', '-performed_at'], name='employee_hi_presenc_e650e1_idx')],
            },
        ),
    ]
