# Generated by Django 6.0.1 on 2026-09-14 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('employee_hierarchy', '0003_permanent_labour_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permanentlabourstrength',
            options={'ordering': ['department__name'], 'permissions': [('can_record_labour_presence', 'Can record how many permanent labourers were present')], 'verbose_name': 'Permanent labour strength', 'verbose_name_plural': 'Permanent labour strength'},
        ),
        migrations.RemoveConstraint(
            model_name='permanentlabourpresence',
            name='uniq_permanent_presence_per_shift',
        ),
        migrations.AddField(
            model_name='permanentlabouraudit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_labour_audit', to='employee_hierarchy.department'),
        ),
        migrations.AddField(
            model_name='permanentlabourpresence',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Null means the count is not split by department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permanent_labour_presence', to='employee_hierarchy.department'),
        ),
        migrations.AddField(
            model_name='permanentlabourstrength',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Null means the figure is not split by department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permanent_labour_strength', to='employee_hierarchy.department'),
        ),
        migrations.AlterField(
            model_name='permanentlabourstrength',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_labour_strength', to='company.company'),
        ),
        migrations.AddIndex(
            model_name='permanentlabouraudit',
            index=models.Index(fields=['company', 'subject', 'department', '-performed_at'], name='employee_hi_company_fb9cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='permanentlabourpresence',
            index=models.Index(fields=['company', 'department', '-work_date'], name='employee_hi_company_ad298a_idx'),
        ),
        migrations.AddConstraint(
            model_name='permanentlabourpresence',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('company', 'department', 'work_date', 'shift'), name='uniq_permanent_presence_per_dept_shift'),
        ),
        migrations.AddConstraint(
            model_name='permanentlabourpresence',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('company', 'work_date', 'shift'), name='uniq_permanent_presence_undivided_shift'),
        ),
        migrations.AddConstraint(
            model_name='permanentlabourstrength',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('company', 'department'), name='uniq_permanent_strength_per_department'),
        ),
        migrations.AddConstraint(
            model_name='permanentlabourstrength',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('company',), name='uniq_permanent_strength_undivided'),
        ),
    ]
