# Generated by Django 6.0.1 on 2026-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_hierarchy', '0005_permanent_labour_shared_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sap_segment',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Which plant the person is costed to in SAP: Oil, Mart, Bev, Water, Construction or Common. Deliberately NOT the company FK -- splitting one factory's directory across three companies would fragment the org chart and break department name uniqueness, and 'Common' belongs to no single company at all.", max_length=30),
        ),
    ]
