# Generated by Django 6.0.1 on 2026-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_hierarchy', '0006_employee_sap_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='budget',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Which budget line the person is costed to, e.g. 'Canola-Labour'.", max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Worker, Operator or Executive -- the workbook's own grouping.", max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_budget',
            field=models.CharField(blank=True, default='', help_text="The budget's parent grouping, e.g. 'Factory-OIL'.", max_length=60),
        ),
    ]
