# Generated by Django 6.0.1 on 2026-06-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0011_dispatch_schedule_viewer_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchplan',
            options={'ordering': ['-updated_at', '-created_at'], 'permissions': [('can_view_dispatch_plans', 'Can view Dispatch Plans dashboard'), ('can_edit_dispatch_plans', 'Can edit Dispatch Plans bookings'), ('can_link_dispatch_vehicle', 'Can link dispatch vehicles'), ('can_view_dispatch_schedule', 'Can view Dispatch Schedule (read-only)'), ('can_view_dispatch_pipeline', 'Can view Dispatch Pipeline board')]},
        ),
    ]
