# Generated by Django 6.0.1 on 2026-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0012_alter_dispatchplan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchplan',
            name='customer_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
