# Generated by Django 6.0.1 on 2026-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0014_service_grpo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchplan',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
