# Generated by Django 6.0.1 on 2026-07-14 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('dispatch_plans', '0016_alter_dispatchplan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchplan',
            options={'ordering': ['-updated_at', '-created_at'], 'permissions': [('can_view_dispatch_plans', 'Can view Dispatch Plans dashboard'), ('can_edit_dispatch_plans', 'Can edit Dispatch Plans bookings'), ('can_link_dispatch_vehicle', 'Can link dispatch vehicles'), ('can_select_dispatch_bills', 'Can select bills for dispatch planning'), ('can_view_dispatch_schedule', 'Can view Dispatch Schedule (read-only)'), ('can_view_dispatch_pipeline', 'Can view Dispatch Pipeline board'), ('can_view_inside_vehicle_manager', 'Can view the Inside Vehicle Manager'), ('can_add_bill_inside_vehicle', 'Can add a bill to an inside vehicle'), ('can_remove_bill_inside_vehicle', 'Can remove a bill from an inside vehicle'), ('can_move_bill_inside_vehicle', 'Can move a bill between inside vehicles'), ('can_unlink_bills_inside_vehicle', 'Can unlink all bills from an inside vehicle'), ('can_mark_out_inside_vehicle', 'Can mark an inside vehicle out from the manager')]},
        ),
        migrations.CreateModel(
            name='SelectedDispatchBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_invoice_doc_entry', models.IntegerField()),
                ('sap_invoice_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_dispatch_bills', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'sap_invoice_doc_entry'], name='dispatch_pl_company_515ea1_idx'), models.Index(fields=['company', 'is_active'], name='dispatch_pl_company_0ee90e_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'sap_invoice_doc_entry'), name='unique_selected_dispatch_bill_per_company')],
            },
        ),
    ]
