# Generated by Django 6.0.1 on 2026-07-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0018_grant_select_dispatch_bills_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchplan',
            name='invoice_number',
        ),
    ]
