# Generated by Django 6.0.1 on 2026-07-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0019_remove_dispatchplan_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchplan',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='driver_id_proof_number',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='driver_id_proof_type',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='driver_license_no',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='driver_mobile_no',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='transporter_gstin',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='dispatchplan',
            name='vehicle_no',
        ),
    ]
