# Generated by Django 6.0.1 on 2026-09-01 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('dispatch_plans', '0020_remove_dispatchplan_contact_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('sap_invoice_doc_entry', models.IntegerField(db_index=True)),
                ('sap_invoice_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('customer_code', models.CharField(blank=True, default='', max_length=50)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('warehouse_codes', models.CharField(blank=True, default='', max_length=200)),
                ('dispatch_date', models.DateField(db_index=True)),
                ('bilty_no', models.CharField(blank=True, default='', max_length=50)),
                ('bilty_date', models.DateField(blank=True, null=True)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=30)),
                ('driver_name', models.CharField(blank=True, default='', max_length=100)),
                ('driver_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('PICKED', 'Picked'), ('CANCELLED', 'Cancelled')], db_index=True, default='GENERATED', max_length=20)),
                ('sap_status', models.CharField(choices=[('NOT_POSTED', 'Not posted to SAP'), ('POSTED', 'Posted to SAP'), ('FAILED', 'SAP refused')], default='NOT_POSTED', max_length=20)),
                ('sap_error', models.TextField(blank=True, default='')),
                ('sap_posted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_summaries', to='company.company')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_summaries_issued', to=settings.AUTH_USER_MODEL)),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_summaries_picked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bill summary',
                'verbose_name_plural': 'bill summaries',
                'db_table': 'dispatch_bill_summary',
                'ordering': ['-dispatch_date', '-id'],
                'permissions': [('can_view_bill_summary', 'Can view bill summaries'), ('can_create_bill_summary', 'Can generate a bill summary'), ('can_pick_bill_summary', 'Can confirm a bill summary as picked'), ('can_cancel_bill_summary', 'Can cancel a bill summary')],
            },
        ),
        migrations.CreateModel(
            name='BillSummaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_line_num', models.IntegerField()),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('warehouse_code', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('pcs_per_box', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('boxes', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('litres', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('dispatch_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dispatch_plans.billsummary')),
            ],
            options={
                'db_table': 'dispatch_bill_summary_line',
                'ordering': ['sap_line_num'],
            },
        ),
        migrations.AddIndex(
            model_name='billsummary',
            index=models.Index(fields=['company', 'dispatch_date'], name='dispatch_bi_company_69f48b_idx'),
        ),
        migrations.AddIndex(
            model_name='billsummary',
            index=models.Index(fields=['company', 'status'], name='dispatch_bi_company_604aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='billsummary',
            index=models.Index(fields=['company', 'sap_invoice_doc_entry'], name='dispatch_bi_company_fef11c_idx'),
        ),
        migrations.AddConstraint(
            model_name='billsummary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('status', 'CANCELLED'), _negated=True)), fields=('company', 'sap_invoice_doc_entry'), name='uniq_live_bill_summary_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='billsummaryline',
            constraint=models.UniqueConstraint(fields=('summary', 'sap_line_num'), name='uniq_bill_summary_line_num'),
        ),
    ]
