# Generated by Django 6.0.1 on 2026-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0021_billsummary_billsummaryline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsummary',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='branch_gstin',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billsummaryline',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='billsummaryline',
            name='loose_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
    ]
