# Generated by Django 6.0.1 on 2026-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0022_billsummary_bill_amount_billsummary_branch_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsummary',
            name='company_legal_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
