# Generated by Django 6.0.1 on 2026-09-03 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0023_billsummary_company_legal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchPlanAttachmentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADDED', 'Added'), ('REPLACED', 'Replaced'), ('DELETED', 'Deleted')], max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Service GRPO screen'), ('VEHICLE_LINKING', 'Vehicle linking')], default='MANUAL', max_length=20)),
                ('old_file', models.CharField(blank=True, default='', max_length=500)),
                ('old_filename', models.CharField(blank=True, default='', max_length=255)),
                ('new_file', models.CharField(blank=True, default='', max_length=500)),
                ('new_filename', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_audits', to='dispatch_plans.dispatchplan')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_plan_attachment_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['dispatch_plan', '-performed_at'], name='dispatch_pl_dispatc_fe2276_idx')],
            },
        ),
    ]
