# Generated by Django 6.0.1 on 2026-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0024_dispatchplanattachmentaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsummary',
            name='sap_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
