# Generated by Django 6.0.1 on 2026-09-23 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0027_alter_dispatchplan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billsummary',
            options={'ordering': [models.OrderBy(models.F('dispatch_date'), descending=True, nulls_first=True), '-id'], 'permissions': [('can_view_bill_summary', 'Can view bill summaries'), ('can_create_bill_summary', 'Can generate a bill summary'), ('can_approve_bill_summary', 'Can set the dispatch date and approve a bill summary'), ('can_pick_bill_summary', 'Can confirm a bill summary as picked'), ('can_cancel_bill_summary', 'Can cancel a bill summary')], 'verbose_name': 'bill summary', 'verbose_name_plural': 'bill summaries'},
        ),
        migrations.AddField(
            model_name='billsummary',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_summaries_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_summaries_printed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_summaries_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billsummary',
            name='submitted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billsummary',
            name='dispatch_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='billsummary',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'With the warehouse'), ('REJECTED', 'Sent back'), ('APPROVED', 'Approved'), ('PRINTED', 'Printed'), ('PICKED', 'Picked'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_APPROVAL', max_length=20),
        ),
    ]
