# Generated by Django 6.0.1 on 2026-09-29 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('dispatch_plans', '0030_freight_benchmarks'),
        ('vehicle_management', '0008_vehicle_height_m_vehicle_length_m_vehicle_width_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchFreightApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_label', models.CharField(max_length=220)),
                ('slab_label', models.CharField(max_length=40)),
                ('vehicle_capacity_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_basis', models.CharField(blank=True, choices=[('PER_TRIP', 'Per trip'), ('PER_KG', 'Per kg')], default='', max_length=10)),
                ('rate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('load_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('benchmark_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_freight', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bill_doc_nums', models.TextField(blank=True, default='')),
                ('customer_names', models.TextField(blank=True, default='')),
                ('bill_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('WITHIN_BENCHMARK', 'Within benchmark'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_freight_approvals', to='company.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_approvals', to='dispatch_plans.freightdestination')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_freight_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_freight_reviews', to=settings.AUTH_USER_MODEL)),
                ('slab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_approvals', to='dispatch_plans.freightslab')),
                ('suggested_slab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatch_plans.freightslab')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_freight_approvals', to='vehicle_management.transporter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_freight_approvals', to='vehicle_management.vehicle')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'permissions': [('can_view_freight_approvals', 'Can view dispatch freight approvals'), ('can_approve_freight_approvals', 'Can approve or reject dispatch freight over its benchmark')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='freight_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='dispatch_plans.dispatchfreightapproval'),
        ),
        migrations.AddIndex(
            model_name='dispatchfreightapproval',
            index=models.Index(fields=['status', 'requested_at'], name='dispatch_pl_status_391d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchfreightapproval',
            index=models.Index(fields=['vehicle', 'status'], name='dispatch_pl_vehicle_04aab1_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchfreightapproval',
            constraint=models.CheckConstraint(condition=models.Q(('actual_freight__gte', 0)), name='freight_approval_actual_not_negative'),
        ),
    ]
