# Generated by Django 6.0.1 on 2026-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0031_freight_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsummary',
            name='sap_status',
            field=models.CharField(choices=[('NOT_POSTED', 'Not posted to SAP'), ('POSTED', 'Posted to SAP'), ('FAILED', 'SAP refused'), ('WAITING', 'Waiting for SAP')], default='NOT_POSTED', max_length=20),
        ),
    ]
