# Generated by Django 6.0.1 on 2026-09-30 05:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=20)),
                ('warehouse_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('snapshot_at', models.DateTimeField(help_text="When SAP's figures were copied.")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audits_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_audits', to='company.company')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audits_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'permissions': [('can_view_stock_audit', 'Can view stock audits'), ('can_count_stock_audit', 'Can enter physical counts in a stock audit'), ('can_view_audit_sap_qty', "Can see SAP's quantity and the difference in a stock audit"), ('can_manage_stock_audit', 'Can start, refresh and close stock audits')],
            },
        ),
        migrations.CreateModel(
            name='StockAuditLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('item_group', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('RM', 'Raw Material'), ('PM', 'Packing Material'), ('FG', 'Finished Goods'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('sap_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('in_sap', models.BooleanField(default=True, help_text="False for an item found on the floor that SAP's copy did not list.")),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_audit.stockaudit')),
            ],
            options={
                'ordering': ['category', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='StockAuditCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audit_counts', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audit_counts_voided', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='stock_audit.stockauditline')),
            ],
            options={
                'ordering': ['counted_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockaudit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('company', 'warehouse_code'), name='uniq_open_stock_audit_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockauditline',
            index=models.Index(fields=['audit', 'category'], name='stock_audit_audit_i_02ca3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockauditline',
            unique_together={('audit', 'item_code')},
        ),
    ]
