# Generated by Django 6.0.1 on 2026-09-30 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('stock_audit', '0002_stock_audit_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockaudit',
            options={'ordering': ['-started_at'], 'permissions': [('can_view_stock_audit', 'Can view stock audits'), ('can_count_stock_audit', 'Can enter physical counts in a stock audit'), ('can_view_audit_sap_qty', "Can see SAP's quantity and the difference in a stock audit"), ('can_manage_stock_audit', 'Can start and refresh stock audits'), ('can_approve_stock_audit', 'Can approve or reject a completed stock audit'), ('can_post_stock_audit_to_sap', "Can post an approved stock audit's RM and PM differences to SAP")]},
        ),
        migrations.RemoveConstraint(
            model_name='stockaudit',
            name='uniq_open_stock_audit_per_warehouse',
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audits_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audits_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audits_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_doc_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_doc_num',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audits_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_posting',
            field=models.CharField(blank=True, choices=[('', 'Not posted'), ('POSTING', 'Posting'), ('DONE', 'Posted'), ('FAILED', 'SAP refused'), ('UNKNOWN', 'No answer from SAP')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_posting_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_posting_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='is_batch',
            field=models.BooleanField(default=False, help_text='SAP manages the item by batch (OITM.ManBtchNum).'),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='item_group_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockaudit',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Completed'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='stockaudit',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'SUBMITTED'])), fields=('company', 'warehouse_code'), name='uniq_active_stock_audit_per_warehouse'),
        ),
    ]
