# Generated by Django 6.0.1 on 2026-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_audit', '0004_backfill_groups_and_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaudit',
            name='approval_comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='sap_posted_lines',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
