# Generated by Django 6.0.1 on 2026-09-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tomorrow_run/sheets/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('tab', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('stock_date', models.DateField()),
                ('date_basis', models.CharField(blank=True, default='', max_length=100)),
                ('header_row', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=dict, help_text='Which sheet column became which field.')),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('net_req_l', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_sheets', to='company.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_sheets_put_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PlanningSheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('plan_l', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('ecom_l', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('stock_l', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('net_l', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('machine', models.CharField(blank=True, default='', max_length=100)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tomorrow_run.planningsheet')),
            ],
            options={
                'ordering': ['sheet', 'row'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TomorrowPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('read_at', models.DateTimeField()),
                ('inputs', models.JSONField(default=dict)),
                ('plan', models.JSONField(default=dict)),
                ('trigger', models.CharField(choices=[('nightly', '7 pm read'), ('manual', 'Read again by hand')], default='nightly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('built_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tomorrow_plans_built', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tomorrow_plans', to='company.company')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='tomorrow_run.planningsheet')),
            ],
            options={
                'ordering': ['-for_date'],
                'permissions': [('can_view_tomorrow_run', "Can view tomorrow's run"), ('can_pick_tomorrow_run', 'Can pick what runs first on a machine'), ('can_manage_tomorrow_run', 'Can put in a planning sheet and read the plan again')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PlanCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField(help_text='The day that was checked.')),
                ('run_at', models.DateTimeField()),
                ('rows', models.JSONField(default=list)),
                ('red', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tomorrow_plan_checks', to='company.company')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='tomorrow_run.tomorrowplan')),
            ],
            options={
                'ordering': ['-for_date'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MachinePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=40)),
                ('job', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('other', models.CharField(blank=True, default='', max_length=120)),
                ('why', models.TextField()),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('top3', models.JSONField(blank=True, default=list, help_text='The three we offered when it was picked.')),
                ('on_plan', models.BooleanField(default=False)),
                ('picked_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_picks_cleared', to=settings.AUTH_USER_MODEL)),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_picks', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='tomorrow_run.tomorrowplan')),
            ],
            options={
                'ordering': ['picked_at', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='planningsheet',
            index=models.Index(fields=['company', '-uploaded_at'], name='tomorrow_ru_company_97700d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tomorrowplan',
            constraint=models.UniqueConstraint(fields=('company', 'for_date'), name='uniq_tomorrow_plan_company_day'),
        ),
        migrations.AddConstraint(
            model_name='plancheck',
            constraint=models.UniqueConstraint(fields=('company', 'for_date'), name='uniq_plan_check_company_day'),
        ),
        migrations.AddConstraint(
            model_name='machinepick',
            constraint=models.UniqueConstraint(condition=models.Q(('cleared_at__isnull', True)), fields=('plan', 'machine'), name='uniq_live_pick_per_machine'),
        ),
    ]
