# Generated by Django 6.0.1 on 2026-06-25 06:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_management', '0013_alter_vehicleentry_entry_type'),
        ('gate_core', '0044_arrivalgatepasssequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['category_name'],
                'permissions': [('can_manage_asset_category', 'Can manage asset category')],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetGateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_description', models.TextField()),
                ('make', models.CharField(blank=True, max_length=120, null=True)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Quantity must be positive')])),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('custodian', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inward_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_entries', to='fixed_asset_gatein.assetcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_entries', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_entries', to='gate_core.unitchoice')),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_asset_entry', to='driver_management.vehicleentry')),
            ],
            options={
                'verbose_name': 'Fixed Asset Gate Entry',
                'verbose_name_plural': 'Fixed Asset Gate Entries',
                'ordering': ['-created_at'],
                'permissions': [('can_complete_fixed_asset_entry', 'Can complete fixed asset gate entry')],
                'indexes': [models.Index(fields=['asset_category'], name='fixed_asset_asset_c_e36ca7_idx'), models.Index(fields=['approval_status'], name='fixed_asset_approva_e411e2_idx'), models.Index(fields=['created_at'], name='fixed_asset_created_3acab8_idx'), models.Index(fields=['work_order_number'], name='fixed_asset_work_or_87c60c_idx')],
            },
        ),
    ]
