# Generated by Django 6.0.1 on 2026-06-25 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_asset_gatein', '0002_seed_asset_categories'),
        ('gate_core', '0044_arrivalgatepasssequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('asset_name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Quantity must be positive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='fixedassetgateentry',
            name='fixed_asset_asset_c_e36ca7_idx',
        ),
        migrations.RemoveIndex(
            model_name='fixedassetgateentry',
            name='fixed_asset_approva_e411e2_idx',
        ),
        migrations.AddField(
            model_name='fixedassetitem',
            name='asset_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_items', to='fixed_asset_gatein.assetcategory'),
        ),
        migrations.AddField(
            model_name='fixedassetitem',
            name='fixed_asset_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fixed_asset_gatein.fixedassetgateentry'),
        ),
        migrations.AddField(
            model_name='fixedassetitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_items', to='gate_core.unitchoice'),
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='asset_category',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='asset_description',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='challan_number',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='make',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='model',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='fixedassetgateentry',
            name='unit',
        ),
        migrations.AddConstraint(
            model_name='fixedassetitem',
            constraint=models.UniqueConstraint(fields=('fixed_asset_entry', 'line_no'), name='unique_fixed_asset_entry_line'),
        ),
    ]
