# Generated by Django 6.0.1 on 2026-09-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wdd_code', models.PositiveIntegerField()),
                ('object_type', models.CharField(blank=True, default='', max_length=20)),
                ('draft_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('WITHDRAW', 'Withdrawn')], max_length=10)),
                ('signed_as', models.CharField(blank=True, default='', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('typed_password', models.BooleanField(default=False, help_text='Signed with a password the user typed, not the stored one.')),
                ('confirmed_duplicate', models.BooleanField(default=False, help_text='Approved although SAP already held a posted copy of the document.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_approval_decisions', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_sap_approval_inbox', 'Can view the SAP approvals inbox'), ('can_decide_sap_approvals', 'Can approve or reject SAP approval requests'), ('can_withdraw_own_sap_approvals', 'Can withdraw SAP approval requests they raised')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['company', 'wdd_code'], name='sap_approva_company_9514fa_idx')],
            },
        ),
    ]
