# Generated by Django 6.0.1 on 2026-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapapprovaldecision',
            name='changed_from',
            field=models.CharField(blank=True, default='', help_text="The request's earlier outcome, when this decision changed it.", max_length=10),
        ),
    ]
