# Generated by Django 6.0.1 on 2026-10-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_approvals', '0002_sapapprovaldecision_changed_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapapprovaldecision',
            options={'default_permissions': (), 'ordering': ['-created_at', '-id'], 'permissions': [('can_view_sap_approval_inbox', 'Can view the SAP approvals inbox'), ('can_decide_sap_approvals', 'Can approve or reject SAP approval requests'), ('can_withdraw_own_sap_approvals', 'Can withdraw SAP approval requests they raised'), ('can_view_sap_rejection_history', 'Can view every SAP rejection and who raised it')]},
        ),
        migrations.AddField(
            model_name='sapapprovaldecision',
            name='category',
            field=models.CharField(blank=True, choices=[('CASH_VOUCHER', 'Cash Voucher'), ('ELECTRICITY', 'Electricity'), ('FUEL', 'Fuel'), ('IMPREST', 'Imprest'), ('RENT', 'Rent'), ('REPAIRS', 'R&M'), ('SERVICE', 'Service'), ('SUBSCRIPTION', 'Subscription'), ('TRANSPORT', 'Transport'), ('UTILITY', 'Utility'), ('OTHER', 'Other')], default='', max_length=20),
        ),
    ]
