# Generated by Django 6.0.1 on 2026-10-09 09:47

from django.db import migrations


def drop_history_right(apps, schema_editor):
    # The history now opens on the inbox rights. Its own right goes with it,
    # off every user and group that held it. The "SAP Approvals - Reviewer"
    # group is left alone: it still grants the inbox, which is what its
    # members came for.
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="sap_approvals",
        codename="can_view_sap_rejection_history",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sap_approvals', '0003_decision_category_and_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapapprovaldecision',
            options={'default_permissions': (), 'ordering': ['-created_at', '-id'], 'permissions': [('can_view_sap_approval_inbox', 'Can view the SAP approvals inbox'), ('can_decide_sap_approvals', 'Can approve or reject SAP approval requests'), ('can_withdraw_own_sap_approvals', 'Can withdraw SAP approval requests they raised')]},
        ),
        migrations.RunPython(drop_history_right, migrations.RunPython.noop),
    ]
