# Generated by Django 6.0.1 on 2026-09-23 04:56

import company_vehicle.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Company Vehicle Permission',
                'permissions': [('can_view_fleet', 'Can view the company vehicle register'), ('can_manage_fleet_vehicle', 'Can add and edit company vehicles'), ('can_add_fleet_expense', 'Can record fuel and service entries'), ('can_approve_fleet_expense', 'Can approve or reject fuel and service entries')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_number', models.CharField(help_text='As on the RC, without spaces, e.g. PB65AB1234. For a machine with no registration, any internal code the factory uses.', max_length=20, unique=True)),
                ('nickname', models.CharField(blank=True, default='', help_text="What the staff actually call it -- 'Truck 1', 'Office Eeco'. Shown beside the number, because nobody remembers numbers.", max_length=50)),
                ('category', models.CharField(choices=[('TRUCK', 'Truck'), ('TEMPO', 'Tempo / Pickup'), ('CAR', 'Car'), ('VAN', 'Van (Eeco / Omni)'), ('TWO_WHEELER', 'Scooty / Bike'), ('TRACTOR', 'Tractor'), ('FORKLIFT', 'Forklift'), ('OTHER', 'Other')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG'), ('PETROL_CNG', 'Petrol + CNG'), ('ELECTRIC', 'Electric')], help_text='What it runs on. Decides the unit on the fuel form (litres or kg) and whether that form offers a petrol/CNG choice.', max_length=12)),
                ('make_model', models.CharField(blank=True, default='', help_text='e.g. Tata 407, Maruti Eeco, Activa 6G.', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_WORKSHOP', 'In workshop'), ('STANDBY', 'Standby'), ('SOLD', 'Sold / Scrapped')], db_index=True, default='ACTIVE', max_length=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assigned_to', models.CharField(blank=True, default='', help_text='Driver or employee who keeps it. Free text on purpose: the drivers of an own vehicle are not always in the driver master.', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('opening_odometer', models.PositiveIntegerField(blank=True, help_text='The km reading on the day this vehicle went on to the system. Only used to show distance run before the first fuel entry.', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fleet/photos/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('entry_date', models.DateField(db_index=True)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG'), ('PETROL_CNG', 'Petrol + CNG'), ('ELECTRIC', 'Electric')], help_text='The ONE fuel actually filled. On a dual-fuel vehicle this is what separates the petrol stream from the CNG one.', max_length=12)),
                ('odometer', models.PositiveIntegerField(help_text='Meter reading in km at the pump.')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Litres, or kg for CNG.', max_digits=9)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('is_tank_full', models.BooleanField(default=True, help_text='Tank filled to the brim. Mileage can only be worked out between two full tanks, so a part fill is recorded but not measured.')),
                ('station_name', models.CharField(blank=True, default='', max_length=120)),
                ('bill_number', models.CharField(blank=True, default='', max_length=50)),
                ('bill_photo', models.FileField(blank=True, null=True, upload_to=company_vehicle.models._bill_upload_path)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Company card'), ('UPI', 'UPI / Online'), ('CREDIT', 'Credit at pump')], default='CASH', max_length=10)),
                ('filled_by', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('odometer_note', models.CharField(blank=True, default='', max_length=255)),
                ('distance_km', models.PositiveIntegerField(blank=True, help_text='Km run since the previous entry of the same fuel.', null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, help_text='Km per litre (per kg for CNG), measured full tank to full tank. Null on a part fill, and on the first fill of a vehicle.', max_digits=7, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='company_vehicle.fleetvehicle')),
            ],
            options={
                'verbose_name_plural': 'Fuel entries',
                'ordering': ['-entry_date', '-odometer', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('entry_date', models.DateField(db_index=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('ROUTINE', 'Routine service'), ('REPAIR', 'Repair / Breakdown'), ('TYRE', 'Tyre'), ('BATTERY', 'Battery'), ('BODY', 'Body work'), ('OTHER', 'Other')], default='ROUTINE', max_length=10)),
                ('workshop_name', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='What was done, and which parts were replaced.')),
                ('parts_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('labour_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Parts plus labour unless the bill says otherwise -- a single-figure garage bill is entered here alone.', max_digits=11)),
                ('bill_number', models.CharField(blank=True, default='', max_length=50)),
                ('bill_photo', models.FileField(blank=True, null=True, upload_to=company_vehicle.models._bill_upload_path)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Company card'), ('UPI', 'UPI / Online'), ('CREDIT', 'Credit at pump')], default='CASH', max_length=10)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('down_days', models.PositiveSmallIntegerField(blank=True, help_text='Days the vehicle was off the road for this.', null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entries', to='company_vehicle.fleetvehicle')),
            ],
            options={
                'verbose_name_plural': 'Service entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doc_type', models.CharField(choices=[('RC', 'Registration (RC)'), ('INSURANCE', 'Insurance'), ('PUC', 'Pollution (PUC)'), ('FITNESS', 'Fitness certificate'), ('PERMIT', 'Permit'), ('ROAD_TAX', 'Road tax'), ('OTHER', 'Other')], max_length=12)),
                ('document_number', models.CharField(blank=True, default='', max_length=60)),
                ('issuing_authority', models.CharField(blank=True, default='', help_text='Insurance company, RTO, testing centre.', max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Premium or fee paid. Not counted as running cost -- it is shown on the document, not in the fuel and service totals.', max_digits=11, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=company_vehicle.models._bill_upload_path)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company_vehicle.fleetvehicle')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='fleetvehicle',
            index=models.Index(fields=['status', 'category'], name='company_veh_status_fd0489_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['vehicle', 'entry_date'], name='company_veh_vehicle_abc0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['vehicle', 'fuel_type', 'odometer'], name='company_veh_vehicle_1d8966_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceentry',
            index=models.Index(fields=['vehicle', 'entry_date'], name='company_veh_vehicle_448eae_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['vehicle', 'doc_type', 'expiry_date'], name='company_veh_vehicle_7f26e4_idx'),
        ),
    ]
