# Generated by Django 6.0.1 on 2026-09-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelentry',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='rejection_reason',
        ),
    ]
