# Generated by Django 6.0.1 on 2026-09-23 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_vehicle', '0002_remove_fuelentry_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reading_date', models.DateField(db_index=True)),
                ('odometer', models.PositiveIntegerField(help_text='Meter reading in km, as it read that day.')),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_readings', to='company_vehicle.fleetvehicle')),
            ],
            options={
                'ordering': ['-reading_date', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'reading_date'], name='company_veh_vehicle_296bb7_idx')],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'reading_date'), name='uq_daily_reading_vehicle_date')],
            },
        ),
    ]
