# Generated by Django 6.0.1 on 2026-09-30 06:24

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_mirror_datasets', to='company.company')),
            ],
            options={
                'ordering': ['company__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MirroredBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.PositiveIntegerField()),
                ('doc_num', models.CharField(max_length=30)),
                ('doc_num_sort', models.BigIntegerField(default=0)),
                ('create_date', models.DateField(null=True)),
                ('create_time', models.CharField(blank=True, max_length=10)),
                ('branch_id', models.IntegerField(null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('warehouse_codes', models.CharField(blank=True, max_length=1000)),
                ('sap_dispatched', models.BooleanField(default=False)),
                ('credited', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('bill', models.JSONField()),
                ('lines', models.JSONField(default=list)),
                ('pickable_lines', models.JSONField(default=list)),
                ('copied_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_mirror_bills', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='MirrorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('search_text', models.CharField(blank=True, max_length=400)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sap_mirror.mirrordataset')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddConstraint(
            model_name='mirrordataset',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_sap_mirror_dataset'),
        ),
        migrations.AddIndex(
            model_name='mirroredbill',
            index=models.Index(fields=['company', 'create_date'], name='sap_mirror_bill_created'),
        ),
        migrations.AddIndex(
            model_name='mirroredbill',
            index=models.Index(fields=['company', 'doc_num'], name='sap_mirror_bill_doc_num'),
        ),
        migrations.AddConstraint(
            model_name='mirroredbill',
            constraint=models.UniqueConstraint(fields=('company', 'doc_entry'), name='unique_sap_mirror_bill'),
        ),
        migrations.AddConstraint(
            model_name='mirrorrow',
            constraint=models.UniqueConstraint(fields=('dataset', 'key'), name='unique_sap_mirror_row'),
        ),
    ]
