# Generated by Django 6.0.1 on 2026-10-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('sap_mirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.PositiveIntegerField()),
                ('doc_num', models.CharField(max_length=30)),
                ('served_at', models.DateTimeField()),
                ('last_served_at', models.DateTimeField()),
                ('copy_as_of', models.DateTimeField(null=True)),
                ('served', models.JSONField()),
                ('outcome', models.CharField(choices=[('PENDING', 'Not checked yet'), ('UNCHANGED', 'Unchanged in SAP'), ('CHANGED', 'Changed in SAP'), ('CANCELLED', 'Cancelled in SAP'), ('CREDITED', 'Credited in SAP')], db_index=True, default='PENDING', max_length=20)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('differences', models.JSONField(blank=True, default=list)),
                ('linked', models.JSONField(blank=True, default=list)),
                ('notified', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_mirror_served_bills', to='company.company')),
            ],
            options={
                'ordering': ['-served_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('outcome', 'PENDING')), fields=('company', 'doc_entry'), name='unique_sap_mirror_pending_served_bill')],
            },
        ),
    ]
