# Generated by Django 6.0.1 on 2026-10-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('sap_mirror', '0002_served_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirroredPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.PositiveIntegerField()),
                ('doc_num', models.CharField(max_length=30)),
                ('supplier_code', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('rows', models.JSONField(default=list)),
                ('copied_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_mirror_purchase_orders', to='company.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'supplier_code'], name='sap_mirror_po_supplier'), models.Index(fields=['company', 'doc_num'], name='sap_mirror_po_doc_num')],
                'constraints': [models.UniqueConstraint(fields=('company', 'doc_entry'), name='unique_sap_mirror_po')],
            },
        ),
    ]
