# Generated by Django 6.0.1 on 2026-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0012_add_qc_hold_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('DAILY_NEED', 'Daily Need / Canteen'), ('MAINTENANCE', 'Maintenance'), ('CONSTRUCTION', 'Construction'), ('FIXED_ASSET', 'Fixed Asset'), ('EMPTY_VEHICLE', 'Empty Vehicle'), ('BST_IN', 'BST In'), ('BST_RETURN', 'BST Return'), ('JOB_WORK', 'Job Work'), ('SALES_DISPATCH', 'Sales Dispatch')], max_length=20),
        ),
    ]
