# Generated by Django 6.0.1 on 2026-07-04 11:43

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0013_alter_vehicleentry_entry_type'),
        ('vehicle_management', '0007_transporter_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='vehicleentry',
            index=models.Index(fields=['company', 'status'], name='vehentry_co_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='vehicleentry',
            index=models.Index(fields=['company', 'entry_type'], name='vehentry_co_entrytype_idx'),
        ),
    ]
