# Generated by Django 6.0.1 on 2026-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0014_alter_vehicleentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOODS', 'Finished Goods'), ('DAILY_NEED', 'Daily Need / Canteen'), ('MAINTENANCE', 'Maintenance'), ('CONSTRUCTION', 'Construction'), ('FIXED_ASSET', 'Fixed Asset'), ('EMPTY_VEHICLE', 'Empty Vehicle'), ('BST_IN', 'BST In'), ('BST_RETURN', 'BST Return'), ('JOB_WORK', 'Job Work'), ('SALES_DISPATCH', 'Sales Dispatch'), ('GOODS_RETURN', 'Goods Return')], max_length=20),
        ),
    ]
