# Generated by Django 6.0.3 on 2026-04-16 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_add_department_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'permissions': [('can_create_verification_request', 'Can create labour verification request'), ('can_view_verification_request', 'Can view labour verification requests'), ('can_close_verification_request', 'Can close labour verification request')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLabourResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_count', models.PositiveIntegerField(default=0)),
                ('labour_details', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_responses', to='accounts.department')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_responses_submitted', to=settings.AUTH_USER_MODEL)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='labour_verification.labourverificationrequest')),
            ],
            options={
                'ordering': ['department__name'],
                'permissions': [('can_submit_department_labour', 'Can submit department labour count')],
                'unique_together': {('verification_request', 'department')},
            },
        ),
    ]
