# Generated by Django 6.0.1 on 2026-09-14 06:37

import artwork.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(help_text='SAP OITM.ItemCode, e.g. PM0000086.', max_length=50)),
                ('item_name', models.CharField(blank=True, default='', help_text='SAP OITM.ItemName as it read when the artwork was filed. A snapshot, so the register still names the item if SAP is unreachable; the live name is shown beside it on the page.', max_length=255)),
                ('sub_group', models.CharField(choices=[('LABEL', 'Label'), ('CARTON', 'Carton')], help_text='SAP OITM.U_Sub_Group -- LABEL or CARTON.', max_length=16)),
                ('document_number', models.CharField(help_text='Controlled document number as printed on the artwork. Typed in, not allocated: artwork numbers are assigned outside this application.', max_length=64)),
                ('revision_number', models.PositiveSmallIntegerField(default=0, help_text='Revision as printed, starting at 00. The document number never changes across a revision; this does.')),
                ('revision_date', models.DateField(help_text='Date this revision was issued, as printed on the artwork.')),
                ('barcode', models.CharField(blank=True, default='', help_text='The barcode printed on the artwork (EAN-13 on a label). Optional: plain cartons frequently carry none, and refusing to file an artwork because it has no barcode would leave it unrecorded. SAP holds no barcode for these items at all -- see constants.py.', max_length=64)),
                ('pdf_file', models.FileField(help_text='Print-ready PDF.', upload_to=artwork.models._artwork_upload_path)),
                ('pdf_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cdr_file', models.FileField(help_text='CorelDRAW (.cdr) source file.', upload_to=artwork.models._artwork_upload_path)),
                ('cdr_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('cdr_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(help_text='The company whose item master this item code comes from. Item codes repeat across the three schemas and mean different things, so a record is only ever read back against its own company.', on_delete=django.db.models.deletion.CASCADE, related_name='artwork_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sub_group', 'item_code'],
                'permissions': [('can_view_artwork', 'Can view the label and carton artwork register'), ('can_manage_artwork', 'Can capture and revise label and carton artwork')],
            },
        ),
        migrations.CreateModel(
            name='ArtworkRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=64)),
                ('revision_number', models.PositiveSmallIntegerField(default=0)),
                ('revision_date', models.DateField()),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('pdf_file', models.FileField(blank=True, upload_to=artwork.models._revision_upload_path)),
                ('pdf_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('cdr_file', models.FileField(blank=True, upload_to=artwork.models._revision_upload_path)),
                ('cdr_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('superseded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='artwork.artworkrecord')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_artwork_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-superseded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='artworkrecord',
            index=models.Index(fields=['company', 'sub_group'], name='artwork_art_company_f62042_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkrecord',
            index=models.Index(fields=['company', 'barcode'], name='artwork_art_company_282b35_idx'),
        ),
        migrations.AddConstraint(
            model_name='artworkrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'item_code'), name='uq_artwork_company_item'),
        ),
        migrations.AddConstraint(
            model_name='artworkrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'document_number'), name='uq_artwork_company_document_number'),
        ),
        migrations.AddIndex(
            model_name='artworkrevision',
            index=models.Index(fields=['record', '-superseded_at'], name='artwork_art_record__7c1c37_idx'),
        ),
    ]
