# Generated by Django 6.0.1 on 2026-09-14 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artworkrecord',
            name='uq_artwork_company_document_number',
        ),
        migrations.AlterField(
            model_name='artworkrecord',
            name='document_number',
            field=models.CharField(blank=True, default='', help_text='Controlled document number as printed on the artwork. Typed in, not allocated: artwork numbers are assigned outside this application. Optional: plenty of artwork reaches the factory before it has been given a number, and refusing to file it until then would leave the artwork itself unrecorded.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='artworkrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('document_number', ''), _negated=True)), fields=('company', 'document_number'), name='uq_artwork_company_document_number'),
        ),
    ]
