# Generated by Django 6.0.1 on 2026-09-08 10:00

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plant_name', models.CharField(default='Oil Plant', help_text="Title at the top of the chart, e.g. 'Oil Plant'.", max_length=120)),
                ('plant_head', models.CharField(blank=True, default='', help_text='Who heads the plant. Blank if the chart does not name one.', max_length=120)),
            ],
            options={
                'verbose_name': 'org chart heading',
                'verbose_name_plural': 'org chart heading',
            },
        ),
        migrations.RemoveConstraint(
            model_name='orgfunction',
            name='uniq_org_function_name_per_department',
        ),
        migrations.AddField(
            model_name='orgdepartment',
            name='head',
            field=models.CharField(blank=True, default='', help_text='Who heads the whole department, printed under its name. Blank for a department the chart does not put one person over.', max_length=120),
        ),
        migrations.AddField(
            model_name='orgfunction',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Second line under the section, telling two rows of the same section apart (Storage – OIL vs Storage – Packing material).', max_length=150),
        ),
        migrations.AlterField(
            model_name='orgfunction',
            name='level_1',
            field=models.JSONField(blank=True, default=list, help_text='Supported by (L2) — list of names.'),
        ),
        migrations.AlterField(
            model_name='orgfunction',
            name='level_2',
            field=models.JSONField(blank=True, default=list, help_text='Team (L3) — list of names.'),
        ),
        migrations.AlterField(
            model_name='orgfunction',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Section. Blank for a department that is not sub-divided.', max_length=150),
        ),
        migrations.AlterField(
            model_name='orgfunction',
            name='owners',
            field=models.JSONField(blank=True, default=list, help_text='Leader (L1) — list of names.'),
        ),
        migrations.AddConstraint(
            model_name='orgfunction',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('department', 'name', 'subtitle'), name='uniq_org_function_name_per_department'),
        ),
        migrations.AddField(
            model_name='orgchartsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgchartsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
