# Generated by Django 6.0.1 on 2026-09-11 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('goods_return', '0013_customer_ref_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dismantle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PARTIALLY_POSTED', 'Partly posted to SAP'), ('POSTED', 'Posted to SAP'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('source', models.CharField(choices=[('GOODS_RETURN', 'From a goods return'), ('STOCK', 'From warehouse stock')], default='GOODS_RETURN', max_length=20)),
                ('warehouse_code', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('pieces_per_box', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('bom_batch_size', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('variety_code', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('sap_order_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_order_doc_num', models.CharField(blank=True, max_length=50)),
                ('sap_receipt_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_receipt_doc_num', models.CharField(blank=True, max_length=50)),
                ('sap_issue_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_issue_doc_num', models.CharField(blank=True, max_length=50)),
                ('order_closed', models.BooleanField(default=False)),
                ('sap_post_error', models.TextField(blank=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dismantles', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('goods_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismantles', to='goods_return.goodsreturn')),
                ('goods_return_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismantles', to='goods_return.goodsreturnitem')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismantles_posted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_dismantle', 'Can view dismantle'), ('can_create_dismantle', 'Can create dismantle'), ('can_edit_dismantle', 'Can edit dismantle'), ('can_post_dismantle', 'Can post a dismantle to SAP')],
            },
        ),
        migrations.CreateModel(
            name='DismantleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('qty_per_piece', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('warehouse_code', models.CharField(blank=True, max_length=50)),
                ('is_batch_managed', models.BooleanField(default=False)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('recovered', models.BooleanField(default=True)),
                ('sap_line_num', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dismantle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dismantle.dismantle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='dismantle',
            index=models.Index(fields=['company', 'status'], name='dismantle_d_company_dd30ec_idx'),
        ),
        migrations.AddIndex(
            model_name='dismantle',
            index=models.Index(fields=['warehouse_code', 'item_code'], name='dismantle_d_warehou_fe2ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='dismantle',
            index=models.Index(fields=['goods_return'], name='dismantle_d_goods_r_5f0001_idx'),
        ),
        migrations.AddIndex(
            model_name='dismantlecomponent',
            index=models.Index(fields=['dismantle'], name='dismantle_d_dismant_533c7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='dismantlecomponent',
            constraint=models.UniqueConstraint(fields=('dismantle', 'item_code'), name='uniq_dismantle_component_item'),
        ),
    ]
