# Generated by Django 6.0.1 on 2026-09-14 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('sap_invoice_doc_entry', models.IntegerField()),
                ('sap_invoice_doc_num', models.CharField(blank=True, max_length=50)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('warehouse_code', models.CharField(max_length=50)),
                ('sap_return_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_return_doc_num', models.CharField(blank=True, max_length=50)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_dispatches', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_dispatches_posted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_short_dispatch', 'Can view short dispatch entries'), ('can_create_short_dispatch', 'Can record and post a short dispatch')],
            },
        ),
        migrations.CreateModel(
            name='ShortDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_line_num', models.IntegerField(blank=True, null=True)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoice_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('short_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('tax_code', models.CharField(blank=True, max_length=20)),
                ('source_warehouse_code', models.CharField(blank=True, max_length=50)),
                ('original_batch_number', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(choices=[('SHORT', 'Short in stock'), ('NOT_LOADED', 'Not loaded on the vehicle'), ('DAMAGED', 'Damaged before loading'), ('CUSTOMER_REFUSED', "Pulled off at customer's request"), ('OTHER', 'Other')], default='SHORT', max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('short_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='short_dispatch.shortdispatch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_line_num', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='shortdispatch',
            index=models.Index(fields=['company', '-created_at'], name='short_dispa_company_76e153_idx'),
        ),
        migrations.AddIndex(
            model_name='shortdispatch',
            index=models.Index(fields=['sap_invoice_doc_entry'], name='short_dispa_sap_inv_c11e96_idx'),
        ),
        migrations.AddIndex(
            model_name='shortdispatchitem',
            index=models.Index(fields=['short_dispatch'], name='short_dispa_short_d_c99459_idx'),
        ),
    ]
