# Generated by Django 6.0.1 on 2026-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdispatch',
            name='sap_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shortdispatch',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted to SAP'), ('QUEUED', 'Waiting for SAP'), ('REFUSED', 'Refused by SAP')], db_index=True, default='POSTED', max_length=20),
        ),
    ]
