# Generated by Django 6.0.1 on 2026-10-07 09:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_id', models.PositiveIntegerField(help_text='SAP OBPL.BPLId.')),
                ('budget_name', models.CharField(help_text='SAP OBPL.BPLName as it read when the claim was put in.', max_length=255)),
                ('gl_account_code', models.CharField(help_text='SAP OACT.AcctCode.', max_length=32)),
                ('gl_account_name', models.CharField(help_text='SAP OACT.AcctName as it read when the claim was put in.', max_length=255)),
                ('comment', models.TextField(help_text="What the money was spent on, in the submitter's own words.")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='', help_text='Required when rejecting.')),
                ('approver', models.ForeignKey(help_text='Who it goes to. Only they can decide it.', on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims_to_approve', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text="The page's 'Branch': Oil, Mart or Beverages, and so whose SAP the budget and the G/L account were picked from.", on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims_decided', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('can_submit_expense_claim', 'Can put in an expense')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['status'], name='expense_cla_status_ac7550_idx'), models.Index(fields=['approver', 'status'], name='expense_cla_approve_fb3a6a_idx')],
            },
        ),
    ]
