# Generated by Django 6.0.1 on 2026-10-07 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('expense_claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseclaim',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': [('can_submit_expense_claim', 'Can put in an expense'), ('can_approve_expense_claims', 'Can approve or reject expenses')]},
        ),
        migrations.RemoveIndex(
            model_name='expenseclaim',
            name='expense_cla_approve_fb3a6a_idx',
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='budget_code',
            field=models.CharField(blank=True, default='', help_text='SAP OOCR.OcrCode, dimension 3.', max_length=32),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='gl_description',
            field=models.TextField(blank=True, default='', help_text="Instead of a G/L account: what the expense is for, in the submitter's words, so accounts can find the account."),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='budget_name',
            field=models.CharField(help_text='SAP OOCR.OcrName as it read when the claim was saved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='gl_account_code',
            field=models.CharField(blank=True, default='', help_text='SAP OACT.AcctCode, an expense account. Blank when the submitter did not know it.', max_length=32),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='gl_account_name',
            field=models.CharField(blank=True, default='', help_text='SAP OACT.AcctName as it read when the claim was saved.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['created_by'], name='expense_cla_created_36baa4_idx'),
        ),
        migrations.RemoveField(
            model_name='expenseclaim',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='expenseclaim',
            name='budget_id',
        ),
    ]
