# Generated by Django 6.0.1 on 2026-09-04 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('invoice_approval', '0002_invoice_approval_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoiceapprovalaudit',
            name='invoice_app_company_c3a870_idx',
        ),
        migrations.AddField(
            model_name='invoiceapprovalaudit',
            name='source',
            field=models.CharField(choices=[('SAP', 'SAP approval request'), ('OMS', 'OMS invoice log')], db_index=True, default='SAP', max_length=3),
        ),
        migrations.AddIndex(
            model_name='invoiceapprovalaudit',
            index=models.Index(fields=['company', 'source', 'approval_code'], name='invoice_app_company_9340aa_idx'),
        ),
    ]
