# Generated by Django 6.0.1 on 2026-09-26 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('CREATE', 'New BOM'), ('UPDATE', 'Change to a BOM')], max_length=10)),
                ('item_code', models.CharField(help_text="The parent item, which is also the BOM's code in SAP.", max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, help_text="How much of the parent the recipe makes (SAP's tree quantity).", max_digits=18)),
                ('bom_type', models.CharField(choices=[('Production', 'Production'), ('Sales', 'Sales'), ('Assembly', 'Assembly'), ('Template', 'Template')], default='Production', max_length=20)),
                ('warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('distribution_rule', models.CharField(blank=True, default='', max_length=50)),
                ('project', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('L1_APPROVED', 'Level 1 approved'), ('L2_APPROVED', 'Level 2 approved'), ('L3_APPROVED', 'Level 3 approved'), ('SAP_PUSHED', 'In SAP'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_data', models.JSONField(blank=True, help_text='UPDATE: the tree as SAP held it, read when the request was raised and again just before it was replaced.', null=True)),
                ('sap_result', models.JSONField(blank=True, help_text='What SAP answered to the push.', null=True)),
                ('sap_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('push_error', models.TextField(blank=True, default='')),
                ('push_failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_portal_id', models.PositiveIntegerField(blank=True, help_text='ZBOM_REQUESTS.ID, for rows imported from SAP Portal.', null=True, unique=True)),
                ('legacy_submitted_by', models.CharField(blank=True, default='', max_length=160)),
                ('legacy_sap_pushed_by', models.CharField(blank=True, default='', max_length=160)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_changes_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_change_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sap_pushed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_changes_pushed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
                'permissions': [('can_view_bom_changes', 'Can view BOM change requests and SAP BOMs'), ('can_request_bom_changes', 'Can request a new BOM or a change to one'), ('can_approve_bom_level_1', 'Can approve BOM changes at level 1'), ('can_approve_bom_level_2', 'Can approve BOM changes at level 2'), ('can_push_bom_to_sap', 'Can give the final BOM approval that writes SAP'), ('can_push_bom_directly', 'Can write a BOM change to SAP without approvals')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BOMChangeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_order', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('item', 'Item'), ('resource', 'Resource')], default='item', max_length=10)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('issue_method', models.CharField(choices=[('Manual', 'Manual'), ('Backflush', 'Backflush')], default='Manual', max_length=10)),
                ('warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('comment', models.CharField(blank=True, default='', max_length=254)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bom_changes.bomchangerequest')),
            ],
            options={
                'ordering': ['visual_order', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BOMChangeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('from_status', models.CharField(choices=[('PENDING', 'Pending'), ('L1_APPROVED', 'Level 1 approved'), ('L2_APPROVED', 'Level 2 approved'), ('L3_APPROVED', 'Level 3 approved'), ('SAP_PUSHED', 'In SAP'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('action', models.CharField(choices=[('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=10)),
                ('legacy_decided_by', models.CharField(blank=True, default='', max_length=160)),
                ('remarks', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_change_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='bom_changes.bomchangerequest')),
            ],
            options={
                'ordering': ['decided_at', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='bomchangerequest',
            index=models.Index(fields=['company', 'status'], name='bom_changes_company_fe423e_idx'),
        ),
        migrations.AddIndex(
            model_name='bomchangerequest',
            index=models.Index(fields=['company', 'item_code'], name='bom_changes_company_e42790_idx'),
        ),
        migrations.AddConstraint(
            model_name='bomchangeapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'APPROVE'), ('decided_by__isnull', False)), fields=('request', 'decided_by'), name='bom_change_one_approval_per_person'),
        ),
    ]
