# Generated by Django 6.0.1 on 2026-03-26 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email_type', models.CharField(choices=[('GATE_ENTRY_CREATED', 'Gate Entry Created'), ('GATE_ENTRY_STATUS_CHANGED', 'Gate Entry Status Changed'), ('SECURITY_CHECK_DONE', 'Security Check Completed'), ('WEIGHMENT_RECORDED', 'Weighment Recorded'), ('ARRIVAL_SLIP_SUBMITTED', 'Arrival Slip Submitted'), ('ARRIVAL_SLIP_SENT_BACK', 'Arrival Slip Sent Back to Gate'), ('QC_INSPECTION_SUBMITTED', 'QC Inspection Submitted'), ('QC_CHEMIST_APPROVED', 'QC Chemist Approved'), ('QC_QAM_APPROVED', 'QC QAM Approved'), ('QC_REJECTED', 'QC Rejected'), ('QC_COMPLETED', 'QC Completed'), ('PO_RECEIVED', 'PO Items Received'), ('GATE_ENTRY_COMPLETED', 'Gate Entry Completed'), ('GRPO_POSTED', 'GRPO Posted to SAP'), ('GRPO_FAILED', 'GRPO Posting Failed'), ('WELCOME', 'Welcome Email'), ('PASSWORD_RESET', 'Password Reset'), ('GENERAL_ANNOUNCEMENT', 'General Announcement')], default='GENERAL_ANNOUNCEMENT', max_length=50)),
                ('click_action_url', models.CharField(blank=True, help_text='Frontend route to navigate to on click', max_length=500)),
                ('reference_type', models.CharField(blank=True, help_text='Entity type: vehicle_entry, inspection, grpo_posting, etc.', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the referenced entity', null=True)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_send_email', 'Can send manual emails'), ('can_send_bulk_email', 'Can send bulk/broadcast emails')],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='mail_emaill_recipie_bbc016_idx'), models.Index(fields=['recipient_email', '-created_at'], name='mail_emaill_recipie_e72c72_idx'), models.Index(fields=['status'], name='mail_emaill_status_2f0b01_idx'), models.Index(fields=['email_type'], name='mail_emaill_email_t_ba654f_idx')],
            },
        ),
    ]
