# Generated by Django 6.0.1 on 2026-09-15 10:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_user_employee_code'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveIntegerField(help_text='Allocated per company at send time, starting at 1.')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('remarks', models.TextField(blank=True, default='', help_text='What the custodian wants the approver to know.')),
                ('sent_at', models.DateTimeField(help_text="When the bunch went for approval. The sheet's 'Send Date'.")),
                ('decided_at', models.DateTimeField(blank=True, help_text="When it was approved or rejected. The sheet's 'Sign Date' -- the app has no signature, so approval is what that column becomes.", null=True)),
                ('decision_note', models.TextField(blank=True, default='', help_text='Required when rejecting: the custodian has to know what to fix before sending it again.')),
                ('company', models.ForeignKey(help_text='The company whose cash box this is. Each company keeps one book with its own running balance.', on_delete=django.db.models.deletion.CASCADE, related_name='cash_bunches', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cash_bunches', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_cash_bunches', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cash bunches',
                'ordering': ['-sent_at', '-id'],
                'permissions': [('can_approve_cash_bunch', 'Can approve or reject a bunch of cash entries')],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_date', models.DateField(help_text='The date the money moved, which is often before the day the voucher reached the book.')),
                ('direction', models.CharField(choices=[('IN', 'Cash in'), ('OUT', 'Cash out')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Which way it moved is ``direction``.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('gl_account_code', models.CharField(blank=True, default='', help_text='SAP OACT.AcctCode, picked from the chart of accounts.', max_length=32)),
                ('gl_account_name', models.CharField(blank=True, default='', help_text='SAP OACT.AcctName as it read when the entry was made. A snapshot, so the register still names the head when SAP is down or the account is later renamed.', max_length=255)),
                ('item', models.CharField(blank=True, default='', help_text="What was actually bought -- 'Vegetable', 'DP switch', 'Drill bit'. The sheet's Item column: a note under the G/L head, not a stock item, so it is free text.", max_length=120)),
                ('detail', models.TextField(help_text='The narrative, as written in the book: who was paid, what for, and any bill or party reference.')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The cash in hand once this entry is applied. Maintained by cash_book.services -- never set directly.', max_digits=14)),
                ('bunch', models.ForeignKey(blank=True, help_text='The bunch this entry was sent for approval in. Null until it is sent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='cash_book.cashbunch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Who the money was spent for. Required on a payment; a cash receipt into the box belongs to no department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cash entries',
                'ordering': ['id'],
                'permissions': [('can_view_cash_book', 'Can view the cash book'), ('can_manage_cash_book', 'Can record, correct and cancel cash entries')],
            },
        ),
        migrations.AddIndex(
            model_name='cashbunch',
            index=models.Index(fields=['company', 'status', '-sent_at'], name='cash_book_c_company_a6c84b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashbunch',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uq_cash_bunch_company_number'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['company', 'id'], name='cash_book_c_company_90fc56_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['company', 'entry_date'], name='cash_book_c_company_ac91de_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['bunch'], name='cash_book_c_bunch_i_8d9628_idx'),
        ),
    ]
