"""
The card, the advances, and a real number for a bunch.

Three things arrive together because they are one story: where the cash comes
from, who is holding it before it is explained, and how the batches of vouchers
are identified.

RENUMBERING THE BUNCHES
-----------------------
The spreadsheet's "Bunch" column was never an identifier. It is the *total* of
the vouchers in the batch -- all 45 of them sum exactly to their own number,
the Send sheet prints each batch under "Total 17570", and the ATM sheet lists
the same figures as "Amount Submit". Importing it as the bunch's number made
the next bunch raised on a seeded book come out at 36973, and would have made
two batches of the same value indistinguishable.

So bunches are renumbered here, 1 upwards per company in the order they were
sent, and the total goes back to being what it always was: a sum, computed from
the entries, correct by construction as they are added or cancelled.
"""

# Generated by Django 6.0.1 on 2026-09-16 05:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def renumber_bunches(apps, schema_editor):
    """Give every bunch a plain sequence number, per company, oldest first.

    The number it had was the batch total -- see the module docstring. It is
    not preserved anywhere because it is not lost: summing the bunch's entries
    returns it exactly.
    """
    CashBunch = apps.get_model("cash_book", "CashBunch")
    Company = apps.get_model("company", "Company")

    for company in Company.objects.all():
        bunches = list(
            CashBunch.objects.filter(company=company).order_by("sent_at", "id")
        )
        if not bunches:
            continue
        # Two passes: the unique constraint on (company, number) would trip on
        # the way past a number still held by a bunch further down the list.
        offset = max(bunch.number for bunch in bunches) + 1
        for index, bunch in enumerate(bunches):
            bunch.number = offset + index
            bunch.save(update_fields=["number"])
        for index, bunch in enumerate(bunches, start=1):
            bunch.number = index
            bunch.save(update_fields=["number"])


def unrenumber_bunches(apps, schema_editor):
    """Put each bunch's number back to the total of its entries.

    Which is what it was before, and is derivable, so reversing loses nothing.
    """
    CashBunch = apps.get_model("cash_book", "CashBunch")
    for bunch in CashBunch.objects.all():
        total = 0
        for entry in bunch.entries.filter(is_active=True):
            total += entry.amount if entry.direction == "OUT" else -entry.amount
        bunch.number = int(total)
        bunch.save(update_fields=["number"])


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0002_branch_replaces_department'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='advance_holder',
            field=models.ForeignKey(blank=True, help_text='On a PAYMENT: the person who spent this out of an advance they were already holding, whose outstanding advance it therefore clears. Blank when the custodian paid it straight out of the box.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_cash_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AtmAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="As the sheet names it, holder and all: 'Ginni Vg Imprest Debit Card (Vishal)'.", max_length=120)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What was on the card when this register started. The sheet opens at 19,538.', max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atm_accounts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cashentry',
            name='atm_account',
            field=models.ForeignKey(blank=True, help_text="On a RECEIPT: the card this cash was drawn off, which is what takes it off that card's balance. Blank when the cash came from somewhere else -- handed over by a director, say.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='cash_book.atmaccount'),
        ),
        migrations.CreateModel(
            name='AtmReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('received_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('detail', models.TextField(blank=True, default='', help_text="Where it came from -- 'Imprest received from Vicky Vg'.")),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cash_book.atmaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['received_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_date', models.DateField()),
                ('direction', models.CharField(choices=[('GIVEN', 'Advance given'), ('RETURNED', 'Cash returned')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; ``direction`` says which way it moved.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('detail', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_advances', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(help_text='Who is holding the money.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advance entries',
                'ordering': ['-entry_date', '-id'],
                'permissions': [('can_manage_cash_advances', 'Can give and take back cash advances')],
                'indexes': [models.Index(fields=['company', 'person', '-entry_date'], name='cash_book_a_company_efa657_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='atmaccount',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_atm_account_company_name'),
        ),
        migrations.AddIndex(
            model_name='atmreceipt',
            index=models.Index(fields=['account', 'received_on'], name='cash_book_a_account_fed3d4_idx'),
        ),
        # Last: the bunches keep their old numbers until every schema change
        # above has landed, so a failure leaves them readable as they were.
        migrations.RunPython(renumber_bunches, unrenumber_bunches),
    ]
