"""
Approval moves from the bunch to the entry.

A bunch is the bundle of paper vouchers walked to the office together. It was
also, until now, the only way anything could be approved -- so a payment typed
on Tuesday waited on a batch that went on Friday, and nothing could be agreed
without first being bundled. Those are two different ideas and they are now two
different fields.

Bunches keep their number, their dates and their membership, because the batch
is real and the Send sheet prints it. What they no longer do is decide whether
a spend was agreed, or freeze the entries in them.

Every entry already in the book takes the state of the bunch it was in, so
nothing loses an approval it already had.
"""

# Generated by Django 6.0.1 on 2026-09-16 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_approval_down_to_entries(apps, schema_editor):
    """Give each entry the state its bunch was holding for it."""
    CashEntry = apps.get_model("cash_book", "CashEntry")

    for entry in CashEntry.objects.select_related("bunch").iterator():
        bunch = entry.bunch
        if bunch is None:
            continue  # never sent, and the default already says so
        entry.approval_state = bunch.status
        entry.approval_sent_at = bunch.sent_at
        entry.approval_decided_at = bunch.decided_at
        entry.approval_decided_by_id = bunch.decided_by_id
        entry.approval_note = bunch.decision_note or ""
        entry.save(
            update_fields=[
                "approval_state",
                "approval_sent_at",
                "approval_decided_at",
                "approval_decided_by",
                "approval_note",
            ]
        )


def clear_entry_approval(apps, schema_editor):
    """Reversing drops the entry's own state; the bunches still carry it."""


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0003_atm_and_advances'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='approval_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='approval_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cash_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='approval_note',
            field=models.TextField(blank=True, default='', help_text='Required when rejecting, so the custodian knows what to fix.'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='approval_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='approval_state',
            field=models.CharField(choices=[('UNSENT', 'Not sent'), ('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNSENT', help_text='Whether this spend has been agreed. Sent straight from the entry form, or later from the register; a bunch no longer decides it.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['company', 'approval_state'], name='cash_book_c_company_9e95d5_idx'),
        ),
        # After the columns exist, so an entry never reads as unsent when its
        # bunch was holding an approval for it.
        migrations.RunPython(carry_approval_down_to_entries, clear_entry_approval),
    ]
