"""
"Not sent for approval" stops being a state a payment can be in.

A cash out joins the approval queue the moment it is written down. There is no
step in between, so there is no state for the gap -- a spend nobody has been
told about is not something the register should be able to hold.

Receipts move the other way: nobody approves money arriving, so they take
NOT_REQUIRED and never appear in a queue at all.

This also settles a disagreement that was visible on screen. The register's
header counted every unapproved payment as pending, while the filter beside it
only showed PENDING -- so 71,013 of imported payments that had never been
bundled were counted in one place and missing from the other. They are payments
awaiting approval, and after this they say so in both.
"""

# Generated by Django 6.0.1 on 2026-09-17 04:41

from django.db import migrations, models


def settle_the_unsent(apps, schema_editor):
    """Put every entry into a state that still exists.

    A payment that was never sent is a payment waiting to be approved -- which
    is what it always was in substance; the old model just had nowhere to say
    so until somebody bundled it.
    """
    CashEntry = apps.get_model("cash_book", "CashEntry")

    CashEntry.objects.filter(approval_state="UNSENT", direction="OUT").update(
        approval_state="PENDING"
    )
    CashEntry.objects.filter(direction="IN").exclude(
        approval_state="NOT_REQUIRED"
    ).update(
        approval_state="NOT_REQUIRED",
        approval_sent_at=None,
        approval_decided_at=None,
        approval_decided_by=None,
        approval_note="",
    )


def unsettle(apps, schema_editor):
    """Reversing cannot tell which pending entries were once unsent, and does
    not pretend to: they stay pending, which is true either way."""


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0004_entry_level_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='approval_state',
            field=models.CharField(choices=[('NOT_REQUIRED', 'No approval needed'), ('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Whether this spend has been agreed. A payment starts awaiting approval the moment it is recorded; a receipt needs none.', max_length=16),
        ),
        migrations.RunPython(settle_the_unsent, unsettle),
    ]
