"""
A bunch stops being an approval and becomes what it always was on paper.

Approval moved to the entry in 0004, which left the bunch holding a status, a
decision, a decider and a note that decided nothing. They go here.

What is left is the batch: which vouchers went in one envelope, what they came
to, who made it up and when it was mailed to head office. ``sent_at`` becomes
nullable because it now means what it says -- a batch exists from the moment it
is bundled, and is sent later, if at all. The imported batches keep the send
dates the workbook recorded, so nothing is lost; their sign dates already live
on the entries.
"""

# Generated by Django 6.0.1 on 2026-09-17 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0005_approval_starts_pending'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbunch',
            options={'ordering': ['-number'], 'verbose_name_plural': 'Cash bunches'},
        ),
        migrations.RemoveIndex(
            model_name='cashbunch',
            name='cash_book_c_company_a6c84b_idx',
        ),
        migrations.AlterField(
            model_name='cashbunch',
            name='company',
            field=models.ForeignKey(help_text='The company whose cash box this is.', on_delete=django.db.models.deletion.CASCADE, related_name='cash_bunches', to='company.company'),
        ),
        migrations.AlterField(
            model_name='cashbunch',
            name='number',
            field=models.PositiveIntegerField(help_text='Allocated per company when the batch is made, starting at 1.'),
        ),
        migrations.AlterField(
            model_name='cashbunch',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Anything the sender wants recorded against the batch.'),
        ),
        migrations.AlterField(
            model_name='cashbunch',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the batch went to head office. Null until somebody says it has gone -- the app does not send the mail, so it cannot know.', null=True),
        ),
        migrations.AddIndex(
            model_name='cashbunch',
            index=models.Index(fields=['company', '-number'], name='cash_book_c_company_924e6d_idx'),
        ),
        migrations.RemoveField(
            model_name='cashbunch',
            name='decided_at',
        ),
        migrations.RemoveField(
            model_name='cashbunch',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='cashbunch',
            name='decision_note',
        ),
        migrations.RemoveField(
            model_name='cashbunch',
            name='status',
        ),
    ]
