# Generated by Django 6.0.1 on 2026-09-19 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0009_a_third_thing_that_happens_to_a_float'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Who this payment was sent to. Only they can decide it. Null on receipts, and on payments recorded before approvals were addressed to a person -- those stay open to any approver.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['company', 'approver', 'approval_state'], name='cash_book_c_company_c093bb_idx'),
        ),
    ]
