# Generated by Django 6.0.1 on 2026-09-19 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0011_a_bill_can_be_attached_to_a_line'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, help_text="The sheet's Sr.no. -- the voucher's own number, which is how a payment is referred to away from the screen. Filled in for you with the next one, and typeable when a voucher carries its own.", null=True),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['company', 'serial_number'], name='cash_book_c_company_7c1cdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False)), fields=('company', 'serial_number'), name='cash_entry_serial_unique_per_company'),
        ),
    ]
