# Generated by Django 6.0.1 on 2026-09-22 06:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0012_a_voucher_carries_its_own_number'),
        ('company', '0003_alter_usercompany_role'),
        ('employee_hierarchy', '0006_employee_sap_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paid_on', models.DateField(help_text='The day the cash was handed over.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(blank=True, default='', help_text='What they asked for it for, in their own words. HR decide on this, so a blank one is a decision taken on the amount alone.')),
                ('state', models.CharField(choices=[('PENDING', 'With HR'), ('APPROVED', 'Approved for deduction'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Whether HR have agreed this comes off a wage.', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='', help_text='Required when rejecting, so accounts know why the money is not coming back off a wage.')),
                ('deduct_from', models.DateField(blank=True, help_text='The first of the salary month the amount comes off. Set when HR approve, and defaulted to the month after it was paid.', null=True)),
                ('deducted_on', models.DateField(blank=True, help_text='The day HR recorded the deduction as actually taken. Until it is set, the amount is still to come off a wage.', null=True)),
                ('cash_entry', models.ForeignKey(blank=True, help_text='The voucher on the register that paid it out, when the two were linked. Null when the cash went out some other way -- by bank transfer, or on a voucher nobody joined up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances', to='cash_book.cashentry')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_salary_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Whose wage this comes back off.', on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='employee_hierarchy.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary advance',
                'verbose_name_plural': 'Salary advances',
                'ordering': ['-paid_on', '-id'],
                'permissions': [('can_approve_salary_advances', 'Can approve or reject advances against salary')],
                'indexes': [models.Index(fields=['company', 'state', '-paid_on'], name='cash_book_s_company_99824c_idx'), models.Index(fields=['company', 'employee', '-paid_on'], name='cash_book_s_company_853734_idx'), models.Index(fields=['company', 'state', 'deducted_on'], name='cash_book_s_company_926154_idx')],
            },
        ),
    ]
