# Generated by Django 6.0.1 on 2026-09-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_book', '0013_an_advance_against_a_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='approved_on_paper',
            field=models.BooleanField(default=False, help_text='True when this payment was agreed on a signed voucher rather than on the approvals screen. It is APPROVED either way -- frozen, and counting as spent -- but the two are not the same evidence, and a register that cannot tell them apart cannot be audited. Set only by the custodian, and only with a photograph of the signed voucher against it.'),
        ),
        migrations.AddField(
            model_name='cashentryattachment',
            name='is_approval_proof',
            field=models.BooleanField(default=False, help_text='A photograph of the signed voucher, attached when a payment was approved on paper rather than on this screen.'),
        ),
    ]
