# Generated by Django 6.0.3 on 2026-04-18 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0016_update_line_config_add_name_remove_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_barcode', models.CharField(help_text='Auto-generated, e.g. BOX-20260417-L4-0001', max_length=50, unique=True)),
                ('barcode_data', models.JSONField(blank=True, default=dict, help_text='Encoded QR payload')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('production_line', models.CharField(blank=True, default='', max_length=50)),
                ('current_warehouse', models.CharField(max_length=20)),
                ('current_bin', models.CharField(blank=True, default='', help_text='App-managed bin location (SAP bins not enabled)', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VOID', 'Void')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes_created', to=settings.AUTH_USER_MODEL)),
                ('production_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='production_execution.productionrun')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabelPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('BOX', 'Box'), ('PALLET', 'Pallet'), ('BIN', 'Bin'), ('WAREHOUSE', 'Warehouse')], max_length=20)),
                ('reference_id', models.CharField(help_text='PK of the Box, Pallet, or Bin as string', max_length=100)),
                ('reference_code', models.CharField(help_text='The barcode string itself', max_length=100)),
                ('print_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('REPRINT', 'Reprint')], default='ORIGINAL', max_length=20)),
                ('reprint_reason', models.TextField(blank=True, default='')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('printer_name', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_print_logs', to='company.company')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_prints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Label Print Log',
                'verbose_name_plural': 'Label Print Logs',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_id', models.CharField(help_text='Auto-generated, e.g. PLT-20260417-L4-001', max_length=50, unique=True)),
                ('barcode_data', models.JSONField(blank=True, default=dict, help_text='Encoded QR payload')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('box_count', models.PositiveIntegerField(default=0)),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('production_line', models.CharField(blank=True, default='', max_length=50)),
                ('current_warehouse', models.CharField(max_length=20)),
                ('current_bin', models.CharField(blank=True, default='', help_text='App-managed bin location (SAP bins not enabled)', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLEARED', 'Cleared'), ('SPLIT', 'Split'), ('VOID', 'Void')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets_created', to=settings.AUTH_USER_MODEL)),
                ('production_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='production_execution.productionrun')),
            ],
            options={
                'verbose_name': 'Pallet',
                'verbose_name_plural': 'Pallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoxMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('PALLETIZE', 'Palletize'), ('DEPALLETIZE', 'Depalletize'), ('VOID', 'Void')], max_length=20)),
                ('from_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('to_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('from_bin', models.CharField(blank=True, default='', max_length=50)),
                ('to_bin', models.CharField(blank=True, default='', max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='barcode.box')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_movements', to='company.company')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_movements_performed', to=settings.AUTH_USER_MODEL)),
                ('from_pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_movements_from', to='barcode.pallet')),
                ('to_pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_movements_to', to='barcode.pallet')),
            ],
            options={
                'verbose_name': 'Box Movement',
                'verbose_name_plural': 'Box Movements',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='box',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='barcode.pallet'),
        ),
        migrations.CreateModel(
            name='PalletMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('CLEAR', 'Clear'), ('SPLIT', 'Split'), ('VOID', 'Void')], max_length=20)),
                ('from_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('to_warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('from_bin', models.CharField(blank=True, default='', max_length=50)),
                ('to_bin', models.CharField(blank=True, default='', max_length=50)),
                ('sap_transfer_doc_entry', models.IntegerField(blank=True, help_text='SAP Stock Transfer DocEntry (if posted)', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_movements', to='company.company')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='barcode.pallet')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallet_movements_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pallet Movement',
                'verbose_name_plural': 'Pallet Movements',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('PUTAWAY', 'Putaway'), ('PICK', 'Pick'), ('COUNT', 'Count'), ('TRANSFER', 'Transfer'), ('SHIP', 'Ship'), ('RETURN', 'Return'), ('LOOKUP', 'Lookup')], max_length=20)),
                ('barcode_raw', models.CharField(help_text='Raw scanned string', max_length=500)),
                ('barcode_parsed', models.JSONField(blank=True, default=dict, help_text='Decoded barcode data')),
                ('entity_type', models.CharField(choices=[('BOX', 'Box'), ('PALLET', 'Pallet'), ('BIN', 'Bin'), ('ITEM', 'Item'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('scan_result', models.CharField(choices=[('SUCCESS', 'Success'), ('NOT_FOUND', 'Not Found'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Error')], default='SUCCESS', max_length=20)),
                ('context_ref_type', models.CharField(blank=True, default='', help_text='E.g. count_session, pick_list, transfer', max_length=50)),
                ('context_ref_id', models.IntegerField(blank=True, help_text='PK of the context entity', null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_logs', to='company.company')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
