# Generated by Django 6.0.3 on 2026-04-20 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('DISMANTLED', 'Dismantled'), ('VOID', 'Void')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='boxmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('PALLETIZE', 'Palletize'), ('DEPALLETIZE', 'Depalletize'), ('DISMANTLE', 'Dismantle'), ('VOID', 'Void')], max_length=20),
        ),
        migrations.CreateModel(
            name='LooseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_qty', models.DecimalField(decimal_places=2, help_text='Qty at time of dismantle (before any repack consumption)', max_digits=12)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(choices=[('REPACK', 'Repack'), ('SAMPLE', 'Sample'), ('DAMAGED', 'Damaged'), ('RETURN', 'Return'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('reason_notes', models.TextField(blank=True, default='')),
                ('current_warehouse', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPACKED', 'Repacked'), ('CONSUMED', 'Consumed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loose_stocks', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_stocks_created', to=settings.AUTH_USER_MODEL)),
                ('repacked_into_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repacked_from', to='barcode.box')),
                ('source_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_stocks', to='barcode.box')),
                ('source_pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_stocks', to='barcode.pallet')),
            ],
            options={
                'verbose_name': 'Loose Stock',
                'verbose_name_plural': 'Loose Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
