# Generated by Django 6.0.3 on 2026-04-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_alter_box_status_alter_boxmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('DISMANTLE', 'Dismantle'), ('CLEAR', 'Clear'), ('SPLIT', 'Split'), ('VOID', 'Void')], max_length=20),
        ),
    ]
