# Generated by Django 6.0.3 on 2026-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0003_alter_palletmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='g_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='n_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
