# Generated by Django 6.0.1 on 2026-07-08 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0012_intercompanytransfer_entity_type'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletVerifyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('DISPATCH', 'Dispatch')], default='MANUAL', max_length=20)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Originating context, e.g. a dispatch bill number', max_length=100)),
                ('reason', models.TextField(blank=True, default='', help_text="Requester's note describing the problem")),
                ('findings', models.JSONField(blank=True, default=dict, help_text="Snapshot of the requester's reconcile result at submit time")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_verify_requests', to='company.company')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_requests', to='barcode.pallet')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallet_verify_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallet_verify_requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pallet Verify Request',
                'verbose_name_plural': 'Pallet Verify Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='barcode_pal_company_e1e369_idx'), models.Index(fields=['requested_by', 'status'], name='barcode_pal_request_5a56eb_idx')],
            },
        ),
    ]
