# Generated by Django 6.0.1 on 2026-07-04 11:43

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('barcode', '0012_intercompanytransfer_entity_type'),
        ('company', '0003_alter_usercompany_role'),
        ('production_execution', '0023_alter_machinebreakdown_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='box',
            index=models.Index(fields=['company', 'status', '-created_at'], name='box_co_status_created_idx'),
        ),
        AddIndexConcurrently(
            model_name='scanlog',
            index=models.Index(fields=['company', '-scanned_at'], name='scanlog_co_scanned_idx'),
        ),
        AddIndexConcurrently(
            model_name='scanlog',
            index=models.Index(fields=['company', 'entity_type'], name='scanlog_co_entity_idx'),
        ),
    ]
