# Generated by Django 6.0.1 on 2026-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0013_palletverifyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxmovement',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
