# Generated by Django 6.0.1 on 2026-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0014_boxmovement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercompanytransfer',
            name='destination_warehouse',
            field=models.CharField(blank=True, default='', help_text='Destination-company warehouse the stock was received into (blank = stock kept its source warehouse code)', max_length=20),
        ),
        migrations.AddField(
            model_name='intercompanytransferline',
            name='from_warehouse',
            field=models.CharField(blank=True, default='', help_text="Box's warehouse at transfer time (restored on reverse)", max_length=20),
        ),
    ]
