# Generated by Django 6.0.1 on 2026-08-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0015_intercompanytransfer_destination_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='pre_load_bin',
            field=models.CharField(blank=True, default='', help_text='Bin before the box was loaded INSIDE_VEHICLE (restored on unscan)', max_length=50),
        ),
        migrations.AddField(
            model_name='box',
            name='pre_load_status',
            field=models.CharField(blank=True, default='', help_text='Status before the box was loaded INSIDE_VEHICLE (restored on unscan)', max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('INSIDE_VEHICLE', 'Inside Vehicle'), ('DISPATCHED', 'Dispatched'), ('DISMANTLED', 'Dismantled'), ('VOID', 'Void')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='boxmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('OWNERSHIP_TRANSFER', 'Ownership Transfer'), ('LOAD_VEHICLE', 'Loaded into Vehicle'), ('UNLOAD_VEHICLE', 'Unloaded from Vehicle'), ('PALLETIZE', 'Palletize'), ('DEPALLETIZE', 'Depalletize'), ('DISPATCH', 'Dispatch'), ('REMOVE_FOR_DISPATCH', 'Remove for Dispatch'), ('DISMANTLE', 'Dismantle'), ('VOID', 'Void')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('INSIDE_VEHICLE', 'Inside Vehicle'), ('DISPATCHED', 'Dispatched'), ('EMPTY', 'Empty'), ('INACTIVE', 'Inactive'), ('CLEARED', 'Cleared'), ('SPLIT', 'Split'), ('VOID', 'Void')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='palletmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('OWNERSHIP_TRANSFER', 'Ownership Transfer'), ('LOAD_VEHICLE', 'Loaded into Vehicle'), ('UNLOAD_VEHICLE', 'Unloaded from Vehicle'), ('DISPATCH', 'Dispatch'), ('REMOVE_FOR_DISPATCH', 'Remove for Dispatch'), ('DISMANTLE', 'Dismantle'), ('CLEAR', 'Clear'), ('SPLIT', 'Split'), ('VOID', 'Void')], max_length=20),
        ),
    ]
