# Generated by Django 6.0.1 on 2026-08-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0016_box_pre_load_bin_box_pre_load_status_and_more'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LooseStockConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_consumptions', to='barcode.box')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loose_stock_consumptions', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_stock_consumptions_created', to=settings.AUTH_USER_MODEL)),
                ('loose_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='barcode.loosestock')),
            ],
            options={
                'verbose_name': 'Loose Stock Consumption',
                'verbose_name_plural': 'Loose Stock Consumptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
