# Generated by Django 6.0.1 on 2026-08-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0017_loosestockconsumption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_box_generation_qty', 'Can edit qty per box on barcode label generation')], 'verbose_name': 'Box', 'verbose_name_plural': 'Boxes'},
        ),
    ]
