# Generated by Django 6.0.1 on 2026-08-24 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0018_alter_box_options'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='reject_code',
            field=models.CharField(blank=True, default='', help_text='Machine-readable reason a REJECTED scan was refused', max_length=80),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='reject_message',
            field=models.TextField(blank=True, default='', help_text='Operator-facing text shown for a REJECTED scan'),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='scan_result',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('NOT_FOUND', 'Not Found'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='SUCCESS', max_length=20),
        ),
    ]
