# Generated by Django 6.0.1 on 2026-09-08 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0020_scanlog_reject_indexes'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='activation_source',
            field=models.CharField(blank=True, choices=[('GATE_SCAN', 'Gate Scan'), ('APPROVAL', 'Approval'), ('REPACK', 'Repack'), ('NOT_REQUIRED', 'Not Required'), ('LEGACY', 'Legacy')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='box',
            name='activation_warehouse',
            field=models.CharField(blank=True, default='', help_text='Warehouse the unit was received into at activation', max_length=20),
        ),
        migrations.AddField(
            model_name='pallet',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pallet',
            name='activation_source',
            field=models.CharField(blank=True, choices=[('GATE_SCAN', 'Gate Scan'), ('APPROVAL', 'Approval'), ('REPACK', 'Repack'), ('NOT_REQUIRED', 'Not Required'), ('LEGACY', 'Legacy')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pallet',
            name='activation_warehouse',
            field=models.CharField(blank=True, default='', help_text='Warehouse the unit was received into at activation', max_length=20),
        ),
        migrations.AlterField(
            model_name='barcodeauditlog',
            name='transaction_type',
            field=models.CharField(choices=[('MANUFACTURED', 'Manufactured'), ('ACTIVATED', 'Activated'), ('SCANNED', 'Scanned'), ('TRANSFER_CREATED', 'Transfer Created'), ('TRANSFER_COMPLETED', 'Transfer Completed'), ('TRANSFER_REVERSED', 'Transfer Reversed'), ('DISPATCH_COMPLETED', 'Dispatch Completed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('INSIDE_VEHICLE', 'Inside Vehicle'), ('DISPATCHED', 'Dispatched'), ('DISMANTLED', 'Dismantled'), ('VOID', 'Void')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='boxmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('ACTIVATE', 'Activated'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('OWNERSHIP_TRANSFER', 'Ownership Transfer'), ('LOAD_VEHICLE', 'Loaded into Vehicle'), ('UNLOAD_VEHICLE', 'Unloaded from Vehicle'), ('PALLETIZE', 'Palletize'), ('DEPALLETIZE', 'Depalletize'), ('DISPATCH', 'Dispatch'), ('REMOVE_FOR_DISPATCH', 'Remove for Dispatch'), ('DISMANTLE', 'Dismantle'), ('VOID', 'Void')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('INSIDE_VEHICLE', 'Inside Vehicle'), ('DISPATCHED', 'Dispatched'), ('EMPTY', 'Empty'), ('INACTIVE', 'Inactive'), ('CLEARED', 'Cleared'), ('SPLIT', 'Split'), ('VOID', 'Void')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='palletmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('ACTIVATE', 'Activated'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('OWNERSHIP_TRANSFER', 'Ownership Transfer'), ('LOAD_VEHICLE', 'Loaded into Vehicle'), ('UNLOAD_VEHICLE', 'Unloaded from Vehicle'), ('DISPATCH', 'Dispatch'), ('REMOVE_FOR_DISPATCH', 'Remove for Dispatch'), ('DISMANTLE', 'Dismantle'), ('CLEAR', 'Clear'), ('SPLIT', 'Split'), ('VOID', 'Void')], max_length=20),
        ),
        migrations.AlterField(
            model_name='palletverifyrequest',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('DISPATCH', 'Dispatch'), ('GATE', 'Godown Gate')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='scan_type',
            field=models.CharField(choices=[('RECEIVE', 'Receive'), ('ACTIVATE', 'Activate'), ('PUTAWAY', 'Putaway'), ('PICK', 'Pick'), ('COUNT', 'Count'), ('TRANSFER', 'Transfer'), ('SHIP', 'Ship'), ('RETURN', 'Return'), ('LOOKUP', 'Lookup')], max_length=20),
        ),
        migrations.CreateModel(
            name='BarcodeActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('warehouse', models.CharField(blank=True, default='', help_text='Warehouse the labels were printed for', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_activation_requests', to='company.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_activation_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_requests', to='barcode.pallet')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_activation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barcode Activation Request',
                'verbose_name_plural': 'Barcode Activation Requests',
                'ordering': ['-requested_at'],
                'permissions': [('can_request_barcode_activation', 'Can request activation of printed barcodes'), ('can_approve_barcode_activation', 'Can approve activation of printed barcodes')],
            },
        ),
        migrations.CreateModel(
            name='BarcodeActivationRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_request_lines', to='barcode.box')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='barcode.barcodeactivationrequest')),
            ],
            options={
                'verbose_name': 'Barcode Activation Request Line',
                'verbose_name_plural': 'Barcode Activation Request Lines',
            },
        ),
        migrations.CreateModel(
            name='BarcodeActivationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch for this company')),
                ('enforced_warehouses', models.JSONField(blank=True, default=list, help_text='Warehouse codes whose printed labels are born inactive, e.g. ["BH-PF"]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_activation_settings', to='company.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_activation_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barcode Activation Settings',
                'verbose_name_plural': 'Barcode Activation Settings',
            },
        ),
        migrations.AddIndex(
            model_name='barcodeactivationrequest',
            index=models.Index(fields=['company', 'status'], name='barcode_bar_company_f88824_idx'),
        ),
        migrations.AddIndex(
            model_name='barcodeactivationrequest',
            index=models.Index(fields=['requested_by', 'status'], name='barcode_bar_request_9d0526_idx'),
        ),
        migrations.AddConstraint(
            model_name='barcodeactivationrequestline',
            constraint=models.UniqueConstraint(fields=('request', 'box'), name='unique_activation_request_box'),
        ),
    ]
