# Generated by Django 6.0.3 on 2026-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0010_add_po_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitemreceipt',
            name='variety',
            field=models.CharField(blank=True, default='', help_text='Item variety from PO (POR1.U_Variety)', max_length=100),
        ),
    ]
