# Generated by Django 6.0.1 on 2026-04-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0011_add_variety_to_po_item_receipt'),
        ('raw_material_gatein', '0011_remove_poitemreceipt_unique_together'),
    ]

    operations = [
    ]
