# Generated by Django 6.0.1 on 2026-06-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0012_add_qc_hold_status'),
        ('raw_material_gatein', '0013_add_po_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POReplacementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_po_number', models.CharField(max_length=30)),
                ('old_supplier_code', models.CharField(blank=True, default='', max_length=30)),
                ('old_supplier_name', models.CharField(blank=True, default='', max_length=150)),
                ('new_po_number', models.CharField(max_length=30)),
                ('new_supplier_code', models.CharField(blank=True, default='', max_length=30)),
                ('new_supplier_name', models.CharField(blank=True, default='', max_length=150)),
                ('supplier_changed', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('previous_qc_remark', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_replacement_logs', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
