# Generated by Django 6.0.1 on 2026-09-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material_gatein', '0014_poreplacementlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poreceipt',
            options={'permissions': [('can_complete_raw_material_entry', 'Can complete raw material gate entry'), ('can_receive_po', 'Can receive PO items'), ('can_repoint_po_receipt', 'Can move a received PO onto another open PO')]},
        ),
    ]
