# Generated by Django 6.0.1 on 2026-10-10 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=30)),
                ('kind', models.CharField(choices=[('FG_FILLING', 'FG filling')], default='FG_FILLING', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('ISSUED', 'Materials issued'), ('RECEIVED', 'FG created'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('pieces_per_box', models.DecimalField(decimal_places=6, max_digits=19)),
                ('litres_per_piece', models.DecimalField(blank=True, decimal_places=6, help_text="OITM.SalPackUn, for the litres SAP's stock caps count.", max_digits=19, null=True)),
                ('boxes', models.PositiveIntegerField(default=0)),
                ('loose_pieces', models.PositiveIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=6, help_text="Pieces: the order's planned quantity.", max_digits=19)),
                ('warehouse', models.CharField(help_text="Where the goods are received (the BOM's).", max_length=8)),
                ('bom_quantity', models.DecimalField(decimal_places=6, help_text="OITT.Qauntity: the BOM's lines are per this many pieces.", max_digits=19)),
                ('posting_date', models.DateField(help_text="The order's posting, start and due date.")),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('variety', models.CharField(blank=True, default='', help_text="OOCR code (dimension 1) on the issue and receipt lines; the product's by default.", max_length=8)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('line_code', models.CharField(blank=True, choices=[('L1', 'Line 1 (Clear Pack)'), ('L2', 'Line 2 (JP Machine)'), ('L3', 'Line 3 (10 Head)'), ('L4', 'Line 4 (6 Head)'), ('L5', 'Line 5 (Tin Head)'), ('M', 'Manual (small packs)')], default='', max_length=2)),
                ('oil_code', models.CharField(blank=True, default='', max_length=10)),
                ('batch_sequence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=36)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('sap_order_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('sap_order_num', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sap_issue_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('sap_issue_num', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sap_receipt_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('sap_receipt_num', models.PositiveBigIntegerField(blank=True, null=True)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_entries', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posting_date', '-id'],
                'permissions': [('can_view_production_orders', 'Can view production order entries'), ('can_create_production_orders', 'Can enter production and plan the SAP production order'), ('can_release_production_orders', 'Can release SAP production orders'), ('can_issue_production_orders', 'Can issue materials to SAP production orders'), ('can_receive_production_orders', 'Can receive finished goods from SAP production orders'), ('can_close_production_orders', 'Can close SAP production orders')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text="The line's place in the BOM.")),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('item_type', models.CharField(choices=[('item', 'Item'), ('resource', 'Resource')], default='item', max_length=10)),
                ('issue_method', models.CharField(default='M', help_text='ITT1.IssueMthd: M or B.', max_length=1)),
                ('base_quantity', models.DecimalField(decimal_places=6, help_text='Per piece of the product (BOM quantity ÷ BOM size).', max_digits=19)),
                ('planned_quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('warehouse', models.CharField(max_length=8)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('batch_managed', models.BooleanField(default=False)),
                ('sap_line_num', models.PositiveSmallIntegerField(blank=True, help_text='WOR1.LineNum, once the order is in SAP.', null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production_orders.productionorderentry')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderEntryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=36)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production_orders.productionorderentryline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='productionorderentry',
            index=models.Index(fields=['company', 'status'], name='production__company_9132f3_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorderentry',
            index=models.Index(fields=['company', 'posting_date'], name='production__company_2a07fa_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorderentry',
            index=models.Index(fields=['company', 'item_code', 'batch_number'], name='production__company_ac89b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionorderentry',
            constraint=models.UniqueConstraint(fields=('company', 'entry_no'), name='prod_order_entry_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='productionorderentryline',
            constraint=models.UniqueConstraint(fields=('entry', 'position'), name='prod_order_line_position_unique'),
        ),
    ]
