# Generated by Django 6.0.1 on 2026-06-25 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        ('person_gatein', '0007_entrylog_actual_entry_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourCountSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_date', models.DateField(help_text='For NIGHT, the shift-start date')),
                ('shift', models.CharField(choices=[('DAY', 'Day (07:00-19:00)'), ('NIGHT', 'Night (19:00-07:00)')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified')], default='DRAFT', max_length=10)),
                ('is_holiday', models.BooleanField(default=False)),
                ('lock_at', models.DateTimeField(help_text='After this, the sheet is auto-submitted and locked')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('gate_counted', models.PositiveIntegerField(blank=True, null=True)),
                ('verify_basis', models.CharField(blank=True, choices=[('TOTAL', 'Grand Total'), ('DEPARTMENT', 'Department'), ('CONTRACTOR', 'Contractor')], max_length=12)),
                ('verify_remark', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_count_sheets', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_count_sheets', to='accounts.department')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_sheets_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_sheets_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Count Sheet',
                'verbose_name_plural': 'Labour Count Sheets',
                'ordering': ['-work_date', 'department_id'],
                'permissions': [('can_submit_labour_count', 'Can submit labour count'), ('can_verify_labour_count', 'Can verify labour count')],
            },
        ),
        migrations.CreateModel(
            name='LabourCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_count_items', to='person_gatein.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labour_count.labourcountsheet')),
            ],
            options={
                'verbose_name': 'Labour Count Item',
                'verbose_name_plural': 'Labour Count Items',
                'ordering': ['contractor_id'],
            },
        ),
        migrations.CreateModel(
            name='LabourShiftWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shift', models.CharField(choices=[('DAY', 'Day (07:00-19:00)'), ('NIGHT', 'Night (19:00-07:00)')], max_length=10)),
                ('submit_lock_time', models.TimeField(help_text='Daily auto-submit / lock time (IST)')),
                ('verify_deadline_time', models.TimeField(help_text='Gate verification deadline (IST)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_shift_windows', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Shift Window',
                'verbose_name_plural': 'Labour Shift Windows',
            },
        ),
        migrations.AddIndex(
            model_name='labourcountsheet',
            index=models.Index(fields=['work_date', 'shift'], name='labour_coun_work_da_e68b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='labourcountsheet',
            index=models.Index(fields=['status'], name='labour_coun_status_6fe889_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labourcountsheet',
            unique_together={('company', 'department', 'work_date', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='labourcountitem',
            unique_together={('sheet', 'contractor')},
        ),
        migrations.AlterUniqueTogether(
            name='labourshiftwindow',
            unique_together={('company', 'shift')},
        ),
    ]
