# Generated by Django 6.0.1 on 2026-06-25 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cleanup_stale_permissions'),
        ('company', '0003_alter_usercompany_role'),
        ('labour_count', '0001_initial'),
        ('person_gatein', '0007_entrylog_actual_entry_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_date', models.DateField()),
                ('shift', models.CharField(choices=[('DAY', 'Day (07:00-19:00)'), ('NIGHT', 'Night (19:00-07:00)')], max_length=10)),
                ('basis', models.CharField(choices=[('TOTAL', 'Grand Total'), ('DEPARTMENT', 'Department'), ('CONTRACTOR', 'Contractor')], max_length=12)),
                ('submitted_total', models.PositiveIntegerField()),
                ('gate_counted', models.PositiveIntegerField()),
                ('variance', models.IntegerField(help_text='gate_counted - submitted_total')),
                ('remark', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_verifications', to='company.company')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_verifications', to='person_gatein.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_verifications', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Verification',
                'verbose_name_plural': 'Labour Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
