# Generated by Django 6.0.1 on 2026-07-30 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0015_alter_vehicleentry_entry_type'),
        ('vehicle_management', '0008_vehicle_height_m_vehicle_length_m_vehicle_width_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('basis', models.CharField(choices=[('INVOICE', 'Against Invoice'), ('DEBIT_NOTE', 'Against Debit Note'), ('LETTER_PAD', 'Against Letter Pad')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_ARRIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('expected_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('gated_in_at', models.DateTimeField(blank=True, null=True)),
                ('sap_gr_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_gr_doc_num', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_returns', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_returns', to='driver_management.driver')),
                ('gated_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_returns_gated_in', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_returns_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_returns', to='vehicle_management.vehicle')),
                ('vehicle_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_return', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_goods_return', 'Can view goods return'), ('can_create_goods_return', 'Can create goods return'), ('can_edit_goods_return', 'Can edit goods return'), ('can_submit_goods_return', 'Can submit goods return'), ('can_gate_in_goods_return', 'Can gate in goods return')],
            },
        ),
        migrations.CreateModel(
            name='GoodsReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('INVOICE_COPY', 'Invoice Copy'), ('DEBIT_NOTE', 'Debit Note'), ('LETTER_PAD', 'Letter Pad'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='goods_return/attachments/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('goods_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='goods_return.goodsreturn')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_return_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReturnInvoiceRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_invoice_doc_entry', models.IntegerField()),
                ('sap_invoice_doc_num', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('goods_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_refs', to='goods_return.goodsreturn')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_line_num', models.IntegerField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoice_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('return_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], default='DAMAGED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('goods_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='goods_return.goodsreturn')),
                ('invoice_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='goods_return.goodsreturninvoiceref')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_line_num', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreturn',
            index=models.Index(fields=['company', 'status'], name='goods_retur_company_212621_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreturn',
            index=models.Index(fields=['status', 'expected_arrival_at'], name='goods_retur_status_cf25d5_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreturn',
            index=models.Index(fields=['vehicle'], name='goods_retur_vehicle_ed07d6_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreturnattachment',
            index=models.Index(fields=['goods_return', 'attachment_type'], name='goods_retur_goods_r_ab7ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreturninvoiceref',
            index=models.Index(fields=['sap_invoice_doc_entry'], name='goods_retur_sap_inv_3aa303_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsreturninvoiceref',
            constraint=models.UniqueConstraint(fields=('goods_return', 'sap_invoice_doc_entry'), name='uniq_goodsreturn_invoice_ref'),
        ),
        migrations.AddIndex(
            model_name='goodsreturnitem',
            index=models.Index(fields=['goods_return'], name='goods_retur_goods_r_8a4c5f_idx'),
        ),
    ]
