# Generated by Django 6.0.1 on 2026-07-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0002_create_goods_return_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreturn',
            name='expected_arrival_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
