# Generated by Django 6.0.1 on 2026-08-03 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0003_alter_goodsreturn_expected_arrival_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreturn',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_view_goods_return', 'Can view goods return'), ('can_create_goods_return', 'Can create goods return'), ('can_edit_goods_return', 'Can edit goods return'), ('can_submit_goods_return', 'Can submit goods return'), ('can_gate_in_goods_return', 'Can gate in goods return'), ('can_receive_goods_return', 'Can receive/post a goods return')]},
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_returns_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='sap_return_warehouse',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goodsreturnitem',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='goodsreturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='goodsreturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_ARRIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('POSTED', 'Posted to SAP'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
