# Generated by Django 6.0.1 on 2026-08-04 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0005_resync_goods_return_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreturn',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_view_goods_return', 'Can view goods return'), ('can_create_goods_return', 'Can create goods return'), ('can_edit_goods_return', 'Can edit goods return'), ('can_submit_goods_return', 'Can submit goods return'), ('can_gate_in_goods_return', 'Can gate in goods return'), ('can_receive_goods_return', 'Can receive/post a goods return'), ('can_approve_goods_return', 'Can approve/reject a goods return')]},
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
    ]
