# Generated by Django 6.0.1 on 2026-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0007_resync_goods_return_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_ARRIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('RECEIVED', 'Received (not in SAP)'), ('POSTED', 'Posted to SAP'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
