# Generated by Django 6.0.1 on 2026-08-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0008_honest_received_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreturnitem',
            name='original_batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
