# Generated by Django 6.0.1 on 2026-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0009_original_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreturninvoiceref',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreturninvoiceref',
            name='sap_gr_doc_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreturninvoiceref',
            name='sap_gr_doc_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goodsreturninvoiceref',
            name='sap_post_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goodsreturninvoiceref',
            name='sap_return_warehouse',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='goodsreturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_ARRIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('RECEIVED', 'Received (not in SAP)'), ('PARTIALLY_POSTED', 'Partly posted to SAP'), ('POSTED', 'Posted to SAP'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
