# Generated by Django 6.0.1 on 2026-09-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0011_backfill_invoice_level_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreturnitem',
            options={'ordering': [models.OrderBy(models.F('invoice_ref'), nulls_last=True), 'source_line_num', 'id']},
        ),
    ]
