# Generated by Django 6.0.1 on 2026-09-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0012_line_order_by_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreturn',
            name='customer_ref_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
