# Generated by Django 6.0.1 on 2026-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0013_customer_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreturnitem',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('LEAKED', 'Leaked'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], default='DAMAGED', max_length=20),
        ),
    ]
