# Generated by Django 6.0.1 on 2026-09-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0015_invoice_ref_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_ARRIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('RECEIVED', 'Received (not in SAP)'), ('SAP_QUEUED', 'Received (waiting for SAP)'), ('PARTIALLY_POSTED', 'Partly posted to SAP'), ('POSTED', 'Posted to SAP'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
