# Generated by Django 6.0.1 on 2026-10-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_return', '0016_alter_goodsreturn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreturn',
            name='comes_on_vehicle',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
