# Generated by Codex on 2026-06-16

from django.db import migrations, models


NOTIFICATION_TYPE_CHOICES = [
    ("GATE_ENTRY_CREATED", "Gate Entry Created"),
    ("GATE_ENTRY_STATUS_CHANGED", "Gate Entry Status Changed"),
    ("SECURITY_CHECK_DONE", "Security Check Completed"),
    ("WEIGHMENT_RECORDED", "Weighment Recorded"),
    ("ARRIVAL_SLIP_SUBMITTED", "Arrival Slip Submitted"),
    ("ARRIVAL_SLIP_SENT_BACK", "Arrival Slip Sent Back to Gate"),
    ("QC_INSPECTION_SUBMITTED", "QC Inspection Submitted"),
    ("QC_CHEMIST_APPROVED", "QC Chemist Approved"),
    ("QC_QAM_APPROVED", "QC QAM Approved"),
    ("QC_REJECTED", "QC Rejected"),
    ("QC_HOLD", "QC On Hold"),
    ("QC_COMPLETED", "QC Completed"),
    ("FACTORY_HEAD_DECISION_REQUIRED", "Factory Head Decision Required"),
    ("FACTORY_HEAD_DECISION_RECORDED", "Factory Head Decision Recorded"),
    ("PO_RECEIVED", "PO Items Received"),
    ("GATE_ENTRY_COMPLETED", "Gate Entry Completed"),
    ("GRPO_POSTED", "GRPO Posted to SAP"),
    ("GRPO_FAILED", "GRPO Posting Failed"),
    ("SERVICE_GRPO_POSTED", "Service GRPO Posted to SAP"),
    ("SERVICE_GRPO_FAILED", "Service GRPO Posting Failed"),
    ("STOCK_ALERT", "Stock Level Alert"),
    ("DOCKING_SCAN_SKIP_REQUESTED", "Docking Scan Skip Requested"),
    ("DOCKING_SCAN_SKIP_REVIEWED", "Docking Scan Skip Reviewed"),
    ("GENERAL_ANNOUNCEMENT", "General Announcement"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_notificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=NOTIFICATION_TYPE_CHOICES,
                default="GENERAL_ANNOUNCEMENT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=NOTIFICATION_TYPE_CHOICES,
                max_length=50,
            ),
        ),
    ]
