# Generated by Django 6.0.1 on 2026-06-16 10:29

from django.db import migrations, models


WORKFLOW_NOTIFICATION_GROUPS = [
    "warehouse",
    "production",
    "dispatch",
    "barcode",
]


def create_workflow_notification_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in WORKFLOW_NOTIFICATION_GROUPS:
        Group.objects.get_or_create(name=name)


def remove_workflow_notification_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=WORKFLOW_NOTIFICATION_GROUPS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_workflow_notification_groups,
            remove_workflow_notification_groups,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GATE_ENTRY_CREATED', 'Gate Entry Created'), ('GATE_ENTRY_STATUS_CHANGED', 'Gate Entry Status Changed'), ('SECURITY_CHECK_DONE', 'Security Check Completed'), ('WEIGHMENT_RECORDED', 'Weighment Recorded'), ('ARRIVAL_SLIP_SUBMITTED', 'Arrival Slip Submitted'), ('ARRIVAL_SLIP_SENT_BACK', 'Arrival Slip Sent Back to Gate'), ('QC_INSPECTION_SUBMITTED', 'QC Inspection Submitted'), ('QC_CHEMIST_APPROVED', 'QC Chemist Approved'), ('QC_QAM_APPROVED', 'QC QAM Approved'), ('QC_REJECTED', 'QC Rejected'), ('QC_HOLD', 'QC On Hold'), ('QC_COMPLETED', 'QC Completed'), ('FACTORY_HEAD_DECISION_REQUIRED', 'Factory Head Decision Required'), ('FACTORY_HEAD_DECISION_RECORDED', 'Factory Head Decision Recorded'), ('PO_RECEIVED', 'PO Items Received'), ('GATE_ENTRY_COMPLETED', 'Gate Entry Completed'), ('DAILY_NEED_ENTRY_CREATED', 'Daily Need Gate Entry Created'), ('MAINTENANCE_ENTRY_CREATED', 'Maintenance Gate Entry Created'), ('CONSTRUCTION_ENTRY_CREATED', 'Construction Gate Entry Created'), ('PERSON_ENTRY_CREATED', 'Person Gate Entry Created'), ('PERSON_ENTRY_EXITED', 'Person Gate Exit Recorded'), ('GRPO_POSTED', 'GRPO Posted to SAP'), ('GRPO_FAILED', 'GRPO Posting Failed'), ('SERVICE_GRPO_POSTED', 'Service GRPO Posted to SAP'), ('SERVICE_GRPO_FAILED', 'Service GRPO Posting Failed'), ('BOM_REQUEST_CREATED', 'BOM Request Submitted to Warehouse'), ('BOM_REQUEST_REVIEWED', 'BOM Request Reviewed'), ('FG_RECEIPT_POSTED', 'Finished Goods Receipt Posted'), ('FG_RECEIPT_FAILED', 'Finished Goods Receipt Failed'), ('PRODUCTION_RUN_SAP_POSTED', 'Production Run Posted to SAP'), ('PRODUCTION_RUN_SAP_FAILED', 'Production Run SAP Posting Failed'), ('DISPATCH_PLAN_BOOKED', 'Dispatch Plan Booked'), ('DISPATCH_PLAN_DISPATCHED', 'Dispatch Plan Dispatched'), ('INTERCOMPANY_TRANSFER_COMPLETED', 'Intercompany Transfer Completed'), ('INTERCOMPANY_TRANSFER_FAILED', 'Intercompany Transfer SAP Failed'), ('STOCK_ALERT', 'Stock Level Alert'), ('DOCKING_SCAN_SKIP_REQUESTED', 'Docking Scan Skip Requested'), ('DOCKING_SCAN_SKIP_REVIEWED', 'Docking Scan Skip Reviewed'), ('GENERAL_ANNOUNCEMENT', 'General Announcement')], default='GENERAL_ANNOUNCEMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('GATE_ENTRY_CREATED', 'Gate Entry Created'), ('GATE_ENTRY_STATUS_CHANGED', 'Gate Entry Status Changed'), ('SECURITY_CHECK_DONE', 'Security Check Completed'), ('WEIGHMENT_RECORDED', 'Weighment Recorded'), ('ARRIVAL_SLIP_SUBMITTED', 'Arrival Slip Submitted'), ('ARRIVAL_SLIP_SENT_BACK', 'Arrival Slip Sent Back to Gate'), ('QC_INSPECTION_SUBMITTED', 'QC Inspection Submitted'), ('QC_CHEMIST_APPROVED', 'QC Chemist Approved'), ('QC_QAM_APPROVED', 'QC QAM Approved'), ('QC_REJECTED', 'QC Rejected'), ('QC_HOLD', 'QC On Hold'), ('QC_COMPLETED', 'QC Completed'), ('FACTORY_HEAD_DECISION_REQUIRED', 'Factory Head Decision Required'), ('FACTORY_HEAD_DECISION_RECORDED', 'Factory Head Decision Recorded'), ('PO_RECEIVED', 'PO Items Received'), ('GATE_ENTRY_COMPLETED', 'Gate Entry Completed'), ('DAILY_NEED_ENTRY_CREATED', 'Daily Need Gate Entry Created'), ('MAINTENANCE_ENTRY_CREATED', 'Maintenance Gate Entry Created'), ('CONSTRUCTION_ENTRY_CREATED', 'Construction Gate Entry Created'), ('PERSON_ENTRY_CREATED', 'Person Gate Entry Created'), ('PERSON_ENTRY_EXITED', 'Person Gate Exit Recorded'), ('GRPO_POSTED', 'GRPO Posted to SAP'), ('GRPO_FAILED', 'GRPO Posting Failed'), ('SERVICE_GRPO_POSTED', 'Service GRPO Posted to SAP'), ('SERVICE_GRPO_FAILED', 'Service GRPO Posting Failed'), ('BOM_REQUEST_CREATED', 'BOM Request Submitted to Warehouse'), ('BOM_REQUEST_REVIEWED', 'BOM Request Reviewed'), ('FG_RECEIPT_POSTED', 'Finished Goods Receipt Posted'), ('FG_RECEIPT_FAILED', 'Finished Goods Receipt Failed'), ('PRODUCTION_RUN_SAP_POSTED', 'Production Run Posted to SAP'), ('PRODUCTION_RUN_SAP_FAILED', 'Production Run SAP Posting Failed'), ('DISPATCH_PLAN_BOOKED', 'Dispatch Plan Booked'), ('DISPATCH_PLAN_DISPATCHED', 'Dispatch Plan Dispatched'), ('INTERCOMPANY_TRANSFER_COMPLETED', 'Intercompany Transfer Completed'), ('INTERCOMPANY_TRANSFER_FAILED', 'Intercompany Transfer SAP Failed'), ('STOCK_ALERT', 'Stock Level Alert'), ('DOCKING_SCAN_SKIP_REQUESTED', 'Docking Scan Skip Requested'), ('DOCKING_SCAN_SKIP_REVIEWED', 'Docking Scan Skip Reviewed'), ('GENERAL_ANNOUNCEMENT', 'General Announcement')], max_length=50),
        ),
    ]
