# Generated by Django 6.0.1 on 2026-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_create_attendance_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_employee_date_attendance',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='direction',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3),
        ),
    ]
