# Generated by Django 6.0.1 on 2026-09-17 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_grant_attendance_to_gate_groups'),
        ('employee_hierarchy', '0005_permanent_labour_shared_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'permissions': [('can_view_daily_attendance', 'Can view the daily attendance sheet'), ('can_override_attendance_status', "Can change an attendance status away from the machine's"), ('can_sync_attendance', 'Can trigger a punch-machine sync'), ('can_export_attendance', 'Can export attendance')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_attendance_records', to='employee_hierarchy.employee'),
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('machine_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('MISSING_PUNCH', 'Missing punch'), ('WEEKLY_OFF', 'Weekly off'), ('ON_LEAVE', 'On leave'), ('ON_DUTY', 'On duty (outside the plant)'), ('HOLIDAY', 'Holiday')], default='ABSENT', help_text='Derived from the punches alone. Immutable once the sync has written it.', max_length=20)),
                ('machine_first_punch', models.TimeField(blank=True, help_text='First punch of the day -- treated as the arrival.', null=True)),
                ('machine_last_punch', models.TimeField(blank=True, help_text='Last punch of the day -- the departure. Equals the first when only one was read.', null=True)),
                ('machine_punch_count', models.PositiveSmallIntegerField(default=0)),
                ('machine_worked_minutes', models.PositiveIntegerField(default=0, help_text='Last punch minus first. Time between gate reads, not productive time.')),
                ('devices', models.CharField(blank=True, default='', help_text='Serials of the readers that saw them, comma separated.', max_length=255)),
                ('effective_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('MISSING_PUNCH', 'Missing punch'), ('WEEKLY_OFF', 'Weekly off'), ('ON_LEAVE', 'On leave'), ('ON_DUTY', 'On duty (outside the plant)'), ('HOLIDAY', 'Holiday')], db_index=True, default='ABSENT', help_text='The status the business goes with. Equals machine_status unless overridden.', max_length=20)),
                ('is_overridden', models.BooleanField(db_index=True, default=False)),
                ('override_reason_code', models.CharField(blank=True, choices=[('FORGOT_PUNCH', 'Forgot to punch'), ('MACHINE_FAILURE', 'Punching machine failed'), ('FINGERPRINT_FAILED', 'Fingerprint not recognised'), ('ON_DUTY_OUTSIDE', 'On duty outside the plant'), ('APPROVED_LEAVE', 'Approved leave'), ('HALF_DAY_APPROVED', 'Half day approved'), ('SHIFT_ADJUSTMENT', 'Shift adjustment'), ('NOT_ENROLLED', 'Not enrolled on the machine'), ('DATA_ERROR', 'Wrong data from the machine'), ('OTHER', 'Other')], default='', max_length=30)),
                ('override_reason', models.TextField(blank=True, default='', help_text='Required when overriding. The code says what kind; this says what happened.')),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When the punches for this day were last rolled up.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='employee_hierarchy.employee')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily attendance',
                'verbose_name_plural': 'Daily attendance',
                'ordering': ['-date', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OVERRIDE', 'Status changed'), ('AMEND', 'Change amended'), ('REVERT', "Reverted to the machine's status")], default='OVERRIDE', max_length=20)),
                ('from_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('MISSING_PUNCH', 'Missing punch'), ('WEEKLY_OFF', 'Weekly off'), ('ON_LEAVE', 'On leave'), ('ON_DUTY', 'On duty (outside the plant)'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('to_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('MISSING_PUNCH', 'Missing punch'), ('WEEKLY_OFF', 'Weekly off'), ('ON_LEAVE', 'On leave'), ('ON_DUTY', 'On duty (outside the plant)'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('machine_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('MISSING_PUNCH', 'Missing punch'), ('WEEKLY_OFF', 'Weekly off'), ('ON_LEAVE', 'On leave'), ('ON_DUTY', 'On duty (outside the plant)'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('reason_code', models.CharField(blank=True, choices=[('FORGOT_PUNCH', 'Forgot to punch'), ('MACHINE_FAILURE', 'Punching machine failed'), ('FINGERPRINT_FAILED', 'Fingerprint not recognised'), ('ON_DUTY_OUTSIDE', 'On duty outside the plant'), ('APPROVED_LEAVE', 'Approved leave'), ('HALF_DAY_APPROVED', 'Half day approved'), ('SHIFT_ADJUSTMENT', 'Shift adjustment'), ('NOT_ENROLLED', 'Not enrolled on the machine'), ('DATA_ERROR', 'Wrong data from the machine'), ('OTHER', 'Other')], default='', max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_override_entries', to=settings.AUTH_USER_MODEL)),
                ('daily_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_log', to='attendance.dailyattendance')),
            ],
            options={
                'verbose_name': 'Attendance override entry',
                'verbose_name_plural': 'Attendance override trail',
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['date', 'effective_status'], name='attendance__date_7b6865_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['employee', '-date'], name='attendance__employe_5aa5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['date', 'is_overridden'], name='attendance__date_3cba1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_daily_attendance_per_employee_day'),
        ),
        migrations.AddIndex(
            model_name='attendanceoverridelog',
            index=models.Index(fields=['daily_attendance', '-performed_at'], name='attendance__daily_a_92fef8_idx'),
        ),
    ]
