# Generated by Django 6.0.1 on 2026-09-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_grant_daily_attendance_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_code', models.CharField(max_length=50, unique=True)),
                ('employee_code', models.CharField(db_index=True, help_text='The JWPL code the alias resolves to.', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Punch alias',
                'verbose_name_plural': 'Punch aliases',
                'ordering': ['alias_code'],
            },
        ),
        migrations.CreateModel(
            name='PunchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(db_index=True, help_text='paycode as the machine holds it -- a JWPL code, or a fac#### alias.', max_length=50)),
                ('punched_at', models.DateTimeField(db_index=True)),
                ('device', models.CharField(blank=True, default='', help_text="Reader serial (e.g. NCD8244900570). Not an IP, despite the source column's name.", max_length=255)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punch event',
                'verbose_name_plural': 'Punch events',
                'ordering': ['-punched_at', 'raw_code'],
                'indexes': [models.Index(fields=['punched_at', 'raw_code'], name='attendance__punched_ee7ab9_idx')],
                'constraints': [models.UniqueConstraint(fields=('raw_code', 'punched_at', 'device'), name='uniq_punch_event')],
            },
        ),
        migrations.CreateModel(
            name='PunchSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('rows_pulled', models.PositiveIntegerField(default=0, help_text='Punches read off the machine.')),
                ('rows_inserted', models.PositiveIntegerField(default=0, help_text='Punches that were new. A healthy re-run inserts nothing.')),
                ('latest_punch_at', models.DateTimeField(blank=True, help_text='Newest punch the machine held at that moment.', null=True)),
                ('ok', models.BooleanField(db_index=True, default=False)),
                ('detail', models.TextField(blank=True, default='', help_text='Error text when ok is false; a summary otherwise.')),
            ],
            options={
                'verbose_name': 'Punch sync run',
                'verbose_name_plural': 'Punch sync runs',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['-started_at', 'ok'], name='attendance__started_bed8ae_idx')],
            },
        ),
    ]
