# Generated by Codex on 2026-05-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_usercompany_role"),
        ("driver_management", "0006_alter_vehicleentry_status"),
        ("gate_core", "0005_gateattachment"),
        ("quality_control", "0022_factory_head_decision"),
        ("vehicle_management", "0006_alter_vehicle_vehicle_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectedQCReturnEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("entry_no", models.CharField(max_length=50, unique=True)),
                ("gate_out_date", models.DateField()),
                ("out_time", models.TimeField(blank=True, null=True)),
                ("challan_no", models.CharField(blank=True, max_length=100)),
                ("eway_bill_no", models.CharField(blank=True, max_length=100)),
                ("manual_sap_reference", models.CharField(blank=True, max_length=100)),
                ("security_name", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled")], default="COMPLETED", max_length=20)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rejected_qc_return_entries", to="company.company")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rejected_qc_return_entries", to="driver_management.driver")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rejected_qc_return_entries", to="vehicle_management.vehicle")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RejectedQCReturnItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("gate_entry_no", models.CharField(blank=True, max_length=50)),
                ("report_no", models.CharField(blank=True, max_length=50)),
                ("internal_lot_no", models.CharField(blank=True, max_length=50)),
                ("item_name", models.CharField(blank=True, max_length=255)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("uom", models.CharField(blank=True, max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="gate_core.rejectedqcreturnentry")),
                ("inspection", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="rejected_qc_return_item", to="quality_control.rawmaterialinspection")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="rejectedqcreturnentry",
            index=models.Index(fields=["company", "gate_out_date"], name="gate_core_r_company_5503e0_idx"),
        ),
        migrations.AddIndex(
            model_name="rejectedqcreturnentry",
            index=models.Index(fields=["status"], name="gate_core_r_status_ef0ced_idx"),
        ),
    ]
