# Generated by Django 6.0.1 on 2026-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0029_salesdispatchboxscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdispatchboxscan',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesdispatchboxscan',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
