# Generated by Django 6.0.1 on 2026-06-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0031_backfill_box_scan_weights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdispatchgateout',
            name='challan_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesdispatchgateout',
            name='challan_weight_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdispatchgateout',
            name='challan_weight_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_dispatch_challan_weights_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
