# Generated by Django 6.0.1 on 2026-06-17 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('gate_core', '0035_dispatch_group_drop_dock_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDispatchAdditionalWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_dispatch_additional_weights', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sales_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_weights', to='gate_core.salesdispatchgateout')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['company', 'sales_dispatch'], name='gate_core_s_company_a2454a_idx')],
            },
        ),
    ]
