# Generated by Django 6.0.1 on 2026-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0036_salesdispatchadditionalweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdispatchgateout',
            name='sap_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateoutdocument',
            name='sap_reference',
            field=models.TextField(blank=True),
        ),
    ]
