# Generated by Django 6.0.1 on 2026-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0037_alter_salesdispatchgateout_sap_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdispatchgateout',
            name='customer_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateout',
            name='customer_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateout',
            name='eway_bill',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateout',
            name='sap_doc_num',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateoutdocument',
            name='customer_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateoutdocument',
            name='customer_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateoutdocument',
            name='eway_bill',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchgateoutdocument',
            name='sap_doc_num',
            field=models.TextField(blank=True),
        ),
    ]
