# Generated by Django 6.0.1 on 2026-06-20 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0012_alter_dispatchplan_options'),
        ('gate_core', '0038_alter_salesdispatchgateout_customer_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emptyvehiclegatein',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emptyvehiclegatein',
            name='retired_reason',
            field=models.CharField(blank=True, choices=[('DISPATCHED', 'Dispatched'), ('EMPTY_OUT', 'Left Empty'), ('CANCELLED', 'Cancelled')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='EmptyVehicleGateInCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.CharField(blank=True, max_length=50)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empty_in_covers', to='dispatch_plans.dispatchplan')),
                ('empty_vehicle_gate_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='gate_core.emptyvehiclegatein')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['sap_doc_entry'], name='gate_core_e_sap_doc_3b2508_idx'), models.Index(fields=['dispatch_plan'], name='gate_core_e_dispatc_64c9d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('empty_vehicle_gate_in', 'sap_doc_entry'), name='unique_empty_vehicle_gate_in_cover')],
            },
        ),
    ]
