# Generated by Django 6.0.1 on 2026-06-20 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0012_add_qc_hold_status'),
        ('gate_core', '0040_backfill_empty_in_covers'),
        ('vehicle_management', '0007_transporter_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('arrival_no', models.CharField(max_length=50, unique=True)),
                ('gate_in_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('weighbridge_slip_no', models.CharField(blank=True, max_length=50)),
                ('security_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('INSIDE', 'Inside'), ('LOADING', 'Loading'), ('DEPARTED', 'Departed'), ('CANCELLED', 'Cancelled')], default='INSIDE', max_length=20)),
                ('gate_out_date', models.DateField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('exit_security_name', models.CharField(blank=True, max_length=100)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_arrivals_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('departed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_arrivals_departed', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='driver_management.driver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='vehicle_management.vehicle')),
            ],
            options={
                'ordering': ['-gate_in_date', '-in_time', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emptyvehiclegatein',
            name='arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_ins', to='gate_core.vehiclearrival'),
        ),
        migrations.AddField(
            model_name='salesdispatchgateout',
            name='arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_outs', to='gate_core.vehiclearrival'),
        ),
        migrations.AddIndex(
            model_name='vehiclearrival',
            index=models.Index(fields=['vehicle'], name='gate_core_v_vehicle_95186e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclearrival',
            index=models.Index(fields=['status'], name='gate_core_v_status_28eec4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclearrival',
            index=models.Index(fields=['gate_in_date'], name='gate_core_v_gate_in_821690_idx'),
        ),
    ]
