# Generated by Django 6.0.1 on 2026-06-20 09:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('gate_core', '0041_vehiclearrival_emptyvehiclegatein_arrival_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdispatchgateoutitem',
            name='dispatched_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesdispatchattachment',
            name='attachment_type',
            field=models.CharField(choices=[('TRUCK_PHOTO', 'Truck Photo'), ('GATEPASS', 'Gatepass'), ('INVOICE_COPY', 'Invoice Copy'), ('DELIVERY_NOTE', 'Delivery Note'), ('BILTY', 'Bilty'), ('EWAY_BILL', 'E-Way Bill'), ('CREDIT_NOTE', 'Credit Note'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='PartialDispatchApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('credit_note_no', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_dispatch_approvals', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partial_dispatch_approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_approvals', to='gate_core.salesdispatchgateoutdocument')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partial_dispatch_approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('sales_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_approvals', to='gate_core.salesdispatchgateout')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_approve_partial_sales_dispatch', 'Can approve partial sales dispatch')],
                'indexes': [models.Index(fields=['company', 'status'], name='gate_core_p_company_439a52_idx'), models.Index(fields=['sales_dispatch'], name='gate_core_p_sales_d_3382e7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document',), name='unique_active_partial_dispatch_approval')],
            },
        ),
    ]
