# Generated by Django 6.0.1 on 2026-06-21 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0043_retire_departed_dispatch_gate_ins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalGatepassSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclearrival',
            name='gatepass_committed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclearrival',
            name='gatepass_committed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_arrivals_gatepass_committed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclearrival',
            name='gatepass_no',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiclearrival',
            name='gatepass_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclearrival',
            name='gatepass_printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_arrivals_gatepass_printed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclearrival',
            name='gatepass_random_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
