# Generated by Django 6.0.1 on 2026-06-23 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0012_intercompanytransfer_entity_type'),
        ('company', '0003_alter_usercompany_role'),
        ('gate_core', '0044_arrivalgatepasssequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdispatchboxscan',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_scans', to='gate_core.salesdispatchgateoutdocument'),
        ),
        migrations.AddIndex(
            model_name='salesdispatchboxscan',
            index=models.Index(fields=['sales_dispatch', 'document'], name='gate_core_s_sales_d_ae4c55_idx'),
        ),
    ]
