# Generated by Django 6.0.1 on 2026-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0045_salesdispatchboxscan_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptyvehiclegatein',
            name='reason',
            field=models.CharField(choices=[('DISPATCH', 'Dispatch'), ('REPAIR_MOVEMENT', 'Repair Movement'), ('JOB_WORK', 'Job Work'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
