# Generated by Django 6.0.1 on 2026-07-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0046_alter_emptyvehiclegatein_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobworkgatein',
            options={'ordering': ['-gate_in_date', '-in_time', '-created_at'], 'permissions': [('can_view_job_work', 'Can view job work gate entries'), ('can_create_job_work', 'Can create/edit job work gate entries'), ('can_complete_job_work', 'Can complete job work gate entries')]},
        ),
    ]
