# Generated by Django 6.0.1 on 2026-07-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0048_assign_job_work_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDispatchUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('REACHED_DESTINATION', 'Reached Destination'), ('UNLOADING', 'Unloading'), ('DELIVERED', 'Delivered'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('RETURNED', 'Returned'), ('DELAYED', 'Delayed'), ('CLOSED', 'Closed')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='dispatch_tracking/proof/')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_updates', to='gate_core.vehiclearrival')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'permissions': [('can_view_dispatch_tracking', 'Can view dispatch tracking'), ('can_update_dispatch_tracking', 'Can add dispatch tracking updates')],
                'indexes': [models.Index(fields=['arrival', '-occurred_at'], name='gate_core_t_arrival_14a52c_idx')],
            },
        ),
    ]
