# Generated by Django 6.0.1 on 2026-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0048_assign_job_work_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptyvehiclegatein',
            name='retired_reason',
            field=models.CharField(blank=True, choices=[('DISPATCHED', 'Dispatched'), ('EMPTY_OUT', 'Left Empty'), ('CANCELLED', 'Cancelled'), ('SUPERSEDED', 'Superseded by trip gate-in')], default='', max_length=30),
        ),
    ]
