# Generated by Django 6.0.1 on 2026-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0053_salesdispatchattachment_bilty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdispatchupdate',
            name='expected_reach_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
