# Generated by Django 6.0.1 on 2026-08-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0054_truckdispatchupdate_expected_reach_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdispatchupdate',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckdispatchupdate',
            name='return_note',
            field=models.FileField(blank=True, null=True, upload_to='dispatch_tracking/return_note/'),
        ),
        migrations.CreateModel(
            name='TruckDispatchPartialDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty_delivered', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('qty_returned', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_delivery_lines', to='gate_core.salesdispatchgateoutdocument')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_lines', to='gate_core.truckdispatchupdate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TruckDispatchPartialDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty_delivered', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('qty_returned', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_delivery_items', to='gate_core.salesdispatchgateoutitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate_core.truckdispatchpartialdeliveryline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='truckdispatchpartialdeliveryline',
            index=models.Index(fields=['update'], name='gate_core_t_update__76046d_idx'),
        ),
        migrations.AddIndex(
            model_name='truckdispatchpartialdeliveryline',
            index=models.Index(fields=['document'], name='gate_core_t_documen_9f596c_idx'),
        ),
        migrations.AddConstraint(
            model_name='truckdispatchpartialdeliveryline',
            constraint=models.UniqueConstraint(fields=('update', 'document'), name='unique_partial_delivery_line_per_bill'),
        ),
        migrations.AddIndex(
            model_name='truckdispatchpartialdeliveryitem',
            index=models.Index(fields=['line'], name='gate_core_t_line_id_778609_idx'),
        ),
        migrations.AddIndex(
            model_name='truckdispatchpartialdeliveryitem',
            index=models.Index(fields=['item'], name='gate_core_t_item_id_be3f01_idx'),
        ),
        migrations.AddConstraint(
            model_name='truckdispatchpartialdeliveryitem',
            constraint=models.UniqueConstraint(fields=('line', 'item'), name='unique_partial_delivery_item_per_line'),
        ),
    ]
