# Generated by Django 6.0.1 on 2026-08-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0057_gateattachment_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdispatchgateout',
            name='total_loose',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesdispatchgateoutdocument',
            name='total_loose',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesdispatchgateoutitem',
            name='sal_factor2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesdispatchgateoutitem',
            name='total_loose',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
