# Generated by Django 6.0.1 on 2026-09-16 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('gate_core', '0059_add_can_view_gate_dashboard'),
        ('vehicle_management', '0008_vehicle_height_m_vehicle_length_m_vehicle_width_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateDispatchGateInApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gate_in_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('bill_doc_nums', models.TextField(blank=True, help_text='Comma-separated SAP invoice numbers the truck is booked to carry.')),
                ('customer_names', models.TextField(blank=True, help_text='Comma-separated customers on those bills.')),
                ('bill_count', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(help_text='Why this truck is being let in after the cutoff.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_dispatch_gate_in_approvals', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empty_vehicle_gate_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_dispatch_approvals', to='gate_core.emptyvehiclegatein')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_dispatch_gate_in_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_dispatch_gate_in_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_dispatch_gate_in_approvals', to='vehicle_management.vehicle')),
            ],
            options={
                'verbose_name': 'Late Dispatch Gate-In Approval',
                'verbose_name_plural': 'Late Dispatch Gate-In Approvals',
                'ordering': ['-requested_at', '-id'],
                'permissions': [('can_view_late_dispatch_gate_in', 'Can view late dispatch gate-in approval requests'), ('can_approve_late_dispatch_gate_in', 'Can approve or reject late dispatch gate-in approval requests')],
                'indexes': [models.Index(fields=['company', 'status'], name='gate_core_l_company_5450b2_idx'), models.Index(fields=['vehicle', 'gate_in_date'], name='gate_core_l_vehicle_a94e43_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'PENDING')), fields=('vehicle', 'gate_in_date'), name='unique_pending_late_dispatch_gate_in')],
            },
        ),
    ]
