# Generated by Django 6.0.1 on 2026-10-10 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0062_late_dispatch_in_time_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDispatchSapReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('NEEDS_PROOF', 'Waiting for the proof of delivery'), ('WAITING', 'Waiting for SAP'), ('POSTED', 'Received in SAP'), ('ALREADY_RECEIVED', 'Already received in SAP'), ('BY_HAND', 'Enter in SAP by hand'), ('REFUSED', 'Refused by SAP'), ('SUPERSEDED', 'Replaced by a later update')], default='NEEDS_PROOF', max_length=20)),
                ('received_date', models.DateField()),
                ('lines', models.JSONField(blank=True, default=list)),
                ('sap_attachment_entry', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_receipts', to='gate_core.salesdispatchgateoutdocument')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_receipts', to='gate_core.truckdispatchupdate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['document', 'status'], name='gate_core_t_documen_7ca95d_idx')],
                'constraints': [models.UniqueConstraint(fields=('update', 'document'), name='unique_sap_receipt_per_update_bill')],
            },
        ),
    ]
