# Generated by Django 6.0.1 on 2026-09-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0062_late_dispatch_in_time_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdispatchattachment',
            name='attachment_type',
            field=models.CharField(choices=[('TRUCK_PHOTO', 'Truck Photo'), ('GATEPASS', 'Gatepass'), ('INVOICE_COPY', 'Invoice Copy'), ('DELIVERY_NOTE', 'Delivery Note'), ('BILTY', 'Bilty'), ('EWAY_BILL', 'E-Way Bill'), ('CREDIT_NOTE', 'Credit Note'), ('SEAL_PHOTO', 'Seal Photo'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
