# Generated by Django 6.0.1 on 2026-08-25 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(choices=[('DAILY_LOG', 'Daily plant log'), ('MONITORING', 'On-line monitoring'), ('CHEMICAL', 'Chemical consumption'), ('SLUDGE', 'Sludge generation'), ('BACKWASH', 'Daily back washing'), ('CALIBRATION', 'Calibration')], max_length=20)),
                ('action', models.CharField(choices=[('CREATED', 'Recorded'), ('UPDATED', 'Edited'), ('DELETED', 'Deleted'), ('VERIFIED', 'Verified')], max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=60)),
                ('entry_date', models.DateField(blank=True, help_text='The date of the register row that changed.', null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etp_register_changes', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='etp.treatmentplant')),
            ],
            options={
                'verbose_name': 'Register Change Log',
                'verbose_name_plural': 'Register Change Log',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['register', '-changed_at'], name='etp_registe_registe_bc2d42_idx'), models.Index(fields=['register', 'object_id'], name='etp_registe_registe_9fa7cc_idx'), models.Index(fields=['entry_date'], name='etp_registe_entry_d_92d0c2_idx')],
            },
        ),
    ]
