# Generated by Django 6.0.1 on 2026-08-25 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('etp', '0002_registerchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtpPrintDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_key', models.CharField(choices=[('ETP_DAILY_RECORD', 'Effluent Treatment Plant Record'), ('ETP_MONITORING_RECORD', 'ETP On Line Monitoring Record'), ('ETP_CHEMICAL_CONSUMPTION', 'Chemical Consumption Record — ETP'), ('STP_CHEMICAL_CONSUMPTION', 'Chemical Consumption Record — STP'), ('ETP_SLUDGE_GENERATION', 'Sludge Generation Record'), ('ETP_BACKWASH_RECORD', 'Daily Back Washing Record'), ('ETP_CALIBRATION_RECORD', 'Calibration Record')], max_length=40)),
                ('form_name', models.CharField(blank=True, default='', help_text="Name printed in the header, e.g. 'SLUDGE GENERATION RECORD'.", max_length=200)),
                ('document_code', models.CharField(blank=True, default='', help_text="Controlled-document code, e.g. 'QA-FRM-14-00-08-06'.", max_length=64)),
                ('revision', models.CharField(blank=True, default='00', help_text="Revision number as printed, e.g. '00'.", max_length=10)),
                ('issue_date', models.DateField(blank=True, help_text='Issue / revision date of this form.', null=True)),
                ('document_id', models.CharField(blank=True, default='', help_text='Optional per-copy document ID printed in the footer, the way the QC prints carry one.', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, help_text='Leave empty for every company (the usual case).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etp_print_documents', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ETP Print Document',
                'verbose_name_plural': 'ETP Print Documents',
                'ordering': ['document_key', 'company__code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_key'), name='uq_etp_print_document_company_key'), models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('document_key',), name='uq_etp_print_document_default_key')],
            },
        ),
    ]
