# Generated by Django 6.0.1 on 2026-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0003_etpprintdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringparameter',
            options={'ordering': ['plant__sequence', models.OrderBy(models.Case(models.When(stage='INFLUENT', then=models.Value(0)), models.When(stage='PRIMARY', then=models.Value(1)), models.When(stage='AERATION', then=models.Value(2)), models.When(stage='SECONDARY', then=models.Value(3)), models.When(stage='TREATED', then=models.Value(4)), models.When(stage='OTHER', then=models.Value(5)), default=models.Value(6), output_field=models.IntegerField())), 'sequence', 'parameter_name'], 'verbose_name': 'Monitoring Parameter', 'verbose_name_plural': 'Monitoring Parameters'},
        ),
    ]
