# Generated by Django 6.0.1 on 2026-08-22 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_internal_key', models.IntegerField(help_text="OUQR.IntrnalKey — the report's identity inside SAP.")),
                ('sap_name', models.CharField(help_text='OUQR.QName, exactly as the query is named in SAP.', max_length=200)),
                ('sap_category_id', models.IntegerField(help_text='OQCN.CategoryId of the SAP query category (e.g. Factory).')),
                ('sap_category_name', models.CharField(max_length=100)),
                ('sql_text', models.TextField(help_text='OUQR.QString with line breaks normalised.')),
                ('sql_hash', models.CharField(help_text='Fingerprint of sql_text; a change here means the query was edited in SAP.', max_length=64)),
                ('statement_kind', models.CharField(choices=[('SELECT', 'Select'), ('CALL', 'Procedure call')], default='SELECT', max_length=10)),
                ('is_runnable', models.BooleanField(default=True, help_text='False when the saved query is not a single read-only statement.')),
                ('not_runnable_reason', models.CharField(blank=True, max_length=255)),
                ('is_missing_in_sap', models.BooleanField(default=False, help_text='Set when a sync no longer finds this query in SAP; kept for its run history.')),
                ('sap_changed_at', models.DateTimeField(blank=True, help_text='OUQR.UpdateDate — when the query was last edited inside SAP.', null=True)),
                ('slug', models.SlugField(help_text='Stable URL name for this report within the company.', max_length=120)),
                ('display_name', models.CharField(blank=True, help_text='Friendlier name to show instead of the raw SAP query name.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this report answers, for the people who run it.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck to hide the report from the module without deleting its history.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower sorts first; ties fall back to the report name.')),
                ('row_limit', models.PositiveIntegerField(blank=True, help_text='Row ceiling for this report only; blank uses the module default.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company database this saved query belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sap_reports', to='company.company')),
            ],
            options={
                'verbose_name': 'SAP report',
                'verbose_name_plural': 'SAP reports',
                'ordering': ['company_id', 'sort_order', 'sap_name'],
                'permissions': [('can_view_sap_reports', 'Can view and run SAP reports'), ('can_manage_sap_reports', 'Can sync SAP reports and edit their setup')],
            },
        ),
        migrations.CreateModel(
            name='SapReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text="The N in SAP's [%N] placeholder.")),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('DATE', 'Date'), ('TEXT', 'Free text'), ('NUMBER', 'Number'), ('ITEM', 'Item / SKU'), ('WAREHOUSE', 'Warehouse'), ('BUSINESS_PARTNER', 'Customer / vendor'), ('ITEM_GROUP', 'Item group'), ('PERIOD', 'Fiscal period')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, help_text='Pre-filled value; used when the caller sends nothing for this prompt.', max_length=120)),
                ('blank_value', models.CharField(blank=True, help_text='What to bind when an optional prompt is left empty (usually blank).', max_length=64)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('is_quoted', models.BooleanField(default=True, help_text='True when SAP wrote the placeholder inside quotes, i.e. bind it as text.')),
                ('occurrences', models.PositiveSmallIntegerField(default=1, help_text='How many times this prompt appears in the SQL.')),
                ('is_customised', models.BooleanField(default=False, help_text='Set when a person edited this parameter; protects it from later syncs.')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='sap_reports.sapreport')),
            ],
            options={
                'verbose_name': 'SAP report parameter',
                'verbose_name_plural': 'SAP report parameters',
                'ordering': ['report_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SapReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='The values the report was run with, keyed by prompt position.')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('was_truncated', models.BooleanField(default=False, help_text='True when the row ceiling cut the result short.')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('export_format', models.CharField(blank=True, help_text='Blank for an on-screen run; csv/xlsx for a download.', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_report_runs', to='company.company')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sap_reports.sapreport')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SAP report run',
                'verbose_name_plural': 'SAP report runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sapreport',
            constraint=models.UniqueConstraint(fields=('company', 'sap_internal_key'), name='uniq_sap_report_per_company_key'),
        ),
        migrations.AddConstraint(
            model_name='sapreport',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='uniq_sap_report_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='sapreportparameter',
            constraint=models.UniqueConstraint(fields=('report', 'position'), name='uniq_sap_report_parameter_position'),
        ),
        migrations.AddIndex(
            model_name='sapreportrun',
            index=models.Index(fields=['report', '-created_at'], name='sap_reports_report__bc3184_idx'),
        ),
        migrations.AddIndex(
            model_name='sapreportrun',
            index=models.Index(fields=['company', '-created_at'], name='sap_reports_company_65e823_idx'),
        ),
    ]
