# Generated by Django 6.0.1 on 2026-09-01 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_report_access_granted', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='sap_reports.sapreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_report_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SAP report access',
                'verbose_name_plural': 'SAP report access',
                'ordering': ['user_id', 'report_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'report'), name='uniq_sap_report_access_user_report')],
            },
        ),
    ]
