# Generated by Django 6.0.1 on 2026-09-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_reports', '0003_sapreport_is_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapreport',
            options={'ordering': ['company_id', 'sort_order', 'sap_name'], 'permissions': [('can_view_sap_reports', 'Can view and run SAP reports'), ('can_manage_sap_reports', 'Can sync SAP reports and edit their setup'), ('can_sync_sap_reports', 'Can sync SAP reports from SAP')], 'verbose_name': 'SAP report', 'verbose_name_plural': 'SAP reports'},
        ),
    ]
