# Generated by Django 6.0.1 on 2026-10-09 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APInvoiceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('grpo_doc_entry', models.IntegerField()),
                ('grpo_doc_num', models.CharField(blank=True, max_length=50)),
                ('grpo_date', models.DateField(blank=True, null=True)),
                ('grpo_reference', models.CharField(blank=True, max_length=100)),
                ('vendor_code', models.CharField(blank=True, max_length=50)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('grpo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('invoice_file', models.FileField(upload_to='ap_invoice_drafts/')),
                ('invoice_filename', models.CharField(blank=True, max_length=255)),
                ('sap_status', models.CharField(choices=[('PENDING', 'Not in SAP yet'), ('CREATED', 'Draft in SAP'), ('FAILED', 'SAP did not take it')], db_index=True, default='PENDING', max_length=20)),
                ('sap_draft_entry', models.IntegerField(blank=True, null=True)),
                ('sap_draft_adopted', models.BooleanField(default=False)),
                ('sap_error', models.TextField(blank=True)),
                ('sap_attachment_entry', models.IntegerField(blank=True, null=True)),
                ('sap_attachment_error', models.TextField(blank=True)),
                ('sap_created_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoice_drafts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_ap_invoice_draft', 'Can view A/P invoice drafts'), ('can_create_ap_invoice_draft', 'Can create an A/P invoice draft in SAP')],
                'indexes': [models.Index(fields=['company', '-created_at'], name='ap_invoice__company_9ad909_idx'), models.Index(fields=['grpo_doc_entry'], name='ap_invoice__grpo_do_18c4b0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'grpo_doc_entry'), name='ap_invoice_draft_one_per_grpo')],
            },
        ),
    ]
