# Generated by Django 6.0.1 on 2026-10-09 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_invoice_draft', '0001_initial'),
        ('grpo', '0020_po_print_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apinvoicedraft',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_view_ap_invoice_draft', 'Can view A/P invoice drafts'), ('can_create_ap_invoice_draft', 'Can create an A/P invoice draft in SAP'), ('can_review_ap_invoice_draft', 'Can mark A/P invoice draft checks OK or not OK')]},
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='checks_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='grpo_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoice_drafts', to='grpo.grpoposting'),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='invoice_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='invoice_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='invoice_read_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='invoice_read_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='invoice_read_status',
            field=models.CharField(choices=[('PENDING', 'Not read yet'), ('READING', 'Reading'), ('READ', 'Read'), ('FAILED', 'Could not read')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='APInvoiceDraftCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PASS', 'OK'), ('FAIL', 'Not OK'), ('REVIEW', 'Needs a look'), ('UNKNOWN', 'Not checked')], default='UNKNOWN', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('review_decision', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], max_length=10)),
                ('review_remark', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='ap_invoice_draft.apinvoicedraft')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoice_draft_checks_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'key'), name='ap_invoice_draft_check_unique_key')],
            },
        ),
    ]
