# Generated by Django 6.0.1 on 2026-10-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_invoice_draft', '0002_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoicedraft',
            name='tds_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='tds_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='tds_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apinvoicedraft',
            name='tds_taxable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
